### ISSUE TITLE
DNS问题反馈

### ISSUE THREAD

**Issue by jkle112** [juewuy/ShellClash#102]
用的测试版1.4.6，内核也是.net的测试版，但是在DNS配置上出现了一点问题：
使用的第三方DNS，由DNSMASQ转发的，如果关闭内置的DNS，好像会不起作用，导致日志页面空白，网页打不开。
我改了内置的DNS地址到指定的转发地址后，网页能打开，日志有显示，不过现实的速度滞后，网页打开了，日志文件还没有现实连接情况。
关闭SHELLCLASH后，DNS好像又获取不到了，重启路由器才恢复正常，我默认是SHELLCLASH不开机启动。
之后升级到1.4.7，我没有再测试了。
请问如何正确设置DNS，谢谢！

**Comment by juewuy** [comment]
在shellclash的7-6里，手动将基础dns和fallbackdns都指定为上游dns端口即可

**Comment by jkle112** [comment]
测试版1.4.7，内核也是.net的测试版，在shellclash的7-6里，手动将基础dns和fallbackdns都指定为上游dns端口，一切顺利，但是关闭clash后，无法打开网友了，获取不到DNS，需要重启路由器才可以。
希望升级的适合能调整一下，这样用起来会方便一点，谢谢！

**Comment by juewuy** [comment]
这应该不是clash的问题，shellclash停止服务时会还原一切变更

**Comment by jkle112** [comment]
测试版1.4.10，内核也是.net的测试版，现在不启动，更新脚本后，过一下子，要重启路由器，网络才恢复。
目前只能手动将基础dns和fallbackdns都指定为上游dns端口，关闭clash后，也需要重启路由器。
用的路由器是Gl-inet mv1000w，它是图文界面和高级界面同时使用的，不同的界面可以看到的功能不同。
在实际使用的，
![Screenshot from 2022-01-08 19-25-29](https://user-images.githubusercontent.com/17021524/148664520-78b5303d-173d-43ad-a5c3-69ea5ebcda4c.png)
发现还是CLASH自己在改DNS配置，这是图文界面的显示情况，高级界面还是我自己的DNS 配置
![Screenshot from 2022-01-02 20-38-09](https://user-images.githubusercontent.com/17021524/148664531-29a9688b-c1f3-4dc0-9716-fe213d1bdfa7.png)

我是高级用户，默认系统配置了两个不同加密方式的DNS工具，比官方的更安全。
如果禁用内置的DNS，会导致图文界面DNS空白，高级界面没有变化，系统混乱，网络不通。
如果使用DNSMASQ转发DNS，和修改基础dns和fallbackdns的结果是一样的。
 
最好的解决方法：直接禁用CLASH自己的DNS管理模块，向系统DNSMASQ发送DNS请求，DNSMASQ转发到对应的工具，这样不会对原来的安全方案有影响。
自己以前用过openwrt x64 下面的clash和openclash，结果都是DNS的问题，一样的情况。

**Comment by juewuy** [comment]
高级用户请自行解决吧，这个脚本主要还是方便小白们使用的
