### ISSUE TITLE
提示安装成功但是无法启动

### ISSUE THREAD

**Issue by Inliang** [juewuy/ShellClash#104]
提示安装成功但是无法启动  ![QQ截图20220107182859](https://user-images.githubusercontent.com/79506519/148530942-b5a25ed3-8130-42a7-85a3-909cab1cbe80.png)

**Comment by Inliang** [comment]
[https://i.jpg.dog/file/jpg-dog/219b2e68140122ef790d4a2fb46e4a8d.jpg](url)

**Comment by juewuy** [comment]
安装命令没输入完整
