### ISSUE TITLE
启动失败，内存不足

### ISSUE THREAD

**Issue by YangQuan666** [juewuy/ShellClash#105]
步骤1：执行`clash`，输入数字`1`
步骤2：运行失败，打印的错误如下：
`fatal error: runtime: out of memory

runtime stack:
runtime.throw({0x48c16b, 0x16})
        runtime/panic.go:1198 +0x5c fp=0xbe9b1954 sp=0xbe9b1940 pc=0x45eb0
runtime.sysMap(0xa6aef000, 0x41000, 0x7a8210)
        runtime/mem_linux.go:169 +0xb0 fp=0xbe9b1978 sp=0xbe9b1954 pc=0x266c8
runtime.(*linearAlloc).alloc(0x797848, 0x408c8, 0x4, 0x7a8210)
        runtime/malloc.go:1488 +0x98 fp=0xbe9b1990 sp=0xbe9b1978 pc=0x1cef4
runtime.(*mheap).sysAlloc(0x797760, 0x400000)
        runtime/malloc.go:746 +0x178 fp=0xbe9b19ec sp=0xbe9b1990 pc=0x1b288
runtime.(*mheap).grow(0x797760, 0x1)
        runtime/mheap.go:1347 +0x70 fp=0xbe9b1a30 sp=0xbe9b19ec pc=0x379c8
runtime.(*mheap).allocSpan(0x797760, 0x1, 0x0, 0x22)
        runtime/mheap.go:1179 +0x1ac fp=0xbe9b1a88 sp=0xbe9b1a30 pc=0x37410
runtime.(*mheap).alloc.func1()
        runtime/mheap.go:913 +0x78 fp=0xbe9b1aac sp=0xbe9b1a88 pc=0x36eec
runtime.(*mheap).alloc(0x797760, 0x1, 0x22, 0x1)
        runtime/mheap.go:907 +0x58 fp=0xbe9b1ad0 sp=0xbe9b1aac pc=0x36ddc
runtime.(*mcentral).grow(0x79899c)
        runtime/mcentral.go:241 +0x64 fp=0xbe9b1af4 sp=0xbe9b1ad0 pc=0x25dd0
runtime.(*mcentral).cacheSpan(0x79899c)
        runtime/mcentral.go:161 +0x274 fp=0xbe9b1b34 sp=0xbe9b1af4 pc=0x25b04
runtime.(*mcache).refill(0xb6f6a088, 0x22)
        runtime/mcache.go:162 +0x94 fp=0xbe9b1b64 sp=0xbe9b1b34 pc=0x25030
runtime.(*mcache).nextFree(0xb6f6a088, 0x22)
        runtime/malloc.go:880 +0x84 fp=0xbe9b1b88 sp=0xbe9b1b64 pc=0x1b924
runtime.mallocgc(0xec, 0x47f300, 0x1)
        runtime/malloc.go:1071 +0x5e8 fp=0xbe9b1bcc sp=0xbe9b1b88 pc=0x1c0c0
runtime.newobject(0x47f300)
        runtime/malloc.go:1228 +0x2c fp=0xbe9b1be0 sp=0xbe9b1bcc pc=0x1c684
runtime.malg(0x8000)
        runtime/proc.go:4220 +0x1c fp=0xbe9b1c00 sp=0xbe9b1be0 pc=0x520b4
runtime.mpreinit(0x792180)
        runtime/os_linux.go:355 +0x1c fp=0xbe9b1c0c sp=0xbe9b1c00 pc=0x4215c
runtime.mcommoninit(0x792180, 0xffffffffffffffff)
        runtime/proc.go:803 +0x14c fp=0xbe9b1c34 sp=0xbe9b1c0c pc=0x4a600
runtime.schedinit()
        runtime/proc.go:691 +0x88 fp=0xbe9b1c60 sp=0xbe9b1c34 pc=0x49ef8
runtime.rt0_go()
        runtime/asm_arm.s:168 +0x7c fp=0xbe9b1ca0 sp=0xbe9b1c60 pc=0x76474
clash服务启动失败！请查看报错信息！
fatal error: runtime: out of memory

runtime stack:
runtime.throw({0x48c16b, 0x16})
        runtime/panic.go:1198 +0x5c fp=0xbeaec9c8 sp=0xbeaec9b4 pc=0x45eb0
runtime.sysMap(0x1800000, 0x400000, 0x7a81a8)
        runtime/mem_linux.go:169 +0xb0 fp=0xbeaec9ec sp=0xbeaec9c8 pc=0x266c8
runtime.(*mheap).grow(0x797760, 0x1)
        runtime/mheap.go:1393 +0x264 fp=0xbeaeca30 sp=0xbeaec9ec pc=0x37bbc
runtime.(*mheap).allocSpan(0x797760, 0x1, 0x0, 0x22)
        runtime/mheap.go:1179 +0x1ac fp=0xbeaeca88 sp=0xbeaeca30 pc=0x37410
runtime.(*mheap).alloc.func1()
        runtime/mheap.go:913 +0x78 fp=0xbeaecaac sp=0xbeaeca88 pc=0x36eec
runtime.(*mheap).alloc(0x797760, 0x1, 0x22, 0x1)
        runtime/mheap.go:907 +0x58 fp=0xbeaecad0 sp=0xbeaecaac pc=0x36ddc
runtime.(*mcentral).grow(0x79899c)
        runtime/mcentral.go:241 +0x64 fp=0xbeaecaf4 sp=0xbeaecad0 pc=0x25dd0
runtime.(*mcentral).cacheSpan(0x79899c)
        runtime/mcentral.go:161 +0x274 fp=0xbeaecb34 sp=0xbeaecaf4 pc=0x25b04
runtime.(*mcache).refill(0xb6ee0088, 0x22)
        runtime/mcache.go:162 +0x94 fp=0xbeaecb64 sp=0xbeaecb34 pc=0x25030
runtime.(*mcache).nextFree(0xb6ee0088, 0x22)
        runtime/malloc.go:880 +0x84 fp=0xbeaecb88 sp=0xbeaecb64 pc=0x1b924
runtime.mallocgc(0xec, 0x47f300, 0x1)
        runtime/malloc.go:1071 +0x5e8 fp=0xbeaecbcc sp=0xbeaecb88 pc=0x1c0c0
runtime.newobject(0x47f300)
        runtime/malloc.go:1228 +0x2c fp=0xbeaecbe0 sp=0xbeaecbcc pc=0x1c684
runtime.malg(0x8000)
        runtime/proc.go:4220 +0x1c fp=0xbeaecc00 sp=0xbeaecbe0 pc=0x520b4
runtime.mpreinit(0x792180)
        runtime/os_linux.go:355 +0x1c fp=0xbeaecc0c sp=0xbeaecc00 pc=0x4215c
runtime.mcommoninit(0x792180, 0xffffffffffffffff)
        runtime/proc.go:803 +0x14c fp=0xbeaecc34 sp=0xbeaecc0c pc=0x4a600
runtime.schedinit()
        runtime/proc.go:691 +0x88 fp=0xbeaecc60 sp=0xbeaecc34 pc=0x49ef8
runtime.rt0_go()
        runtime/asm_arm.s:168 +0x7c fp=0xbeaecca0 sp=0xbeaecc60 pc=0x76474
fatal error: runtime: out of memory

runtime stack:
runtime.throw({0x48c16b, 0x16})
        runtime/panic.go:1198 +0x5c fp=0xbe9599c8 sp=0xbe9599b4 pc=0x45eb0
runtime.sysMap(0x1800000, 0x400000, 0x7a81a8)
        runtime/mem_linux.go:169 +0xb0 fp=0xbe9599ec sp=0xbe9599c8 pc=0x266c8
runtime.(*mheap).grow(0x797760, 0x1)
        runtime/mheap.go:1393 +0x264 fp=0xbe959a30 sp=0xbe9599ec pc=0x37bbc
runtime.(*mheap).allocSpan(0x797760, 0x1, 0x0, 0x22)
        runtime/mheap.go:1179 +0x1ac fp=0xbe959a88 sp=0xbe959a30 pc=0x37410
runtime.(*mheap).alloc.func1()
        runtime/mheap.go:913 +0x78 fp=0xbe959aac sp=0xbe959a88 pc=0x36eec
runtime.(*mheap).alloc(0x797760, 0x1, 0x22, 0x1)
        runtime/mheap.go:907 +0x58 fp=0xbe959ad0 sp=0xbe959aac pc=0x36ddc
runtime.(*mcentral).grow(0x79899c)
        runtime/mcentral.go:241 +0x64 fp=0xbe959af4 sp=0xbe959ad0 pc=0x25dd0
runtime.(*mcentral).cacheSpan(0x79899c)
        runtime/mcentral.go:161 +0x274 fp=0xbe959b34 sp=0xbe959af4 pc=0x25b04
runtime.(*mcache).refill(0xb6f88088, 0x22)
        runtime/mcache.go:162 +0x94 fp=0xbe959b64 sp=0xbe959b34 pc=0x25030
runtime.(*mcache).nextFree(0xb6f88088, 0x22)
        runtime/malloc.go:880 +0x84 fp=0xbe959b88 sp=0xbe959b64 pc=0x1b924
runtime.mallocgc(0xec, 0x47f300, 0x1)
        runtime/malloc.go:1071 +0x5e8 fp=0xbe959bcc sp=0xbe959b88 pc=0x1c0c0
runtime.newobject(0x47f300)
        runtime/malloc.go:1228 +0x2c fp=0xbe959be0 sp=0xbe959bcc pc=0x1c684
runtime.malg(0x8000)
        runtime/proc.go:4220 +0x1c fp=0xbe959c00 sp=0xbe959be0 pc=0x520b4
runtime.mpreinit(0x792180)
        runtime/os_linux.go:355 +0x1c fp=0xbe959c0c sp=0xbe959c00 pc=0x4215c
runtime.mcommoninit(0x792180, 0xffffffffffffffff)
        runtime/proc.go:803 +0x14c fp=0xbe959c34 sp=0xbe959c0c pc=0x4a600
runtime.schedinit()
        runtime/proc.go:691 +0x88 fp=0xbe959c60 sp=0xbe959c34 pc=0x49ef8
runtime.rt0_go()
        runtime/asm_arm.s:168 +0x7c fp=0xbe959ca0 sp=0xbe959c60 pc=0x76474`

步骤三：使用`top`命令查看系统剩余内存，看上去内存足够
<img width="553" alt="屏幕截图 2022-01-15 160304" src="https://user-images.githubusercontent.com/27985301/149614638-3b02c40e-f365-4837-b3d9-5955b5460d42.png">

**Comment by juewuy** [comment]
抱歉内核问题我这里解决不了，请移步：https://github.com/Dreamacro/clash/issues
