### ISSUE TITLE
自动添加的防回环规则格式有问题

### ISSUE THREAD

**Issue by AzunyanDaisuki** [juewuy/ShellClash#106]
![image](https://user-images.githubusercontent.com/18110400/150459550-5185578e-e0aa-4286-8e23-1dd194418644.png)
ShellClash 自动添加进来的这条用于防止回环 SRC-IP-CIDR 规则没有缩进，会导致配置文件格式错误无法启动，手动缩进后可以正常运行

**Comment by juewuy** [comment]
rules：的下面不要有空行
就会正确获取到缩进了
