### ISSUE TITLE
ubuntun21本地安装shellclash 1.4.12, 自建vless节点，没有流量无法上网

### ISSUE THREAD

**Issue by magicmatt2020** [juewuy/ShellClash#108]
ubuntun21本地安装shellclash 1.4.12, 自建vless节点，核心分别试了meta和clash.net的版本(config.yaml在windows用clash.net和clashmini都能成功运行），支持vless+ws+tls .开启后显示成功，查看clash运行时报错信息显示一正常。打开 管理页面后显示节点，策略都正常但是没有流量，无法上网，如何解决？

**Comment by juewuy** [comment]
尝试使用本机代理增强模式

**Comment by magicmatt2020** [comment]
> 尝试使用本机代理增强模式

使用本机代理增强模式成功，内存占用小，速度不错，赞！
