### ISSUE TITLE
建议更新 ip 数据库使用 master 分支下的包

### ISSUE THREAD

**Issue by RikudouPatrickstar** [juewuy/ShellClash#109]
目前使用 1.4.4 正式版，发现更新 控制面板，拉取的是 master 分支下的包，而更新 ip 数据库则是却用的 tag 1.4.4 下的。建议更新 ip 数据库使用 master 分支下的包，或者直接使用上游每隔几天更新的包。

**Comment by juewuy** [comment]
这不是一个从稳定性考量的建议

**Comment by RikudouPatrickstar** [comment]
好的吧（感觉数据库用新的问题不大
