### ISSUE TITLE
使用自定义的DNS设定

### ISSUE THREAD

**Issue by in-out** [juewuy/ShellClash#11]
现状：
自定义的clash中 包含了dns的设定 包括监听端口和dns server，但是 使用了脚本的获取订阅后 会被覆写成 114(start.sh?)
   例如：
`
dns:
  enable: true # 是否启用dns false
  ipv6: false
  listen: 0.0.0.0:53
  enhanced-mode: fake-ip # 模式：redir-host或fake-ip
  #fake-ip-range: 198.18.0.1/16 #
  #fake-ip-filter: # fake ip 白名单列表，如果你不知道这个参数的作用，请勿修改
     #- '*.lan'
     #- localhost.ptlogin2.qq.com
  nameserver:    
     - https://doh.pub/dns-query
     - https://dns.rubyfish.cn/dns-query
  fallback:
     - https://dns.cloudflare.com/dns-query
     - https://dns.google/dns-query
  fallback-filter:
     geoip: true # 默认
     #ipcidr: # 在这个网段内的 IP 地址会被考虑为被污染的 IP
       #- 240.0.0.0/4
`
希望：能够使用自定义的DNS设置

**Comment by juewuy** [comment]
请使用 进阶设置 ——不修饰config.yaml 功能
