### ISSUE TITLE
tg群显示当前对话不可用

### ISSUE THREAD

**Issue by 1259225** [juewuy/ShellClash#113]
之前加过不说话好像被t了，现在只能今通告群

**Comment by juewuy** [comment]
请私聊t.me/juewuy

从 Windows 版邮件发送

发件人: 1259225
发送时间: 2022年1月31日 1:43
收件人: juewuy/ShellClash
抄送: Subscribed
主题: [juewuy/ShellClash] tg群显示当前对话不可用 (Issue #113)

之前加过不说话好像被t了，现在只能今通告群
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
