### ISSUE TITLE
为什么小米路由器PRO不能安装shellclash？

### ISSUE THREAD

**Issue by wangchuanyes** [juewuy/ShellClash#114]
小米路由R3P，老的路由器好像都不能shellclash？，是不是需要在哪个步骤设置一下权限。

**Comment by juewuy** [comment]
可以安装的，有问题请提供具体问题报错信息

**Comment by wangchuanyes** [comment]
谢谢您的解答

> 可以安装的，有问题请提供具体问题报错信息

以下是报错内容，无论在线安装还是本地服务器安装（https://juewuy.github.io/m7BojFXBO/）都出现这个：
请输入相应数字 > 1
目标目录/etc空间剩余：128.8M
确认安装？(1/0) > 1
-----------------------------------------------
开始从服务器获取安装文件！
-----------------------------------------------
######################################################################## 100.0%
sh: missing ]
文件下载失败,请尝试使用其他安装源！
root@XiaoQiang:~#

**Comment by wangchuanyes** [comment]
安装ShellClash至少需要预留约1MB的磁盘空间
 1 在/etc目录下安装(适合root用户)
 2 在/usr/share目录下安装(适合Linux设备)
 3 在当前用户目录下安装(适合非root用户)
 4 手动设置安装目录
 0 退出安装
-----------------------------------------------
请输入相应数字 > 1
目标目录/etc空间剩余：128.8M
确认安装？(1/0) > 1
-----------------------------------------------
开始从服务器获取安装文件！
-----------------------------------------------

curl: (28) Connection timed out after 5019 milliseconds
sh: missing ]
文件下载失败,请尝试使用其他安装源！

**Comment by juewuy** [comment]
使用shellclash.ga源安装测试版

**Comment by wangchuanyes** [comment]
已经解决，使用作者提供的低版本wget安装方式export url='http://shellclash.ga/' && wget -q -O /tmp/install.sh $url/install.sh  && sh /tmp/install.sh && source /etc/profile &> /dev/null
