### ISSUE TITLE
黑/白名单模式下，设置为不走 clash 的设备，无法访问 dashboard

### ISSUE THREAD

**Issue by Mongkii** [juewuy/ShellClash#115]
是否可以支持访问？

----
 我的场景是：
 路由器安装 clash 给游戏加速，因此设置了白名单，只让游戏主机走 clash。

有时需要切换 clash 为全局/规则，想用手机访问 dashboard 修改设置，因为不在白名单内，打开 url 只能看到文件目录，而不是 ui 面板。

**Comment by juewuy** [comment]
抱歉，未能复现此问题
请提供相关报错截图

**Comment by Mongkii** [comment]
> 抱歉，未能复现此问题 请提供相关报错截图

1.5.0 之前版本的问题，升级到 1.5.0+ 后解决
