### ISSUE TITLE
DNS查询全部失败是怎么回事？

### ISSUE THREAD

**Issue by torobucks** [juewuy/ShellClash#116]
[TCP] dial 🐟 漏网之鱼 (match Match/) to xxx error: xxx.com connect error: all DNS requests failed, first error: Post "https://doh.opendns.com/dns-query": x509: certificate signed by unknown authority
是不是因为缺少open ssl呢？我是在小米路由Pro(R3P)上安装，整体运行没问题，就是没法正常工作。

**Comment by juewuy** [comment]
证书问题，使用非加密dns即可

**Comment by torobucks** [comment]
> 证书问题，使用非加密dns即可

请问在哪里设置啊

**Comment by torobucks** [comment]
小小成功，继续研究
