### ISSUE TITLE
VPS开启本地代理后Docker无法下载镜像

### ISSUE THREAD

**Issue by KawausoJyou** [juewuy/ShellClash#117]
会出现这种情况：
![image](https://user-images.githubusercontent.com/92703641/152296740-497d07bc-0a3e-4650-a62a-2de4484f9cdc.png)
设置如下：
![image](https://user-images.githubusercontent.com/92703641/152296830-985593eb-53eb-47a2-870d-9ed7250a371b.png)
ShellClash版本如下：
![image](https://user-images.githubusercontent.com/92703641/152296874-8d5f4e9f-3d11-430a-a6a5-e1c7b6fbb17c.png)

**Comment by juewuy** [comment]
请提供dashboard面板访问日志

**Comment by KawausoJyou** [comment]
拉取镜像时日志没有变化，直接显示上图中的错误🥲
2022年2月3日 +0800 16:06 juewuy ***@***.***>，写道：

**Comment by KawausoJyou** [comment]
> 请提供dashboard面板访问日志

![image](https://user-images.githubusercontent.com/92703641/152319025-16bc33f1-0a52-4c26-90a9-cc8ad83e993a.png)
这是访问日志，在规则里面看到下图规则
![image](https://user-images.githubusercontent.com/92703641/152320023-b07f5029-2347-46d6-9125-ea03e4d001cf.png)
不过我订阅的规则中并没有这一条，在ShellClash中搜索可以搜到相关内容。
![image](https://user-images.githubusercontent.com/92703641/152320176-74567ff5-2dc6-4c54-b44a-62521ace5a96.png)
不知是否有关

**Comment by KawausoJyou** [comment]
![image](https://user-images.githubusercontent.com/92703641/152330218-fd4f9e95-d8d9-410e-9544-b21010aef981.png)
这是内网解析出问题了吗？

**Comment by juewuy** [comment]
不要用fakeip
