### ISSUE TITLE
start.sh第269行多了一个mode导致每次启动报错

### ISSUE THREAD

**Issue by kurtn2005** [juewuy/ShellClash#118]
[ -n "$(cat $yaml | grep -E '^script:')" ] && mode='mode: Script'

这行在生成配置文件会多写一个mode，yaml里面就变成了mode: mode: Script导致解析失败，不知道Rule一类字段的是不是也有这个问题。

[ -n "$(cat $yaml | grep -E '^script:')" ] && mode='Script'

就行了。

**Comment by kurtn2005** [comment]
应该是277行多写了一个mode:

**Comment by juewuy** [comment]
上次适配自适应mode时忘记移除这段代码，已移除
