### ISSUE TITLE
只有一个自建Trojan节点，在线生成config.yaml配置后上不了网

### ISSUE THREAD

**Issue by wangchuanyes** [juewuy/ShellClash#119]
我自建的Trojan节点只有域名、443端口、密码这三个参数，哪位大神帮忙传个写好的config.yaml，我自己填上这三个参数就能用的那种。我个人再到/etc/clash目录里面去替换，万分感谢！
我觉得我用不到太多的规则，绕过大陆IP就行，GFWList更好。有人写了https://github.com/poplovetorock/gfwrules 但是不是给shellclash用的，格式不一样怎不知道怎么修改。
我目前是自己用配置参数写成trojan://密码@域名:443?peer=#别名的格式再转换成订阅链接，然后用shellclash生成config.yaml配置文件的，无论内外完全不能上网。

**Comment by juewuy** [comment]
不要包含#号注释
trojan只需要密码域名端口即可
