### ISSUE TITLE
华硕AX86U断开SSH会话后会自动退出后台

### ISSUE THREAD

**Issue by feijj** [juewuy/ShellClash#120]
连接SSH，启动Clash，然后断开SSH会话后，Clash会停止服务。重复启动退出启动退出几次后，watchdog似乎会起作用然后使Clash常驻。

**Comment by juewuy** [comment]
这是华硕系统的问题，等待1分钟后后台就会自动拉起

**Comment by juewuy** [comment]
1.5.2版本已修复
