### ISSUE TITLE
使用后很多国内网站和服务打开不正常，谁有绕过局域网和大陆地址的规则？

### ISSUE THREAD

**Issue by sirliu** [juewuy/ShellClash#122]
如题，比如淘宝直播啥的，很难打开。。。不像OpenWrt的酸酸乳客户端，通过DNS记录和IP规则，可以使用绕过局域网和大陆地址......
谁有这样的clash规则文件，求分享？

**Comment by juewuy** [comment]
6-1里有大量成熟的在线规则都可以套用
