### ISSUE TITLE
红米AC2100官方系统 配置好clash之后无法访问google

### ISSUE THREAD

**Issue by huangxiangdan** [juewuy/ShellClash#124]
红米AC2100官方系统，配置好clash之后，国内网址可以访问，国外网址无法访问。但通过连接上clash的7890代理端口，外网访问正常。排除是翻墙服务器不稳定的问题。怀疑问题出在iptables的配置上。

在iptables里找到如下信息，不知是否有影响
```
Chain prerouting_lan_rule (1 references)
target     prot opt source               destination         
REDIRECT   udp  --  anywhere             anywhere             udp dpt:domain u32 "0x0>>0x16&0x3c@0x14&0xffdfdfdf=0x3575757&&0x0>>0x16&0x3c@0x18&0xffdfdfdf=0x64d4957&&0x0>>0x16&0x3c@0x1c&0xdfdfdfff=0x49464903&&0x0>>0x16&0x3c@0x20&0xdfdfdf00=0x434f4d00" redir ports 53

REDIRECT   udp  --  anywhere             anywhere             udp dpt:domain u32 "0x0>>0x16&0x3c@0x14&0xffdfdfdf=0x64d4957&&0x0>>0x16&0x3c@0x18&0xdfdfdfff=0x49464903&&0x0>>0x16&0x3c@0x1c&0xdfdfdf00=0x434f4d00" redir ports 53
```

telegram貌似不能说话，进去没多久好像就被踢了，只能这里提问了。

**Comment by huangxiangdan** [comment]
我后面删掉53端口的prerouting，但好像也不起作用。贴上iptables的配置

 1 查看clash运行时的报错信息
 2 查看系统DNS端口(:53)占用 
 3 测试ssl加密（aes-128-gcm）跑分
 4 查看iptables端口转发详情
 5 查看config.yaml前40行
 6 测试代理服务器连通性（google.tw)
 7 重新进入新手引导
 9 查看后台脚本运行日志
-----------------------------------------------
 0 返回上级目录！
请输入对应数字 > 4
-----------------------------------------------
Chain PREROUTING (policy ACCEPT)
num  target     prot opt source               destination         
1    clash      tcp  --  anywhere             dns.google          
2    zone_lan_prerouting  all  --  anywhere             anywhere             /* !fw3 */
3    zone_ready_prerouting  all  --  anywhere             anywhere             /* !fw3 */
4    zone_guest_prerouting  all  --  anywhere             anywhere             /* !fw3 */
5    clash_dns  udp  --  anywhere             anywhere            
6    clash      tcp  --  anywhere             anywhere            
-----------------------------------------------
Chain clash (2 references)
num  target     prot opt source               destination         
1    RETURN     all  --  anywhere             0.0.0.0/8           
2    RETURN     all  --  anywhere             10.0.0.0/8          
3    RETURN     all  --  anywhere             127.0.0.0/8         
4    RETURN     all  --  anywhere             169.254.0.0/16      
5    RETURN     all  --  anywhere             172.16.0.0/12       
6    RETURN     all  --  anywhere             192.168.0.0/16      
7    RETURN     all  --  anywhere             base-address.mcast.net/4 
8    RETURN     all  --  anywhere             240.0.0.0/4         
9    RETURN     all  --  anywhere             anywhere             match-set cn_ip dst
10   REDIRECT   tcp  --  anywhere             anywhere             multiport dports ssh,domain,submission,ssmtp,pop3s,imaps,imap2,www,https,8080 redir ports 7892
-----------------------------------------------
Chain clash_dns (1 references)
num  target     prot opt source               destination         
1    REDIRECT   udp  --  anywhere             anywhere             udp dpt:domain redir ports 1053
2    REDIRECT   tcp  --  anywhere             anywhere             tcp dpt:domain redir ports 1053
-----------------------------------------------
Chain PREROUTING (policy ACCEPT)
num  target     prot opt source               destination         
1    clashv6_dns  udp      anywhere             anywhere            
-----------------------------------------------
ip6tables: No chain/target/match by that name.
-----------------------------------------------
Chain clashv6_dns (1 references)
num  target     prot opt source               destination

**Comment by juewuy** [comment]
尝试使用7-6里的使用dnsmasq转发功能
还不行就删除自定义防火墙里的DNS相关内容亦可

**Comment by huangxiangdan** [comment]
结案了，ip6tables版本太低了，1.4.12，不支持nat。 https://www.snbforums.com/threads/any-plan-to-update-ip-6-tables.50074/

我在电脑上禁用ipv6就可以访问了。难怪启动的时候提示，
```
ip6tables v1.4.12.2: unknown option "--to"
Try `ip6tables -h' or 'ip6tables --help' for more information.
ip6tables v1.4.12.2: unknown option "--to"
Try `ip6tables -h' or 'ip6tables --help' for more information.
```
