### ISSUE TITLE
start.sh进程很多是否正常？

### ISSUE THREAD

**Issue by kurtn2005** [juewuy/ShellClash#125]
ubuntu@raspberrypi:~$ ps -ef|grep start.sh|wc -l
122

有122个，是否正常呢？

<img width="766" alt="image" src="https://user-images.githubusercontent.com/23029247/154829688-392719d9-ac56-496e-83f6-4933bc901b98.png">

<img width="536" alt="image" src="https://user-images.githubusercontent.com/23029247/154829696-21e36ad4-7c9e-45c6-98f6-9aed4f8e4019.png">

**Comment by juewuy** [comment]
不正常，尝试更新最新测试版

**Comment by kurtn2005** [comment]
测试版没有这个问题。

**Comment by kurtn2005** [comment]
今天发现测试版本还是有很多进程。

ubuntu@raspberrypi:~$ ps -ef|grep clash |wc -l
243

可能之前是我观察时间短。

**Comment by juewuy** [comment]
是持续的吗？还是只是开机后一会儿？

**Comment by juewuy** [comment]
我用wsl2的Ubuntu未能复现你的问题

**Comment by kurtn2005** [comment]
> 是持续的吗？还是只是启动后一会儿？

刚启动没有这个现象，过了一天看就是这样了。

我是用树莓派4B，ubuntu 20.04.4，root用户安装。我看是start.sh steaming这个进程多，我看了一下我的配置。

<img width="201" alt="image" src="https://user-images.githubusercontent.com/23029247/158553059-78a33f56-bc0d-4a8f-be6b-d26a3c4f54dc.png">

**Comment by juewuy** [comment]
好的，我再观察一下

**Comment by juewuy** [comment]
我这边改成每5分钟执行一次，依然没能复现问题呃
建议继续更新到最新测试版，再尝试一下

**Comment by kurtn2005** [comment]
> 我这边改成每5分钟执行一次，依然没能复现问题呃
> 建议继续更新到最新测试版，再尝试一下

我更新到1.5.4，间隔1小时，试试看。

**Comment by kurtn2005** [comment]
1.5.5测试版没有复现该问题。
