### ISSUE TITLE
输入clash命令后无反应，

### ISSUE THREAD

**Issue by dddd64693** [juewuy/ShellClash#126]
![image](https://user-images.githubusercontent.com/14047878/155078021-0e81ed84-ba2f-4efb-9f5b-b233d6a141fc.png)
![image](https://user-images.githubusercontent.com/14047878/155078118-8942258f-f26c-4414-9c0b-fe18275a5066.png)

**Comment by juewuy** [comment]
尝试重装脚本或者重启设备，如果依然无法解决请使用clash -t命令查看问题出现在哪一步

**Comment by signfind** [comment]
u can test with this command : `source /etc/profile`
