### ISSUE TITLE
Steaming 预解析脚本问题

### ISSUE THREAD

**Issue by wzxjohn** [juewuy/ShellClash#130]
https://github.com/juewuy/ShellClash/blob/6e4b4e14a65b1b801231775c713943f2880369aa/scripts/start.sh#L924-L945

在 Linux 机器上测试发现，两个问题：
1. 第一次使用 `${dns_port}` 变量在 `getconfig` 之后，导致取不到值，解析一直失败，导致死循环。数天后卡死服务器，只能重启
2. CentOS 上 nslookup 的[正确语法](https://linux.die.net/man/1/nslookup)是 `nslookup -port=${dns_port} baidu.com`，脚本里的方法由于无法获取返回值导致一直卡住死循环

**Comment by juewuy** [comment]
语法是为了兼容
getconfig确实是bug，下一版本修改

**Comment by JohyC** [comment]
> 语法是为了兼容 getconfig确实是bug，下一版本修改

能不能测试版先上一个修复的！我的debian10也有这个问题，最近一直在找解决方法。。

**Comment by wzxjohn** [comment]
> 语法是为了兼容 getconfig确实是bug，下一版本修改

语法兼容这里，我测试了常见的 Linux 发行版，他们的 `nslookup` 命令默认均来自 `bind-utils`。这个组件的源码在这里：https://gitlab.isc.org/isc-projects/bind9/-/blob/main/bin/dig/nslookup.c
可以看到，Linux 下 `bind-utils` 里的 `nslookup` 是不支持 `:53` 这种语法的，所以该脚本在常见 Linux 发行版下均会卡住死循环。因此这里可能需要根据具体的执行环境切换不同的执行语句，来进行兼容了。

另外，这里的死循环建议加上兜底策略。否则就会在 Linux 机器上必现的遇到开启该功能后，每个更新周期新起一个死循环，直到最后把机器搞死的情况出现。

**Comment by wzxjohn** [comment]
> > 语法是为了兼容 getconfig确实是bug，下一版本修改
> 
> 能不能测试版先上一个修复的！我的debian10也有这个问题，最近一直在找解决方法。。

@JohyC 你可以先本地修改这个文件，把 `getconfig` 提前到第一个 `while` 循环前，并将 `nslookup` 命令改成 `nslookup -port=${dns_port}` 这个格式，就可以跑起来了。

这是我本地修改之后的脚本：

```bash
steaming)	 
                getconfig 
 		#设置循环检测clashDNS端口 
 		i=1 
 		while [ $i -lt 10 ];do 
 			sleep 1 
 			nslookup -port=${dns_port} baidu.com 127.0.0.1 > /dev/null 2>&1 
 			[ "$?" = 0 ] && i=10 
 		done 
 		steaming_dns(){ 
 			steaming_dir=$clashdir/steaming/${steaming_type}_Domains.list 
 			if [ ! -f "$steaming_dir" ];then 
 				echo 未找到$steaming_type域名数据库，正在下载！ 
 				mkdir -p $clashdir/steaming 
 				$0 webget "$steaming_dir" "$update_url/bin/${steaming_type}_Domains.list" 
 				[ "$?" = "1" ] && logger "$steaming_type数据库文件下载失败" 
 			fi 
 			if [ -f "$steaming_dir" ];then 
 				for line in $(cat $steaming_dir);do 
 					[ -n "$line" ] && nslookup -port=${dns_port} "$line" 127.0.0.1 
 				done >/dev/null 2>&1 
 				echo "$steaming_type域名预解析完成！" 
```

**Comment by JohyC** [comment]
> > > 语法是为了兼容 getconfig确实是bug，下一版本修改
> > 
> > 
> > 能不能测试版先上一个修复的！我的debian10也有这个问题，最近一直在找解决方法。。
> 
> @JohyC 你可以先本地修改这个文件，把 `getconfig` 提前到第一个 `while` 循环前，并将 `nslookup` 命令改成 `nslookup -port=${dns_port}` 这个格式，就可以跑起来了。 另外记得将已经跑起来的 `start.sh steaming` 进程 kill 掉，不然死循环还会一直吃资源。
> 
> 这是我本地修改之后的脚本：
> 
> ```shell
> steaming)	 
>                 getconfig 
>  		#设置循环检测clashDNS端口 
>  		i=1 
>  		while [ $i -lt 10 ];do 
>  			sleep 1 
>  			nslookup -port=${dns_port} baidu.com 127.0.0.1 > /dev/null 2>&1 
>  			[ "$?" = 0 ] && i=10 
>  		done 
>  		steaming_dns(){ 
>  			steaming_dir=$clashdir/steaming/${steaming_type}_Domains.list 
>  			if [ ! -f "$steaming_dir" ];then 
>  				echo 未找到$steaming_type域名数据库，正在下载！ 
>  				mkdir -p $clashdir/steaming 
>  				$0 webget "$steaming_dir" "$update_url/bin/${steaming_type}_Domains.list" 
>  				[ "$?" = "1" ] && logger "$steaming_type数据库文件下载失败" 
>  			fi 
>  			if [ -f "$steaming_dir" ];then 
>  				for line in $(cat $steaming_dir);do 
>  					[ -n "$line" ] && nslookup -port=${dns_port} "$line" 127.0.0.1 
>  				done >/dev/null 2>&1 
>  				echo "$steaming_type域名预解析完成！" 
> ```

啊！好的，我马上去修改。困扰我好几天了。。。

**Comment by juewuy** [comment]
好的，周末更新

**Comment by juewuy** [comment]
https://github.com/juewuy/ShellClash/commit/76a24bee7aca5e9ad15d7c15db57c80cd7cfaa1a
