### ISSUE TITLE
无线mesh，子路由clash无效，求设置方法。

### ISSUE THREAD

**Issue by czrwill** [juewuy/ShellClash#131]
无线mesh，子路由clash无效。不知道是不是需要设置什么，找了网上那些；都是有线mesh的办法。求无线mesh的设置办法。

**Comment by czrwill** [comment]
> 无线mesh，子路由clash无效。不知道是不是需要设置什么，找了网上那些；都是有线mesh的办法。求无线mesh的设置办法。

**Comment by saury** [comment]
碰到一样的问题，保守模式开了没用。。。还要改别的配置吗？
