### ISSUE TITLE
【建议】可以加上filebrowser

### ISSUE THREAD

**Issue by Mr-xn** [juewuy/ShellClash#134]
如题，加上 [filebrowser](https://github.com/filebrowser/filebrowser) 
1. 方便在线编辑配置文件和更新 clash 内核 
2. filebrowser是跨平台的，实际测试在路由器上可行

tips: 当然这个可以作为一个备选功能，用户自行选择是否安装

**Comment by juewuy** [comment]
太臃肿了

**Comment by Mr-xn** [comment]
好吧 个人需求 #134
