### ISSUE TITLE
有关内置dns

### ISSUE THREAD

**Issue by Borelset** [juewuy/ShellClash#136]
clash脚本中就有配置dns的参数，shellclash在菜单中也有一个内置dns配置，这两个是什么关系呢？

**Comment by juewuy** [comment]
小白建议用菜单
熟手可以用自定义配置文件功能
大佬直接改代码就行

**Comment by qqjianyue** [comment]
Clash内置DNS cache住 DDNS的旧值
导致家里内部网络访问DDNS域名反而无效

临时解决方案， 在DDNS更新记录的后面加上脚本同时更新[clash自定义hos](https://juewuy.github.io/chang-jian-wen-ti/#%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8%E8%87%AA%E5%AE%9A%E4%B9%89host)t(user.yaml)再重启clash
有什么更好的接口可以动态更新自定义host

**Comment by juewuy** [comment]
ddns查询外部IP靠的是在线地址或者本地网口，不懂和DNS有什么关系呢？
你ddns查询如果地址路由了内核，外部网站识别的就是你内核所在设备的地址而不是下级设备地址，这才是问题所在

**Comment by qqjianyue** [comment]
> 

我的ddns更新[没经内核](https://juewuy.github.io/chang-jian-wen-ti/#%E7%BE%A4%E8%BE%89ddns%E6%9C%8D%E5%8A%A1%E5%A4%B1%E6%95%88)，这个没问题， 谢谢Juewuy大牛的文档

问题是clash劫持了局域网的dns解析，我在局域网查询我的入口域名时，很经常查到局域网dns解析服务缓存的旧IP
（nslookup 显示的dns默认服务器是路由器的dns服务器地址）

我的域名A记录（TTL应该是1分钟）很快在上游域名服务器更新正确了，但是clash的内核域名服务还cache住旧值（几个小时候后还这样）
所以导致很尴尬的状态在局域网解析自己局域网入口反而失败，手机切换到4G/5G网络，反而很正确地访问到家里局域网入口

**Comment by juewuy** [comment]
这个问题比较无解，我没有在官方文档找到刷新内置DNS缓存的办法
可以尝试使用DNS进阶设置里启用dnsmasq转发试试，但不保证有效
