### ISSUE TITLE
在AX3600上似乎tun模式不能用

### ISSUE THREAD

**Issue by Borelset** [juewuy/ShellClash#140]
个人怀疑是ax3600内置的网游加速器把tun占用了，对于这种情况有什么应对方案吗

**Comment by ericsyj** [comment]
请问现在能用了吗，我这里还是用不了

**Comment by juewuy** [comment]
@ericsyj 一直可以，不能用通常是固化引发的bug或者使用了内置网游加速器

**Comment by ericsyj** [comment]
@juewuy 我没有使用内置的加速器，请问大佬如果是固化的bug应该怎么处理呢

**Comment by juewuy** [comment]
@ericsyj 换教程重做固化

**Comment by ericsyj** [comment]
@juewuy 重做固化没用，我还原之前的bdata分区后，降级到1.0.17版本，然后直接用web开启ssh，没有固化，尝试后发现也不能用，通过ifconfig可以看到utun网卡，但是就是没有用，确认没有开启内置加速器，而且clash日志里面也什么都没有，应该是流量完全没有经过clash内核，然后dns也出问题了，局域网内所有设备都解析不了网页了。
![image](https://user-images.githubusercontent.com/97294040/187980676-3a2e015a-ae57-4b52-87c8-5695a5cccb09.png)

**Comment by juewuy** [comment]
@ericsyj 我只能告诉你是个例，其他爱莫能助
