### ISSUE TITLE
使用内置序号为1的规则，Safari内词条右键“谷歌”搜索，无法访问

### ISSUE THREAD

**Issue by findyy99** [juewuy/ShellClash#143]
<img width="704" alt="image" src="https://user-images.githubusercontent.com/26852735/160279963-8afcad7a-27d6-4579-b218-d933365954e7.png">
但是只访问Google又是OK的。

<img width="748" alt="image" src="https://user-images.githubusercontent.com/26852735/160280021-ef229e64-9e15-41d7-9547-5f1e925d8504.png">

**Comment by juewuy** [comment]
请提供相关访问时面板的访问日志
