### ISSUE TITLE
希望可以支持alpine linux

### ISSUE THREAD

**Issue by huangzulin** [juewuy/ShellClash#144]
希望可以支持alpine linux

**Comment by juewuy** [comment]
现在使用有什么问题吗？

**Comment by huangzulin** [comment]
安装环境 pve下虚拟apline linux，下载install.sh 执行可以安装，但是出现其他问题
![image](https://user-images.githubusercontent.com/9855749/160622373-eb4743b6-250d-4a52-855d-1de466bfeedf.png)

**Comment by huangzulin** [comment]
再有一个问题就是 apline linux 使用的是openRC管理服务，不知道shellclash有没有考虑到这个

**Comment by juewuy** [comment]
第一个应该是你使用的cdn源访问失败导致的
第二个问题所的很清楚，非root用户要额外source环境变量，或者重新进入ssh

管理服务的话可以使用保守模式，只需要支持crontab就行

**Comment by juewuy** [comment]
我在docker下直接使用 docker run -t -i alpine /bin/sh
安装没发现什么问题，缺少curl和contab需要手动apk add

**Comment by huangzulin** [comment]
谢谢，已按照安装必要的组件，成功安装

**Comment by zhuwei** [comment]
请问面板访问，但无法登录，怎么解决？默认显示了docker容器内部ip

**Comment by juewuy** [comment]
@zhuwei 替换成你映射出去的外部IP
