### ISSUE TITLE
小米AX3600默认小米固件破解ssh后安装ShellClash时的报错

### ISSUE THREAD

**Issue by AlanBacker** [juewuy/ShellClash#147]
未找到clash核心，正在下载！
###################################################################################################################################################################################################################### 100.0% -=O=-         #         #           #             #                                                                                                                                                                        
curl: (28) Connection timed out after 3138 milliseconds
###################################################################################################################################################################################################################### 100.0%###################################################################################################################################################################################################################### 100.0%panic: reflect: call of reflect.Value.Type on zero Value

goroutine 1 [running]:
reflect.Value.Type({0x0, 0x0, 0x0})
        reflect/value.go:2249 +0x178
github.com/Dreamacro/clash/common/structure.(*Decoder).decodeString(0x400017f570, {0x4000456230, 0xa}, {0x0, 0x0}, {0x422c00, 0x4000324260, 0x198})
        github.com/Dreamacro/clash/common/structure/structure.go:120 +0x1a4
github.com/Dreamacro/clash/common/structure.(*Decoder).decode(0x400017f570, {0x4000456230, 0xa}, {0x0, 0x0}, {0x422c00, 0x4000324260, 0x198})
        github.com/Dreamacro/clash/common/structure/structure.go:70 +0x3bc
github.com/Dreamacro/clash/common/structure.(*Decoder).decodeSlice(0x400017f570, {0x40ce9a, 0x7}, {0x41d980, 0x400011e9a8}, {0x41e840, 0x40003f9e50, 0x197})
        github.com/Dreamacro/clash/common/structure/structure.go:161 +0x3a4
github.com/Dreamacro/clash/common/structure.(*Decoder).decode(0x400017f570, {0x40ce9a, 0x7}, {0x41d980, 0x400011e9a8}, {0x41e840, 0x40003f9e50, 0x197})
        github.com/Dreamacro/clash/common/structure/structure.go:74 +0x1b4
github.com/Dreamacro/clash/common/structure.(*Decoder).Decode(0x400017f570, 0x40001b6ed0, {0x413ae0, 0x40003f9e30})
        github.com/Dreamacro/clash/common/structure/structure.go:57 +0x3d4
github.com/Dreamacro/clash/config.proxyGroupsDagSort({0x400010c370, 0xa, 0xa})
        github.com/Dreamacro/clash/config/utils.go:40 +0x114
github.com/Dreamacro/clash/config.parseProxies(0x400018a200)
        github.com/Dreamacro/clash/config/config.go:310 +0x9fc
github.com/Dreamacro/clash/config.ParseRawConfig(0x400018a200)
        github.com/Dreamacro/clash/config/config.go:210 +0xd0
github.com/Dreamacro/clash/config.Parse({0x4000280000, 0x2a661, 0x2a662})
        github.com/Dreamacro/clash/config/config.go:157 +0x6c
github.com/Dreamacro/clash/hub/executor.ParseWithBytes(...)
        github.com/Dreamacro/clash/hub/executor/executor.go:65
github.com/Dreamacro/clash/hub/executor.ParseWithPath({0x4000122138, 0x16})
        github.com/Dreamacro/clash/hub/executor/executor.go:60 +0x74
github.com/Dreamacro/clash/hub/executor.Parse(...)
        github.com/Dreamacro/clash/hub/executor/executor.go:50
main.main()
        github.com/Dreamacro/clash/main.go:76 +0x3a8
clash服务启动失败！请查看报错信息！
panic: reflect: call of reflect.Value.Type on zero Value

goroutine 1 [running]:
reflect.Value.Type({0x0, 0x0, 0x0})
        reflect/value.go:2249 +0x178
github.com/Dreamacro/clash/common/structure.(*Decoder).decodeString(0x4000175570, {0x4000450230, 0xa}, {0x0, 0x0}, {0x422c00, 0x400038a220, 0x198})
        github.com/Dreamacro/clash/common/structure/structure.go:120 +0x1a4
github.com/Dreamacro/clash/common/structure.(*Decoder).decode(0x4000175570, {0x4000450230, 0xa}, {0x0, 0x0}, {0x422c00, 0x400038a220, 0x198})
        github.com/Dreamacro/clash/common/structure/structure.go:70 +0x3bc
github.com/Dreamacro/clash/common/structure.(*Decoder).decodeSlice(0x4000175570, {0x40ce9a, 0x7}, {0x41d980, 0x40001149c0}, {0x41e840, 0x40003f3e50, 0x197})
        github.com/Dreamacro/clash/common/structure/structure.go:161 +0x3a4
github.com/Dreamacro/clash/common/structure.(*Decoder).decode(0x4000175570, {0x40ce9a, 0x7}, {0x41d980, 0x40001149c0}, {0x41e840, 0x40003f3e50, 0x197})
        github.com/Dreamacro/clash/common/structure/structure.go:74 +0x1b4
github.com/Dreamacro/clash/common/structure.(*Decoder).Decode(0x4000175570, 0x400022aed0, {0x413ae0, 0x40003f3e30})
        github.com/Dreamacro/clash/common/structure/structure.go:57 +0x3d4
github.com/Dreamacro/clash/config.proxyGroupsDagSort({0x4000100370, 0xa, 0xa})
        github.com/Dreamacro/clash/config/utils.go:40 +0x114
github.com/Dreamacro/clash/config.parseProxies(0x4000200200)
        github.com/Dreamacro/clash/config/config.go:310 +0x9fc
github.com/Dreamacro/clash/config.ParseRawConfig(0x4000200200)
        github.com/Dreamacro/clash/config/config.go:210 +0xd0
github.com/Dreamacro/clash/config.Parse({0x4000280000, 0x2a661, 0x2a662})
        github.com/Dreamacro/clash/config/config.go:157 +0x6c
github.com/Dreamacro/clash/hub/executor.ParseWithBytes(...)
        github.com/Dreamacro/clash/hub/executor/executor.go:65
github.com/Dreamacro/clash/hub/executor.ParseWithPath({0x4000118138, 0x16})
        github.com/Dreamacro/clash/hub/executor/executor.go:60 +0x74
github.com/Dreamacro/clash/hub/executor.Parse(...)
        github.com/Dreamacro/clash/hub/executor/executor.go:50
main.main()
        github.com/Dreamacro/clash/main.go:76 +0x3a8
panic: reflect: call of reflect.Value.Type on zero Value

goroutine 1 [running]:
reflect.Value.Type({0x0, 0x0, 0x0})
        reflect/value.go:2249 +0x178
github.com/Dreamacro/clash/common/structure.(*Decoder).decodeString(0x400017f570, {0x4000458230, 0xa}, {0x0, 0x0}, {0x422c00, 0x4000324260, 0x198})
        github.com/Dreamacro/clash/common/structure/structure.go:120 +0x1a4
github.com/Dreamacro/clash/common/structure.(*Decoder).decode(0x400017f570, {0x4000458230, 0xa}, {0x0, 0x0}, {0x422c00, 0x4000324260, 0x198})
        github.com/Dreamacro/clash/common/structure/structure.go:70 +0x3bc
github.com/Dreamacro/clash/common/structure.(*Decoder).decodeSlice(0x400017f570, {0x40ce9a, 0x7}, {0x41d980, 0x400011e9c0}, {0x41e840, 0x40003fbde0, 0x197})
        github.com/Dreamacro/clash/common/structure/structure.go:161 +0x3a4
github.com/Dreamacro/clash/common/structure.(*Decoder).decode(0x400017f570, {0x40ce9a, 0x7}, {0x41d980, 0x400011e9c0}, {0x41e840, 0x40003fbde0, 0x197})
        github.com/Dreamacro/clash/common/structure/structure.go:74 +0x1b4
github.com/Dreamacro/clash/common/structure.(*Decoder).Decode(0x400017f570, 0x4000236ed0, {0x413ae0, 0x40003fbdc0})
        github.com/Dreamacro/clash/common/structure/structure.go:57 +0x3d4
github.com/Dreamacro/clash/config.proxyGroupsDagSort({0x400010c370, 0xa, 0xa})
        github.com/Dreamacro/clash/config/utils.go:40 +0x114
github.com/Dreamacro/clash/config.parseProxies(0x400020a200)
        github.com/Dreamacro/clash/config/config.go:310 +0x9fc
github.com/Dreamacro/clash/config.ParseRawConfig(0x400020a200)
        github.com/Dreamacro/clash/config/config.go:210 +0xd0
github.com/Dreamacro/clash/config.Parse({0x4000280000, 0x2a661, 0x2a662})
        github.com/Dreamacro/clash/config/config.go:157 +0x6c
github.com/Dreamacro/clash/hub/executor.ParseWithBytes(...)
        github.com/Dreamacro/clash/hub/executor/executor.go:65
github.com/Dreamacro/clash/hub/executor.ParseWithPath({0x4000122138, 0x16})
        github.com/Dreamacro/clash/hub/executor/executor.go:60 +0x74
github.com/Dreamacro/clash/hub/executor.Parse(...)
        github.com/Dreamacro/clash/hub/executor/executor.go:50
main.main()
        github.com/Dreamacro/clash/main.go:76 +0x3a8
Killed
-----------------------------------------------
欢迎使用ShellClash！            版本：1.5.6fix
Clash服务没有运行（Redir模式），已设置开机启动！
TG群：https://t.me/clashfm

**Comment by juewuy** [comment]
更新里重新安装内核

**Comment by AlanBacker** [comment]
ok谢谢大佬

**Comment by AlanBacker** [comment]
> 更新里重新安装内核

ok谢谢大佬

**Comment by AlanBacker** [comment]
> 更新里重新安装内核

不好意思，更新里是数字几啊

**Comment by juewuy** [comment]
9

**Comment by AlanBacker** [comment]
> 9

已解决！十分感谢
