### ISSUE TITLE
小米AX1800使用小米设备软固化SSH没有反应--请求支持！跪谢

### ISSUE THREAD

**Issue by laiqinghua** [juewuy/ShellClash#149]
root@XiaoQiang:/userdisk/data/clash# uname -r
4.4.60
root@XiaoQiang:/userdisk/data/clash# uname -a
Linux XiaoQiang 4.4.60 #0 SMP PREEMPT Tue Apr 7 09:37:26 2020 armv7l GNU/Linux
root@XiaoQiang:/userdisk/data/clash# cat /etc/os-release
NAME="OpenWrt"
VERSION="18.06-SNAPSHOT"
ID="openwrt"
ID_LIKE="lede openwrt"
PRETTY_NAME="OpenWrt 18.06-SNAPSHOT"
VERSION_ID="18.06-snapshot"
HOME_URL="http://openwrt.org/"
BUG_URL="http://bugs.openwrt.org/"
SUPPORT_URL="http://forum.lede-project.org/"
BUILD_ID="unknown"
LEDE_BOARD="ipq60xx/MiWiFi"
LEDE_ARCH="arm_cortex-a7"
LEDE_TAINTS="no-all busybox"
LEDE_DEVICE_MANUFACTURER="OpenWrt"
LEDE_DEVICE_MANUFACTURER_URL="http://openwrt.org/"
LEDE_DEVICE_PRODUCT="Generic"
LEDE_DEVICE_REVISION="v0"
LEDE_RELEASE="OpenWrt 18.06-SNAPSHOT unknown"
root@XiaoQiang:/userdisk/data/clash#

****************************
小米AX1800使用小米设备软固化SSH没有反应
一直提示
本页工具可能无法兼容全部Linux设备，请酌情使用！
磁盘占用/所在目录：
9.3M    /userdisk/data/clash
-----------------------------------------------
 1 ShellClash测试菜单
 2 配置外网访问SSH
 3 配置DDNS服务(需下载相关脚本)
 4 流媒体预解析————用于解决DNS解锁在TV应用上失效的问题
 5 启用小米系统自动更新
 6 小米设备软固化SSH ———— 未启用
-----------------------------------------------
 0 返回上级菜单
-----------------------------------------------
请输入对应数字 > 6
不支持的设备！
设置成功！
-----------------------------------------------
欢迎使用其他工具菜单：
本页工具可能无法兼容全部Linux设备，请酌情使用！
磁盘占用/所在目录：
9.3M    /userdisk/data/clash
-----------------------------------------------
 1 ShellClash测试菜单
 2 配置外网访问SSH
 3 配置DDNS服务(需下载相关脚本)
 4 流媒体预解析————用于解决DNS解锁在TV应用上失效的问题
 5 启用小米系统自动更新
 6 小米设备软固化SSH ———— 未启用
-----------------------------------------------
 0 返回上级菜单
-----------------------------------------------
请输入对应数字 > 6
不支持的设备！
设置成功！
-----------------------------------------------
欢迎使用其他工具菜单：
本页工具可能无法兼容全部Linux设备，请酌情使用！
磁盘占用/所在目录：
9.3M    /userdisk/data/clash
-----------------------------------------------
 1 ShellClash测试菜单
 2 配置外网访问SSH
 3 配置DDNS服务(需下载相关脚本)
 4 流媒体预解析————用于解决DNS解锁在TV应用上失效的问题
 5 启用小米系统自动更新
 6 小米设备软固化SSH ———— 未启用
-----------------------------------------------
 0 返回上级菜单
-----------------------------------------------
请输入对应数字 > 0

**Comment by juewuy** [comment]
暂时不支持的设备，后续会考虑

**Comment by laiqinghua** [comment]
感谢回复收到，期待此功能！
