### ISSUE TITLE
希望修改一下 请使用http://192.168.31.1/clash管理内置规则 这句话

### ISSUE THREAD

**Issue by Kandom** [juewuy/ShellClash#15]
在macOS的terminal中，如果使用control点击链接地址，会在浏览器中跳转到 http://192.168.31.1/clash管理内置规则  造成404错误，有一点不方便，谢谢

**Comment by juewuy** [comment]
这个是SSH终端自己的问题，没办法针对各个终端一一适配，建议存一下浏览器书签

发送自 Windows 10 版邮件应用

发件人: Kandom
发送时间: 2020年11月15日 10:30
收件人: juewuy/ShellClash
抄送: Subscribed
主题: [juewuy/ShellClash] 希望修改一下 请使用http://192.168.31.1/clash管理内置规则 这句话 (#15)

在macOS的terminal中，如果使用control点击链接地址，会在浏览器中跳转到 http://192.168.31.1/clash管理内置规则 造成404错误，有一点不方便，谢谢
