### ISSUE TITLE
[Feature request]建议增加 LAN 代理的 authentication 配置功能和 external-controller 的 secret 配置功能

### ISSUE THREAD

**Issue by zxkmm** [juewuy/ShellClash#152]
## 亲爱的开发者们，您好，有两个功能不知是否方便添加
# FR 1
希望增加 LAN 代理的认证设置，即配置文件中的
```
allow-lan: true
authentication:   # authentication of local SOCKS5/HTTP(S) server
  - "user1:pass1"
  - "user2:pass2"
```
# FR 2
希望增加外置控制器的secret功能，即
```
external-controller: :9999
external-ui: ui
secret: 
```
# 说明
不知是不是我的操作有问题，还是脚本有“自动纠错”功能，我尝试自行修改config.yaml，但是修改后执行clash会自动重新下载clash内核，然后配置文件被还原。
感谢亲爱的开发者们！祝天天开心

**Comment by juewuy** [comment]
请使用7-8

**Comment by zxkmm** [comment]
@juewuy 谢谢🙏抱歉，是我没注意已经有这个功能，我会关掉issue。
