### ISSUE TITLE
计划任务报错

### ISSUE THREAD

**Issue by crackerfly** [juewuy/ShellClash#153]
ShellClash版本：1.5.7
OS版本：21.02.2
执行任务：*/10 * * * * test -n "$(pidof clash)" && /etc/clash/start.sh web_save #每10分钟保存节点配置
错误提示：Thu Feb 11 20:50:00 2022 cron.err crond[9459]: user root pid cmd test -n "$(pidof clash)" && /etc/clash/start.sh web_save
备注：直接shell里执行是没问题的，怀疑是权限或路径问题，参考 https://blog.csdn.net/qq_29307291/article/details/72922058

**Comment by juewuy** [comment]
openwrt应该不存在权限问题，路径也一直是绝对路径
挺奇怪的，暂时无法定位问题原因
