### ISSUE TITLE
debian系统下用不了

### ISSUE THREAD

**Issue by auqfgmd** [juewuy/ShellClash#154]
安装好了 也设置好了 服务 正常打开
就是不能代理  不知道哪里出了问题
debian11.3  内核5.10
shellclash   1.5.1
redir模式
debian也放问不了外网

**Comment by juewuy** [comment]
网络问题请提供面板相关访问日志

**Comment by juewuy** [comment]
本机使用请启用本机代理功能
旁路由请正确设置网关和DNS

**Comment by auqfgmd** [comment]
> 本机使用请启用本机代理功能
> 旁路由请正确设置网关和DNS

![image](https://user-images.githubusercontent.com/51310550/164342802-423c779b-3696-4391-9cb6-45fa755c765e.png)![image](https://user-images.githubusercontent.com/51310550/164342814-19f918ce-bac6-4b89-9d93-e5749ab0304e.png)![image](https://user-images.githubusercontent.com/51310550/164342827-4837a580-d43d-43ca-9105-ef7dbf4f15b2.png)![image](https://user-images.githubusercontent.com/51310550/164342835-70fa08dd-e95b-4480-845f-2e4632087992.png)![image](https://user-images.githubusercontent.com/51310550/164342845-d581124c-7f97-4c77-a042-7cbd9bb9f318.png)![image](https://user-images.githubusercontent.com/51310550/164342855-d1f04704-5c0c-41bc-bef0-ef85b84285a0.png)
都设置了  但是把网关指向debian主机   还是不能访问google.com

**Comment by juewuy** [comment]
网关和DNS

**Comment by auqfgmd** [comment]
> 网关和DNS

你好  我主路由网关是192.168.254.254
debian  ip是192.168.254.250/24   网关192.168.254.254   dns61.147.37.1      61.177.7.1
现在的问题是  局域网pc用代理  是可以翻墙的   代理ip设置192.168.254.250   端口7890

但是pc设置debian系统的地址192.168.254.250做为网关是不能上网的


下面是debian的设置
![image](https://user-images.githubusercontent.com/51310550/164459567-98dd7bd6-bc6e-437f-9250-ba0a1e95614e.png)![image](https://user-images.githubusercontent.com/51310550/164459588-d8c6b268-a421-4819-992f-ba1fd9fd3c27.png)

**Comment by juewuy** [comment]
终端DNS也要指定

**Comment by auqfgmd** [comment]
> 终端DNS也要指定

dns设置debian系统 直接没有网络

**Comment by juewuy** [comment]
旁路由就是这么设置的
具体请参考常见问题
https://juewuy.github.io

**Comment by auqfgmd** [comment]
> 旁路由就是这么设置的
> 具体请参考常见问题
> https://juewuy.github.io
> 

好奇怪哦   还是找不到原因

**Comment by auqfgmd** [comment]
安装了很多个系统  问题依旧出现  还是没有找到问题所在    debian11.3 
centos7 
centos_stream9    
ubuntu server22.04
photon 4.0
大佬能不能抽个时间 远程帮我指导下   谢谢了

**Comment by juewuy** [comment]
请务必详细阅读常见问题

**Comment by auqfgmd** [comment]
好的

**Comment by auqfgmd** [comment]
ip转发开启了

**Comment by auqfgmd** [comment]
> 请务必详细阅读常见问题
> 

大佬 我的问题解决了   系统防火墙没关    关了 就好了
