### ISSUE TITLE
[问题] 小米路由器clash服务不稳定访问外网失败

### ISSUE THREAD

**Issue by Mao0509** [juewuy/ShellClash#161]
小米路由器
![image](https://user-images.githubusercontent.com/22870376/166494961-9b5cdd0b-abdf-4158-95c6-dbb757d022fd.png)
日志截图
![image](https://user-images.githubusercontent.com/22870376/166494524-4179e6db-5505-47b4-8db2-6c5fcac6c930.png)
有时能访问成功 但大部分时候访问失败
尝试过重启服务以及修改DNS运行模式 但没有解决
希望您有空时能指点一下

**Comment by juewuy** [comment]
更新一下最新测试版

**Comment by Mao0509** [comment]
更新到了新版本
![Screenshot 2022-05-04 010408](https://user-images.githubusercontent.com/22870376/166504136-eb6b8ab2-e407-4528-87e0-5fc20bf2ea68.png)
出现了SSL验证错误
日志正常打印
![Screenshot 2022-05-04 001938](https://user-images.githubusercontent.com/22870376/166504199-22199804-307a-4e60-8b91-1548e809bb13.png) 看起来未出现错误

尝试开启dnsmap转发以及切换fake-ip依然访问外网失败

**Comment by juewuy** [comment]
检查一下有没有其他第三方DNS软件强制劫持了本机DNS服务

**Comment by lemoeo** [comment]
红米ax6s安装了shellclash测试版，感觉也是不稳定，有时候能用有时候不能用。不知道咋回事，反正经常无法访问外网的情况，有时候特别慢

**Comment by juewuy** [comment]
@lemoeo 请先参考常见问题https://juewuy.github.io

**Comment by lemoeo** [comment]
> @lemoeo 请先参考常见问题https://juewuy.github.io

谢谢，貌似是dns设置的问题。重新设置了一下dns，再用几天看看稳定不稳定。
