### ISSUE TITLE
自动选择模式中，如果延迟最低的是一个错误的代理，那么默认模式容易卡死

### ISSUE THREAD

**Issue by fweiger** [juewuy/ShellClash#162]
是否可以在class命令行里 可以对代理进行删除。如果自动选择模式中，低延迟的一个是错误的代理或者失效的代理的话，整个模式就会出现BUG

建议：
1、可以对代理进行删除
2、如果日志出现代理错误，看看是不是可以向后一个低延迟代理跳转

**Comment by fweiger** [comment]
准确的应该是说，从网上拿到一堆代理，然后开始是可以用的，速度也还可以（我都是1M/S以下的全部过滤掉了）但是在使用过程中，会遇到这个代理，延迟很低，但是速度可能降低比较低，低到无法打开网页的情况（可能测试的时候会发现还是能测试连接成功），这种体验让人觉得速度会起不来。

**Comment by juewuy** [comment]
@fweiger 个人不建议使用聚合的免费节点，脚本也无法实现你需要的功能
