### ISSUE TITLE
TG 群打不开了

### ISSUE THREAD

**Issue by MBRjun** [juewuy/ShellClash#164]
![IMG_20220505_071747](https://user-images.githubusercontent.com/55020690/166840482-df9b04d8-70ad-4d91-ab5e-30fc0102d87a.jpg)

**Comment by juewuy** [comment]
交流群被误封，正在申诉，敬请稍安勿躁
有问题请加备用群提问
https://t.me/+wEE-5Luq6kAyODZl
关注发布频道不迷路
https://t.me/ShellClash
