### ISSUE TITLE
Openwrt本机代理模式无法使用

### ISSUE THREAD

**Issue by cnclg** [juewuy/ShellClash#165]
在openwrt 上打开“本机代理”模式，选择IPtables增强模式，提示当前设备无法使用增强模式！
是目前还不支持,还是本机相关设置有问题，谢谢！

**Comment by juewuy** [comment]
@cnclg 增强模式暂不支持非标准Linux设备

**Comment by cnclg** [comment]
@juewuy 感谢！特别是配合Meta内核，简单好用。
