### ISSUE TITLE
请问Mac下如何自定义规则？

### ISSUE THREAD

**Issue by tulifulegend** [juewuy/ShellClash#168]
提示说Windows下使用winscp进入/etc/clash目录后手动编辑，Mac 系统该怎么编辑呢？

**Comment by juewuy** [comment]
@tulifulegend 用scp命令操作下载上传

**Comment by tulifulegend** [comment]
> @tulifulegend 用scp命令操作下载上传

感谢作者，麻烦能详细告知下命令和步骤吗？我是文科生，完全没这方面的知识，正在一步一步摸索

**Comment by juewuy** [comment]
@tulifulegend 很麻烦

**Comment by juewuy** [comment]
@juewuy SecureFX for Mac
你可以尝试，但不保证可用
