### ISSUE TITLE
在禁用和卸载 ShellClash 后，路由器提供的 DNS 无法正常工作。

### ISSUE THREAD

**Issue by SimonShiki** [juewuy/ShellClash#169]
## 问题描述
在禁用和卸载 ShellClash 后，路由器提供的 DNS 无法正常工作。
## 详细描述
在 ShellClash 服务被禁用后，Wi-Fi 下的网络设备均无法正常访问互联网（表现为所有域名被重定向至192.168.x.x，即内置DNS服务器地址），在卸载后仍存在该问题。
## 详细信息
Xiaomi Router 3（R3P）原厂最新开发版

**Comment by juewuy** [comment]
@SimonShiki shellclash不会将DNS定向到192.168.xx，卸载后也不会继续工作，请检查其他问题

**Comment by jdjxk** [comment]
同样遇到此问题，关闭或卸载后，无法访问互联网，请问目前是否定位到原因？

**Comment by juewuy** [comment]
@jdjxk 是不是启用dnsmasq转发了

**Comment by jdjxk** [comment]
未启用

**Comment by juewuy** [comment]
@jdjxk 那是旁路由模式？

**Comment by juewuy** [comment]
@jdjxk 电脑上运行nslookup google.com 看一下

**Comment by jdjxk** [comment]
AX6主路由

**Comment by jdjxk** [comment]
Server:         10.0.0.1
Address:        10.0.0.1#53

Name:   google.com
Address: 172.217.163.46

**Comment by juewuy** [comment]
@jdjxk 这不是正常吗？

**Comment by jdjxk** [comment]
上面是打开的，停止Clash服务后如下：

;; communications error to 10.0.0.1#53: timed out
;; communications error to 10.0.0.1#53: timed out
;; communications error to 10.0.0.1#53: timed out
;; communications error to fe80::9e9d:7eff:fec5:f79a%8#53: timed out
;; no servers could be reached

**Comment by juewuy** [comment]
@jdjxk 重启设备也不行？

**Comment by jdjxk** [comment]
对的，重启啥的都试过了

**Comment by juewuy** [comment]
@jdjxk 脚本不会干扰原系统，你可以排查是否安装过其他应用

**Comment by jdjxk** [comment]
解锁之后只装过ShellClash，很奇怪，现在只能恢复原厂再试了

**Comment by xj233168** [comment]
遇到了相同问题，甚至重装shellclash也无法解决，在线更新脚本说无法从服务器下载安装文件，本地版安装后无法检查更新，安装内核，获取配置文件等，所有网络都跟不可用一样
