### ISSUE TITLE
ArchLinux，如果shellclash中重启clash，firefox中会出现pr_end_of_file_error，ui显示连接全是ip地址，没有域名

### ISSUE THREAD

**Issue by GuangDai** [juewuy/ShellClash#171]
我在clash_for_Windows中也遇到了类似的问题，也是最新的clash 内核。

我不确定是否是内核的问题，还是我的Arch问题，也没找到类似的issue。

发到这里是因为shell clash在我arch上的复现率几乎100%。不知道如何切换shell clash 的clash内核？如果能切换内核，我可以尝试测试之前的两个clash内核，并确定是否是clash内核的问题。

如果作者认为不应该在这里发issue，我将关闭这个issue，谢谢。

**Comment by juewuy** [comment]
@GuangDai 是否是启用了浏览器安全DNS？这与透明代理并不兼容。

**Comment by GuangDai** [comment]
> @GuangDai 是否是启用了浏览器安全DNS？这与透明代理并不兼容。

并没有启用。经过测试之后，发现是整个系统的网络都出现了这个问题。

**Comment by juewuy** [comment]
你可以直接到安装目录替换内核文件

**Comment by GuangDai** [comment]
> 你可以直接到安装目录替换内核文件

替换内核后也没有作用，尝试了几个版本的内核。我稍后会尝试其他系统，确认是否我的Arch在哪里出现了问题。

![image](https://user-images.githubusercontent.com/59678726/169630497-fb4c8ec2-0748-4db8-b833-fb3224a19f10.png)

**Comment by GuangDai** [comment]
> > 你可以直接到安装目录替换内核文件
> 
> 替换内核后也没有作用，尝试了几个版本的内核。我稍后会尝试其他系统，确认是否我的Arch在哪里出现了问题。
> 
> ![image](https://user-images.githubusercontent.com/59678726/169630497-fb4c8ec2-0748-4db8-b833-fb3224a19f10.png)

是我Arch的问题，切换到另一个arch衍生版，没有bug，我会关闭该issue
