### ISSUE TITLE
默认纯净模式导致无法正常代理

### ISSUE THREAD

**Issue by yourfriendyo** [juewuy/ShellClash#174]
我安装在centos7.6服务器上默认是纯净模式，该模式需要配置http/sock5代理。但默认这个是没有配置的，所以会导致无法代理。还是改成默认redir好一点。
![B8B8FACEA0C86AB7D50D8CB56E374523](https://user-images.githubusercontent.com/78334412/170799060-08e44188-da91-4363-abbf-580c4829395d.jpg)
另外最好提醒一下用户放开所需要的端口更好吧。^o^

**Comment by juewuy** [comment]
@yourfriendyo 没有所谓的默认，有新手引导，按需选择

**Comment by RikudouPatrickstar** [comment]
@yourfriendyo 用混合代理端口就可以了，同时支持socks5和http
