### ISSUE TITLE
路由器重启无法自动翻q

### ISSUE THREAD

**Issue by lifsux** [juewuy/ShellClash#18]
clash已设置开机自启动，但是路由器重启后不能自动翻q，需要手动进入ssh重新启动clash服务才能连接（手动进入clash后命令行显示clash服务是启动的，但是不能翻q）。总：存在开机不能自动fq的问题。ax1800最新固件（1.0.378 稳定版）。

**Comment by juewuy** [comment]
更新test版本或者切换一下clash运行模式

发送自 Windows 10 版邮件应用

发件人: lifsux
发送时间: 2020年12月11日 23:32
收件人: juewuy/ShellClash
抄送: Subscribed
主题: [juewuy/ShellClash] 路由器重启无法自动翻q (#18)

clash已设置开机自启动，但是路由器重启后不能自动翻q，需要手动进入ssh重新启动clash服务才能连接（手动进入clash后命令行显示clash服务是启动的，但是不能翻q）。总：存在开机不能自动fq的问题。ax1800最新固件（1.0.378 稳定版）。

**Comment by lifsux** [comment]
我用最新beta17版本。而且不装mixbox的话，clash命令无法运行，not found。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: juewuy <notifications@github.com&gt;
发送时间: 2020年12月12日 09:49
收件人: juewuy/ShellClash <ShellClash@noreply.github.com&gt;
抄送: lifsux <853956801@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[juewuy/ShellClash] 路由器重启无法自动翻q (#18)





 更新test版本或者切换一下clash运行模式 
 
 发送自 Windows 10 版邮件应用 
 
 发件人: lifsux 
 发送时间: 2020年12月11日 23:32 
 收件人: juewuy/ShellClash 
 抄送: Subscribed 
 主题: [juewuy/ShellClash] 路由器重启无法自动翻q (#18) 
 
 clash已设置开机自启动，但是路由器重启后不能自动翻q，需要手动进入ssh重新启动clash服务才能连接（手动进入clash后命令行显示clash服务是启动的，但是不能翻q）。总：存在开机不能自动fq的问题。ax1800最新固件（1.0.378 稳定版）。

**Comment by juewuy** [comment]
卸载重装一下

发送自 Windows 10 版邮件应用

发件人: lifsux
发送时间: 2020年12月12日 9:51
收件人: juewuy/ShellClash
抄送: juewuy; Comment
主题: Re: [juewuy/ShellClash] 路由器重启无法自动翻q (#18)

我用最新beta17版本。而且不装mixbox的话，clash命令无法运行，not found。 



发自我的iPhone 


------------------ 原始邮件 ------------------ 
发件人: juewuy <notifications@github.com&gt; 
发送时间: 2020年12月12日 09:49 
收件人: juewuy/ShellClash <ShellClash@noreply.github.com&gt; 
抄送: lifsux <853956801@qq.com&gt;, Author <author@noreply.github.com&gt; 
主题: 回复：[juewuy/ShellClash] 路由器重启无法自动翻q (#18) 





更新test版本或者切换一下clash运行模式 

发送自 Windows 10 版邮件应用 

发件人: lifsux 
发送时间: 2020年12月11日 23:32 
收件人: juewuy/ShellClash 
抄送: Subscribed 
主题: [juewuy/ShellClash] 路由器重启无法自动翻q (#18) 

clash已设置开机自启动，但是路由器重启后不能自动翻q，需要手动进入ssh重新启动clash服务才能连接（手动进入clash后命令行显示clash服务是启动的，但是不能翻q）。总：存在开机不能自动fq的问题。ax1800最新固件（1.0.378 稳定版）。

**Comment by lifsux** [comment]
clash命令不起作用的情况下，怎么卸载？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: juewuy <notifications@github.com&gt;
发送时间: 2020年12月12日 09:56
收件人: juewuy/ShellClash <ShellClash@noreply.github.com&gt;
抄送: lifsux <853956801@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[juewuy/ShellClash] 路由器重启无法自动翻q (#18)





卸载重装一下

发送自 Windows 10 版邮件应用

发件人: lifsux
发送时间: 2020年12月12日 9:51
收件人: juewuy/ShellClash
抄送: juewuy; Comment
主题: Re: [juewuy/ShellClash] 路由器重启无法自动翻q (#18)

我用最新beta17版本。而且不装mixbox的话，clash命令无法运行，not found。 



发自我的iPhone 


------------------ 原始邮件 ------------------ 
发件人: juewuy <notifications@github.com&amp;gt; 
发送时间: 2020年12月12日 09:49 
收件人: juewuy/ShellClash <ShellClash@noreply.github.com&amp;gt; 
抄送: lifsux <853956801@qq.com&amp;gt;, Author <author@noreply.github.com&amp;gt; 
主题: 回复：[juewuy/ShellClash] 路由器重启无法自动翻q (#18) 





更新test版本或者切换一下clash运行模式 

发送自 Windows 10 版邮件应用 

发件人: lifsux 
发送时间: 2020年12月11日 23:32 
收件人: juewuy/ShellClash 
抄送: Subscribed 
主题: [juewuy/ShellClash] 路由器重启无法自动翻q (#18) 

clash已设置开机自启动，但是路由器重启后不能自动翻q，需要手动进入ssh重新启动clash服务才能连接（手动进入clash后命令行显示clash服务是启动的，但是不能翻q）。总：存在开机不能自动fq的问题。ax1800最新固件（1.0.378 稳定版）。

**Comment by juewuy** [comment]
sh $clashdir/clash.sh

**Comment by juewuy** [comment]
或者sh /etc/clash/clash.sh
如果使用的默认目录

**Comment by lifsux** [comment]
可以增加iPhone捷径实现一键关闭或者开启clash吗？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: juewuy <notifications@github.com&gt;
发送时间: 2020年12月15日 10:38
收件人: juewuy/ShellClash <ShellClash@noreply.github.com&gt;
抄送: lifsux <853956801@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[juewuy/ShellClash] 路由器重启无法自动翻q (#18)






Closed #18.

**Comment by juewuy** [comment]
不懂这个，很久不用iPhone了

**Comment by ablebodied** [comment]
我的也是AX1800，也是重启路由器后不能fq，甚至不能上网，要进入ssh重启一下服务才行，我把开机启动关掉了
