### ISSUE TITLE
建议加个在网页上更新订阅和切换订阅的功能

### ISSUE THREAD

**Issue by Kado814** [juewuy/ShellClash#180]
建议加个在网页上更新订阅和切换订阅的功能，这样就能随时在手机上管理了

**Comment by juewuy** [comment]
@Kado814 这不是我能实现的，建议移步上游

**Comment by Kado814** [comment]
> @Kado814 这不是我能实现的，建议移步上游 手机使用可以参考 https://juewuy.github.io/-F7dWmBj5/
好吧，感谢回复！这样也是一个可行办法
