### ISSUE TITLE
[bug]开启固化ssh就会报错

### ISSUE THREAD

**Issue by tangfenga** [juewuy/ShellClash#186]
机型：RM ax6s
系统版本：蓝皮内测only for test
shellclash版本：1.5.9
问题描述：开启ssh固化之后就无法使用脚本了
![image](https://user-images.githubusercontent.com/78092871/173861544-a925edc9-c153-4209-b1b3-5a619cebf2f0.png)

**Comment by tangfenga** [comment]
![image](https://user-images.githubusercontent.com/78092871/173865747-2c94cee6-7554-40f7-9a71-89dbfcfecca7.png)
最新版本也报错

**Comment by juewuy** [comment]
我不确定是不是系统的问题，但是我仅凭信息无法解决
请使用官方原版系统或者尝试卸载并重装最新版本
