### ISSUE TITLE
使用 clash.Meta内核 google无法访问

### ISSUE THREAD

**Issue by dongxicc** [juewuy/ShellClash#188]
小米ax6000  试了下shellclash
youtube访问正常 ，其他都正常
一访问google 页面提示:  您的连接不是私密连接

**Comment by dongxicc** [comment]
换了其他浏览器也是这个提示

**Comment by dongxicc** [comment]
https://accounts.google.com/  这个也没问题，但是 https://www.google.com/  提示不安全
![image](https://user-images.githubusercontent.com/29423511/174113252-65871df5-638b-4253-8ce3-9fcaae9aac8b.png)

**Comment by juewuy** [comment]
@dongxicc DNS问题，请参考常见问题
https://juewuy.github.io/

**Comment by dongxicc** [comment]
换了fake-ip模式可以了
