### ISSUE TITLE
请问为什么这里只代理这两个内网地址？

### ISSUE THREAD

**Issue by neroxps** [juewuy/ShellClash#189]
https://github.com/juewuy/ShellClash/blob/f3eb5c16c89a833786ed0b8955256fb10f3a3e52/scripts/start.sh#L444

感觉应该需要把局域网地址都写进来？或者感觉不写 source ip都行了？

网络环境是 172.22.0.1/16 的地址段默认代理不了。

**Comment by juewuy** [comment]
@neroxps 下面不是有自动获取的本地网段吗？

**Comment by neroxps** [comment]
哦？我的环境是跨网段，所以不生效。

**Comment by juewuy** [comment]
@neroxps 可以使用1.5.1版本或者自己修改源码
