### ISSUE TITLE
[bug]【 5 过滤局域网设备 】功能不可用

### ISSUE THREAD

**Issue by lijiachang** [juewuy/ShellClash#190]
路由器是AX6，
shellclash 1.6.1正式版

![shellclash 过滤](https://user-images.githubusercontent.com/28041718/174526286-84abef5b-a2ce-469a-bda8-c4f8bcbb4bd3.png)

如图所示，已开启黑名单过滤模式，但是黑名单的三台设备，均可以访问外网。
（PS：开启黑名单的原因是：家人手机使用小红书和京东APP，经常打不开）

**Comment by juewuy** [comment]
本地无法复现
