### ISSUE TITLE
How to install ShellClash on the Mac(OS X)?

### ISSUE THREAD

**Issue by Jeremy-JM** [juewuy/ShellClash#193]
Hi Juewuy,

Our company have provide a Mac mini to do our test server, 
I want to konw that who to install a ShellClash on the Mac?

Thanks, 
Regards!

**Comment by juewuy** [comment]
@Jeremy-JM Sorry,it's not support the  MACOS .You can use the other clash client just like :CLASHX or Clash for Windows (mac)
