### ISSUE TITLE
能否直接跳过所有的ipv6地址呢？

### ISSUE THREAD

**Issue by foreverlong** [juewuy/ShellClash#196]
能否直接跳过所有的ipv6地址呢？一旦开启clash，设备的ipv6就不可用了。但是设备还是需要ipv4的clash的。所以能否让所有的ipv6地址不经过clash呢？谢谢。

**Comment by juewuy** [comment]
@foreverlong 默认就不经过

**Comment by kob** [comment]
你应该没理解他的意思，就是即用shellclash又可以支持IPV6，现在是是支持IPV6，但还是不能把GFW里面的域名的AAAA解析屏蔽

**Comment by foreverlong** [comment]
> @foreverlong 默认就不经过

我现在打开clash之后，test-ipv6.com就无法通过，关掉就可以了。就是想ipv4走clash，ipv6直接完全不走clash，这样可行吗？

**Comment by xausky** [comment]
shellclash 中开启 IPv6 支持（DNS会返回 IPv6 地址），之后运行以下命令（IPv6 流量不通过 clash）即可

```
ip6tables --table nat --flush clashv6
```

**Comment by DustinWin** [comment]
> > @foreverlong 默认就不经过
> 
> 我现在打开clash之后，test-ipv6.com就无法通过，关掉就可以了。就是想ipv4走clash，ipv6直接完全不走clash，这样可行吗？

同样的问题，很是头疼。

**Comment by DustinWin** [comment]
> shellclash 中开启 IPv6 支持（DNS会返回 IPv6 地址），之后运行以下命令（IPv6 流量不通过 clash）即可
> 
> ```
> ip6tables --table nat --flush clashv6
> ```
> 
> 每次 shellclash 重启都需要重新运行，如果作者可以作为一个选项进行支持就好了

感谢！终于解决了我的问题，虽然需要手动。

**Comment by HappyGame137** [comment]
ipv6跟clashshell不能同时开启，希望能优化一下。

**Comment by Feb17** [comment]
同样有这个需求，希望作者可以添加支持

**Comment by juewuy** [comment]
> 同样有这个需求，希望作者可以添加支持

最新测试版已经修复

**Comment by DustinWin** [comment]
> 请问是1.6.8fix 还是1.6.9？ 我来去测试下

1.6.8+版本就可以，我选择的  Tproxy 模式+redir_host。
