### ISSUE TITLE
SSH重新连接执行clash提示Command not found

### ISSUE THREAD

**Issue by skw2022** [juewuy/ShellClash#198]
用的是netgear改梅林固件路由器，开启ssh，使用admin用户进行安装，断开会话后，再次ssh连接（过一段时间吧，不是马上连接），执行clash提示Command not found，不知是否与使用admin安装有关？不知到如何root连接，请问如何解决？
不稳定，似乎是一天断一次服务，无法访问相关网站，无法连接到设置的UI界面，有时软启动可以恢复，有时需要重新硬启动路由器。

**Comment by juewuy** [comment]
@shekenwa 可能与内置插件有冲突
