### ISSUE TITLE
uci操作后没有commit，可能会导致操作不生效或者配置丢失

### ISSUE THREAD

**Issue by devioa** [juewuy/ShellClash#199]
![image](https://user-images.githubusercontent.com/38558065/180031239-12198073-419c-4d79-b186-ec60e3b5168b.png)

**Comment by juewuy** [comment]
这样写应该没问题吧？

**Comment by devioa** [comment]
这个`uci commit`是我自己加上去的，原来是没有这一行的，我只是标出来可以加上这一行

**Comment by juewuy** [comment]
@devioa 哦 好的

**Comment by devioa** [comment]
建议在这两行后面加上`uci commit dhcp`
https://github.com/juewuy/ShellClash/blob/ce1b4cb92633505e7f694d91cc48a5b79d716d66/scripts/start.sh#L674
https://github.com/juewuy/ShellClash/blob/ce1b4cb92633505e7f694d91cc48a5b79d716d66/scripts/start.sh#L859

**Comment by luckyyyyy** [comment]
@juewuy 有几个问题
1、 建议加上 commit 否则会导致配置界面任何修改不生效
2、另外这里为啥删除了 cachesize 我是习惯性改为0，不喜欢被dnsmasq缓存
3、似乎没有使用clash premium 内核的选项？因为premium才支持tracing

受够了openclash乱改iptables 换过来正常多了

**Comment by juewuy** [comment]
@luckyyyyy uci应该都有加commit，如果有遗漏，请指出
dnsmasq功能早就应该移除了，并不建议使用，代码也没有操作cach
内核请用meta
