### ISSUE TITLE
能否增加多开功能

### ISSUE THREAD

**Issue by grayguest** [juewuy/ShellClash#20]
想在本地机器多开，不知道能否增加多开功能。

**Comment by juewuy** [comment]
不会提供这个功能，clash的配置设置也不适合多开
可以尝试使用分流规则对不同的应用指定不同的服务器

发送自 Windows 10 版邮件应用

发件人: XiaoMeng
发送时间: 2020年12月30日 13:51
收件人: juewuy/ShellClash
抄送: Subscribed
主题: [juewuy/ShellClash] 能否增加多开功能 (#20)

想在本地机器多开，不知道能否增加多开功能。
