### ISSUE TITLE
【疑问】请问 fake-ip 模式下 fake-ip-filter: 内置的规则能否自定义设置

### ISSUE THREAD

**Issue by neroxps** [juewuy/ShellClash#205]
https://github.com/juewuy/ShellClash/blob/d4549ba582a3cde3fa2bbc946e3af314b016676a/scripts/start.sh#L294

因为 proxy.golang.org 我这边的网络怎么都连不上，而我又使用 fake-ip 分流，导致流量一直过不去 clash 里面。我把 proxy.golang.org 删掉就正常了。

目前我是修改 start.sh 来修复这个问题。请问能否将这里的配置也给用户自己配置？

**Comment by juewuy** [comment]
@neroxps 功能设置里

**Comment by juewuy** [comment]
@neroxps 先提供相关面板连接信息

**Comment by neroxps** [comment]
> @neroxps 先提供相关面板连接信息

抱歉，这个没明白，请问是功能设置的哪个位置？因为这个配置我看了下是脚本内置的，脚本配置fake-ip-filter 里面是新增 好像没有默认配置删除？

**Comment by juewuy** [comment]
@neroxps 没有，你先把面板连接日志发出来

**Comment by neroxps** [comment]
> @neroxps 没有，你先把面板连接日志发出来

哦 是这样的，我是通过主路由将fake-ip 的流量发到OpenWrt 所以如果解析不是 fake-ip 的话，流量是不会发到 OpenWrt

**Comment by juewuy** [comment]
@neroxps 这样复杂的网络结构不在脚本支持范围内

**Comment by neroxps** [comment]
> @neroxps 这样复杂的网络结构不在脚本支持范围内

ok 那我用修改脚本方法把，谢谢。
