### ISSUE TITLE
树莓派用openwrt做旁路由无法使用本插件

### ISSUE THREAD

**Issue by goxofy** [juewuy/ShellClash#207]
树莓派刷入 https://github.com/SuLingGG/OpenWrt-Rpi 这个固件后，设置为旁路由，安装shellclash之后无效，不能科学，是固件本身bug吗？

**Comment by juewuy** [comment]
@goxofy 提供的信息太少

**Comment by goxofy** [comment]
@juewuy 硬件是树莓派2B+ ，刷入了OpenWrt-Rpi的最新版固件，然后按照那个项目的wiki把树莓派设置成旁路由，这个时候测试网络是ok的。

然后ssh进树莓派，安装shellclash成功，在ssh下测试树莓派本身科学是ok的，但是其他设备以树莓派为网关和dns，无法科学，shellclash这边测试了tun模式和混合模式，均不行

**Comment by juewuy** [comment]
@goxofy 请提供clash面板相关日志及连接信息

**Comment by goxofy** [comment]
开启shellclash时，通过ssh直接在树莓派内curl 墙外网站，日志如下
```
[2022-08-02 12:06:36][INFO] [TCP] 127.0.0.1:49448 --> www.facebook.com:443 match DomainKeyword(facebook) using Proxies[🇭🇰 香港 Aliyun [01]]
[2022-08-02 12:07:21][INFO] [TCP] 127.0.0.1:56272 --> www.google.com.hk:443 match DomainKeyword(google) using Proxies[🇭🇰 香港 Aliyun [01]]
```
连接页面为空。

其他设备以树莓派为网关和dns访问墙外网站时，日志页面不产生任何信息

**Comment by juewuy** [comment]
@goxofy 应该是缺少iptables吧

**Comment by goxofy** [comment]
@juewuy 
我看了一下组件，只有这几个，是不是缺少组件？
![image](https://user-images.githubusercontent.com/1695416/182312285-712088b6-4823-4a37-aff4-db667b2ba5c8.png)

**Comment by juewuy** [comment]
@goxofy 没缺，那我也不知道什么原因了

**Comment by goxofy** [comment]
@juewuy 崩溃，用固件里带的那个openclash又能用，但是我又不想用那个。。唉
