### ISSUE TITLE
【疑问】ax6000使用shellclash上网速率

### ISSUE THREAD

**Issue by allenlai1985** [juewuy/ShellClash#209]
你好，请问为什么同样的线路，使用clash windows在speedtest测速能达到几百兆，但用ax6000使用shell clash测速的情况下只有几十M。是设置的问题吗？

**Comment by juewuy** [comment]
@allenlai1985 更换加密协议，路由设备上不同协议速度差距很大

**Comment by allenlai1985** [comment]
@juewuy 你好，请问你提到的更换加密协议，是指路由器上的配置还是clash脚本上的配置？

**Comment by bearbazooka** [comment]
> @juewuy 你好，请问你提到的更换加密协议，是指路由器上的配置还是clash脚本上的配置？

机场的加密协议
