### ISSUE TITLE
AMD64 架构 Clash Meta 核心存在问题。

### ISSUE THREAD

**Issue by Mirr0ch1** [juewuy/ShellClash#212]
核心已下载完成但提示“核心下载失败”。
已尝试切换 jsdeliver 与 fastgit 源，均如此。

切换 clash -t 命令后再次尝试输出如下内容：
![Screenshot_2022-08-14-04-42-48-834_com.server.auditor.ssh.client.jpg](https://user-images.githubusercontent.com/3250823/184510205-3880bf47-efc1-4dc0-b029-1502745c64cd.jpg)

同一网络环境下 ARM 设备下载 ARM 架构核心正常。

**Comment by juewuy** [comment]
@Mirr0ch1 什么设备？另外切换其他内核试试

**Comment by Mirr0ch1** [comment]
> @Mirr0ch1 什么设备？另外切换其他内核试试

软路由，j4125 处理器。 openwrt x86 与 debian 下都是这个问题。

clash、clashpre、clashnet 均没问题，仅 clash meta 下载成功但提示下载失败。

半年前是没这个问题的，后来（近两个月内）突然某次再重装的时候 就不行了，一直这个问题。

**Comment by juewuy** [comment]
@Mirr0ch1 可能是某些原因导致未通过内核自带的测试

**Comment by zhfish** [comment]
https://github.com/MetaCubeX/Clash.Meta/issues/165
Mark一下..我这里meta也跑不起来

**Comment by juewuy** [comment]
建议手动winscp上传或者去上游报告一下
