### ISSUE TITLE
出现 Bus error (core dumped) 错误

### ISSUE THREAD

**Issue by rainbowg0** [juewuy/ShellClash#213]
导入配置文件成功后, 启动时运行 start.sh 出现以下报错:

/etc/clash/start.sh: line 844: 54420 Bus error               (core dumped) $nohup $bindir/clash -d $bindir > /dev/null 2>&1
/etc/clash/start.sh: line 844: 54421 Bus error               (core dumped) $bindir/clash -t -d $bindir > /dev/null
clash服务启动失败！请查看报错信息！
/etc/clash/start.sh: line 844: 54428 Bus error               (core dumped) $bindir/clash -t -d $bindir

运行环境是腾讯云的ubuntu

**Comment by juewuy** [comment]
@rainbowg0 重装内核
