### ISSUE TITLE
建议添加基于geoip模块的cn ip内核绕过

### ISSUE THREAD

**Issue by YtnbFirewings** [juewuy/ShellClash#215]
华硕路由器官方固件没有包含ipset模块，但包含了geoip模块，如果使用geoip模块进行内核过滤，可以支持更多设备

**Comment by juewuy** [comment]
@YtnbFirewings 查了下geoip 模块可能需要xtables依赖，大部分设备都不支持

**Comment by YtnbFirewings** [comment]
> @YtnbFirewings 查了下geoip 模块可能需要xtables依赖，大部分设备都不支持

我也手工测试了一下，确实有些问题，最后通过geoip自动生成iprange解决了，缺点就是导入iprange规则（7000多条）需要很久
