### ISSUE TITLE
开启TUN模式后局域网设备无法访问外网

### ISSUE THREAD

**Issue by AXAZXFAXA** [juewuy/ShellClash#216]
开启TUN模式后局域网设备无法访问外网,开启本机流量经过clash内核后本机可以访问外网
设备为AX6S

**Comment by AXAZXFAXA** [comment]
混合模式无法代理UDP

**Comment by juewuy** [comment]
@AXAZXFAXA 说明设备大概率不支持tun
尝试使用tproxy

**Comment by AXAZXFAXA** [comment]
> @AXAZXFAXA 说明设备大概率不支持tun 尝试使用tproxy

设备是可以跑tun的,而且curl www.google.com也是有反应的
tproxy提示您的设备不支持tproxy模式，无法开启！您的设备不支持tproxy模式，无法开启！

**Comment by AXAZXFAXA** [comment]
![image](https://user-images.githubusercontent.com/99458999/185379476-2203fed4-e13c-4508-b716-215b069e85a1.png)

**Comment by juewuy** [comment]
@AXAZXFAXA curl并不会走tun，另外也可能是你DNS没有正确接管

**Comment by AXAZXFAXA** [comment]
dns是没问题的，但是curl谷歌确实是通了。

**Comment by AXAZXFAXA** [comment]
并且访问外网是直接提示拒绝连接，而不是dns错误

**Comment by AXAZXFAXA** [comment]
已刷openwrt
