### ISSUE TITLE
为什么多个模式下不支持google.com

### ISSUE THREAD

**Issue by yejinjian** [juewuy/ShellClash#22]
为什么多个模式下不支持google.com

**Comment by juewuy** [comment]
可能是你使用的规则文件有问题或者DNS配置有问题
参考
https://juewuy.github.io/chang-jian-wen-ti/

**Comment by huangzulin** [comment]
用shellclash生成的规则，也无法访问google

**Comment by juewuy** [comment]
可能是运营商DNS劫持，请尝试使用加密dns

发送自 Windows 10 版邮件应用

发件人: huangzulin
发送时间: 2021年2月25日 0:20
收件人: juewuy/ShellClash
抄送: juewuy; State change
主题: Re: [juewuy/ShellClash] 为什么多个模式下不支持google.com (#22)

用shellclash生成的规则，也无法访问google
