### ISSUE TITLE
内置GeoIP和CN_IP资源建议

### ISSUE THREAD

**Issue by crackerfly** [juewuy/ShellClash#220]
内置的GeoIP和CN_IP资源数据不准确, 导致很多国内服务判断为走机场代理
建议替换成这两个资源, 实测很准
https://github.com/Loyalsoldier/geoip
https://github.com/mayaxcn/china-ip-list

**Comment by juewuy** [comment]
@crackerfly 用的已经是优化版的了，并不是原版geoip
