### ISSUE TITLE
旁路由模式外网访问内部设备

### ISSUE THREAD

**Issue by ihnic** [juewuy/ShellClash#221]
配置：向导默认配置

shellclash设备从外网能够访问
但是指向shellclash网关的设备均无法在外网访问
请问应该如何设置

**Comment by juewuy** [comment]
@nicholastz 从你主路由设置端口映射

**Comment by nicholastz** [comment]
是的， 我目前从主路由映射端口，但是无法访问

**Comment by juewuy** [comment]
最好办法只能是局域网设备过滤

**Comment by happyeddie** [comment]
+1
