### ISSUE TITLE
配置文件支持emoji

### ISSUE THREAD

**Issue by dbian** [juewuy/ShellClash#231]
我这有个特殊的机场，clash配置里有很多emoji，导致clash解析失败，大佬们，能不能支持一下这种配置文件，跪谢了

报错信息：

![image](https://user-images.githubusercontent.com/1283828/190634117-738ae024-9ee2-42b9-a6bb-67eef57d80f3.png)

配置：

![image](https://user-images.githubusercontent.com/1283828/190633754-ab7c97d8-783a-4aa3-8cfb-b747d8be17ea.png)

emoji示例🎯🚀🔰

**Comment by juewuy** [comment]
@dbian 和emoji应该无关

**Comment by dbian** [comment]
> @dbian 和emoji应该无关

@juewuy 
感谢大佬的回复，确实不是emoji的问题，配置文件也没有问题，用下面的流程就可以了

`选取在线生成服务器 -> 选取在线配置规则模版 -> 输入机场url -> 开始生成配置文件`
