### ISSUE TITLE
为什么raw.githubusercontent.com 拒绝访问

### ISSUE THREAD

**Issue by ceylog** [juewuy/ShellClash#234]

**Comment by juewuy** [comment]
不知道

**Comment by ceylog** [comment]
> 不知道

用openclash 同样的配置文件没这个问题呀   好奇怪  规则里面强制使用github 关键词也不行

**Comment by juewuy** [comment]
@ceylog 可能是DNS污染，参考常见问题
https://juewuy.github.io

**Comment by ceylog** [comment]
> @ceylog 可能是DNS污染，参考常见问题
> https://juewuy.github.io

@juewuy 谢谢
