### ISSUE TITLE
启用白名单和fakeip模式后，会因为dns托管导致非白名单设备无法正常解析dns

### ISSUE THREAD

**Issue by SnowWarri0r** [juewuy/ShellClash#240]
![image](https://user-images.githubusercontent.com/62747881/192229504-ffb8b89d-b42f-4572-bb38-5891b0535d75.png)

**Comment by juewuy** [comment]
黑名单设备DNS不会走clash
如果使用的dnsmasq转发，请取消

**Comment by SnowWarri0r** [comment]
> 黑名单设备DNS不会走clash 如果使用的dnsmasq转发，请取消

使用的是白名单，没有使用dnsmasq转发
混合模式+fakeip，未在白名单设备dns解析是如上图，改成redir则是上图的下半部分

**Comment by juewuy** [comment]
@SnowWarri0r 请检查相关依赖
或者重启设备重试

**Comment by SnowWarri0r** [comment]
> @SnowWarri0r 请检查相关依赖 或者重启设备重试

检查依赖后发现没装ip6tables-mod-nat
安装后目前已恢复正常

**Comment by SnowWarri0r** [comment]
> > @SnowWarri0r 请检查相关依赖 或者重启设备重试
> 
> 检查依赖后发现没装ip6tables-mod-nat 安装后目前已恢复正常

发现只是dns缓存使得可以访问，其他网页还是会通过clash内核进行dns解析，但是不在白名单的设备无法进行解析

**Comment by SnowWarri0r** [comment]
脚本有提示过我的硬件设备可能不支持tun模式和混合模式，然后我用了clash pre的内核，依旧提示，是不是因为硬件的原因导致的？

**Comment by juewuy** [comment]
@SnowWarri0r 我建议你重装一下脚本
