### ISSUE TITLE
导入配置文件 报错x509

### ISSUE THREAD

**Issue by aglent** [juewuy/ShellClash#241]
有个集成了多家机场的配置文件 之前用在windows和android上正常使用，但是我用shellclash导入后，加载失败，错误信息是【ERRO[0000] initial proxy provider ...url....  x509: certificate signed by unknown authority   
configuration file /tmp/clash_config_root.yaml test failed
】
好像机场链接 报错了x509？我用在线生成是可以的

**Comment by juewuy** [comment]
@aglent 参考常见问题

**Comment by aglent** [comment]
看了这篇https://juewuy.github.io/chang-jian-wen-ti/，提示证书错误或者ssl验证失败可能是由于本地DNS污染导致的。
我换了dns模式，不起作用。
因为报错的机场链接直接导入是可以的，但是写在自己的配置文件里会报错。

**Comment by juewuy** [comment]
@aglent 你看得不对，仔细点看
