### ISSUE TITLE
关闭覆盖订阅配置的 hosts

### ISSUE THREAD

**Issue by nauxliu** [juewuy/ShellClash#243]
目前订阅文件中的 hosts 配置会被本地配置覆盖掉，有办法关闭这个行为吗？

**Comment by juewuy** [comment]
@nauxliu 会直接读取本机/etc/hosts文件

**Comment by nauxliu** [comment]
了解，但是我希望使用远端订阅的配置。这份配置我们使用 git 管理，自动生成的。我不太想在每台机器上去手动配置 hosts

**Comment by juewuy** [comment]
@nauxliu 那你只能改代码了

**Comment by nauxliu** [comment]
能指路一下大概动哪里吗？ 读了一会儿代码还没有头绪。

**Comment by juewuy** [comment]
@nauxliu https://github.com/juewuy/ShellClash/blob/master/scripts/start.sh#L360-L360

**Comment by nauxliu** [comment]
感谢，我看到这一块代码了。但是好奇怎么改动能读取到原始配置中的 hosts，想要做一个 PR 维持原有 hosts 并和 /etc/hosts 合并。追了一下代码还是没思路，对 shell 不是太熟悉，望指教。

**Comment by juewuy** [comment]
@nauxliu 自定义配置文件7-7然后在config.yaml里添加
