### ISSUE TITLE
issue: /etc/rc.common: line 1: /data/clash: Permission denied

### ISSUE THREAD

**Issue by lucewang** [juewuy/ShellClash#246]
基本每使用一天，clash就会连不上网，重启会出现下面错误 /etc/rc.common: line 1: /data/clash: Permission denied ，
只能重新安装解决；已经采用软固化且成功。

**Comment by juewuy** [comment]
@lucewang 提供一下设备信息

**Comment by juewuy** [comment]
@lucewang 尝试切换保守模式

**Comment by kennyzhuce** [comment]
@lucewang 你好，我也出现了同样的问题，能否请教下，后来是具体是怎么解决的？谢谢

**Comment by kennyzhuce** [comment]
设备ax6000，clash版本1.6.3
1，我尝试启用了，“更多工具”里边的“小米设备软固化ssh”，无法启动clash，也不能开机启动clash。
2，我尝试启用了，“clash进阶设置”里边的“使用保守模式启动”，可以成功启动clash服务了，但是设备reboot以后，依然不能开机启动clash，虽然已经提示“已设置开机启动”
3，另外，我选择“禁用clash开机启动”后，再次选择“允许clash开机启动”后，有报错：
“
cat: read error: Is a directory
cat: read error: Is a directory
cat: read error: Is a directory
cat: read error: Is a directory
已设置Clash开机启动！
”

**Comment by kennyzhuce** [comment]
覆盖升级到1.6.5版本，问题解决了，现在reboot，也可以开机启动了。

**Comment by lucewang** [comment]
@kennyzhuce 我也是 1.6.5, 用保守模式启动后，目前尚未出现 Permission denied 错误，继续观察。
@juewuy 请问保守模式和标准模式有什么区别，会影响性能吗？

**Comment by juewuy** [comment]
@lucewang 区别不大

**Comment by lucewang** [comment]
@juewuy 使用保守模式启动一周，没有出现上述错误了，谢谢。
已启用每天更新订阅重起，不再继续跟踪，该问题关闭。

**Comment by geekyouth** [comment]
我在小米主路由 ax6s 后台新增端口转发后，
![image](https://user-images.githubusercontent.com/12899262/197370198-dc9dbc68-1990-4fe2-afac-2b790200088b.png)


就出现以下故障：

![image](https://user-images.githubusercontent.com/12899262/197370135-cd0c6596-03c3-4d6f-8e8d-981967538caa.png)

参考 https://github.com/juewuy/ShellClash/issues/226#issue-1373105062 ，也出现类似的重复命令
```shell
alias clash="/data/clash/clash.sh"
export clashdir="/data/clash"
alias clash="/data/clash/clash.sh"
export clashdir="/data/clash"
alias clash="/data/clash/clash.sh"
export clashdir="/data/clash"
alias clash="/data/clash/clash.sh"
export clashdir="/data/clash"
alias clash="/data/clash/clash.sh"
export clashdir="/data/clash"
root@XiaoQiang:~# cat /etc/profile

```
最后我更新到 1.6.5 内测版，可以启动，目前观察中。
