### ISSUE TITLE
装本地版dashboard管理面板 失败

### ISSUE THREAD

**Issue by maiff** [juewuy/ShellClash#247]
装本地版dashboard管理面板
打开管理面板的速度更快且更稳定
-----------------------------------------------
请选择面板安装类型：
-----------------------------------------------
 1 安装官方面板(约500kb)
 2 安装Meta面板(约800kb)
 3 安装Yacd面板(约1.1mb)
 4 安装Yacd-Meta魔改面板(约1.5mb)
 5 卸载本地面板
 0 返回上级菜单
请输入对应数字 > 1
-----------------------------------------------
请选择面板安装目录：
-----------------------------------------------
 1 在/data/clash/ui目录安装
 2 在/www/clash目录安装
-----------------------------------------------
 0 返回上级菜单
请输入对应数字 > 2
-----------------------------------------------
正在连接服务器获取安装文件…………
################################################################################################################# 100.0%
-----------------------------------------------
文件下载失败！

**Comment by maiff** [comment]
电脑下载项目yacd的压缩文件scp到对应位置解决

**Comment by Lennon2017** [comment]
切换源再重新安装就好了
