### ISSUE TITLE
用了shellclash后，IPV6失效了

### ISSUE THREAD

**Issue by 450717565** [juewuy/ShellClash#248]
禁用SC就能正常使用V6，开启就失效，用的混合模式+fakeIP，进阶设置里也开启支持V6了，但还是不行。

请问是本来就不支持，还是哪里没设置对

大佬的SC非常好用，望继续加油

**Comment by Corpama** [comment]
开启fake-ip后貌似不支持ipv6，如果说的不对希望大佬解答

**Comment by 450717565** [comment]
> 开启fake-ip后貌似不支持ipv6，如果说的不对希望大佬解答

我看了相关FAQ，换成redir模式也不行

**Comment by Corpama** [comment]
在我这，redir实测可以

**Comment by 450717565** [comment]
> 在我这，redir实测可以

老哥方便发个截图看看相关设置吗

**Comment by Corpama** [comment]
1 切换Clash运行模式: 	混合模式
 2 切换DNS运行模式：	redir_host
-----------------------------------------------
 1 使用保守模式启动:	未开启	————切换时会停止clash服务
 2 启用ipv6支持:	已开启	————实验性功能，可能不稳定
-----------------------------------------------
当前基础DNS：https://doh.apad.pro/dns-query, tls://223.5.5.5:853
fallbackDNS：https://doh.apad.pro/dns-query, tls://8.8.4.4:853
 5 ipv6_dns解析：	已开启	————建议开启
-----------------------------------------------
ps.我的所有vps都是有ipv6的，然后设备为wrt32x(原厂openwrt系统)，macbook
-----------------------------------------------
![Screen Shot 2022-10-09 at 9 08 44 PM](https://user-images.githubusercontent.com/32979675/194758703-26603536-5bb2-4bb2-9aa4-ca312db9bc7f.png)

**Comment by 450717565** [comment]
> 

好的，谢谢老哥

**Comment by Corpama** [comment]
对了，附送一个纯ipv6网站用作测试，可以测试ipv6dns与ipv6访问是否正常，https://mirrors6.tuna.tsinghua.edu.cn/

**Comment by lwh201314** [comment]
一样开了clash ipv6就连不上了， 测试了各种配置都不行，只有加黑名单的机器才正常😰

**Comment by heganyuliang** [comment]
> 一样开了 clash ipv6 就连不上了， 测试了各种配置都不行，只有加黑名单的机器才正常😰

https://github.com/juewuy/ShellClash/issues/196#issuecomment-1219569336

**Comment by Aexus** [comment]
开机后，在终端执行： `ip6tables --table nat --flush clashv6` 试试。目前这种方法可用

**Comment by juewuy** [comment]
最新测试版应该已经修复
