### ISSUE TITLE
开启tun模式+fakeip后无法正常运行

### ISSUE THREAD

**Issue by Borelset** [juewuy/ShellClash#249]

**Comment by Borelset** [comment]
shellclash运行在路由器上。
测试发现，pc确实会把域名解析到fakeip，对路由器发送请求，但是路由器方面却没有反应，log里没有产生任何记录。
对于这种情况用什么工具来调试比较好呢？

**Comment by juewuy** [comment]
@Borelset 那就是不支持tun模式

**Comment by Borelset** [comment]
@juewuy 可是安装的确实是clash premium呀，而且我观察了一下确实新建了一个虚拟网卡... 
我还想看看iptables的log，但是ax3600也不知道log生成到哪里去了。。。 头疼

**Comment by juewuy** [comment]
@Borelset 8-1-4

**Comment by Januswork** [comment]
一样的问题
