### ISSUE TITLE
redis_host 经常出现污染

### ISSUE THREAD

**Issue by xujimu** [juewuy/ShellClash#250]
现在遇到一个很尴尬的问题,如果开启CN_IP绕过内核我得500m宽带可以跑满,如果不开启只能跑到200m速率这样, 但是CN_IP绕过内核不兼容Fake-ip,意味着我只能使用redir_host,但是redis_host 经常出现污染的情况 访问谷歌就会被拦截提示

www.google.com 时，该网站发回了异常的错误凭据。这可能是因为有攻击者在试图冒充 必须手动清理dns才能继续使用 非常麻烦

没有办法解决这个问题吗

**Comment by juewuy** [comment]
@xujimu 参考常见问题

**Comment by xujimu** [comment]
> @xujimu 参考常见问题

常见问题解决方案是 Dnsmasq转发 但是我看只支持openwrt 我得是老毛子

**Comment by juewuy** [comment]
@xujimu 没有让你使用加密DNS？
