### ISSUE TITLE
grep 3.8 后似乎对正则识别改变

### ISSUE THREAD

**Issue by debeetle** [juewuy/ShellClash#255]
grep: warning: stray \ before white space

**Comment by juewuy** [comment]
@debeetle 不可能适配所有版本

**Comment by dacancc** [comment]
> grep: warning: stray \ before white space
降级grep即可，我是的系统是manjaro,使用downgrade降级如下：
先安装downgrade：sudo pacman -Sy downgrade
downgrade降级grep至3.7版本：sudo DOWNGRADE_FROM_ALA=1 downgrade downgrade

**Comment by juewuy** [comment]
已修复
