### ISSUE TITLE
ax9000 1.0.140版本固件安装问题

### ISSUE THREAD

**Issue by ThermalEng** [juewuy/ShellClash#256]
环境：
ax9000 开通1.0.140 ssh已固化
经测试，curl完整；wget只支持http；无iptables-mod-nat。
网络环境：可访问外网
问题：
1.无法安装正式版
![image](https://user-images.githubusercontent.com/38897886/198254098-22c459b3-29bd-4942-a1e1-73e098cd1547.png)
2.ui面板都无法正常安装
![image](https://user-images.githubusercontent.com/38897886/198254403-2fd58117-7cc5-4540-92e2-6d493cadc1f4.png)
打开网址后界面如下
![image](https://user-images.githubusercontent.com/38897886/198255348-2e1c400c-e081-4f11-b3b1-bc47e16c0477.png)

**Comment by juewuy** [comment]
@ThermalEng 那就装测试版

**Comment by ThermalEng** [comment]
> @ThermalEng 那就装测试版

测试版又存在问题2，测试了一下，列出的几个面板都无法正常安装。

**Comment by ThermalEng** [comment]
> 

几个源都测试了一下，问题依旧，下载没问题

**Comment by juewuy** [comment]
空间不足吧，重置一下设备试试
