### ISSUE TITLE
开启自定义配置后，无法自定义内置DNS

### ISSUE THREAD

**Issue by csy19960309** [juewuy/ShellClash#258]
通过7-7开启自定义配置后，如果直接修改config.yaml则重启服务后修改过的dns模块会被覆盖，如果修改在user.yaml则重启服务后config.yaml会出现两个dns模块（一个修改过的，一个是生成的）共存。
请问自定义内置DNS的正确方式是什么？

**Comment by juewuy** [comment]
@csy19960309 7-6

**Comment by csy19960309** [comment]
> @csy19960309 7-6

谢谢，但是这里能修改的字段比较有限，比如我想修改fakeip-filter，就只能直接修改config.yaml, 然而重启clash服务时又被覆盖了。这种情况有解决方式么？

**Comment by juewuy** [comment]
@csy19960309 filter在2-8里，其他自己改代码
