### ISSUE TITLE
Meta内核tun模式面板报错

### ISSUE THREAD

**Issue by Alexrobot03** [juewuy/ShellClash#260]
设备r4s，混合模式正常，tun模式下面板报错：something is went wrong ，且无法代理

**Comment by juewuy** [comment]
@Alexrobot03 请提供具体报错截图

**Comment by Alexrobot03** [comment]
> @Alexrobot03 请提供具体报错截图

截图忘拍照了，面板打开就是一句话：oops,something is went wrong 
其他啥也没有

**Comment by juewuy** [comment]
@Alexrobot03 尝试更换其他面板

**Comment by Alexrobot03** [comment]
> @Alexrobot03 尝试更换其他面板

关键问题是纯tun开启了不能代理，无法富强

**Comment by juewuy** [comment]
@Alexrobot03 固件问题
