### ISSUE TITLE
安装完启动失败 /etc/clash/start.sh: line 514: iptables: not found

### ISSUE THREAD

**Issue by ldy694** [juewuy/ShellClash#261]
错误信息是/etc/clash/start.sh: line 514: iptables: not found

之前是正常的，后来升级了openwrt，就不正常了：
`这里是测试命令菜单
如遇问题尽量运行相应命令后截图发群
-----------------------------------------------
 1 查看Clash运行时的报错信息(会停止clash服务)
 2 查看系统DNS端口(:53)占用 
 3 测试ssl加密(aes-128-gcm)跑分
 4 查看iptables端口转发详情
 5 查看config.yaml前40行
 6 测试代理服务器连通性（google.tw)
 7 重新进入新手引导
 9 查看后台脚本运行日志
-----------------------------------------------
 0 返回上级目录！
请输入对应数字 > 4
-----------------------------------------------
/etc/clash/clash.sh: line 1133: iptables: not found
-----------------------------------------------
/etc/clash/clash.sh: line 1135: iptables: not found
-----------------------------------------------
/etc/clash/clash.sh: line 1137: iptables: not found
-----------------------------------------------
/etc/clash/clash.sh: line 1139: ip6tables: not found
-----------------------------------------------
/etc/clash/clash.sh: line 1141: ip6tables: not found
-----------------------------------------------
/etc/clash/clash.sh: line 1143: ip6tables: not found

路由器信息：

主机名 | OpenWrt
-- | --
型号 | Newifi-D2
架构 | MediaTek MT7621 ver:1 eco:3
目标平台 | ramips/mt7621
固件版本 | OpenWrt 22.03.2 r19803-9a599fee93 / LuCI openwrt-22.03 branch git-22.288.45147-96ec0cd
内核版本 | 5.10.146
本地时间 | 2022-11-02 05:21:07
运行时间 | 1h 43m 51s
平均负载 | 0.29, 0.52, 0.42

`

**Comment by juewuy** [comment]
@ldy694 请使用编译了iptables的包

**Comment by juewuy** [comment]
@juewuy 需要重新编译固件

**Comment by cnxocean** [comment]
opkg update
opkg install iptables
