### ISSUE TITLE
关闭 DNS 劫持

### ISSUE THREAD

**Issue by nauxliu** [juewuy/ShellClash#262]
是否有办法关闭 DNS 劫持，因为开发的需求，有时候需要手动从其他 dns server 手动查询 dns 记录。

**Comment by juewuy** [comment]
@nauxliu 7-6

**Comment by nauxliu** [comment]
7-6-7？我希望保留内置 dns，可以手动将 dns server 指向 clash。只希望关闭劫持所有 dns (udp:53) 的请求。7-6 中没看到符合我需求的选项

**Comment by juewuy** [comment]
@nauxliu 自己改代码

**Comment by juewuy** [comment]
现在dns配置优先读取user.yaml

**Comment by AfxMsgBox** [comment]
我也是有类似的需求，改了代码就不好升级了

**Comment by juewuy** [comment]
@AfxMsgBox 7-6关闭内置DNS即可

**Comment by AfxMsgBox** [comment]
> 

不行，我需要用clash内置的dns作为adguardhome的上游dns，以实现分流。现在我就是改代码的，这个需求是旁路由的一个典型场景，希望加上一个劫持dns开关，这样还能保持升级

**Comment by AfxMsgBox** [comment]
> 不行，我需要用clash内置的dns作为adguardhome的上游dns，以实现分流。现在我就是改代码的，这个需求是旁路由的一个典型场景，希望加上一个劫持dns开关，这样还能保持升级

旁路由，clash全局，启用fakeip加dns分流，是目前最问题最少，折腾也不影响家人上网的方式。

**Comment by juewuy** [comment]
@AfxMsgBox 关闭内置DNS就是关闭转发，不会禁用

**Comment by AfxMsgBox** [comment]
> @AfxMsgBox 关闭内置DNS就是关闭转发，不会禁用

明白了，建议改一下文案，谢谢作者
