### ISSUE TITLE
1.6.5 版本安装到主路由运行后会限制公网下载速度，关闭运行则恢复正常下载速度

### ISSUE THREAD

**Issue by geekyouth** [juewuy/ShellClash#263]
1.6.5 版本安装到主路由运行后会限制公网下载速度，关闭运行则恢复正常下载速度

如图：
1、停止运行 shellclash 时，360测速下载速度79MB/S属于正常；
![image](https://user-images.githubusercontent.com/12899262/199950422-c22db867-ed3e-49b7-9900-d7621fc41d0e.png)

2、运行  shellclash时，测速为 15MB/S，限速严重：
![image](https://user-images.githubusercontent.com/12899262/199950685-21913c39-d967-4f2d-a954-506d3f9ec32f.png)

尝试如下方案未解决问题：
1、路由器 小米 R3P 恢复出厂设置，重装 shellclash，只能安装 1.6.5 版本，运行shellclash 后故障依旧；
2、本地安装ShellClash的教程 | Juewuy's Blog https://juewuy.github.io/m7BojFXBO/ 
尝试本地安装，却发现该教程针对的是 win系统，只能放弃；
3、clash 命令 ---> 9 更新/卸载 ---> 7 切换安装源及安装版本 ---> 9 版本回退
```
请输入对应数字 > 9
-----------------------------------------------
请选择想要回退至的release版本：
 1 <html>根据我们的服务条款，已屏蔽具有该内容的文件，请点击<a
 0 返回上级菜单
请输入对应数字 >
```
4、下载 release 压缩包，在命令行执行 install.sh 也失败了；

以上4种办法最后都陷入死胡同，特来求救，如何恢复上一个正式版？因为上一个正式版（好像是1.6.3）在小米 R3P 机型用了好几个月没啥问题。

**Comment by juewuy** [comment]
@geekyouth 启用绕过cnIP

**Comment by geekyouth** [comment]
![image](https://user-images.githubusercontent.com/12899262/200094914-1e3d7b4e-401f-4dfc-a8a4-371c1eae20a3.png)
列表下载失败了 @juewuy

**Comment by geekyouth** [comment]
@juewuy  请问如何恢复到 1.6.3 版本？

**Comment by geekyouth** [comment]
我查看了安装脚本的核心源码，发现是 cdn_url 挂了，导致无法安装正式版

![image](https://user-images.githubusercontent.com/12899262/200095535-9472c1d8-db43-4869-9de6-d985f7d8586e.png)

![image](https://user-images.githubusercontent.com/12899262/200095540-9153e453-29ae-4e6a-ad53-916760e60f1b.png)

针对 RAW 资源加速限制以下仓库使用的说明 · Discussion #5 · 7ednet/yard
https://github.com/7ednet/yard/discussions/5

**Comment by juewuy** [comment]
@geekyouth 好的，了解

**Comment by geekyouth** [comment]
经过半小时的折腾，我想到了一个野路子：

我的路由器不支持 https 访问，其次 shellclash 项目本身不支持 raw.githubusercontents.com 代理网站的访问，所以我就对症下药如下。

1、fork 并且 clone 该项目到本地，修改 url_cdn 为 url_cdn="https://ghproxy.com/https://raw.githubusercontent.com/geekyouth/ShellClash"

2、在局域网电脑打开 everything，启动 http 服务（因为全网都找不到http协议的 github cdn 代理，全都是 https），默认目录就是该项目目录，之后修改安装脚本为：
export url='http://192.168.8.12:18080/' && wget -q -O /tmp/install.sh $url/install.sh  && sh /tmp/install.sh && source /etc/profile &> /dev/null

3、在路由器上启用临时局域网代理，用来给路由器临时访问外网生成订阅配置文件
export http_proxy=http://192.168.8.12:1080
export https_proxy=http://192.168.8.12:1080
export socks_proxy=http://192.168.8.12:1080

4、开始配置 shellclash，开启CN_IP绕过内核功能！！

5、打开 360 测速，完美跑满带宽

6、目前发现，科学上网会受到影响，youtube 打开时转了很久。不知道是否和机场节点选择有关。

附图：
![image](https://user-images.githubusercontent.com/12899262/200098073-740adea5-d418-480f-85f8-6d2f052467ec.png)

**Comment by geekyouth** [comment]
主要修改内容：
https://github.com/juewuy/ShellClash/compare/master...geekyouth:ShellClash:master?diff=split

**Comment by juewuy** [comment]
@geekyouth 额，我博客里有提供本地安装的教程

**Comment by geekyouth** [comment]
> @geekyouth 额，我博客里有提供本地安装的教程

最核心的问题是 url_cdn 无法正常返回，所以就算本地安装，也需要访问该链接查找 release 版本，否则只能安装测试版，问题很多

**Comment by juewuy** [comment]
@geekyouth 公测版稳定性不会差的

**Comment by geekyouth** [comment]
使用 1.6.3 发现，在开启CN_IP绕过内核功能之后，临时可以跑满宽带，第二天不管是否运行 shellclash ，网速依然跑不满。
于是又切回 1.6.5 版本了，现已开启CN_IP绕过内核功能，正在观察。
