### ISSUE TITLE
想问下，clash shell 整个安装下来，大概占用多少空间啊？

### ISSUE THREAD

**Issue by 1457384613gh** [juewuy/ShellClash#264]
想问下，clash shell 整个安装下来，大概占用多少空间啊？
我的 Openwrt 只有 64MB。
大概可用 12MB。
12 MB 安装 clash shell 够吗？

**Comment by juewuy** [comment]
@1457384613gh 可以

**Comment by 1457384613gh** [comment]
没开玩笑吗？那么小的空间，也足够？

**Comment by juewuy** [comment]
@1457384613gh 小闪存模式只需要1MB闪存

**Comment by 1457384613gh** [comment]
安装好以后，直接 输入 clash，没有管理员权限，无法更新配置。

一定 要 以管理员权限运行 clash吗？

**Comment by 1457384613gh** [comment]
我用的 chromeOS，Google 公司基于 Gentoo 二次开发的。
和普通的Linux发行版出入较大。

在 root 权限下 安装 clash shell成功，但无法 `sudo clash`，只能 `clash`。

本来打算 安装到 `～/Downloads` 下，方便读写；但是安装的时候提示 没有权限写入`～/Downloads`。

**Comment by juewuy** [comment]
@1457384613gh 对

**Comment by 1457384613gh** [comment]
那怎么办呢？有办法利用chromeOS 的特点适配 chromeOS 吗？
chromeOS Flex 正式版已经出来了，大概 16 GiB 的分区就够了，可以拯救 旧设备，只是正好缺少代理。
然而 clash shell 就差一步之遥，就是想方设法安装到 chromeOS 的 用户可读写的路径。可不知道这路径该如何填写。

**Comment by juewuy** [comment]
@1457384613gh ls -l看一下吧

**Comment by DustinWin** [comment]
我这边占用 17M。
![QQ截图20221203172808](https://user-images.githubusercontent.com/45238096/205434009-c784b4de-207c-4220-afdf-04883d1d660f.png)
