### ISSUE TITLE
K2P 老毛子固件，开机自启失败

### ISSUE THREAD

**Issue by yuwoa** [juewuy/ShellClash#266]
clash状态是开启的，手动关闭后无法开启，提示下方错误。

clash服务启动失败！请查看报错信息！
ERRO[0000] yaml: incomplete UTF-8 octet sequence
configuration file /tmp/clash_shen/config.yaml test failed

最后更新了一下订阅就可以启动了。

接着我重启路由器，测试有没有复现，这次打开谷歌提示证书问题。然后可以关闭clash，再启动。

第三次重启，这次正常使用。。

另外关于自定义规则，我添加5个域名，不知道怎么有一个一个解析到保留地址了

**Comment by juewuy** [comment]
自启失败大概是小闪存模式没有成功下载内核，这个无解
自定义规则去面板上确认是否添加成功
