### ISSUE TITLE
rule-providers 过大导致导入 Clash 配置文件链接失败

### ISSUE THREAD

**Issue by DustinWin** [juewuy/ShellClash#271]
在导入 Clash 配置文件链接时报错，报错信息如下：
`ERRO[0021] initial rule provider reject error: context deadline exceeded`

我是用的 reject 下载链接如下：
`https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt`
由于此文件过大，有 5 万多条，导致导入的时候出错。

**Comment by juewuy** [comment]
@DustinWin 这不是脚步能解决的问题，路由上也不建议使用过大的配置文件

**Comment by DustinWin** [comment]
> @DustinWin 这不是脚本能解决的问题，路由上也不建议使用过大的配置文件

感谢回复，我重试了好几次，终于成功导入了。

**Comment by delicacyyy** [comment]
![image](https://github.com/user-attachments/assets/d26fd871-d923-4f93-ad51-9dd9ce46fe14)
那五百条怎么也不行

**Comment by DustinWin** [comment]
> ![image](https://private-user-images.githubusercontent.com/11476249/360514672-d26fd871-d923-4f93-ad51-9dd9ce46fe14.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMzgzNDcsIm5iZiI6MTcyNDMzODA0NywicGF0aCI6Ii8xMTQ3NjI0OS8zNjA1MTQ2NzItZDI2ZmQ4NzEtZDkyMy00ZjkzLWFkNTEtOWRkOWNlNDZmZTE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDE0NDcyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAwOTQ4NDJkNGEyMmViOWYwNDgxYTIzYzhmMTA4ZGVjNTAzYjBkZTlmOTU3ZTdjZWRjMmQ0ODhhNmFkNjVmMzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.reuzWmh9RgS2XA39vi27afli1idkuv9nmxbvDXBtWy4) 那五百条怎么也不行

多试几次。

**Comment by delicacyyy** [comment]
> 多试几次。

目前试了一个晚上 所有的 rule set 都无法更新 也不知道哪里出了问题 大佬们有没有什么经验可以帮忙排查
