### ISSUE TITLE
使用 Fake-ip 模式进行 bt 下载时，tackerslist 的 udp 无法连接

### ISSUE THREAD

**Issue by DustinWin** [juewuy/ShellClash#272]
如图：
![QQ截图20221110041115](https://user-images.githubusercontent.com/45238096/200931792-fecf8d57-f864-449e-89d5-2f5ff20ef185.png)

如果切换到 Redir-host 模式，则正常。可以有什么方法可以使 udp 正常连接吗？
注：Fake-ip 模式和 Redir-host 模式下都开启了 ipv6

**Comment by juewuy** [comment]
@DustinWin 使用混合模式

**Comment by DustinWin** [comment]
> @DustinWin 使用混合模式

忘了说了，已打开混合模式。

**Comment by juewuy** [comment]
@juewuy 关掉常用端口过滤

**Comment by DustinWin** [comment]
> @juewuy 关掉常用端口过滤

已经关掉了，但还是不行，如图：
![20221110134455](https://user-images.githubusercontent.com/45238096/201010439-7ef4670c-c972-4c4e-a8e4-6e2604b96bf3.png)

**Comment by juewuy** [comment]
@DustinWin 那就别用fakeip了

**Comment by DustinWin** [comment]
> @DustinWin 那就别用fakeip了

好吧，试了多个配置，确实鱼和熊掌不可兼得。

**Comment by DustinWin** [comment]
该问题已完美解决。通过 Github Actions 自动提取 trackersList 里的域名并添加到 user.yaml 的 `fake-ip-filter` 里就可以了。详见：https://github.com/DustinWin/clash-geosite#3-useryaml
