### ISSUE TITLE
Unraid 配置路由模式报错 systemctrl not found

### ISSUE THREAD

**Issue by ProfessorX** [juewuy/ShellClash#274]
系统底层为 slacksware

通过脚本已完成下载及安装。

配置文件已导入，启动服务失败。

报错内容见下：
>是否启动clash服务以使配置文件生效？(1/0) > 1
-----------------------------------------------
grep: warning: stray \ before white space
grep: warning: stray \ before white space
grep: warning: stray \ before white space
grep: warning: stray \ before white space
/etc/clash/start.sh: line 963: systemctl: command not found

**Comment by juewuy** [comment]
@ProfessorX grep版本太高，先降级使用

**Comment by ProfessorX** [comment]
这个是固定在U盘启动的系统，咋降级比较好。没看到包管理软件。

**Comment by ProfessorX** [comment]
yinggai不是grep的问题  grep 只是警告。

这个系统是传统的 slackwarelinux，里面没有 systemctrl 来管理服务。

尝试启动失败了。

**Comment by ProfessorX** [comment]
root@Tower:/mnt/user/appdata/clash# uname -a
Linux Tower 5.19.17-Unraid #2 SMP PREEMPT_DYNAMIC Wed Nov 2 11:54:15 PDT 2022 x86_64 Intel(R) Xeon(R) CPU E3-1265L v3 @ 2.50GHz GenuineIntel GNU/Linux

设备信息在上面

**Comment by juewuy** [comment]
@ProfessorX 尝试保守模式

**Comment by ProfessorX** [comment]
尝试了几个方案：
1. NAS机 IP 254 cmd装shellclash 可以开起来，不知道怎么让里面的docker服务走代理流量
2.Armbian IP：253 直接跑 shellclash，因为是linux 不带路由，貌似没用也可能有用，NAS机器的docker还是没加速

最后忍不住，还是往 Armbian 里面走了个KVM,按照恩山的教程加载 openwrt的镜像，再里面跑 openclash，挂配置文件成功启动。

有个小插曲，由于是虚拟机里面的，开始没带 clash 核心，能找到 shellclash 下载的核心文件，但是用不了；openclash repo上面下载了一个 arm版本的文件，成功启动。
