### ISSUE TITLE
Armbian 安装增强面板失败

### ISSUE THREAD

**Issue by ProfessorX** [juewuy/ShellClash#275]
请选择面板安装类型：
-----------------------------------------------
 1 安装官方面板(约500kb)
 2 安装Meta面板(约800kb)
 3 安装Yacd面板(约1.1mb)
 4 安装Yacd-Meta魔改面板(约1.5mb)
 5 卸载本地面板
 0 返回上级菜单
请输入对应数字 > 3
-----------------------------------------------
检测到您已经安装过本地面板了！
-----------------------------------------------
是否覆盖安装？[1/0] > 1
-----------------------------------------------
正在连接服务器获取安装文件…………
下载成功，正在解压文件！

gzip: stdin: unexpected end of file
tar: 归档文件中异常的 EOF
tar: 归档文件中异常的 EOF
tar: Error is not recoverable: exiting now

gzip: stdin: unexpected end of file
tar: 归档文件中异常的 EOF
tar: 归档文件中异常的 EOF
tar: Error is not recoverable: exiting now
文件解压失败！
root@amlogic:~# uname -a
Linux amlogic 5.4.108-flippy-56+o #254 SMP Wed Mar 24 22:22:33 CST 2021 aarch64 GNU/Linux
root@amlogic:~# 请选择面板安装类型：

**Comment by juewuy** [comment]
@ProfessorX 换源重下

**Comment by ProfessorX** [comment]
东西在NAS上面，平时没空去折腾，先关闭了。

我结婚了还没婚房会到处乱说。

**Comment by ProfessorX** [comment]
东西在NAS上面，平时没空去折腾，先关闭了。

我结婚了还没婚房会到处乱说。
