### ISSUE TITLE
为什么 clashpre 内核最新版是 2021.09.15 版本？

### ISSUE THREAD

**Issue by DustinWin** [juewuy/ShellClash#276]
为什么最新版一直是这个版本，请问如何自己手动去更换内核？
![QQ截图20221115223021](https://user-images.githubusercontent.com/45238096/201945314-9b3888a4-9a56-4037-84fa-2fa187ebe1a7.png)
![QQ截图20221115223049](https://user-images.githubusercontent.com/45238096/201945344-2e6673ea-6534-4c31-ac2c-c56b0ff15149.png)

**Comment by juewuy** [comment]
测试版已经更新

**Comment by DustinWin** [comment]
> 测试版已经更新
已更新，感谢作者。
