### ISSUE TITLE
安装本地版dashboard管理面板解压文件失败

### ISSUE THREAD

**Issue by george510257** [juewuy/ShellClash#277]
安装本地版dashboard管理面板
打开管理面板的速度更快且更稳定
-----------------------------------------------
请选择面板安装类型：
-----------------------------------------------
 1 安装官方面板(约500kb)
 2 安装Meta面板(约800kb)
 3 安装Yacd面板(约1.1mb)
 4 安装Yacd-Meta魔改面板(约1.5mb)
 5 卸载本地面板
 0 返回上级菜单
请输入对应数字 > 3
-----------------------------------------------
请选择面板安装目录：
-----------------------------------------------
 1 在/data/clash/ui目录安装
 2 在/www/clash目录安装
-----------------------------------------------
 0 返回上级菜单
请输入对应数字 > 1
-----------------------------------------------
检测到您已经安装过本地面板了！
-----------------------------------------------
是否覆盖安装？[1/0] > 1
-----------------------------------------------
正在连接服务器获取安装文件…………
下载成功，正在解压文件！
tar: unexpected end of file
tar: short read
tar: unexpected end of file
tar: short read
文件解压失败！

**Comment by george510257** [comment]
路由器小米AC3600

**Comment by juewuy** [comment]
@george510257 换源重下

**Comment by george510257** [comment]
export url='https://fastly.jsdelivr.net/gh/juewuy/ShellClash@master' && sh -c "$(curl -kfsSl $url/install.sh)" && source /etc/profile &> /dev/null

用的是这个。github的源好像也不行

**Comment by Jason2225** [comment]
不翻墙的情况下似乎所有源都不行

**Comment by juewuy** [comment]
@Jason2225 那是你自己网络环境不行
