### ISSUE TITLE
小米路由器HD  Clash订阅连接问题

### ISSUE THREAD

**Issue by mjiecg** [juewuy/ShellClash#280]
路由器正常ssh成功。clash也正常安装完成
在自动在线生成配置文件的时候出错了。
我输入订阅连接。
总是会报配置文件获取失败。没有一次成功过。
大概就是报

Failed to connect to 2606:4700:3034::ac43:cb2f: Operation not permitted
配置文件失败

路由器
小米路由器HD
官方显示我这个路由器是 (小米路由器3HD) 
版本
BusyBox v1.19.4 (2019-05-30 08:08:06 UTC) built-in shell (ash)

有没有哪位大神可以帮帮忙。

**Comment by juewuy** [comment]
@mjiecg winscp手动上传，或者尝试更新到最新测试版

**Comment by mjiecg** [comment]
> @mjiecg winscp手动上传，或者尝试更新到最新测试版

上传到那个路径啊。还有那些文件。？

**Comment by 911SnIpEr** [comment]
同是R3D，和你的问题一样...是不是是IPv6的锅

**Comment by juewuy** [comment]
> > @mjiecg winscp手动上传，或者尝试更新到最新测试版
> 
> 上传到那个路径啊。还有那些文件。？

参考常见问题https://juewuy.github.io/

**Comment by 911SnIpEr** [comment]
已解决，不选1在线生成，强选2直接输入订阅链接http:****.yaml即可使用。1.6.8fix和1.6.9都可以用
