### ISSUE TITLE
iptables 执行异常

### ISSUE THREAD

**Issue by hqman** [juewuy/ShellClash#281]
iptables v1.8.7 (nf_tables): unknown option "--to"
Try `iptables -h' or 'iptables --help' for more information.
iptables v1.8.7 (nf_tables): unknown option "--to-ports"
Try `iptables -h' or 'iptables --help' for more information.
iptables v1.8.7 (nf_tables): unknown option "--to-ports"
Try `iptables -h' or 'iptables --help' for more information.
clash服务已启动！

**Comment by juewuy** [comment]
@hqman 更新内测版
