### ISSUE TITLE
玩客云旁路由问题

### ISSUE THREAD

**Issue by maxwelldong** [juewuy/ShellClash#283]
你好，玩客云当旁路由使用1.63和1.65版一切正常，能正常翻墙，升级到1.68和1.69的几个版本不管怎么设置都无法翻墙，日志和连接里都是空的，只有shellclash自身检查更新才会有一条记录，卸载后重装一样翻不了，降级回1.63又能正常。

**Comment by juewuy** [comment]
@maxwelldong 执行8-1-4，结果发一下

**Comment by maxwelldong** [comment]
Chain PREROUTING (policy ACCEPT)
num  target     prot opt source               destination
1    clash_dns  udp  --  anywhere             anywhere             udp dpt:domain
2    prerouting_rule  all  --  anywhere             anywhere             /* !fw3: Custom prerouting rule chain */
3    zone_lan_prerouting  all  --  anywhere             anywhere             /* !fw3 */
Chain clash_dns (1 references)
num  target     prot opt source               destination
1    REDIRECT   udp  --  anywhere             anywhere             redir ports 1053
iptables: No chain/target/match by that name.

**Comment by juewuy** [comment]
@maxwelldong 模式不对吧？用的什么模式？

**Comment by maxwelldong** [comment]
Rddir模式，DNS是fake-ip,不管模式怎么切换就是没有记录，切换成混合还有TProxy全是空的。

**Comment by juewuy** [comment]
@maxwelldong 有显示nft模式吗？有的话换成nft试试

**Comment by maxwelldong** [comment]
Redir模式，混合模式，Tproxy混合，Tun模式，Tproxy模式，纯净模式，显示8种模式。

**Comment by juewuy** [comment]
@maxwelldong 这是6种……

**Comment by maxwelldong** [comment]
升级到新版不管怎么调模式，日志，连接里都是空的，什么配置都不改降回1.63又是能正常翻墙。

**Comment by juewuy** [comment]
@maxwelldong 我大概知道问题了，静等修复吧

**Comment by maxwelldong** [comment]
收到，谢谢。

**Comment by juewuy** [comment]
测试版已修复

**Comment by maxwelldong** [comment]
收到，新版已经在用了，还有几个奇怪的问题另外的网络AX9000上装了shellclash过两天就会导致网络中断,必须重启路由器才能重新使用，AX9000上的状态灯都是正常的表明路由器连接外网是正常的，AX9000上不装shellclash都是正常的不会断网，还有一台小米R2D装shellclash也会有导致网络中断的问题。还有在主路由上开启shellclash微信支付一直会转圈圈无法完成，只有把设备列入白名单才能正常。还有AX9000上面没有Tproxy模式是这样子吗？

**Comment by juewuy** [comment]
@maxwelldong 网络中断可能是流量太大，最好绕过下载机，并且启用定时重启
微信支付没听说有报告的，可以尝试启用绕过cnIP功能
最后，ax9000不支持tproxy
