### ISSUE TITLE
clash.sh source: not found

### ISSUE THREAD

**Issue by Forgoys** [juewuy/ShellClash#285]
安装时切换到了root用户，并且选择安装到了非root用户下的某个目录。
运行时：
<img width="710" alt="image" src="https://user-images.githubusercontent.com/47031885/204419561-f52d7a88-aea4-4698-aad0-3d051cf60a5a.png">
输入9无法进入相应面板：
<img width="609" alt="image" src="https://user-images.githubusercontent.com/47031885/204419778-954a0960-9870-4214-bc82-82c3a842575b.png">
请问是什么原因？

**Comment by juewuy** [comment]
@Forgoys 安装和运行都尽量使用root

**Comment by Forgoys** [comment]
@juewuy 感谢解答，已解决。
