### ISSUE TITLE
有没有老哥在K3 官改V21D上用，能安装使用，就是时不时的掉线

### ISSUE THREAD

**Issue by excellenttank** [juewuy/ShellClash#289]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

有没有老哥在K3 官改V21D上用过，能安装使用，就是时不时的掉线，面板也能打开，运行./clash.sh，状态也正常，就是翻不出去，重启后能用，但是过几个小时问题依旧，每天需要重启过次才行，有没有老哥遇到这种情况，怎么解决的，谢谢

**Comment by juewuy** [comment]
@excellenttank 可能是与同类型插件有冲突

**Comment by excellenttank** [comment]
> 

感谢回复，官改里面应该有个自带的ssr，这个应该是关掉了，其他的同类型插件没有安装啊，

**Comment by excellenttank** [comment]
![image](https://user-images.githubusercontent.com/16424424/206836038-13aa1c12-d2cf-4c3d-adc0-73ff37f0c182.png)
现在是停用未运行状态，

**Comment by juewuy** [comment]
@excellenttank 请当明确处于掉线状态后，提供8-1-1和8-1-4的返回数据

**Comment by excellenttank** [comment]
> @excellenttank 请当明确处于掉线状态后，提供8-1-1和8-1-4的返回数据

好的，到时候发出来

**Comment by excellenttank** [comment]
> @excellenttank 请当明确处于掉线状态后，提供8-1-1和8-1-4的返回数据

8-1-1
请输入对应数字 > 8
-----------------------------------------------
欢迎使用其他工具菜单：
本页工具可能无法兼容全部Linux设备，请酌情使用！
磁盘占用/所在目录：
8.7M    /tmp/media/nand/clash
-----------------------------------------------
 1 ShellClash测试菜单
 4 流媒体增强————用于解决流媒体解锁在TV应用上失效的问题
-----------------------------------------------
 0 返回上级菜单
-----------------------------------------------
请输入对应数字 > 1
-----------------------------------------------
这里是测试命令菜单
如遇问题尽量运行相应命令后截图发群
-----------------------------------------------
 1 查看Clash运行时的报错信息(会停止clash服务)
 2 查看系统DNS端口(:53)占用 
 3 测试ssl加密(aes-128-gcm)跑分
 4 查看iptables端口转发详情
 5 查看config.yaml前40行
 6 测试代理服务器连通性（google.tw)
 7 重新进入新手引导
 9 查看后台脚本运行日志
-----------------------------------------------
 0 返回上级目录！
请输入对应数字 > 1
sed: can't create temp file '/etc/profileTxQfpP': Read-only file system
sed: can't create temp file '/etc/profile8onTlH': Read-only file system
-----------------------------------------------
INFO[0000] Start initial compatible provider 📢 谷歌FCM    
INFO[0000] Start initial compatible provider Ⓜ️ 微软服务    
INFO[0000] Start initial compatible provider 🐟 漏网之鱼     
INFO[0000] Start initial compatible provider 🎥 DisneyP  
INFO[0000] Start initial compatible provider ♻️ 自动选择    
INFO[0000] Start initial compatible provider 🚀 节点选择     
INFO[0000] Start initial compatible provider 🍎 苹果服务     
INFO[0000] Start initial compatible provider 📲 电报消息     
INFO[0000] Start initial compatible provider 🇸🇬 新加坡节点   
INFO[0000] Start initial compatible provider 🛑 广告拦截     
INFO[0000] Start initial compatible provider 🎯 全球直连     
INFO[0000] Start initial compatible provider 🎥 NETFLIX  
INFO[0000] Start initial compatible provider 🚀 手动切换     
INFO[0000] Start initial compatible provider 🌍 国外媒体     
configuration file /tmp/media/nand/clash/config.yaml test is successful
测试通过！
[K3 /tmp/media/nand/clash]#

**Comment by excellenttank** [comment]
8-1-4


请输入对应数字 > 8
-----------------------------------------------
欢迎使用其他工具菜单：
本页工具可能无法兼容全部Linux设备，请酌情使用！
磁盘占用/所在目录：
8.7M    /tmp/media/nand/clash
-----------------------------------------------
 1 ShellClash测试菜单
 4 流媒体增强————用于解决流媒体解锁在TV应用上失效的问题
-----------------------------------------------
 0 返回上级菜单
-----------------------------------------------
请输入对应数字 > 1
-----------------------------------------------
这里是测试命令菜单
如遇问题尽量运行相应命令后截图发群
-----------------------------------------------
 1 查看Clash运行时的报错信息(会停止clash服务)
 2 查看系统DNS端口(:53)占用 
 3 测试ssl加密(aes-128-gcm)跑分
 4 查看iptables端口转发详情
 5 查看config.yaml前40行
 6 测试代理服务器连通性（google.tw)
 7 重新进入新手引导
 9 查看后台脚本运行日志
-----------------------------------------------
 0 返回上级目录！
请输入对应数字 > 4
-----------------------------------------------
Chain PREROUTING (policy ACCEPT)
num  target     prot opt source               destination         
1    adbyby_chain  tcp  --  anywhere             anywhere            
-----------------------------------------------
iptables: No chain/target/match by that name.
-----------------------------------------------
iptables: No chain/target/match by that name.
-----------------------------------------------
ip6tables v1.4.12.2: can't initialize ip6tables table `nat': Table does not exist (do you need to insmod?)
Perhaps ip6tables or your kernel needs to be upgraded.
-----------------------------------------------
ip6tables v1.4.12.2: can't initialize ip6tables table `nat': Table does not exist (do you need to insmod?)
Perhaps ip6tables or your kernel needs to be upgraded.
-----------------------------------------------
ip6tables v1.4.12.2: can't initialize ip6tables table `nat': Table does not exist (do you need to insmod?)
Perhaps ip6tables or your kernel needs to be upgraded.
[K3 /tmp/media/nand/clash]#

**Comment by juewuy** [comment]
@excellenttank iptables被重置了，怀疑是adbyby

**Comment by excellenttank** [comment]
![image](https://user-images.githubusercontent.com/16424424/206859377-bbfe1fad-2ec4-4d97-a0b5-66d1bc33fd15.png)
adbyby还真开着，而且adbyby是自动启动的，我关掉试试

**Comment by excellenttank** [comment]
> @excellenttank iptables被重置了，怀疑是adbyby

再次出现无法使用的情况

```
请输入对应数字 > 8
-----------------------------------------------
欢迎使用其他工具菜单：
本页工具可能无法兼容全部Linux设备，请酌情使用！
磁盘占用/所在目录：
8.7M    /tmp/media/nand/clash
-----------------------------------------------
 1 ShellClash测试菜单
 4 流媒体增强————用于解决流媒体解锁在TV应用上失效的问题
-----------------------------------------------
 0 返回上级菜单
-----------------------------------------------
请输入对应数字 > 1
-----------------------------------------------
这里是测试命令菜单
如遇问题尽量运行相应命令后截图发群
-----------------------------------------------
 1 查看Clash运行时的报错信息(会停止clash服务)
 2 查看系统DNS端口(:53)占用 
 3 测试ssl加密(aes-128-gcm)跑分
 4 查看iptables端口转发详情
 5 查看config.yaml前40行
 6 测试代理服务器连通性（google.tw)
 7 重新进入新手引导
 9 查看后台脚本运行日志
-----------------------------------------------
 0 返回上级目录！
请输入对应数字 > 4
-----------------------------------------------
Chain PREROUTING (policy ACCEPT)
num  target     prot opt source               destination         
-----------------------------------------------
Chain clash (0 references)
num  target     prot opt source               destination         
-----------------------------------------------
Chain clash_dns (0 references)
num  target     prot opt source               destination         
-----------------------------------------------
ip6tables v1.4.12.2: can't initialize ip6tables table `nat': Table does not exist (do you need to insmod?)
Perhaps ip6tables or your kernel needs to be upgraded.
-----------------------------------------------
ip6tables v1.4.12.2: can't initialize ip6tables table `nat': Table does not exist (do you need to insmod?)
Perhaps ip6tables or your kernel needs to be upgraded.
-----------------------------------------------
ip6tables v1.4.12.2: can't initialize ip6tables table `nat': Table does not exist (do you need to insmod?)
Perhaps ip6tables or your kernel needs to be upgraded.
[K3 /tmp/media/nand/clash]# 
```

**Comment by juewuy** [comment]
@excellenttank iptables被重置了，不知道是什么应用

**Comment by excellenttank** [comment]
@juewuy 这个有没有办法查是哪个应用重置了，或者能不能禁用iptables重置

**Comment by juewuy** [comment]
@excellenttank 没法整，最好去咨询固件作者

**Comment by excellenttank** [comment]
@excellenttank 好的，谢谢，不好整，结帖

**Comment by yahaha-rf** [comment]
> @excellenttank iptables被重置了，不知道是什么应用

重新拨号就会被重置 我这里电信大概两周把 会强制踢一次
