### ISSUE TITLE
请求更新最新版Xray core，以实现对xtls-rprx-vision流控格式的支持

### ISSUE THREAD

**Issue by caleche** [juewuy/ShellClash#290]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

请求更新最新版Xray core，以实现对xtls-rprx-vision流控格式的支持。
目前已对1.6.13测试版进行尝试，仍未支持。

**Comment by juewuy** [comment]
@caleche 这是ShellClash不是ShellXray
