### ISSUE TITLE
[Bug] 1.6.14有BUG节点订阅有问题

### ISSUE THREAD

**Issue by maxwelldong** [juewuy/ShellClash#291]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

你好，最新的版本节点订阅有问题，换不同的在线订阅不同的错误。降回1.6.13相同的订阅节点就是正常的。
Clash服务启动失败！请查看报错信息！
INFO[0000] Start initial configuration in progress
INFO[0000] Geodata Loader mode: memconservative
ERRO[0000] rules[0] [IP-CIDR,155.137.205.36,DIRECT] error: payloadRule error
configuration file /etc/clash/config.yaml test failed
/etc/clash/start.sh: line 1214: 11088 Killed                  /etc/init.d/clash start

Clash服务启动失败！请查看报错信息！
INFO[0000] Start initial configuration in progress
INFO[0000] Geodata Loader mode: memconservative
ERRO[0000] rules[0] [IP-CIDR,104.17.32.10,DIRECT] error: payloadRule error
configuration file /etc/clash/config.yaml test failed
/etc/clash/start.sh: line 1214: 11621 Killed                  /etc/init.d/clash start

Clash服务启动失败！请查看报错信息！
INFO[0000] Start initial configuration in progress
INFO[0000] Geodata Loader mode: memconservative
ERRO[0000] rules[0] [IP-CIDR,162.19.226.84,DIRECT] error: payloadRule error
configuration file /etc/clash/config.yaml test failed
/etc/clash/start.sh: line 1214: 10553 Killed                  /etc/init.d/clash start

**Comment by juewuy** [comment]
@maxwelldong 是有开内测版的节点绕过功能吗？

**Comment by maxwelldong** [comment]
对，有开启节点绕过功能了

**Comment by juewuy** [comment]
@maxwelldong 我也不清楚为啥会报错，按理说这样配置是正常的，你有切换内核尝试吗？

**Comment by maxwelldong** [comment]
刚又试了下，关闭节点绕过功能可以正常订阅，看样子这个功能有点问题，核心用的是clash.meta.
还有提个建议在线订阅能不能增加节点过滤IP的功能，节点过滤关键字有些没办法处理啊，免费的节点有些就只有SSR3个字母，然后导入出错节点提示chacha20协议的，这样的名字不好设置过滤条件。

**Comment by juewuy** [comment]
@maxwelldong 那个是在线sub的功能，我做不了更多
