### ISSUE TITLE
[Feature] 希望添加本地Subconverter地址

### ISSUE THREAD

**Issue by BBBoZi** [juewuy/ShellClash#292]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

因为第一是安全问题，第二是自己也希望使用本地的，不然每次更新修改脚本比较麻烦。
所以希望作者能在在线订阅的服务器里面添加本地订阅服务器地址

**Comment by juewuy** [comment]
@BBBoZi 使用6-2就可以导入本地局域网sub链接

**Comment by BBBoZi** [comment]
@juewuy 但是使用6-2 我这里会报错:
配置文件获取失败！
请尝试使用【在线生成配置文件】功能！

但是修改了start.sh的后端地址，使用6-1没问题

**Comment by juewuy** [comment]
@BBBoZi 这俩应该没区别的
