### ISSUE TITLE
[Feature] 关于自定义配置proxy-groups的困惑。

### ISSUE THREAD

**Issue by fallenyy** [juewuy/ShellClash#293]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

我订阅了一个机场，但是节点的名称经常发生变化，导致proxy-groups中的配置找不到相应节点信息从而报错，就像这样。
![tmp67EF](https://user-images.githubusercontent.com/70746058/208799354-bf27e5fc-25ed-4916-88d2-df7330d1c40f.png)
![tmp9980](https://user-images.githubusercontent.com/70746058/208799356-4cbf055b-77a8-44cf-8ebb-6d5d7fd4d0ea.png)
请问是否能设置多个相同分组名称且不同节点信息的配置，在一个分组错误后自动忽略然后读取下一个配置，或者现在是否就有更好的方法来解决。谢谢。

**Comment by juewuy** [comment]
@fallenyy 使用6-1在线生成

**Comment by fallenyy** [comment]
> 

这两个都是在线生成的cofig，会在这两中命名方式中反复横跳，如果我proxy-groups设置成第一种，那自动更新订阅后命名方式有可能变成第二种了，那proxy-groups找不到相应节点clash就运行不起来

**Comment by juewuy** [comment]
@fallenyy 每次不都是重新生成吗？重新生成时候难道不会自动适应节点？

**Comment by fallenyy** [comment]
> @fallenyy 每次不都是重新生成吗？重新生成时候难道不会自动适应节点？

对不起，是我表达不清楚，生成的时候config.yaml会自适应节点然后分组，我是启用了自定义配置，自己建了一个分组，在自定义配置proxy-groups.yaml中的proxies:参数可能找不到config.yaml中的节点名称（因为这个机场节点名称经常变），从而导致运行不起来。

**Comment by juewuy** [comment]
@fallenyy 你可以通过github托管自定义subconverter规则，或者使用proxy-providers来实现特殊分组

**Comment by fallenyy** [comment]
谢谢大佬解答！我研究研究，感谢！
