### ISSUE TITLE
[Bug] 安装到OpenWrt后Linux端部分网站代理不正常，已经排除订阅问题

### ISSUE THREAD

**Issue by Zaphkito** [juewuy/ShellClash#295]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

首先，这个bug在Windows，Android（Linux内核但是不受影响），iOS均不会出现，仅仅存在于Linux系统中
简单的说就像标题，我只要使用Linux系统，无论是虚拟机，物理机，都会出现隐私错误或者连接被关闭的错误，更换浏览器无效，错误与ipv6无关，错误与网络拓扑无关，curl也会报ssl相关错误
而我在尝试访问一些其他网站的时候，网站会显示我的对应ip地址是在海外，Linux的安装向导也会自动帮我分配对应地点的源地址和时区，也就是说我的Linux的网络访问已经被代理，但就是存在网站报错，而这些报错的网站在其他设备均不会出现问题，而且Android也可以正常访问
经过更换路由器插件为ssrp后，问题得到了解决，故认为与shellclash自身有关
我的设置如下，模式为混合，其他均为默认，另外已经排查ipv6相关问题，和ipv6无关，该问题与是否勾选常用端口无关
![Screenshot_20221227-180214](https://user-images.githubusercontent.com/64299266/209649907-e7b5ca82-f61e-4015-bfbc-f483a47eff9b.png)
![Screenshot_20221227-180221](https://user-images.githubusercontent.com/64299266/209649923-48a661bd-1299-4ccc-bf62-f523f40a9aef.png)
![Screenshot_20221227-180227](https://user-images.githubusercontent.com/64299266/209649941-442e5650-7c8d-4fbf-a792-dd8c65188356.png)
以下是一些出现问题的图片，不方便截图，只能手机拍屏幕了，果咩
再提醒一下，终端报错的google系网站和twitter等网站在Linux系统下用任何浏览器均进不去！
![IMG_20221227_171604785_HDR](https://user-images.githubusercontent.com/64299266/209650135-5dd73227-e2f9-4d3a-bfab-66b5310807b1.jpg)
![IMG_20221227_172433594](https://user-images.githubusercontent.com/64299266/209650187-9cc35193-53e7-4a19-912f-6f5d24b508ec.jpg)
![37371b5494a1986f](https://user-images.githubusercontent.com/64299266/209650346-c12d11c6-15ee-4dbd-b533-4378a0ea7666.jpg)

**Comment by juewuy** [comment]
@Zaphkito DNS问题，请根据面板相关日志排查

**Comment by Zaphkito** [comment]
> @Zaphkito DNS问题，请根据面板相关日志排查

首先我看了面板和日志有关的命令我得不到任何有用的信息，可以的话麻烦告诉我如何定位，找遍了没找到
![Screenshot_20221227-191900](https://user-images.githubusercontent.com/64299266/209659436-0541ef99-57cf-4ed6-a2ab-8a327649133e.png)
![Screenshot_20221227-191926](https://user-images.githubusercontent.com/64299266/209659463-40132fc2-f0a2-49ed-8831-256a2b41a21f.png)
![IMG_20221227_191942612](https://user-images.githubusercontent.com/64299266/209659486-dbc24d21-f07d-4402-bf9c-abb01ba8c0a0.jpg)


但是无论如何，我认为这次遇到的问题与dns无关，所有的Linux全部遇到这种问题，重启路由，重新联网，重启设备均无效，全新安装的Windows也可以正常使用，唯独Linux无论何种方式均无法访问

这个问题通过更换插件会得到解决

通过观察web页面的连接选项卡确实能看到它在尝试代理我访问YouTube或Google等网站，但无法正常上网

**Comment by juewuy** [comment]
面板日志里看相关访问是域名还是IP

如果是IP就是DNS没有接管

或者你启用域名嗅探后再尝试访问看能否解决问题

**Comment by Zaphkito** [comment]
> 面板日志里看相关访问是域名还是IP
> 
> 如果是IP就是DNS没有接管
> 
> 或者你启用域名嗅探后再尝试访问看能否解决问题

测试完回来了
域名嗅探开启前后无变化
观察面板有大量的IP地址和一部分域名，观察后侧的规则它确实有击中google，twitter等内容，全部走的“国外流量”，但是网站无法访问

值得注意的是使用其他设备访问也是这个情况，但是不会报隐私安全错误或者直接拒绝连接

**Comment by Zaphkito** [comment]
![IMG_20221227_200138483](https://user-images.githubusercontent.com/64299266/209664064-f8fd0862-74c2-4f0e-89e7-291ce9ef18b6.jpg)
![IMG_20221227_200132790](https://user-images.githubusercontent.com/64299266/209664073-3bc4ef0e-8a59-4a81-995b-b8a570f44707.jpg)

**Comment by juewuy** [comment]
尝试DNS切换到fakeip模式
再测试一下

**Comment by Zaphkito** [comment]
> 尝试DNS切换到fakeip模式 再测试一下

访问是正常了
但是fakeip把我的nat给干碎了
fakeip的nat降级这个情况我在openclash也遇到过，这个情况的影响还挺大的，在这里我反馈过https://github.com/vernesong/OpenClash/issues/2612
fakeip将会影响加速器的加速效果，导致游戏极度不稳定，无论是在何种模式的fakeip下

**Comment by juewuy** [comment]
@Zaphkito fakeip只是证明你DNS接管有问题
redirhost模式需要启用加密DNS，并且不能使用pre内核
