### ISSUE TITLE
请教AX6S官方固件root后自启动自定义脚本方式

### ISSUE THREAD

**Issue by ntgeralt** [juewuy/ShellClash#296]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

您好，问个题外话（google了一遍找不到  求助这里试试~）

1：自启动sh /data/start.sh这行代码，请教ssh里面应该什么操作~
（etc/init.d里面放入东西重启就丢了，好像要点技术含量，主要想做个frpc自启动）
2：frpc问题：
./frpc内网穿透 192.168.31.1:80端口，外面访问会提示404 not found，进不去小米web正常页面。
在openwrt同样代码则能访问到op主页，小米固件则不行。有人知道怎么解决吗？

**Comment by juewuy** [comment]
@ntgeralt clash目录下misnap_init文件末尾添加启动命令

**Comment by captainnx** [comment]
小米的路由器穿透web管理端口是8180
