### ISSUE TITLE
[Bug] 选择 Clash.Meta 内核提示核心文件下载失败

### ISSUE THREAD

**Issue by DustinWin** [juewuy/ShellClash#298]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

1.6.14c 版本，未开启 clash 服务（代理）时选择 Clash.Meta 内核，下载核心失败，切换 jsdelivr 源和内测源都不行。

**Comment by juewuy** [comment]
@DustinWin 检查闪存空间

**Comment by DustinWin** [comment]
> @DustinWin 检查闪存空间

切换到 Clashpre 内核是可以下载的，而且空间足够。

**Comment by DustinWin** [comment]
> @DustinWin 检查闪存空间

我再试几下，描述不准确。

**Comment by DustinWin** [comment]
我是在 ShellClash 配置 9-->2 里面更新核心的，都失败了。如果退出脚本，使用/data/clash/start.sh start 命令是可以自动下载内核的，就是非常慢。

**Comment by juewuy** [comment]
@DustinWin 运行服务后再使用更新功能，或者本地下载后用winscp上传

**Comment by DustinWin** [comment]
> @DustinWin 运行服务后再使用更新功能，或者本地下载后用winscp上传

好的，谢谢！
