### ISSUE TITLE
[Bug] 华硕 AC68U 梅林固件386.5，设置节点过滤后订阅报错

### ISSUE THREAD

**Issue by wuzhaozhongguo** [juewuy/ShellClash#299]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

华硕 AC68U 梅林固件386.5，设置节点过滤后订阅报错。不设置节点过滤正常订阅。
![image](https://user-images.githubusercontent.com/7008778/211272789-dea27ffe-e707-491f-85d0-eed3aeaf1e32.png)

**Comment by wuzhaozhongguo** [comment]
shellclash版本：1.6.13d

**Comment by juewuy** [comment]
@wuzhaozhongguo 内测版已修复

**Comment by wuzhaozhongguo** [comment]
感谢
