### ISSUE TITLE
设置本机代理服务,无法启动

### ISSUE THREAD

**Issue by JsonSong89** [juewuy/ShellClash#30]
版本1.2.0 
clash->2->6 
然后看起来是启动了
但是重启clash后再次进入clash->2 
又变成未启动了.
常看日志没有发现任何错误.

**Comment by JsonSong89** [comment]
系统是armbian  
Ubuntu 20.04.2 LTS with Linux 5.9.0-rc7-aml-s812

**Comment by juewuy** [comment]
可能是没有写入环境变量权限导致的？
