### ISSUE TITLE
[Bug] 无法启动clash服务相关问题

### ISSUE THREAD

**Issue by greswt** [juewuy/ShellClash#300]
### Verify steps

- [x]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

*使用AX3600官方固件 在路由器/etc上使用大hosts文件以屏蔽广告
1.使用[v1.6.13d]时，无法启动clash服务，附件下图。本人无解。
<img width="1080" alt="截屏2023-01-08 08 50 43" src="https://user-images.githubusercontent.com/104300237/211473088-bb78e654-dd50-44da-be56-0510cb70520f.png">
-
2.使用[v1.6.3正式版]时，路由器重启或更新订阅配置后，无法启动clash服务，附件下图。不完美的解决方法是9-1更新管理脚本至[v1.6.3正式版]，更新完成后可再次启动clash服务，但设备重启后依旧无法启动clash服务，需要重复9-1更新管理脚本至[v1.6.3正式版]。
<img width="1080" alt="截屏2023-01-10 13 44 46" src="https://user-images.githubusercontent.com/104300237/211474234-7a6c0b8f-1a5f-49bc-afde-72aafc16a689.png">
-
可能与我在路由器上使用的广告屏蔽hosts有关？
<img width="1080" alt="截屏2023-01-10 14 04 57" src="https://user-images.githubusercontent.com/104300237/211474288-4af6de93-3af2-4c10-a482-ad1eef576324.png">
hosts文件>>[hosts.zip](https://github.com/juewuy/ShellClash/files/10379420/hosts.zip)

**Comment by juewuy** [comment]
@greswt 路由器hosts屏蔽没什么用，硬要用的话可以尝试最新内测版

**Comment by greswt** [comment]
> @greswt 路由器hosts屏蔽没什么用，硬要用的话可以尝试最新内测版
其实是用来屏蔽小米路由器的遥测和小米盒子的广告用的，关于刚才提到的开机重启clash服务显示/etc/rc. common: line 1: /data/clash: Permission denied的问题，已经参考 #226 的方法，在/etc/profile文件末尾删除alias clash="/data/clash/clash.sh"
export clashdir="/data/clash"

**Comment by greswt** [comment]
@juewuy 其实是用来屏蔽小米路由器的遥测和小米盒子的广告用的，关于刚才提到的开机重启clash服务显示/etc/rc. common: line 1: /data/clash: Permission denied的问题，已经参考 #226  的方法解决了，在/etc/profile文件末尾删除alias clash="/data/clash/clash.sh"
export clashdir="/data/clash"
我会先试一试更新到最新内测版，看看有没有解决configuration file /data/clash/config.yaml test failed的相关问题。

**Comment by JustinFeng** [comment]
我升级到测试版本 v1.6.13d 并重启路由器后，出现了clash无法启动的问题，错误如下
```
Initial configuration directory error: can't create config directory /root/.config/clash: mkdir /root/.config: read-only file system
```
目前重新安装了稳定版v1.6.3

**Comment by juewuy** [comment]
> 我升级到测试版本 v1.6.13d 并重启路由器后，出现了clash无法启动的问题，错误如下
> ```
> Initial configuration directory error: can't create config directory /root/.config/clash: mkdir /root/.config: read-only file system
> ```
> 目前重新安装了稳定版v1.6.3

你安装目录不对
