### ISSUE TITLE
[Feature] 如果要手动添加删除v2ray/ssr的节点现在只能通过ssh处理，可以把这个功能做到面板上吗？

### ISSUE THREAD

**Issue by womarklee** [juewuy/ShellClash#301]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

在面板上直接进行节点的添加和删除，这样小白用户也不用一直通过ssh处理

**Comment by juewuy** [comment]
@womarklee 这不是我能做的，你严重低估了其中的难度
