### ISSUE TITLE
[Bug] 官方面板无法打开

### ISSUE THREAD

**Issue by GDTR12** [juewuy/ShellClash#302]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

重新安装面板也不行

**Comment by juewuy** [comment]
清理浏览器数据及缓存

**Comment by GDTR12** [comment]
解决了，还得是你。
我搞了一下午，太他么离谱了
