### ISSUE TITLE
[Bug] Merlin 关闭 Clash 后无法上网

### ISSUE THREAD

**Issue by Maasea** [juewuy/ShellClash#303]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

本地环境：原版 Merlin

设备：Ac86u

BUG:：关闭 Clash 后无法上网。

troubleshoot: 
1. 经过排查是 Clash 关闭后，DNS 依旧被劫持，无法获取IP。
2. 原因是 Clash 在关闭时，stop_firewall() 函数先用command -v 判断 iptables 命令是否存在, 而 command 命令在merlin 中无法使用，导致后续的路由清理被跳过。

> 脚本里有大量的 command -v 判断语句，对于 merlin 来说都返回了 false，目前我的解决方案是使用 -h 去替代  command -v,部分不支持 -h 的命令，被 --version，-l 替代。

Note: 

1. Merlin 的 /jffs/script 下的启动任务，需要可执行权限，见 [Merlin Creating scripts](https://github.com/RMerl/asuswrt-merlin.ng/wiki/User-scripts#creating-scripts)。 
  `install.sh` 好像并未做这一步，这导致 clash 不能使用 nat-start 方案启动。
2. 全局环境变量在重启后失效，需要使用 `source /etc/profile` 刷新文件

**Comment by juewuy** [comment]
@Maasea 好的，感谢提供反馈
