### ISSUE TITLE
[Bug] 386架构无法更换meta内核

### ISSUE THREAD

**Issue by harnseen** [juewuy/ShellClash#304]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

386架构下可以更换clash和premium内核，切换meta内核失败，提示核心文件下载失败！

**Comment by juewuy** [comment]
@harnseen 换源

**Comment by harnseen** [comment]
换源试过了
![image](https://user-images.githubusercontent.com/42644295/212470740-e2b069fa-963d-494c-8473-21c13b39fc63.png)
1，2，3，4，5，7全试过，都提示核心文件下载失败！

**Comment by juewuy** [comment]
@harnseen 检查剩余空间

**Comment by harnseen** [comment]
> @harnseen 检查剩余空间

![image](https://user-images.githubusercontent.com/42644295/212471225-22c8137b-9504-49aa-afd6-fdf12f658a5b.png)
@juewuy 剩余空间也够

**Comment by juewuy** [comment]
@harnseen 那就手动下载内核后上传吧
