### ISSUE TITLE
如何导入本地的配置文件存储在哪？

### ISSUE THREAD

**Issue by bao3** [juewuy/ShellClash#307]
我知道导入配置文件是在 6-1，6-2 里完成。不过我的文件是本地配置文件( ~/basic.yaml ) ，所以

我选 6-1,则提示我“请输入正确的链接或者数字“

我选 6-2，则提示我“请输入正确的配置文件链接地址！！！仅支持http、https、ftp以及ftps链接”

总结起来就是没有找到导入本地配置文件的接口。所以想问一下，本地的配置文件是存储在哪里，我是不是可以直接使用我本地的配置文件？

**Comment by juewuy** [comment]
@bao3 直接复制到安装目录并重命名为config.yaml
