### ISSUE TITLE
[Feature] 建议增加openssl检测

### ISSUE THREAD

**Issue by wwng2333** [juewuy/ShellClash#308]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

如题，目前脚本没有openssl的话curl根本不会报错，会一直卡住
```
K2P:/etc/storage/clash # wget https://fastly.jsdelivr.net/gh/juewuy/ShellClash@master/bin/clash/clash-linux-mipsle-softfloat
Connecting to fastly.jsdelivr.net (151.101.1.229:443)
wget: can't execute 'openssl': No such file or directory
```

**Comment by juewuy** [comment]
使用 wget --no-check-certificate
