### ISSUE TITLE
能不能直接配置成linux 全局http代理

### ISSUE THREAD

**Issue by jth445600** [juewuy/ShellClash#31]
比如说在ubuntu server没有图形界面的设备,设置成http全局代理.
以前的解决方案是 socks5+redsocks
这个clash自带http代理呀,就不需要redsocks了

**Comment by juewuy** [comment]
目前只支持配置到环境变量里，至于应用是否调用就没办法了
未来会考虑改成使用iptables全局代理

**Comment by jth445600** [comment]
iptables全局代理应该怎么写呀？
我这么写不行呀

```shell
 sudo iptables -t nat -N TEST
 sudo iptables -t nat -A TEST -d 104.19.52.88 -j RETURN  #server_ip
 sudo iptables -t nat -A TEST -d 0.0.0.0/8 -j RETURN
 sudo iptables -t nat -A TEST -d 10.0.0.0/8 -j RETURN
 sudo iptables -t nat -A TEST -d 127.0.0.0/8 -j RETURN
 sudo iptables -t nat -A TEST -d 169.254.0.0/16 -j RETURN
 sudo iptables -t nat -A TEST -d 172.16.0.0/12 -j RETURN
 sudo iptables -t nat -A TEST -d 192.168.0.0/16 -j RETURN
 sudo iptables -t nat -A TEST -d 224.0.0.0/4 -j RETURN
 sudo iptables -t nat -A TEST -d 240.0.0.0/4 -j RETURN
 sudo iptables -t nat -A TEST -p tcp -j REDIRECT --to-ports 7890
 sudo iptables -t nat -A OUTPUT -p tcp -j TEST

```

**Comment by juewuy** [comment]
参考https://github.com/Dreamacro/clash/issues/555#issuecomment-595064646

**Comment by Jefffish09** [comment]
> 参考[Dreamacro/clash#555 (comment)](https://github.com/Dreamacro/clash/issues/555#issuecomment-595064646)

最近用shellclash，发现即使开了本机代理，本机上的一些应用确实也无法走代理，比如我在alpine开了本机代理，装adguardhome之后，在adg web页面上更新各种规则（github）也是无法连接的。想问问，更好的解决办法吗？

**Comment by juewuy** [comment]
@Jefffish09 开增强模式

**Comment by juewuy** [comment]
@Jefffish09 alpine不是标准Linux系统，需要自行安装相关依赖
