### ISSUE TITLE
armv8核心下载失败

### ISSUE THREAD

**Issue by kongdd** [juewuy/ShellClash#310]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

clash无法启动，请问有解决方法吗？

```
当前clash核心： 未安装核心
当前系统处理器架构： armv8
请选择需要使用的核心版本！
-----------------------------------------------

未找到clash核心，正在下载！
################################################################################### 100.0%
核心下载失败，请重新运行或更换安装源！
```

**Comment by juewuy** [comment]
@kongdd 更新最新版

**Comment by kongdd** [comment]
谢谢，安装成功了，但有个bug。

SwitchyOmege可以正常使用，但如果是直连的话失败。该如何排错呢？

```
欢迎使用功能设置菜单：
-----------------------------------------------
 1 切换Clash运行模式:   Redir模式
 2 切换DNS运行模式：    redir_host
 3 跳过本地证书验证：   已开启   ————解决节点证书验证错误
 4 只代理常用端口：     已开启   ————用于过滤P2P流量
 5 过滤局域网设备：     未开启   ————使用黑/白名单进行过滤
 6 设置本机代理服务:    未开启   ————使本机流量经过clash内核
 7 屏蔽QUIC流量:        未开启   ————优化视频性能
 8 CN_IP绕过内核:       未开启   ————优化性能，不兼容Fake-ip
-----------------------------------------------
```

**Comment by juewuy** [comment]
@kongdd 如果是直连是什么意思

**Comment by kongdd** [comment]
clash选择Rules mode，Proxies自动选择代理；浏览器中关掉SwitchyOmege，然后访问google失败

**Comment by juewuy** [comment]
@kongdd 参考常见问题

**Comment by kongdd** [comment]
多谢，改成fake-ip之后，可以使用了。
