### ISSUE TITLE
1.7在小米ax3600官方固件运行时/mark报错

### ISSUE THREAD

**Issue by DoveKi** [juewuy/ShellClash#314]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

官方固件没有/mark的创建权限，安装时的/mark报错之前修复了，但是运行时还是经常出现/mark有关的No such file or directory报错

**Comment by juewuy** [comment]
@DoveKi 请安装最新版本，之前版本有bug已修复

**Comment by DoveKi** [comment]
> @DoveKi 请安装最新版本，之前版本有bug已修复

是修复了 版本号没改么

**Comment by juewuy** [comment]
@DoveKi 你是新安装还是升级的

**Comment by DoveKi** [comment]
> @DoveKi 你是新安装还是升级的

前几天看issues有人提安装时的mark报错，你回修复了，我就完全卸载重新装了，那天看了下三个安装源虽然版本号都是1.7，但好像没同步更新，只有一个修复了，而且第一次运行没引导菜单，现在重装试了一下可以了，而且第一次运行也有引导菜单了

**Comment by juewuy** [comment]
@DoveKi OK，可能是CDN缓存原因
