### ISSUE TITLE
[Bug] 首先添加订阅，然后添加vmess分享链接后UI界面中的手动选择TAG消失

### ISSUE THREAD

**Issue by wangran99** [juewuy/ShellClash#315]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

 1 更新管理脚本         1.6.3 > 1.6.3正式版
 2 切换clash核心        v1.7.1 > v1.7.1
 3 更新GeoIP/CN-IP      20220709 > 20220709

首先导入配置文件，添加订阅链接，然后再追加vmess分享链接后，9999端口的UI界面中的手动选择TAG消失，没有任何可选择的线路，ssh中也没有报错。

**Comment by juewuy** [comment]
@wangran99 说明链接有问题或者生成配置失败

**Comment by wangran99** [comment]
> @wangran99 说明链接有问题或者生成配置失败

测试后发现分享的vmess的别名中全是中文就会出现上述问题，改成应为就没有问题了
