### ISSUE TITLE
无法使用ssh-key连接github

### ISSUE THREAD

**Issue by ShIRannx** [juewuy/ShellClash#316]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

在将ssh-key加入github设置页的SSH and GPG keys 后 在被shellclash代理后的局域网主机无法成功验证 
![image](https://user-images.githubusercontent.com/72802064/215251026-1d2992bb-8e2c-471f-a1d2-d915f7c43410.png)
关闭shellclash后可以成功连接
![image](https://user-images.githubusercontent.com/72802064/215251134-02b27a23-637f-4be9-9048-752a93897344.png)

**Comment by juewuy** [comment]
请提供相关连接的clash面板日志

**Comment by ShIRannx** [comment]
![image](https://user-images.githubusercontent.com/72802064/215254803-126110dd-824d-493d-ae2f-bc1eae38c97c.png)

**Comment by juewuy** [comment]
@ShIRannx 日志没问题，可能是节点原因

**Comment by ShIRannx** [comment]
感谢
