### ISSUE TITLE
[Bug] 跳过本地证书验证

### ISSUE THREAD

**Issue by itcut** [juewuy/ShellClash#317]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

设置中跳过本地证书验证 无论是选择开启或者未开启，配置文件中的skip-cert-verify 均为true，无任何变化。手动修改配置文件中的skip-cert-verify为false，实际连接节点的时候还是能通过验证。

已安装最新1.7.0 版本

**Comment by itcut** [comment]
[https://github.com/MetaCubeX/Clash.Meta/pull/333](url)

应该是Meta内核的原因，用最新Alpha版本测试skip-cert-verify 为false的时候节点就无法连接了。

但是用脚本关闭跳过本地证书验证时还是无法对应修改配置文件中为false，大佬能否再看看

**Comment by juewuy** [comment]
公测版已修复

**Comment by itcut** [comment]
好的，我试试，thx!
