### ISSUE TITLE
[错误] 提示start.sh文件错误

### ISSUE THREAD

**Issue by CathayGk** [juewuy/ShellClash#318]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

大佬帮帮忙 谢谢🙏
![Uploading C62CF894-0663-49D0-8EDC-1A6915885BC9.png…]()

**Comment by CathayGk** [comment]
![Uploading AE161476-A7C5-4D56-AD25-3FDDE8331CAF.jpeg…]()

**Comment by CathayGk** [comment]
-----------------------------------------------
/share/clash/clash/start.sh: line 1272: syntax error near unexpected token `;;'
/share/clash/clash/start.sh: line 1272: `       ;;'
[admin@XK ~]#

**Comment by juewuy** [comment]
不行就卸载重装试试
也可能是配置文件有问题

**Comment by CathayGk** [comment]
> 不行就卸载重装试试
> 也可能是配置文件有问题

我再试试

**Comment by CathayGk** [comment]
> 不行就卸载重装试试
> 也可能是配置文件有问题


大佬 还是这个错误

**Comment by juewuy** [comment]
@CathayGk 把自定义配置文件相关内容移除

**Comment by CathayGk** [comment]
> @CathayGk 把自定义配置文件相关内容移除

大佬 我在自己研究研究

**Comment by CathayGk** [comment]
> @CathayGk 把自定义配置文件相关内容移除

[admin@K clash]# ./start.sh
./start.sh: line 1272: syntax error near unexpected token ./start.sh: line 1272:
大佬 单独执行也出现这个问题

**Comment by CathayGk** [comment]
> @CathayGk 把自定义配置文件相关内容移除
大佬 单独执行这个文件 也是这样提示
[admin@K clash]# ./start.sh
./start.sh: line 1272: syntax error near unexpected token `;;`
./start.sh: line 1272: ` ;;`

**Comment by juewuy** [comment]
@CathayGk 更新里重新安装过吗？脚本正常是不会报错的

**Comment by CathayGk** [comment]
> @CathayGk 更新里重新安装过吗？脚本正常是不会报错的

好的 大佬 我在研究研究

**Comment by CathayGk** [comment]
> > @CathayGk 更新里重新安装过吗？脚本正常是不会报错的
> 
> 好的 大佬 我在研究研究
> 

大佬 我是威联通453dmini
以前用过 直接安装就行 现在还是报 1272 这个错误  本地搭建 直接gthub下载文件导入进去还是这个错误。是不是缺少什么软件没按照  我nas恢复出厂了 然后就提示这样

**Comment by juewuy** [comment]
@CathayGk ls -l /bin/sh 运行结果发一下

**Comment by CathayGk** [comment]
> ls -l /bin

-rwxr-xr-x 1 admin administrators 947808 2023-01-12 06:09 /bin/sh*

**Comment by juewuy** [comment]
@CathayGk type bash 
运行这个呢？
如果结果是正常的，把start.sh文件头里/bin/sh改成/bin/bash

**Comment by CathayGk** [comment]
> @CathayGk type bash 
> 运行这个呢？
> 如果结果是正常的，把start.sh文件头里/bin/sh改成/bin/bash

我装下 type

**Comment by CathayGk** [comment]
> > @CathayGk type bash 
> > 运行这个呢？
> > 如果结果是正常的，把start.sh文件头里/bin/sh改成/bin/bash
> 
> 我装下 type

文件里面就是bash

**Comment by CathayGk** [comment]
> > @CathayGk type bash 
> > 运行这个呢？
> > 如果结果是正常的，把start.sh文件头里/bin/sh改成/bin/bash
> 

bash is hashed (/bin/bash)

**Comment by juewuy** [comment]
@CathayGk 那不应该啊，bash我没见过报错的

**Comment by CathayGk** [comment]
> @CathayGk 那不应该啊，bash我没见过报错的

那看来就是我机器的毛病了  我在研究一下吧
