### ISSUE TITLE
我在ikuai上装了后运行一段时间会出现 一些奇怪的回环请求

### ISSUE THREAD

**Issue by greatxin** [juewuy/ShellClash#32]
![image](https://user-images.githubusercontent.com/48113335/118522623-da331b00-b76e-11eb-80af-5725ebd7ec1a.png)
如图，在运行一段时间后就会出现这样的本机外网ip请求外网7890端口的请求，数量非常多，请求非常快，导致cpu占用高，有什么解决方法吗？
netstats -alp 没有pid显示

**Comment by juewuy** [comment]
请问是哪个1.3.2版本吗

**Comment by greatxin** [comment]
是1.3.0
![image](https://user-images.githubusercontent.com/48113335/118629267-0480e900-b800-11eb-8e91-56e205081ab2.png)

**Comment by juewuy** [comment]
请更新一下1.3.2版本试一下

**Comment by juewuy** [comment]
目前无法明确定位问题所在

**Comment by greatxin** [comment]
黑名单能设置ip吗，我现在用白名单模式似乎有缓解，如果现在还会出现我再升1.3.2试试

**Comment by greatxin** [comment]
![image](https://user-images.githubusercontent.com/48113335/118679722-b46e4a80-b830-11eb-9a41-d4555dbde761.png)
还是出现了，还导致白名单内设备无法上网，我现在换1.3.2试试

**Comment by greatxin** [comment]
![image](https://user-images.githubusercontent.com/48113335/118745305-74d34d00-b888-11eb-9a64-08f58cdcf912.png)

**Comment by juewuy** [comment]
这个最好发到核心那边试一下，我也不明白为什么还会出现这个bug
1.3.0版本只有preouting链允许流量，而本机发出的流量理论上是不会进入preouting链的

**Comment by greatxin** [comment]
我找到怎么触发的了，我用nmap扫描了一下wan口地址，然后就重现了

**Comment by juewuy** [comment]
PREOUTING链会处理内部从LAN口到本机/WAN的流量，也会处理WAN到本机/LAN的流量，但是不会处理本机发出的流量
所以问题应该是出在为什么会有外部WAN到本机的流量经过clash内核
你可以通过进阶设置，指定本机host设置，将本机host仅指定为局域网ip或者localhost地址，可能会改善这个问题
但是对于clash产生的流量为什么会从WAN网卡对本机或局域网产生访问，我就不是特别清楚了

**Comment by greatxin** [comment]
我的ip是公网ip，被人扫是很正常的事，目前我把端口换到8080(电信屏蔽的端口)，就没出现问题了

**Comment by greatxin** [comment]
![image](https://user-images.githubusercontent.com/48113335/119101264-5f5a5080-ba4b-11eb-974a-3cde29ffb60a.png)
该怎么填写

**Comment by juewuy** [comment]
这可能是个bug

**Comment by juewuy** [comment]
已修复@1.3.3
