### ISSUE TITLE
[Bug] 使用relay方式无法后无法正常使用

### ISSUE THREAD

**Issue by sryanyuan** [juewuy/ShellClash#320]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

机器型号红米AX6000

config配置内，使用relay方式来进行上网，前置代理由proxy-providers提供，落地为固定IP机器

运行模式设置为redir模式，通过日志查看，已经有访问对应网站到对应的relay组的日志，并且在路由器抓包也有双向流量，但是无法通过直接访问来上网。具体表现为向服务器发送了Client Hello后只有ack，没有后续的响应，而路由器上抓包是有正常的响应数据的

在机器上主动设置代理服务器7890端口可以正常使用，落地IP也是正确的

==============================

假设不使用relay组直接使用proxy-providers组是正常的，使用relay就无法正常使用

==============================
```
-------------------Redir---------------------
Chain PREROUTING (policy ACCEPT)
num  target     prot opt source               destination
1    clash_dns  udp  --  anywhere             anywhere             udp dpt:domain
2    prerouting_rule  all  --  anywhere             anywhere             /* !fw3: Custom prerouting rule chain */
3    zone_lan_prerouting  all  --  anywhere             anywhere             /* !fw3 */
4    zone_wan_prerouting  all  --  anywhere             anywhere             /* !fw3 */
5    clash      tcp  --  anywhere             anywhere             multiport dports ssh,domain,www,ntp,imap2,194,https,ssmtp,submission,853,imaps,pop3s,xmpp-client,8080,8443
Chain clash_dns (1 references)
num  target     prot opt source               destination
1    REDIRECT   udp  --  anywhere             anywhere             redir ports 1053
Chain clash (1 references)
num  target     prot opt source               destination
1    RETURN     all  --  anywhere             0.0.0.0/8
2    RETURN     all  --  anywhere             10.0.0.0/8
3    RETURN     all  --  anywhere             127.0.0.0/8
4    RETURN     all  --  anywhere             100.64.0.0/10
5    RETURN     all  --  anywhere             169.254.0.0/16
6    RETURN     all  --  anywhere             172.16.0.0/12
7    RETURN     all  --  anywhere             192.168.0.0/16
8    RETURN     all  --  anywhere             base-address.mcast.net/4
9    RETURN     all  --  anywhere             240.0.0.0/4
10   REDIRECT   tcp  --  192.168.0.0/16       anywhere             redir ports 7892
11   REDIRECT   tcp  --  10.0.0.0/8           anywhere             redir ports 7892
```

**Comment by juewuy** [comment]
确定使用的内核支持吗？切换meta内核尝试

**Comment by sryanyuan** [comment]
> 确定使用的内核支持吗？切换meta内核尝试

感谢回复。

clash premium和clash meta都是一样的，应该不是内核支持问题，因为浏览器不走路由器的透明代理直接走7890的http代理是可以正常访问的，并且落地IP也是relay后的，所以流量是走通的。

路由器上抓包也有相应数据，就是不知道clash进程是否收到数据并且返回给浏览器数据了

**Comment by juewuy** [comment]
@sryanyuan 最好能搭配面板日志和连接，排查问题
另外也要排除是否是触发cnip绕过或者常用端口过滤等规则

**Comment by sryanyuan** [comment]
好的 我之前开过Debug日志 有用信息不多
从代理机器回来的流量应该直接进到协议栈 目前tcpdump可以抓到 但是不知道clash内核是否真的收到此数据包了 理论上代理是国外的不会触发cnip绕过（443端口https），并且走7890能正常访问 理论上进来的流量也是会走iptables处理一遍的

后面我该下规则排除下干扰再看看有没有更多线索

**Comment by juewuy** [comment]
7-6启用加密DNS
