### ISSUE TITLE
[Bug] sh: 65: source: not found，显示安装成功但无法运行[已定位bug]

### ISSUE THREAD

**Issue by Xerxes-zhz** [juewuy/ShellClash#322]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

使用README_CN中的下载链接安装时会报错，同时install.sh显示安装成功，但无法打开clash，服务列表也没有clash。
看了下install.sh的相关代码，发现是source指令无法在sh中运行，所以手动curl install.sh到本地，直接在bash里source install.sh就不会报错。
```
-----------------------------------------------
开始解压文件！
clash.service
clash.sh
clashservice
Country.mmdb
getdate.sh
init.sh
misnap_init.sh
start.sh
sh: 65: source: not found
-----------------------------------------------
ShellClash 已经安装成功!
-----------------------------------------------
输入 clash 命令即可管理！！！

```

我使用的自动安装链接是
```
#jsDelivrCDN源
export url='https://fastly.jsdelivr.net/gh/juewuy/ShellClash@master' && sh -c "$(curl -kfsSl $url/install.sh)" && source /etc/profile &> /dev/null
```
可以看到是用sh启动的install.sh，理论上所有的用sh启动的install.sh都无法运行

**Comment by juewuy** [comment]
@Xerxes-zhz 不仔细看文档的结果

**Comment by Xerxes-zhz** [comment]
> @Xerxes-zhz 重进ssh即可

@juewuy 研究了一下光重进应该不行，debian 的sh指向的是dash，dash不支持source
我又看了下问题文档，应该是没对类似的问题解释，也可以在安装文档提一句
```
$ ls -la /usr/bin/sh
lrwxrwxrwx 1 root root 4 Feb 11 18:54 /usr/bin/sh -> dash
```
