### ISSUE TITLE
[Bug] openwrt开启tproxy模式国内外皆无法联网

### ISSUE THREAD

**Issue by lisansas** [juewuy/ShellClash#323]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description
设备J4125软路由,iptables-mod-tproxy，kmod-ipt-tproxy，kmod-nf-tproxy，kmod-nft-tproxy皆已安装
如题，其他模式皆正常，但只要涉及到tproxy的功能全部显示block，dashboard里面没有任何连接，但从路由器本身发出的连接可以看到。

![Clip_20230217_155645](https://user-images.githubusercontent.com/38862056/219585555-ab39444a-2546-4e8b-bb17-16803228ebe9.jpg)
这是8-1-4

**Comment by juewuy** [comment]
iptables正常，是不是自定义了特殊网段？

**Comment by lisansas** [comment]
> iptables正常，是不是自定义了特殊网段？

只自定义了

dns:
  enable: true
  listen: 0.0.0.0:1053
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16   
  fake-ip-filter:
      - "*.lan"
      - "*.localdomain"
      - "*.example"
      - "*.invalid"
      - "*.localhost"
      - "*.test"
      - "*.local"
      - "*.home.arpa"
    #放行NTP服务"
      - "time.*.com"
      - "time.*.gov"
      - "time.*.edu.cn"
      - "time.*.apple.com"
      - "time1.*.com"
      - "time2.*.com"
      - "time3.*.com"
      - "time4.*.com"
      - "time5.*.com"
      - "time6.*.com"
      - "time7.*.com"
      - "ntp.*.com"
      - "ntp1.*.com"
      - "ntp2.*.com"
      - "ntp3.*.com"
      - "ntp4.*.com"
      - "ntp5.*.com"
      - "ntp6.*.com"
      - "ntp7.*.com"
      - "*.time.edu.cn"
      - "*.ntp.org.cn"
      - "+.pool.ntp.org"
      - "time1.cloud.tencent.com"
    #放行网易云音乐"
      - "music.163.com"
      - "*.music.163.com"
      - "*.126.net"
    #百度音乐"
      - "musicapi.taihe.com"
      - "music.taihe.com"
    #酷狗音乐"
      - "songsearch.kugou.com"
      - "trackercdn.kugou.com"
    #酷我音乐"
      - "*.kuwo.cn"
    #JOOX音乐"
      - "api-jooxtt.sanook.com"
      - "api.joox.com"
      - "joox.com"
    #QQ音乐"
      - "y.qq.com"
      - "*.y.qq.com"
      - "streamoc.music.tc.qq.com"
      - "mobileoc.music.tc.qq.com"
      - "isure.stream.qqmusic.qq.com"
      - "dl.stream.qqmusic.qq.com"
      - "aqqmusic.tc.qq.com"
      - "amobile.music.tc.qq.com"
    #虾米音乐"
      - "*.xiami.com"
    #咪咕音乐"
      - "*.music.migu.cn"
      - "music.migu.cn"
    #win10本地连接检测"
      - "+.msftconnecttest.com"
      - "+.msftncsi.com"
      - "msftconnecttest.com"
      - "msftncsi.com"
    #QQ快捷登录"
      - "localhost.ptlogin2.qq.com"
      - "localhost.sec.qq.com"
    #Game"
    #Nintendo Switch"
      - "+.srv.nintendo.net"
    #Sony PlayStation"
      - "+.stun.playstation.net"
    #Microsoft Xbox"
      - "xbox.*.microsoft.com"
      - "xnotify.xboxlive.com"
      - "+.ipv6.microsoft.com"
    #Wotgame"
      - "+.battlenet.com.cn"
      - "+.wotgame.cn"
      - "+.wggames.cn"
      - "+.wowsgame.cn"
      - "+.wargaming.net"
    #Golang"
      - "proxy.golang.org"
    #STUN"
      - "stun.*.*"
      - "stun.*.*.*"
      - "+.stun.*.*"
      - "+.stun.*.*.*"
      - "+.stun.*.*.*.*"
      - "+.pvp.net"
    #Linksys Router"
      - "heartbeat.belkin.com"
      - "*.linksys.com"
      - "*.linksyssmartwifi.com"
    #ASUS Router"
      - "*.router.asus.com"
    #Apple Software Update Service"
      - "mesu.apple.com"
      - "swscan.apple.com"
      - "swquery.apple.com"
      - "swdownload.apple.com"
      - "swcdn.apple.com"
      - "swdist.apple.com"
    #Google"
      - "lens.l.google.com"
      - "stun.l.google.com"
    #Netflix"
      - "+.nflxvideo.net"
    #FinalFantasy XIV Worldwide Server & CN Server"
      - "*.square-enix.com"
      - "*.finalfantasyxiv.com"
      - "*.ffxiv.com"
      - "*.ff14.sdo.com"
      - "ff.dorado.sdo.com"
    #Bilibili"
      - "*.mcdn.bilivideo.cn"
    #Disney Plus"
      - "+.media.dssott.com"
      - "s.amoe.cc"
------------------------
其余皆是默认设置。

**Comment by juewuy** [comment]
@lisansas 先移除自定义配置，看是否是相关问题

**Comment by lisansas** [comment]
> @lisansas 先移除自定义配置，看是否是相关问题

已移除并且全默认，只6-1生成了一个配置文件，tproxy仍旧没有任何其他设备流量经过，无论国内外网站皆无法连接。

**Comment by juewuy** [comment]
@lisansas 是主路由吗？不是旁路由或者无线中继？

**Comment by lisansas** [comment]
> @lisansas 是主路由吗？不是旁路由或者无线中继？

是的，我目前想到最可能的原因是装的openwrt原先自带一个叫clash的插件，我没有卸载直接安装了shellclash，刚刚看了眼网页面板，在里面可以看到shellclash的一些运行状态。

**Comment by juewuy** [comment]
@lisansas 建议尝试其他模式试试，另外网段必须是192.168.x或者10.x

**Comment by lisansas** [comment]
> @lisansas 建议尝试其他模式试试，另外网段必须是192.168.x或者10.x

其余模式redir和tun皆正常，网段也正常，刚刚把clash和shellclash都卸载了效果也是一样，应该是tproxy转发出了问题，搜了下可能是防火墙还是啥？

我刚刚用tproxy模式更新shellclash的时候，dashboard是有流量正常通过的，只是使用其他设备的时候都没有流量了。

另外用passwall2测试过tproxy也可以正常启用。

**Comment by juewuy** [comment]
@lisansas 不是很清楚，可能是流量标记有冲突

**Comment by lisansas** [comment]
> @lisansas 不是很清楚，可能是流量标记有冲突

自己在防火墙设定了规则解决

**Comment by TigerBeanst** [comment]
> 自己在防火墙设定了规则解决

想问下设置了什么规则，我也遇到这个了（
