### ISSUE TITLE
Redmi AX6000里使用shellclash+aguardhome如何设置dns？

### ISSUE THREAD

**Issue by twedu** [juewuy/ShellClash#328]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

采用的是Troproxy+fakeIP模式。
是不是需要将shellclash里的基础dns改为adguardhome的端口号，即127.0.0.1:xxxx
然后在AX6000里将LAN的DNS改为adguardhome ip，即网关ip？
还需要别的设置么，打不开speedtest.net,有的网站，如v2ex.com也挺慢

**Comment by juewuy** [comment]
@twedu 参考
https://t.me/ShellClash/148

**Comment by twedu** [comment]
我按照那个设置后发现网速变得很慢。
我用的tproxy+fakeip，
ax6000里将dns设为跟网关一致，还有一个223.5.5.5
shellclash里基础dns设置为127.0.0.1:xxx
adguardhome的端口为xxxx
按上面设置完之后，突然油管只有几百k，重启速度还是在2000k左右，speedtest及fast这个页面打不开，只好将shellclash的dns重置，关闭adg，暂时恢复正常。
请问是哪里的问题？


juewuy ***@***.***> 于 2023年2月27日周一 16:30写道：

**Comment by juewuy** [comment]
@twedu 不要用fakeip，另外注意设备内存占用

**Comment by twedu** [comment]
> 不要用fakeip，另外注意设备内存占用

另外7-6里dns加密就提示要安装证书，但下载100%后又无法安装，这个怎么解决？换源也不管用

**Comment by juewuy** [comment]
@twedu 证书换正式版源下载

**Comment by twedu** [comment]
adg里设置dnsmasq转发到adg端口，如何操作？

**Comment by twedu** [comment]
目前用的方案：
shellclash里关闭dns，adg里上游服务器127.0.0.1:xxxx
这个方案有问题么?
b站视频偶尔会卡一下
这个方案里外网dns交给谁了？
2023年3月2日 +0800 22:19 juewuy ***@***.***>，写道：

**Comment by CaoKang-David** [comment]
个人觉得目前最好的方案是adguardhome做dns解析，clash的dns服务和劫持dns都关掉，开启sniffer，这样就好了。速度能跟上。注意，sniffer只有clash meta才支持。
