### ISSUE TITLE
[Bug] 导入订阅链接中包含%26时，会被错误解析为&符号导致订阅失败

### ISSUE THREAD

**Issue by tinymins** [juewuy/ShellClash#329]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

如图，输入订阅链接后确认时候链接地址已经错误变更了：
![image](https://user-images.githubusercontent.com/1808990/221504299-e1df8ed6-d139-48b8-9a31-f22cfdbf0fda.png)

删除该行后功能恢复正常：

https://github.com/juewuy/ShellClash/blob/master/scripts/start.sh#L179

![image](https://user-images.githubusercontent.com/1808990/221504688-26372e56-4953-4cdb-8313-6f5591e51353.png)

这行看起来是故意添加的，不知道为何要故意增加一行导致出现 BUG 的逻辑呢？

**Comment by juewuy** [comment]
@tinymins 这只是取舍，并不是bug

**Comment by tinymins** [comment]
@juewuy 我的表述问题，就是看起来是故意加的似乎要解决什么问题，但是从提交历史上没有看出增加这行逻辑的目的，所以比较疑惑。
因为是想要看看究竟是需要解决什么问题，从而思考有没有办法同时解决这两个问题。

**Comment by juewuy** [comment]
@tinymins &是特殊符号，无法正常存档在配置文件里
