### ISSUE TITLE
导入配置文件报错，大佬看下啥情况 ，好像是oom了

### ISSUE THREAD

**Issue by ceylog** [juewuy/ShellClash#33]
-----------------------------------------------
请输入完整链接 > http://192.168.1.96/sub.yaml
-----------------------------------------------
请检查输入的链接是否正确：
http://192.168.1.96/sub.yaml
确认导入配置文件？原配置文件将被更名为config.yaml.bak![1/0] > 1
-----------------------------------------------
正在连接服务器获取配置文件…………链接地址为：
http://192.168.1.96/sub.yaml
可以手动复制该链接到浏览器打开并查看数据是否正常！
############################################################################################################################### 100.0%
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x769b2d, 0x16)
	runtime/panic.go:1117 +0x54 fp=0x7fca31d2e0 sp=0x7fca31d2b0 pc=0x42b24
runtime.sysMap(0x4000000000, 0x4000000, 0xcbc430)
	runtime/mem_linux.go:169 +0xbc fp=0x7fca31d320 sp=0x7fca31d2e0 pc=0x2714c
runtime.(*mheap).sysAlloc(0xca33c0, 0x400000, 0x7fca31d438, 0x35b50)
	runtime/malloc.go:729 +0x188 fp=0x7fca31d3d0 sp=0x7fca31d320 pc=0x1b528
runtime.(*mheap).grow(0xca33c0, 0x1, 0x0)
	runtime/mheap.go:1346 +0x80 fp=0x7fca31d440 sp=0x7fca31d3d0 pc=0x35d50
runtime.(*mheap).allocSpan(0xca33c0, 0x1, 0x2c00, 0x0)
	runtime/mheap.go:1173 +0x670 fp=0x7fca31d4d0 sp=0x7fca31d440 pc=0x35b80
runtime.(*mheap).alloc.func1()
	runtime/mheap.go:910 +0x54 fp=0x7fca31d520 sp=0x7fca31d4d0 pc=0x6d924
runtime.(*mheap).alloc(0xca33c0, 0x1, 0x7fca31012c, 0x264a4)
	runtime/mheap.go:904 +0x64 fp=0x7fca31d570 sp=0x7fca31d520 pc=0x350f4
runtime.(*mcentral).grow(0xcb56f8, 0x0)
	runtime/mcentral.go:232 +0x74 fp=0x7fca31d5c0 sp=0x7fca31d570 pc=0x267a4
runtime.(*mcentral).cacheSpan(0xcb56f8, 0x0)
	runtime/mcentral.go:158 +0x344 fp=0x7fca31d630 sp=0x7fca31d5c0 pc=0x26594
runtime.(*mcache).refill(0x7f9a311108, 0x2c)
	runtime/mcache.go:162 +0xc0 fp=0x7fca31d690 sp=0x7fca31d630 pc=0x258d0
runtime.(*mcache).nextFree(0x7f9a311108, 0xc8be2c, 0x7fca31d718, 0x1cd10, 0x7fca31d748)
	runtime/malloc.go:882 +0x8c fp=0x7fca31d6e0 sp=0x7fca31d690 pc=0x1bc3c
runtime.mallocgc(0x178, 0x75b700, 0x7fca31d701, 0x7fca31d7d8)
	runtime/malloc.go:1069 +0x75c fp=0x7fca31d790 sp=0x7fca31d6e0 pc=0x1c52c
runtime.newobject(0x75b700, 0x465e8)
	runtime/malloc.go:1177 +0x38 fp=0x7fca31d7c0 sp=0x7fca31d790 pc=0x1c748
runtime.malg(0x8000, 0x0)
	runtime/proc.go:3944 +0x2c fp=0x7fca31d810 sp=0x7fca31d7c0 pc=0x4da7c
runtime.mpreinit(0xc8be40)
	runtime/os_linux.go:355 +0x28 fp=0x7fca31d830 sp=0x7fca31d810 pc=0x3f918
runtime.mcommoninit(0xc8be40, 0xffffffffffffffff)
	runtime/proc.go:744 +0xdc fp=0x7fca31d880 sp=0x7fca31d830 pc=0x4670c
runtime.schedinit()
	runtime/proc.go:637 +0x98 fp=0x7fca31d8e0 sp=0x7fca31d880 pc=0x46228
runtime.rt0_go(0x7fca31fe73, 0x7fca31fe89, 0x7fca31fe8c, 0x7fca31fe8f, 0x7fca31fe9f, 0x7fca31fea2, 0x0, 0x7fca31febe, 0x7fca31fedf, 0x7fca31fee9, ...)
	runtime/asm_arm64.s:82 +0xa8 fp=0x7fca31d910 sp=0x7fca31d8e0 pc=0x73ff8
配置文件加载失败！请查看报错信息！
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x769b2d, 0x16)
	runtime/panic.go:1117 +0x54 fp=0x7fd6b71da0 sp=0x7fd6b71d70 pc=0x42b24
runtime.sysMap(0x4000000000, 0x4000000, 0xcbc430)
	runtime/mem_linux.go:169 +0xbc fp=0x7fd6b71de0 sp=0x7fd6b71da0 pc=0x2714c
runtime.(*mheap).sysAlloc(0xca33c0, 0x400000, 0x7fd6b71ef8, 0x35b50)
	runtime/malloc.go:729 +0x188 fp=0x7fd6b71e90 sp=0x7fd6b71de0 pc=0x1b528
runtime.(*mheap).grow(0xca33c0, 0x1, 0x0)
	runtime/mheap.go:1346 +0x80 fp=0x7fd6b71f00 sp=0x7fd6b71e90 pc=0x35d50
runtime.(*mheap).allocSpan(0xca33c0, 0x1, 0x2c00, 0x0)
	runtime/mheap.go:1173 +0x670 fp=0x7fd6b71f90 sp=0x7fd6b71f00 pc=0x35b80
runtime.(*mheap).alloc.func1()
	runtime/mheap.go:910 +0x54 fp=0x7fd6b71fe0 sp=0x7fd6b71f90 pc=0x6d924
runtime.(*mheap).alloc(0xca33c0, 0x1, 0x7fd6b7012c, 0x264a4)
	runtime/mheap.go:904 +0x64 fp=0x7fd6b72030 sp=0x7fd6b71fe0 pc=0x350f4
runtime.(*mcentral).grow(0xcb56f8, 0x0)
	runtime/mcentral.go:232 +0x74 fp=0x7fd6b72080 sp=0x7fd6b72030 pc=0x267a4
runtime.(*mcentral).cacheSpan(0xcb56f8, 0x0)
	runtime/mcentral.go:158 +0x344 fp=0x7fd6b720f0 sp=0x7fd6b72080 pc=0x26594
runtime.(*mcache).refill(0x7f90170108, 0x2c)
	runtime/mcache.go:162 +0xc0 fp=0x7fd6b72150 sp=0x7fd6b720f0 pc=0x258d0
runtime.(*mcache).nextFree(0x7f90170108, 0xc8be2c, 0x7fd6b721d8, 0x1cd10, 0x7fd6b72208)
	runtime/malloc.go:882 +0x8c fp=0x7fd6b721a0 sp=0x7fd6b72150 pc=0x1bc3c
runtime.mallocgc(0x178, 0x75b700, 0x7fd6b72201, 0x7fd6b72298)
	runtime/malloc.go:1069 +0x75c fp=0x7fd6b72250 sp=0x7fd6b721a0 pc=0x1c52c
runtime.newobject(0x75b700, 0x465e8)
	runtime/malloc.go:1177 +0x38 fp=0x7fd6b72280 sp=0x7fd6b72250 pc=0x1c748
runtime.malg(0x8000, 0x0)
	runtime/proc.go:3944 +0x2c fp=0x7fd6b722d0 sp=0x7fd6b72280 pc=0x4da7c
runtime.mpreinit(0xc8be40)
	runtime/os_linux.go:355 +0x28 fp=0x7fd6b722f0 sp=0x7fd6b722d0 pc=0x3f918
runtime.mcommoninit(0xc8be40, 0xffffffffffffffff)
	runtime/proc.go:744 +0xdc fp=0x7fd6b72340 sp=0x7fd6b722f0 pc=0x4670c
runtime.schedinit()
	runtime/proc.go:637 +0x98 fp=0x7fd6b723a0 sp=0x7fd6b72340 pc=0x46228
runtime.rt0_go(0x7fd6b74e73, 0x7fd6b74e89, 0x7fd6b74e8c, 0x7fd6b74e8f, 0x7fd6b74e9f, 0x7fd6b74ea2, 0x0, 0x7fd6b74ebe, 0x7fd6b74edf, 0x7fd6b74ee9, ...)
	runtime/asm_arm64.s:82 +0xa8 fp=0x7fd6b723d0 sp=0x7fd6b723a0 pc=0x73ff8
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x769b2d, 0x16)
	runtime/panic.go:1117 +0x54 fp=0x7fecc28c80 sp=0x7fecc28c50 pc=0x42b24
runtime.sysMap(0x4000000000, 0x4000000, 0xcbc430)
	runtime/mem_linux.go:169 +0xbc fp=0x7fecc28cc0 sp=0x7fecc28c80 pc=0x2714c
runtime.(*mheap).sysAlloc(0xca33c0, 0x400000, 0x7fecc28dd8, 0x35b50)
	runtime/malloc.go:729 +0x188 fp=0x7fecc28d70 sp=0x7fecc28cc0 pc=0x1b528
runtime.(*mheap).grow(0xca33c0, 0x1, 0x0)
	runtime/mheap.go:1346 +0x80 fp=0x7fecc28de0 sp=0x7fecc28d70 pc=0x35d50
runtime.(*mheap).allocSpan(0xca33c0, 0x1, 0x2c00, 0x0)
	runtime/mheap.go:1173 +0x670 fp=0x7fecc28e70 sp=0x7fecc28de0 pc=0x35b80
runtime.(*mheap).alloc.func1()
	runtime/mheap.go:910 +0x54 fp=0x7fecc28ec0 sp=0x7fecc28e70 pc=0x6d924
runtime.(*mheap).alloc(0xca33c0, 0x1, 0x7fecc2012c, 0x264a4)
	runtime/mheap.go:904 +0x64 fp=0x7fecc28f10 sp=0x7fecc28ec0 pc=0x350f4
runtime.(*mcentral).grow(0xcb56f8, 0x0)
	runtime/mcentral.go:232 +0x74 fp=0x7fecc28f60 sp=0x7fecc28f10 pc=0x267a4
runtime.(*mcentral).cacheSpan(0xcb56f8, 0x0)
	runtime/mcentral.go:158 +0x344 fp=0x7fecc28fd0 sp=0x7fecc28f60 pc=0x26594
runtime.(*mcache).refill(0x7fa325c108, 0x2c)
	runtime/mcache.go:162 +0xc0 fp=0x7fecc29030 sp=0x7fecc28fd0 pc=0x258d0
runtime.(*mcache).nextFree(0x7fa325c108, 0xc8be2c, 0x7fecc290b8, 0x1cd10, 0x7fecc290e8)
	runtime/malloc.go:882 +0x8c fp=0x7fecc29080 sp=0x7fecc29030 pc=0x1bc3c
runtime.mallocgc(0x178, 0x75b700, 0x7fecc29101, 0x7fecc29178)
	runtime/malloc.go:1069 +0x75c fp=0x7fecc29130 sp=0x7fecc29080 pc=0x1c52c
runtime.newobject(0x75b700, 0x465e8)
	runtime/malloc.go:1177 +0x38 fp=0x7fecc29160 sp=0x7fecc29130 pc=0x1c748
runtime.malg(0x8000, 0x0)
	runtime/proc.go:3944 +0x2c fp=0x7fecc291b0 sp=0x7fecc29160 pc=0x4da7c
runtime.mpreinit(0xc8be40)
	runtime/os_linux.go:355 +0x28 fp=0x7fecc291d0 sp=0x7fecc291b0 pc=0x3f918
runtime.mcommoninit(0xc8be40, 0xffffffffffffffff)
	runtime/proc.go:744 +0xdc fp=0x7fecc29220 sp=0x7fecc291d0 pc=0x4670c
runtime.schedinit()
	runtime/proc.go:637 +0x98 fp=0x7fecc29280 sp=0x7fecc29220 pc=0x46228
runtime.rt0_go(0x7fecc2be73, 0x7fecc2be89, 0x7fecc2be8c, 0x7fecc2be8f, 0x7fecc2be9f, 0x7fecc2bea2, 0x0, 0x7fecc2bebe, 0x7fecc2bedf, 0x7fecc2bee9, ...)
	runtime/asm_arm64.s:82 +0xa8 fp=0x7fecc292b0 sp=0x7fecc29280 pc=0x73ff8

**Comment by juewuy** [comment]
这个问题，一般重启就好
