### ISSUE TITLE
最新1.7.1脚本，升级meta内核，下载成功但校验失败，手动指定也不行。

### ISSUE THREAD

**Issue by ajmz** [juewuy/ShellClash#330]
路由架构是mipsle，脚本和GeoIP都正常升级到了最新版，升级meta内核，下载成功但校验失败，手动指定选下面的选项6或7都不行。
 
 1 更 新 管 理 脚 本          1.7.1 > 1.7.1测 试 版
 2 切 换 clash核 心         v1.13.2 > v1.14.2
 3 更 新 GeoIP/CN-IP      20230225 > 20230225

----------------------------------------------

正 在 在 线 获 取 clash核 心 文 件 ……
################################################ 

100.0%核 心 文 件 下 载 成 功 但 校 验 失 败 ！ 请 尝 试 手 动 指 定 CPU版 本
-----------------------------------------------
仅 适 合 脚 本 无 法 正 确 识 别 核 心 或 核 心 无 法 正 常 运 行 时 使 用 ！
当 前 可 供 在 线 下 载 的 处 理 器 架 构 为 ：
1 armv5
2 armv7
3 armv8
4 386
5 amd64
6 mipsle-softfloat
7 mipsle-hardfloat
8 mips-softfloat
不 知 道 如 何 获 取 核 心 版 本 ？ 请 参 考 ： https://juewuy.github.io/bdaz

**Comment by juewuy** [comment]
@ajmz 可能是内存不足了，这个无解，建议用其他内核

**Comment by ajmz** [comment]
> @ajmz 可能是内存不足了，这个无解，建议用其他内核

谢谢，刚刚想再试一下，看到clash在45分钟前有自己重启，meta升级成功了。

**Comment by ajmz** [comment]
> > @ajmz 可能是内存不足了，这个无解，建议用其他内核
> 
> 谢谢，刚刚想再试一下，看到clash在45分钟前有自己重启，meta升级成功了。

再补充，meta 1.14.2 内存占用比之前版本大不少，重启路由后，又自动退回到1.13.2了，连clashshell脚本也退回到了1.7.0。

**Comment by juewuy** [comment]
@ajmz 这没办法，功能越多，消耗内存也就越大

**Comment by ajmz** [comment]
> @ajmz 这没办法，功能越多，消耗内存也就越大

我又测试更新到管理脚本1.7.1和Meta 1.14.2 ，显示成功。
但xray-agent生成的链接，VLESS现在默认vision，用2和4两个支持vless的在线生成服务器，都提示unsupported xtls flow type: xtls-rprx-vision ，手动复制链接到浏览器打开并查看数据是正常的。
换VLESS gRPC，生成配置文件成功，但启动clash服务后，翻不了墙。
切换安装源，退回到Meta 1.13.2，VLESS gRPC就正常了。

**Comment by juewuy** [comment]
@ajmz 内核问题请移步meta项目

**Comment by ajmz** [comment]
> @ajmz 内核问题请移步meta项目

不只是内核问题，管理脚本1.7.1，Meta 1.13.2，CPU负载经常100%，运行clash命令都出不来菜单。
管理脚本也退回到1.7.0，CPU负载10%左右了。
我再等等正式版吧，谢谢。

**Comment by ajmz** [comment]
v1.7.3b-公测版。

小闪存模式自定义目录，指定到了路由的SD卡上。
通过shellclash下载了clash.meta到目录中，在文件系统中能看到。
启动clash服务也显示成功，但上不了网了，内存占用明显比正常情况小很多。
又从GitHub上下载了clash.meta的原始文件，传到SD卡上，也不行。

**Comment by juewuy** [comment]
@ajmz 不一定是内核原因，先尝试切换其他内核
