### ISSUE TITLE
大佬，您的Telegram群多久解封啊？

### ISSUE THREAD

**Issue by ximiTech** [juewuy/ShellClash#331]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

大佬，您的Telegram群多久解封啊？进入时没注意就被ban了，要ban多久才能重新申请加入啊？

**Comment by juewuy** [comment]
@ximiTech 私聊管理解封
