### ISSUE TITLE
[Bug] 部分订阅url会报错ERRO[0000] yaml: invalid leading UTF-8 octet

### ISSUE THREAD

**Issue by wswx** [juewuy/ShellClash#332]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

导入url后，下载的配置文件不是utf-8的
<img width="523" alt="image" src="https://user-images.githubusercontent.com/35282496/222742298-cc3a6460-4b0e-48fc-b038-691f5bfae131.png">

**Comment by juewuy** [comment]
@wswx 请提供生成方式以及使用的规则

**Comment by wswx** [comment]
错误生成方式
1、执行clash
<img width="507" alt="image" src="https://user-images.githubusercontent.com/35282496/222871960-5274fa0f-c338-4d16-bf63-153818991d97.png">

2、选择6导入配置文件
<img width="674" alt="image" src="https://user-images.githubusercontent.com/35282496/222871969-b75ca1b4-a1dd-44ca-ac02-fdcc7468374c.png">
3、选择1在线生成Clash配置文件
<img width="749" alt="image" src="https://user-images.githubusercontent.com/35282496/222872070-bac9cb7c-49ed-4262-b9d1-f9e414f712b7.png">

4、输入订阅链接：https://service-jaz4ivuy-1313667892.gz.apigw.tencentcs.com/link/MVSsq0CjMj12OPku?clash=2
<img width="913" alt="image" src="https://user-images.githubusercontent.com/35282496/222872091-6d616313-65e5-403d-b1f4-ef39edbbb590.png">

5、选择1开始生成配置文件，就产生错误
<img width="1319" alt="image" src="https://user-images.githubusercontent.com/35282496/222872135-f3f2dfee-771f-4f0d-bde8-2c6be426dedf.png">

我认为是下载生成的文件编码不对，检查临时文件编码如下：unknown-8bit
<img width="645" alt="image" src="https://user-images.githubusercontent.com/35282496/222872214-7072640d-8d15-49b0-a92c-696554341db4.png">
查看配置文件编码为：utf-8
<img width="593" alt="image" src="https://user-images.githubusercontent.com/35282496/222872267-db8a2cad-afec-4afc-814a-17b53f403b09.png">

**Comment by juewuy** [comment]
这种应该就是网络问题导致下载的配置文件出错
建议尝试在6-1里切换一下后端服务器
另外订阅链接已经泄露，务必重置

**Comment by wswx** [comment]
几个后端服务器都试了一遍，还是不行，我直接把start.sh 里面下载那写死了😂
链接已重置
