### ISSUE TITLE
[Feature] upgrade clash pre version

### ISSUE THREAD

**Issue by douglarek** [juewuy/ShellClash#333]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

https://github.com/Dreamacro/clash/releases/tag/premium. latest version is 2023-03-04.

**Comment by juewuy** [comment]
由于新版premium内核移除了redirhost支持，故暂时不会考虑升级

**Comment by douglarek** [comment]
> 由于新版premium内核移除了redirhost支持，故暂时不会考虑升级

多谢回复，能否提供跟简单直接的方式更新核心的版本。

**Comment by juewuy** [comment]
@douglarek 可以使用本地安装
https://juewuy.github.io/bdaz
