### ISSUE TITLE
[Feature] 定时任务频率新增每X小时

### ISSUE THREAD

**Issue by Toad-stool** [juewuy/ShellClash#334]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

目前定时任务的最小时间间隔为每天X时X分一次，新建第二条Y时Y分任务会覆盖上一条任务，无法实现一天内多次定时任务的功能，希望自动任务增加每X小时一次，例如每1小时热更新一次订阅链接，这对于订阅链接更新很实用。

**Comment by GuangDai** [comment]
直接crontab -e即可
