### ISSUE TITLE
VPS 上使用 有UI界面，但是没有节点

### ISSUE THREAD

**Issue by geekhuashan** [juewuy/ShellClash#335]
本人小白，一顿操作之后，连接VPS的公网地址
IP:9090/ui 会有显示 但是里面没有节点信息 是哪里设置的不对嘛

![Screenshot_20230309-111915.png](https://user-images.githubusercontent.com/47098938/223907901-e132cdb7-3869-445b-b2b3-60c3ff4f3848.png)

![Screenshot_20230309-111951.png](https://user-images.githubusercontent.com/47098938/223907993-72bcceed-dcc5-49ef-b005-848d3ec6a64a.png)

过了一会跳出来这个 这里该填什么呢

**Comment by juewuy** [comment]
@geekhuashan 面板设置里修改一下host和端口

**Comment by geekhuashan** [comment]
> @geekhuashan 面板设置里修改一下host和端口

是在第二张图片里的地方填吗，应该填什么啊 

http://172.17.16.227:9090 
secret 那里填 geekhuashan 嘛
