### ISSUE TITLE
[Bug] openwrt22.03 iptables v1.8.7 (legacy): Couldn't load match `owner':No such file or directory

### ISSUE THREAD

**Issue by zyystudio** [juewuy/ShellClash#336]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

升级了22.03后使用公开版1.7.1 测试版1.7.1都有启动clash后这个问题

iptables-legacy -t nat -A clash_out -m owner --gid-owner 7890 -j RETURN 应该是这条命令抛出的
iptables v1.8.7 (legacy): Couldn't load match `owner':No such file or directory

**Comment by juewuy** [comment]
@zyystudio 说明不支持本机代理iptables增强模式

**Comment by zyystudio** [comment]
openwrt旧版本支持。这个样子怎么搞？openwrt缺包还是咱们可以绕过去？谢谢这么快的回复。

**Comment by juewuy** [comment]
@zyystudio 不是啊

**Comment by juewuy** [comment]
@zyystudio 你要是用的nftables，就使用本机代理nftables增强模式

**Comment by zyystudio** [comment]
说句实话我都不知道有没有安装nftables哦。我搜了下openclash也有类似问题。有个建议的是安装这些：
-dnsmasq -firewall4 -nftables -kmod-nft-offload -odhcpd-ipv6only \
firewall iptables-legacy kmod-inet-diag coreutils-nohup bash dnsmasq-full curl ca-certificates ipset ip-full iptables-mod-tproxy iptables-mod-extra libcap libcap-bin ruby ruby-yaml kmod-tun

**Comment by archichen** [comment]
@zyystudio Hi, 我也遇到了这个问题，请问你解决了吗？
