### ISSUE TITLE
[Feature] 关于fake-ip的小问题

### ISSUE THREAD

**Issue by nil-ca** [juewuy/ShellClash#338]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

固件版本 OpenWrt 22.03.3
硬件 R2S 
已安装 iptables-nft

看了一下新版的clash都在推荐fake-ip，所以提前体验了下，现在用着fake-ip模式因为所有的流量都要经过clash，如果开着2-4只代理常用端口的话，不在常用端口里面的端口流量是会变成无网状态，前两天用着手机APP所得税和电信才发现的，还有些手机APP用的端口也是跨度比较大，没办法一个个添加进常用端口，需要自己手动关闭2-4这个功能。

```
请使用 http://xxx.xxx.xxx.xxx:9999/ui 管理内置规则
cat: read error: Is a directory
cat: can't open '8361/status': No such file or directory
```
上面的提示每次重启后不知到后面这两个cat是哪里的sh引起的。

问一下作者，不知道fake-ip能不能像redir模式一样可以让国内的ip不经过clash，好像这方面是靠iptables或者nftables控制的吧。

**Comment by juewuy** [comment]
@nil-ca 那就重启设备即可
