### ISSUE TITLE
[Bug] 公网无法连接混合端口

### ISSUE THREAD

**Issue by 2715481617** [juewuy/ShellClash#339]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

在腾讯云centos8服务器搭建，系统是centos8 内网下可以正常连接代理，公网无法连接混合端口，只能在Dashboard下自定义Socks5 端口，使用自定义的端口连接，混合端口无法连接
公网ip:混合端口不能用 Socks5端口就可以用

**Comment by 2715481617** [comment]
自定义host已经设置成了公网ip

**Comment by 2715481617** [comment]
公网ip:混合端口不能用 Socks5端口就可以用

> ### Verify steps
> * [x]   我已经在 [Issue Tracker](%E2%80%A6%E2%80%A6/) 中找过我要提出的问题 I have searched on the [issue tracker](%E2%80%A6%E2%80%A6/) for a related issue.
> * [x]   我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists.
> * [x]   我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题
> 
> ### Description
> 在腾讯云轻量型服务器搭建，系统是centos8 内网下可以正常连接代理，公网无法连接混合端口，只能在Dashboard下自定义Socks5 端口，使用自定义的端口连接，混合端口无法连接
公网ip:混合端口不能用 Socks5端口就可以用

**Comment by juewuy** [comment]
@2715481617 默认7890会自动拒绝入站

**Comment by 2715481617** [comment]
> @2715481617 默认7890会自动拒绝入站

那是要改端口还是怎么做

**Comment by juewuy** [comment]
@2715481617 启用公网访问选项里有提示

**Comment by 2715481617** [comment]
> @2715481617 启用公网访问选项里有提示

已经打开公网访问了

**Comment by 2715481617** [comment]
![image](https://user-images.githubusercontent.com/73612172/224526574-35467a95-8dcf-4f97-9f06-88834be4e68d.png)

**Comment by juewuy** [comment]
@2715481617 那就重新进去看

**Comment by 2715481617** [comment]
> @2715481617 那就重新进去看

我的意思是已经在开启公网访问的条件下 公网的混合端口无法连接的

**Comment by 2715481617** [comment]
> @2715481617 那就重新进去看

只更改默认的端口不设置用户名和密码可以会自动拒绝吗，

**Comment by juewuy** [comment]
@2715481617 会
