### ISSUE TITLE
[Bug] 设备已有根证书，仍然提示安装

### ISSUE THREAD

**Issue by heganyuliang** [juewuy/ShellClash#340]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

尝试开启加密 DNS 时，同时提示“缺少本地根证书”和“检测到系统已经安装根证书”，确认安装后没有变化，手动上传到 /etc/ssl/certs 目录也一样

设备是 360T7，版本 1.7.1 公测版

![](https://s2.loli.net/2023/03/12/cZEIvoHxdTjkeP3.png)

**Comment by abcfy2** [comment]
我也遇到了这个问题，解决方案是不去管它，直接修改`mark`文件中的`dns_nameserver=`和`dns_fallback=`即可，使用自己喜欢的DoH或DoT

**Comment by juewuy** [comment]
更新1.7.3即可
