### ISSUE TITLE
[Bug] Padavan小闪存自启动问题

### ISSUE THREAD

**Issue by qzydustin** [juewuy/ShellClash#342]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

启动脚本（/etc/storage/clash/start.sh init #ShellClash初始化脚本）
应该放在Run After WAN Up/Down Events中，而不是Run After Router Started中

因为小闪存模式需要联网下载内容，放在Run After Router Started中会因为没有网而启动失败

放在Run After WAN Up/Down Events中正常启动

**Comment by juewuy** [comment]
@qzydustin 可以自行设置启动延迟

**Comment by qzydustin** [comment]
> @qzydustin 可以自行设置启动延迟

日志中显示，shell中的延迟启动不会延迟下载核心等文件，只是延迟“启动”
