### ISSUE TITLE
ntpd错误

### ISSUE THREAD

**Issue by suuzen** [juewuy/ShellClash#344]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

18 Mar 10:00:54 ntpd[2185666]: ntpd 4.2.8p12@1.3728-o (1): Starting
18 Mar 10:00:54 ntpd[2185666]: Command line: ntpd -n -q -p 203.107.6.88
18 Mar 10:00:54 ntpd[2185666]: proto: precision = 0.391 usec (-21)
18 Mar 10:00:54 ntpd[2185666]: pid file 203.107.6.88: Permission denied
18 Mar 10:00:54 ntpd[2185666]: bind(16) AF_INET 127.0.0.1#123 flags 0x5 failed: Address already in use
18 Mar 10:00:54 ntpd[2185666]: unable to create socket on lo (0) for 127.0.0.1#123

**Comment by juewuy** [comment]
@suuzen 什么设备

**Comment by suuzen** [comment]
腾讯云服务器 ，ubuntu20.04

**Comment by juewuy** [comment]
@suuzen 可以无视，或者更新最新内测版

**Comment by suuzen** [comment]
> @suuzen 可以无视，或者更新最新内测版

最新内测版是1.7.3吗，请问在哪里获取，我的版本是1.7.1，安装源没办法使用内侧版

**Comment by juewuy** [comment]
公测版已更新
