### ISSUE TITLE
[Bug] 使用ipv6地址访问内置DNS防污染会失效

### ISSUE THREAD

**Issue by abcfy2** [juewuy/ShellClash#345]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

shellclash会启用clash的内置DNS，但是发现使用ipv6地址访问的时候会造成防污染失效，原因不明。

重现如下，我在路由器上安装shellclash，开启了内置DNS(看配置默认监听1053端口)，并且开启域名探嗅，使用ipv4地址 127.0.0.1解析域名是OK的:

```sh
# nslookup www.okx.com 127.0.0.1:1053
Server:    127.0.0.1
Address 1: 127.0.0.1 localhost.localdomain

Name:      www.okx.com
Address 1: 2606:4700::6812:297
Address 2: 2606:4700::6812:397
Address 3: 104.18.2.151
Address 4: 104.18.3.151
```

可以看到上述解析符合期望。然而我用ipv6地址访问这个DNS服务器时，得到的却是被污染的域名:

```sh
# nslookup www.okx.com '[::1]:1053'
Server:    ::1
Address 1: ::1 ip6-localhost

Name:      www.okx.com
Address 1: 169.254.0.2
```

我的DNS配置如下:

```txt
-----------------------------------------------
当前基础DNS：https://223.5.5.5/dns-query, https://doh.pub/dns-query, tls://dns.rubyfish.cn:853
FallbackDNS：https://1.0.0.1/dns-query, tls://1.0.0.1:853
多个DNS地址请用“|”或者“, ”分隔输入
必须拥有本地根证书文件才能使用dot/doh类型的加密dns
-----------------------------------------------
 1 修改基础DNS
 2 修改Fallback_DNS
 3 重置DNS配置
 4 一键配置加密DNS
 5 hosts优化：  	已开启	————调用本机hosts并劫持NTP服务
 6 Dnsmasq转发：	未开启	————不推荐使用
 7 禁用DNS劫持：	未禁用	————取消劫持局域网53端口
 0 返回上级菜单
-----------------------------------------------
请输入对应数字 >
```

是还需要有什么别的配置吗？

**Comment by juewuy** [comment]
@abcfy2 什么设备？启用ipv6代理后能正常代理ipv6流量吗？

**Comment by abcfy2** [comment]
> @abcfy2 什么设备？启用ipv6代理后能正常代理ipv6流量吗？

华硕AX5400路由器，启用ipv6是正常的。我发现我的路由器会通过DHCP给客户端同时分配ipv4和ipv6地址，DNS也是有ipv4地址(192.168.50.1)和ipv6地址(2409:8a70:96d:5670::1)两个，我发现客户端如果走192.168.50.1解析就没问题，走2409:8a70:96d:5670::1解析就会被污染，于是我在路由器上测试了一下，发现果然如此，使用127.0.0.1解析就没问题，但是改用 [::1] 就被污染了

**Comment by juewuy** [comment]
@abcfy2 中继或者旁路由模式？正常来说ipv6dns解析是会劫持的

**Comment by abcfy2** [comment]
我在想问题会不会出在DNS的配置上，我看shellclash生成的DNS监听地址是 0.0.0.0:1053，我看了下路由器的UDP端口监听，应该是同时监听了ipv4和ipv6地址:

```sh
# netstat -nlup | grep 1053
udp        0      0 :::1053                 :::*                                28202/clash
```

走ipv4地址没问题，走ipv6地址感觉防污染DNS配置没起作用

**Comment by abcfy2** [comment]
> @abcfy2 中继或者旁路由模式？正常来说ipv6dns解析是会劫持的

不是中继，就一个单独的路由器，应该是路由模式

**Comment by juewuy** [comment]
@abcfy2 面板日志开debug看一下DNS解析到底进没进内核

**Comment by abcfy2** [comment]
> @abcfy2 面板日志开debug看一下DNS解析到底进没进内核

好像根本没进入内核。我用127.0.0.1:1053解析，发现日志中有如下的日志:
![image](https://user-images.githubusercontent.com/5327677/226111852-989dc964-2e92-4a01-ab97-38bfba20f0ac.png)

但是我改用`[::1]:1053`解析，根本没有任何DNS日志输出。疑似走了ipv6地址根本没进入内核

**Comment by juewuy** [comment]
@abcfy2 这种可能是设备ip6tables有缺失导致的，没什么好的解决办法

**Comment by abcfy2** [comment]
好吧，多谢解答了。我看了下我的设备的信息:

```sh
# uname -a
Linux TUF-AX5400-0368 4.1.52 #1 SMP PREEMPT Fri Apr 29 22:00:21 CST 2022 armv7l Merlin_Koolshare_RT-AX95Q

# ip6tables --version
ip6tables v1.4.12.2
```

Linux 4.1.52 内核版本，iptables 1.4.12.2版本，启动的时候也有个错误:

```
ip6tables v1.4.12.2: unknown option "--to"
Try `ip6tables -h' or 'ip6tables --help' for more information.
clash服务已启动！
请使用 http://192.168.1.2:9999/ui 管理内置规则
```

看来可能是iptables版本太低不支持这种转发

**Comment by abcfy2** [comment]
多谢解答，这个问题非shellclash本身，so closed.

**Comment by juewuy** [comment]
@abcfy2 正常应该是会reject掉，不明白为什么你的设备没有触发，你可以参考start.sh里iptables及dns相关

**Comment by abcfy2** [comment]
> @abcfy2 正常应该是会reject掉，不明白为什么你的设备没有触发，你可以参考start.sh里iptables及dns相关

什么会被reject掉？需要dump iptables的规则链排查吗？

**Comment by juewuy** [comment]
@abcfy2 lsmod | grep 'xt_nat' 执行以下看有输出吗

**Comment by abcfy2** [comment]
> lsmod | grep 'xt_nat'

空的，没有输出

**Comment by juewuy** [comment]
@abcfy2 OK，下版本修复
