### ISSUE TITLE
[Bug] 核心下载失败，几个源都试了，有没有本地下载远程安装的方法

### ISSUE THREAD

**Issue by guzy0324** [juewuy/ShellClash#346]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

核心下载失败，几个源都试了，有没有本地下载远程安装的方法

**Comment by guzy0324** [comment]
应该更新一下文档https://juewuy.github.io/bdaz/，核心名字应为clash

**Comment by juewuy** [comment]
@guzy0324 认真看文档

**Comment by guzy0324** [comment]
我用本地配置文件会报错`invalid mode: redir-host`

**Comment by juewuy** [comment]
@guzy0324 请用本项目提供的内核文件
