### ISSUE TITLE
想要增加一个预处理的配置文件[Feature] 

### ISSUE THREAD

**Issue by WeiKKJ** [juewuy/ShellClash#347]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

shellclash没有看到有能够配置预处理文件的地方，想要个能够和win版clash一样的能够在获取订阅的时候自动追加自己配置信息的功能，否则每次更新订阅还得手工添加配置信息。

**Comment by juewuy** [comment]
@WeiKKJ 7-7

**Comment by WeiKKJ** [comment]
厉害了，大佬，完美解决了我的问题。

> 

可以按照大佬的回复处理下就行了
![image](https://user-images.githubusercontent.com/50602973/228747424-df8a9dd5-1ef6-442b-ba48-dd57d4e6d520.png)
![image](https://user-images.githubusercontent.com/50602973/228747521-6b0f6fef-9ad9-414f-9061-3d839bab86a6.png)
