### ISSUE TITLE
[Feature] 如何查看崩溃日志？

### ISSUE THREAD

**Issue by abcfy2** [juewuy/ShellClash#349]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

最近运行的时候，总是运行一段时间clash内核就会莫名其妙的崩溃，表现形式是clash交互式菜单显示clash未运行，原因不明。

因此我想看看clash内核的日志，最后崩溃前有什么错误信息导致的，但是似乎shellclash并未输出这个日志，有没有办法查询崩溃日志？

**Comment by juewuy** [comment]
@abcfy2 正常来说崩溃了是会自动拉起来的

**Comment by juewuy** [comment]
@abcfy2 日志这个确实没办法看

**Comment by abcfy2** [comment]
我看start.sh最终会使用命令 `/jffs/clash/clash -d /jffs/clash`运行程序，是否可以考虑改成 `/jffs/clash/clash -d /jffs/clash &> /tmp/clash.log`类似的，用重定向覆盖，每次重启的时候会清空日志，只保留最后一次运行的时候终端输出。

我这边确实没有自动拉起来，每次都是发现页面已经无法访问的时候上路由器看一眼，发现clash进程已经消失了，只能手工重启服务

**Comment by juewuy** [comment]
@abcfy2 数据量太大了，你可以通过网页面板进行监控

**Comment by abcfy2** [comment]
页面监控的内容无法持久化，页面一关啥都没了，而且我怀疑崩溃日志页面是否能监控到都是问题，崩溃前的日志大概率会输出到终端上。

我现在我本地脚本改一下看看能否找到clash崩溃原因吧

**Comment by abcfy2** [comment]
奇怪，早上那会频繁崩溃，大概1小时崩溃一次，这会不崩溃了，我先关闭这个issue吧。

**Comment by ling7334** [comment]
我也一直崩溃，怎么优化配置减小内存消耗啊？
