### ISSUE TITLE
[Bug]反馈域名嗅探的问题

### ISSUE THREAD

**Issue by CaoKang-David** [juewuy/ShellClash#350]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

1，域名嗅探里面需要加入skip-domain字段，并维护常见清单。比如，我就遇到了米家设备无法联网的情况，必须要加入skip-domain:'Mijia Cloud'才可以。
2，感谢作者开发的脚本，让我们可以在不刷各种改版固件的前提下就可以出国。

**Comment by win9zhanhuaxi0ng** [comment]
果然有人遇到了跟我一样的问题。我还以为是路由器问题，换了红米AX6000，1.7.0f版本，Tproxy fake-ip模式，启用节点绕过，此时配置下一旦打开域名嗅探，就无法连接米家设备

**Comment by win9zhanhuaxi0ng** [comment]
@CaoKang-David 请问“域名嗅探里面需要加入skip-domain字段”这个步骤该如何操作？求指点

**Comment by juewuy** [comment]
主要pre核 和meta核对域名嗅探的写法并不一致，所以暂时不会加入
米家设备所属网段目前尝试通过iptables屏蔽

**Comment by CaoKang-David** [comment]
> @CaoKang-David 请问“域名嗅探里面需要加入skip-domain字段”这个步骤该如何操作？求指点

可参考此wiki：https://clash-meta.wiki/function/dns/sniffer#pei-zhi-shi-li

**Comment by CaoKang-David** [comment]
> 主要pre核 和meta核对域名嗅探的写法并不一致，所以暂时不会加入 米家设备所属网段目前尝试通过iptables屏蔽

个人感觉，在脚本里判断P核还是M核再写入字段，要比采用iptables。
无论如何，感谢您的无私奉献！
