### ISSUE TITLE
[Bug] 尝试使用一元机场的订阅链接在shell clash中导入配置文件失败

### ISSUE THREAD

**Issue by NyoronX10A** [juewuy/ShellClash#351]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

无法导入一元机场提供的订阅链接，导入时报错：
curl: (28) Failed to connect to api.dler.io port 443 after 2354 ms: Operation timed out                                                                                                   
sh: out of range
第二到第四次重试时显示：
curl: (3) Error
curl: (3) Error

一元机场：
https://xn--4gq62f52gdss.com/

**Comment by wjp919497158** [comment]
检查下github能打开不，我看他在线配置那用了GitHub上存的规则，我这里移动github打不开要改路由器hosts

**Comment by MotorBottle** [comment]
选“在线生成Clash配置文件”，不要选第二个

**Comment by juewuy** [comment]
公测版已修复
