### ISSUE TITLE
[Bug] ERRO[0000] yaml: line 22: did not find expected node content  configuration file /data/clash/config.yaml test failed Killed

### ISSUE THREAD

**Issue by AbianTang** [juewuy/ShellClash#354]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

已成功获取配置文件！
是否启动clash服务以使配置文件生效？(1/0) > 1
-----------------------------------------------
未找到clash核心，正在下载！
################################################################################################################################################################################################################################################ 100.0%
Clash服务启动失败！请查看报错信息！
ERRO[0000] yaml: line 22: did not find expected node content 
configuration file /data/clash/config.yaml test failed
Killed

**Comment by juewuy** [comment]
@AbianTang 配置文件错误
