### ISSUE TITLE
[Feature] 日志推送能不能带路由器(环境)名称

### ISSUE THREAD

**Issue by rebron1900** [juewuy/ShellClash#355]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

在不同的网络环境里装了shellclash，都开启推送的话会分不清是那个网络环境里的shellclash的日志。

**Comment by juewuy** [comment]
可以尝试配置不同的推送通道或者推送账号

**Comment by juewuy** [comment]
https://github.com/juewuy/ShellClash/commit/ca2da3f8fd08f551dd02fe174b7c82332f2a9b90
