### ISSUE TITLE
[Bug] 测试通过但是无法连接youtube

### ISSUE THREAD

**Issue by Zerovoice** [juewuy/ShellClash#356]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

路由器 miwifi mini，固件OpenWrt 22.03.3 r20028-43d71ad93e / LuCI openwrt-22.03 branch git-22.361.69894-438c598
----------------------------------------------
 1 查看Clash运行时的报错信息(会停止clash服务)
 2 查看系统DNS端口(:53)占用 
 3 测试ssl加密(aes-128-gcm)跑分
 4 查看clash相关路由规则
 5 查看config.yaml前30行
 6 测试代理服务器连通性（google.tw)
-----------------------------------------------
 0 返回上级目录！
请输入对应数字 > 1
-----------------------------------------------
INFO[0001] Start initial compatible provider 🎥 NETFLIX  
INFO[0001] Start initial compatible provider ⛔️ 广告拦截    
INFO[0001] Start initial compatible provider 🔰 节点选择     
INFO[0001] Start initial compatible provider 🛑 全球拦截     
INFO[0001] Start initial compatible provider 🌍 国外媒体     
INFO[0001] Start initial compatible provider Ⓜ️ 微软服务    
INFO[0001] Start initial compatible provider 🚫 运营劫持     
INFO[0001] Start initial compatible provider 🐟 漏网之鱼     
INFO[0001] Start initial compatible provider 🌏 国内媒体     
INFO[0001] Start initial compatible provider 🎯 全球直连     
INFO[0001] Start initial compatible provider ♻️ 自动选择    
INFO[0001] Start initial compatible provider 🍎 苹果服务     
INFO[0001] Start initial compatible provider 📲 电报信息     
configuration file /etc/clash/config.yaml test is successful
测试通过！
------------------------------------------------------
但是无法联通youtube，google等网站
root@OpenWrt:/# ping youtube.com
PING youtube.com (157.240.15.8): 56 data bytes
^C
--- youtube.com ping statistics ---
4 packets transmitted, 0 packets received, 100% packet loss
root@OpenWrt:/# 

求大神帮忙看看，可以回复我qq（61348867）或者qq邮箱（61348867@qq.com） 谢谢

**Comment by Zerovoice** [comment]
补充，连接国内网站ok

**Comment by juewuy** [comment]
@Zerovoice 不支持ping，另外请先参考常见问题

**Comment by sqiangcao99** [comment]
> 

有点奇怪，但是我尝试了下Windows版本的clash,tun模式能Ping通的。
