### ISSUE TITLE
[Feature] 能否将在线配置规则模板中的日韩节点分开筛选为日本节点和韩国节点？

### ISSUE THREAD

**Issue by soratanmer** [juewuy/ShellClash#357]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

个人习惯在节点选择中使用日本节点，但是在线配置规则模板中大部分规则模板都只有日韩节点。
虽说可以使用节点过滤把韩国节点都过滤掉，但是偶尔会有使用韩国节点的需求。

**Comment by juewuy** [comment]
会考虑但不是现在
你可以尝试直接使用在线订阅转换并搭配6-2使用

**Comment by juewuy** [comment]
https://github.com/juewuy/ShellClash/commit/28b6686a7487e1bdbccf8d9d0d449e2d8b4dde35
