### ISSUE TITLE
[Bug] DDNS无法连接，无法更新脚本

### ISSUE THREAD

**Issue by CaoKang-David** [juewuy/ShellClash#358]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

1，我的使用环境：华硕Ax86u pro, 梅林官方固件，388.2 beta1。
2，我的配置：

   -  在/jffs/scripts里面加入了一个自定义脚本：dnsmasq.postconf，让其开机添加port=0代码，以便禁用dnsmasq的DNS解析服务。
  -  使用clash premium内核，clash关闭dns劫持，监听53端口，以接管系统DNS服务。在遇到以下问题期间，我还尝试过在脚本下载clash pre内核以后各种环境设置好以后，使用官方最新的premium内核替换脚本下载的内核，但问题依旧。
  - clash启用Tproxy，fake ip模式，IPv6只开启内核和解析，没有开启ipv6透明代理 ；关闭嗅探。

3，我遇到的问题：

-  进入9 更新菜单，无法更新，切换源也无法更新，开启本机代理，也不行，提示没有网络连接；
-  根据上述现象，似乎开启本机代理无效。最新版的本机代理菜单只有一个选项“环境变量”的方式开启本机代理，我记得以前旧版里是有什么什么增强方式开启的。
- 路由器通过IPV6公网地址开启DDNS，始终无法连接，提示“无法连接请重试”之类的错误。卸载clash，恢复路由器dnsmasq之后就正常；
- 网内还有一台NAS，也通过IPV6公网DDNS，倒是能正常访问，但总会卡个两三秒，这段时间内在浏览器上什么操作都做不了。卸载clash，恢复路由器dnsmasq之后，也会恢复正常。
-  clash的域名解析cache似乎有问题，经常很长时间了，cache里面的域名还是旧的，即便新的已经在DNS服务器上更新过了。经常会出现我用手机自带流量比局域网先刷出来新地址的尴尬局面。

**Comment by CaoKang-David** [comment]
除了开启本机代理无效以外，其他问题已经解决。

**Comment by juewuy** [comment]
没有增强模式就是设备缺少依赖
