### ISSUE TITLE
[Bug]定时重启并不生效

### ISSUE THREAD

**Issue by zhajingwen** [juewuy/ShellClash#359]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

设置凌晨三点重启，我是在前一天下午设置的，但是今天早上看运行时间不对，根据运行时间推算根本就没有重启嘛
![image](https://user-images.githubusercontent.com/33952447/228989867-80046c70-4806-491e-8105-19bfaa4922b1.png)
这是成功重启后的样子，运行时间一定会更新
![image](https://user-images.githubusercontent.com/33952447/228989921-ef323d60-8948-44be-8883-f8d983bf935a.png)

**Comment by juewuy** [comment]
@zhajingwen 定时任务依赖设备本身的crontab服务，有可能是crontab被杀进程或者其他相关原因导致

**Comment by zhajingwen** [comment]
> @zhajingwen 定时任务依赖设备本身的crontab服务，有可能是crontab被杀进程或者其他相关原因导致

好的我测试下

**Comment by zhajingwen** [comment]
多种测试发现是系统的crontab并没有运行；通过下面的两行命令可以解决该问题
1、在 OpenWrt 中，可以使用以下命令启动 crontab 服务：
`/etc/init.d/cron start`
2、这个命令会启动 crontab 服务，并使其在后台运行。如果需要设置 crontab 开机自启动，可以使用以下命令：
`/etc/init.d/cron enable`
