### ISSUE TITLE
[Feature] clash.meta v1.14.3 发布了希望更新一下

### ISSUE THREAD

**Issue by lvii** [juewuy/ShellClash#360]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

Hi

clash.meta 最近更新了：https://github.com/MetaCubeX/Clash.Meta/releases/tag/v1.14.3

希望能更新一下运行文件。

感谢！

**Comment by juewuy** [comment]
可以参考本地安装教程，手动先行更新
本项目不会过度追新
