### ISSUE TITLE
Mi Router BE10000 could not install on /data 

### ISSUE THREAD

**Issue by chenlei630** [juewuy/ShellClash#361]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

After opening SSH on BE10000, could not install shellclash with one key command to the router, because of the space only 188k.

**Comment by juewuy** [comment]
@chenlei630 You can try using '自定义目录' for installation. If you are not sure about the directory space, try using the 'df -h' command.

**Comment by chenlei630** [comment]
> @chenlei630 You can try using '自定义目录' for installation. If you are not sure about the directory space, try using the 'df -h' command.

there are no such selection for choosing, only 
检测到当前设备为小米官方系统，请选择安装位置
 1 安装到/data目录(推荐，支持软固化功能)
 2 安装到USB设备(支持软固化功能)
 0 退出安装
Would you tell me how can I use  '自定义目录' for installation?

**Comment by juewuy** [comment]
@chenlei630 cac9d85: v1.7.4

**Comment by chenlei630** [comment]
> @chenlei630 [cac9d85](https://github.com/juewuy/ShellClash/commit/cac9d8534c76621e472f0c765428f62db6f0677d): v1.7.4

Thanks，but how can I choose the version 1.7.4 in the command? 
export url='https://fastly.jsdelivr.net/gh/juewuy/ShellClash@master' 
&& sh -c "$(curl -kfsSl $url/install.sh)" && source /etc/profile &> /dev/null
when I use this command, it shows only v1.7.0 and v1.7.3b

**Comment by juewuy** [comment]
@chenlei630 export url='http://t.jwsc.eu.org' && sh -c "$(curl -kfsSl $url/install.sh)" && source /etc/profile &>
/dev/null

**Comment by chenlei630** [comment]
> @chenlei630 export url='http://t.jwsc.eu.org' && sh -c "$(curl -kfsSl $url/install.sh)" && source /etc/profile &>
> /dev/null
Sorry it shows:
curl: (56) Recv failure: Connection reset by peer

**Comment by juewuy** [comment]
Use local_install type like: https://juewuy.github.io/bdaz/
