### ISSUE TITLE
间歇性无法打开页面 ERR_CONNECTION_CLOSED

### ISSUE THREAD

**Issue by zhajingwen** [juewuy/ShellClash#362]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

报错信息
ERR_CONNECTION_CLOSED
很频繁，时好时坏
![image](https://user-images.githubusercontent.com/33952447/229685218-b5f5003c-a866-4215-9003-c259eee80540.png)

**Comment by juewuy** [comment]
@zhajingwen 请先参考常见问题

**Comment by zhajingwen** [comment]
OK

> @zhajingwen 请先参考常见问题

OK

**Comment by zhajingwen** [comment]
> @zhajingwen 请先参考常见问题

似乎没有找到类似的问题

**Comment by juewuy** [comment]
@zhajingwen 仅凭你反馈的信息我无法做任何工作

**Comment by zhajingwen** [comment]
> @zhajingwen 仅凭你反馈的信息我无法做任何工作

谢谢我再研究研究

**Comment by kylesean** [comment]
@zhajingwen 遇到同样问题，不知道你什么设备，我是小米 AX6 路由器用 windows 系统解锁 ssh 安装的，稳定版配置，根据常用问题列表，改了 fake-ip 和 clash.Meta 内核，运行模式四种都尝试了，问题依旧。手机和其他电脑设备浏览器访问正常。另外，clash for windows 客户端主动开启，恢复原来的使用习惯，就正常了。

**Comment by kylesean** [comment]
@zhajingwen 
![Uploading image.png…]()

**Comment by juewuy** [comment]
这不是之前chromium内核和小米路由冲突导致的问题吗？
升级固件解决
