### ISSUE TITLE
路由器重启以后 Clash无法启动[Bug] 

### ISSUE THREAD

**Issue by chenlei630** [juewuy/ShellClash#366]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

小米万兆路由器 重新启动以后 Clash无法开启
root@XiaoQiang:/# clash
-ash: clash: not found
root@XiaoQiang:/# /userdisk/clash/clash start
FATA[0000] Initial configuration directory error: can't create config directory /root/.config/clash: mkdir /root/.config: read-only file system 
root@XiaoQiang:/# /userdisk/clash/clash -s start
flag provided but not defined: -s

应该如何正确开启clash？

**Comment by juewuy** [comment]
@chenlei630 安装公测版
