### ISSUE TITLE
[Feature] 

### ISSUE THREAD

**Issue by koloum** [juewuy/ShellClash#367]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

小米4A安装openwrt后安装shellclash，但CPU容易跑到60~90%，有没解决办法

**Comment by juewuy** [comment]
@koloum 换个性能更强的设备，或者尝试使用绕过cnIP

**Comment by koloum** [comment]
thanks，我试下
