### ISSUE TITLE
[Bug]PVE lxc模板无法使用tun模式

### ISSUE THREAD

**Issue by wenju88** [juewuy/ShellClash#368]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

PVE内核5.15，5.19，6.1和6.2分别测试过，LXC分别装过Ubuntu22.04和debian10.11,测试，tun模式无法使用，开启后没有网络，不知何故？请问作者能否找个环境测试一下，修复一下，谢谢

**Comment by juewuy** [comment]
https://cloud.tencent.com/developer/article/1925127
参考这个？

**Comment by juewuy** [comment]
https://github.com/juewuy/ShellClash/commit/3c7bcf901b5751c7ebc8346aa6160966a3d8a0e1
