### ISSUE TITLE
[Feature] 重启clash或者重启路由器后，yacd面板中选择好的规则无法保存

### ISSUE THREAD

**Issue by CasenChan** [juewuy/ShellClash#369]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [x]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

重启clash或者重启路由器后，yacd面板中选择好的规则无法保存

**Comment by juewuy** [comment]
@CasenChan 启动后，ssh界面是否存在报错？

**Comment by CasenChan** [comment]
> 

没有存在报错

**Comment by juewuy** [comment]
@CasenChan 尝试使用正式版

**Comment by CasenChan** [comment]
> @CasenChan 尝试使用正式版

好的，我试试
