### ISSUE TITLE
[Bug] 混合模式下，dns 查询结果错误，切回 redir 模式恢复正常

### ISSUE THREAD

**Issue by geekyouth** [juewuy/ShellClash#370]
### Description

混合模式下，dns 查询结果错误，切回 redir 模式恢复正常，redir 模式下，github 图片和原始 raw 文件有时无法查看，切到 混合模式，可以查看。
但是新的问题是，dns 查询一个 ddns 服务之后域名的IP，查询结果是错误的。比如我在家里的小米路由器1绑定了花生壳ddns服务，我在外地通过 nslookup 查询我的花生壳域名，当我在外地公寓的路由器2使用了混合模式，就无法获得最新的域名映射IP

**Comment by juewuy** [comment]
第一个问题是你的ShellClash并没有正确接管dns服务，使用了系统或浏览器提供的dns
第二个问题是需要使用7-7自定义规则跳过ddns相关域名，或者直接在运行ShellClash的设备上使用ddns服务并禁用本机代理
