### ISSUE TITLE
[Feature] Linux主机开了openvpn（nat），视为Linux主机还是路由设备

### ISSUE THREAD

**Issue by qq1052983095** [juewuy/ShellClash#371]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

Linux主机开了openvpn（nat），视为Linux主机还是路由设备

**Comment by juewuy** [comment]
@qq1052983095 我不知道你的需求是什么

**Comment by qq1052983095** [comment]
我想咨询的问题是，我的LINUX主机，是开了一个OVPN业务，OVPN是通过虚接口IP和防火墙NAT转换上网的（相当于一个路由器），此时我运行安装脚本，是使用LINUX标准模式好，还是使用路由器模式？

**Comment by qq1052983095** [comment]
好的感谢，我应该使用路由器模式。目前测试通畅
