### ISSUE TITLE
[Bug] 域名规则分流策略组没有生效

### ISSUE THREAD

**Issue by sky31even** [juewuy/ShellClash#373]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

我用的 dler cloud 的托管服务，其中有专为 chatGPT 准备的策略组，可以为 openai.com 域名单独手选不同的链接。

但是在 shellclash 运行中这个策略组却没有生效，查看了日志后发现是因为策略组中的规则是使用的 domain，但日志里面的请求都是 ip 地址的，如下图：13.107.246.39 是 openai 的 ip 地址。

![image_17gugay](https://user-images.githubusercontent.com/49628447/232377226-40637a6a-ba33-40be-8cde-2c2623ce9704.png)

想知道下有什么方法可以解决这一问题，让路由器能看到域名请求并执行对应的分流策略组，谢谢！

**Comment by juewuy** [comment]
@sky31even DNS没接管到 参考常见问题
