### ISSUE TITLE
[Bug] ASUS AX92U 原厂固件 正常运行一段时间后路由器软重启

### ISSUE THREAD

**Issue by Cryolitia** [juewuy/ShellClash#375]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

正常安装并配置之后可以正常使用几小时到一两天不等的时间，在此之后路由器会突然软重启，所有有线/无线设备断开连接。等待一小段时间后连接上路由器，此时clash服务没有运行，且在ssh中运行 `clash` 命令会提示找不到命令。

手动执行安装目录下的 `clash.sh` 会自动初始化环境变量，重新启动clash后又可以正常使用几小时至几天时间。

软重启并丢失环境的变量还会随机出现在使用更新菜单的过程中，包括检查更新，一键导入配置文件，下载内核等。具体表现是下载到一半有几率ssh断开连接，网络连接断开，重启完成后环境变量丢失。

**Comment by juewuy** [comment]
@Cryolitia 华硕官方固件必须搭配USB设备才能开机启动并配置环境变量
另外死机可能是流量过大或者未知原因导致的内存溢出，建议使用绕过cn+常用端口过滤+每日定时重启

**Comment by Cryolitia** [comment]
开机自启是没有问题的，正在使用USB设备。原厂固件无法开启绕过CN，提示 `当前设备缺少ipset模块或未使用Nft模式，无法启用绕过功能！！` ，定时任务最多只能每天执行一次，往往坚持不到1天就死机了。

**Comment by juewuy** [comment]
@Cryolitia 那就善用黑白名单过滤吧，把流量大的设备过滤掉

**Comment by Cryolitia** [comment]
好的，谢谢
