### ISSUE TITLE
[Feature] 有没有大佬知道unraid下如何使用shellclash

### ISSUE THREAD

**Issue by MechanE** [juewuy/ShellClash#376]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

有没有大佬知道unraid下如何使用shellclash，

按照标准按照方式的确可以使用，但只要修改了unraid的系统代理，貌似就会循环卡在启动阵列上。

**Comment by juewuy** [comment]
@MechanE 为什么要修改系统代理？你的需求是什么
