### ISSUE TITLE
NTP问题

### ISSUE THREAD

**Issue by AngelaCooljx** [juewuy/ShellClash#38]
开发者大大能不能增加一个脚本，就是在启动前执行某些命令强制同步ntp服务器以获得校准时间，如果时间误差超过60s，v2节点是用不了的，trojan正常，我这边（CR6608 padavan）NTP服务器一直不正常，日志一直是（NTP Client: Synchronizing time to ntp1.aliyun.com），不知道是不是我这边宽带的问题导致每次都无法同步时间，但奇怪的是OpenWrt下和手机或者电脑win10系统都能正常从网络上获取标准时间，路由器老毛子每次都得用date -s 2021-6-14 && date xx:xx:xx手动校准当前时间，每次重启时间就不准了，所以希望大大能做一个每次开启/重启clash程序之前强制同步标准时间的脚本给老毛子用（比如绕过可能是被禁用的ntp服务器的端口号，用另外的方式获取时间），并做个开关自由选择是否开启强制同步ntp服务器标准时间

**Comment by juewuy** [comment]
你把时间同步的命令添加到padavan管理页面的：
自定义设置-在防火墙启动后执行 
的最末端就行了
除非大量用户报告类似问题不然我不可能单独加功能
