### ISSUE TITLE
[Bug] 手动设置小闪存目录后，无法运行

### ISSUE THREAD

**Issue by posystorage** [juewuy/ShellClash#382]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

路由器插U盘后在菜单4-5设置了小闪存模式目录 
` 
4 启用小闪存模式:      已开启  ————用于闪存空间不足的设备

 5 设置小闪存目录:      /media/AiDisk_a1/shellclash
`
实测重启clash服务后，设置的目录下第一次运行会自动下载 clash程序本体和country.mmdb
但是缺少ui面板文件夹和config.yaml

尝试解决：
1、ui面板文件夹可以从 etc/storage/clash下复制
2、手动复制config.yaml可以运行，但是使用手动更新订阅或者自动定时更新
/etc/storage/clash/start.sh getyaml && /etc/storage/clash/start.sh restart
都不可以实现更新手动目录下的config.yaml
3、阅读strat.sh发现问题在modify_yaml()，约446行处，判断了$tmpdir是否等于$bindir，如果不等，则从$tmpdir往$clashdir目录复制了config.yaml，但没有复制到$bindir，导致config.yaml永远没法更新订阅
4、尝试修改strat.sh 446行如下，测试有效
`
	#如果没有使用小闪存模式

	if [ "$tmpdir" != "$bindir" ];then

		cmp -s $tmpdir/config.yaml $yaml >/dev/null 2>&1

		[ "$?" != 0 ] && mv -f $tmpdir/config.yaml $yaml || rm -f $tmpdir/config.yaml

		if [ "$clashdir" != "$bindir" ];then

			mv -f $yaml $bindir/config.yaml

		fi

	fi
`
5、ui面板如何拷贝，没有研究，麻烦大佬看下

**Comment by juewuy** [comment]
@posystorage 好的，已收到
