### ISSUE TITLE
离线模式 wget 低版本参数不支持

### ISSUE THREAD

**Issue by pengchujin** [juewuy/ShellClash#39]
参数1：
wget: unrecognized option: show-progress
BusyBox v1.28.3 () multi-call binary.
参数2:
wget: unrecognized option: timeout=5
参数3：
wget: unrecognized option: no-check-certificate

**Comment by juewuy** [comment]
https://github.com/juewuy/ShellClash/commit/27892429311ac624278013334a31828afe1159fe

**Comment by pengchujin** [comment]
> [d7dd915](https://github.com/juewuy/ShellClash/commit/d7dd9154721afd48d6b43dd91bdd3839664664e3)

getdate.sh 这个脚本内的 wget 并没有处理，获取 dashboard 面板等仍然报错：

安装本地Dashboard面板，可以更快捷的管理clash内置规则！
-----------------------------------------------
需要安装本地Dashboard面板吗？(1/0) > 1
wget: unrecognized option: no-check-certificate
BusyBox v1.28.3 () multi-call binary.
