### ISSUE TITLE
curl google 失败  SSL_ERROR_SYSCALL in connection to www.google.com:443

### ISSUE THREAD

**Issue by gooutlook** [juewuy/ShellClash#390]
![image](https://user-images.githubusercontent.com/119985624/235421193-32abfa8a-72cc-4fe8-bad1-965f3af0d020.png)
这个啥原因

**Comment by juewuy** [comment]
@gooutlook 用-k

**Comment by gooutlook** [comment]
> 

![image](https://user-images.githubusercontent.com/119985624/235446608-a2152960-7713-4348-9210-89eeb712659f.png)
一样的问题，我这个是在虚拟机中部署的
