### ISSUE TITLE
[Bug] Padavan配置不会自动保存，重启后消失

### ISSUE THREAD

**Issue by qzydustin** [juewuy/ShellClash#392]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

Padavan中的/etc/storage重启后会重置，需要运行以下命令来保存到闪存

```shell
/sbin/mtd_storage.sh save
```

**Comment by juewuy** [comment]
想了一下单独加一个命令也不好，还是建议每次配置完成后正常执行一次设备重启吧
