### ISSUE TITLE
[Bug] 无法通过clash 脚本在后台重启clash服务

### ISSUE THREAD

**Issue by wxyzh** [juewuy/ShellClash#394]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

## 使用场景
通过ssh 使用clash提供的代理Port 7890连接 shellclash所在服务器。
运行clash 选择1 重启clash服务 
## 预期结果
能够正常重启clash服务
### 实际结果
clash 服务停止后，ssh会话断开
直连服务器后发现clash 服务并未启动

**Comment by juewuy** [comment]
@wxyzh 我觉得可能是你操作有问题，如果确定无法启动请提供报错信息

**Comment by wxyzh** [comment]
并不是操作问题，无报错信息
我是通过clash提供的代理连的SSH
当clash服务停止后，SSH就会断开，之后的启动自然就无法运行了。

**Comment by juewuy** [comment]
@wxyzh 不要套娃，如果实在要套娃，使用
clash -s start &

**Comment by wxyzh** [comment]
因为我有时需要在外部配置该服务器。所以有套娃的需求。
我先暂时使用``clash -s start &``

**Comment by juewuy** [comment]
@wxyzh 这不是bug，不用期待会“修复”
