### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by KerryJi** [juewuy/ShellClash#395]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

在本机环境中有docker运行时，同时ip route获取的真实中结尾是metric 100时，将会吧docker的虚拟ip作为唯一出口ip，从而无法通过redirect上网
https://github.com/juewuy/ShellClash/blob/master/scripts/start.sh#LL139C8-L139C8

**Comment by juewuy** [comment]
请提供一下
ip route
命令的运行结果

**Comment by KerryJi** [comment]
![image](https://github.com/juewuy/ShellClash/assets/26683083/de58809f-bbaf-4275-8929-04c9f797577e)
