### ISSUE TITLE
[Bug] PPPOE断线重连导致shellclash重启

### ISSUE THREAD

**Issue by abcfy2** [juewuy/ShellClash#396]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

我这边是移动的网络，似乎每过2小时PPPOE会被踢掉，然后路由器自动断线重播获得新的WAN口地址，但是这个过程会导致shellclash不明原因重启，于是有几分钟的时间内无法访问网络，直到clash重启完成之后网络才恢复正常。

我尝试改从运营商给的光猫处PPPOE拨号，路由器采用动态IP方式连接，shellclash就能稳定运行十几小时不重启。

希望这个问题可以改善，不然每次clash重启过程都有几分钟时间无法访问网络

**Comment by juewuy** [comment]
@abcfy2 卸载重装到/etc，如果重启会丢失，则基本无解

**Comment by abcfy2** [comment]
> @abcfy2 卸载重装到/etc，如果重启会丢失，则基本无解

有点好奇这是什么原理，为什么重装到/etc/就不会有这个问题呢？我的是华硕路由器，会安装到/jffs/clash/，我之前开启过DEBUG日志观察下，好像是因为PPPOE断掉的时候好多DNS查询都失败了，然后clash进程莫名其妙被kill了导致重启，日志内容: https://github.com/MetaCubeX/Clash.Meta/issues/540#issuecomment-1535651183

**Comment by juewuy** [comment]
@abcfy2 那就不是一个原因了，你这种是内核问题

**Comment by abcfy2** [comment]
> @abcfy2 那就不是一个原因了，你这种是内核问题

试了好个版本的clash.meta，还有TProxy模式和Redir模式都试过了，都是这个问题。我现在只好将路由器连接模式改为动态IP，在光猫上PPPOE拨号来避免clash重启导致的网络长时间断线，目前我看clash进程已经稳定运行一天了都没有退出过
