### ISSUE TITLE
[Feature] 支持自建的订阅转换源

### ISSUE THREAD

**Issue by labulac** [juewuy/ShellClash#398]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

是否有计划支持填写自建的订阅转换源，避免隐私泄露

**Comment by juewuy** [comment]
@labulac 用6-2即可

**Comment by labulac** [comment]
谢谢，close
