### ISSUE TITLE
[Feature] 多配置文件一键切换，以及 参数命令，以及profile

### ISSUE THREAD

**Issue by joyanhui** [juewuy/ShellClash#399]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

## 希望增加配置文件合并功能  
在 机场流量用光的情况下，自动选择节点 会有概率一直选择 哪怕流量已经用光的节点。  
openclash  那边 是可以一键切换的。   
shellclash这边。。。要  clash > 6 >2 ....  然后粘贴 包含转换过滤等规则的url，操作挺不方便的。
## 希望增加命令参数
所有操作 除了 重启卸载等寥寥几个功能， 都要  依次去菜单输入数字，麻烦。。。甚至重启 都要 clash -s stop && clash -s start  ，有没有可能 把菜单挪到参数里面    
例如
```
clash -menu  1 #重启/启动
clash -menu  9 1 #更新
clash -menu  9  3 # 更新geoip
```
## /etc/profile
linux下或许是用户级执行的，安装脚本 就不要去搞全局配置文件了吧。 ~/.profile 更合理一些。

## 最后一点点小建议
https://juewuy.github.io/chang-jian-wen-ti/  这个页面的前端是不是太夸张了一点，cpu占用也太离谱了。。。

**Comment by joyanhui** [comment]
> @joyanhui 第一个后续会增加但不是现在 第二点我想不到要怎么实现以及实现之后到底有何意义 第三点，如果是非root用户安装不会写入系统全局变量 第四点，未能发现你说的问题

第二点 
- crontab 切换配置文件，当然可以自己写脚本替换/etc/clash/里面的配置文件。只是如果您能集成更好一些。
- 一键进行一些操作，例如开关ipv6现在需要 在一堆菜单里面逐个查看选项

补充
> /etc/clash/start.sh: line 495: ipset: command not found

**Comment by juewuy** [comment]
第二点是代码压根无法简单实现不用想了
ipset是你在脚本设置时候就提示了缺少依赖
