### ISSUE TITLE
[Bug] /usr/share/clash/start.sh: line 56: /tmp/ShellClash_log: Permission denied

### ISSUE THREAD

**Issue by Whyjsee** [juewuy/ShellClash#400]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

`/usr/share/clash/start.sh: line 56: /tmp/ShellClash_log: Permission denied`
启动及调整clash配置的过程中一直会有这个报错，在ubuntu的root环境下运行的

**Comment by juewuy** [comment]
@Whyjsee 说明是伪root用户，不过这个后续会考虑调整一下

**Comment by Whyjsee** [comment]
> @Whyjsee 说明是伪root用户，不过这个后续会考虑调整一下

这边查了下linux伪用户的概念，里面提及伪root用户uid不会为0，但这边看了下uid依然为0，想请教下这边有什么办法去判断是否是伪用户吗？以及有什么办法进入真实的root用户呢？ 这边是腾讯云的轻量服务器ubuntu系统，谢谢

`root@VM-12-2-ubuntu:/lib# id root
uid=0(root) gid=0(root) groups=0(root)
root@VM-12-2-ubuntu:/lib# clash
-----------------------------------------------
欢迎使用ShellClash！            版本：1.7.0f
Clash服务正在运行（纯净模式），已设置开机启动！
当前内存占用：11656 kB，已运行：
TG频道：https://t.me/ShellClash
-----------------------------------------------
 1 启动/重启clash服务
 2 clash功能设置
 3 停止clash服务
 4 clash启动设置
 5 设置定时任务
 6 导入配置文件
 7 clash进阶设置
 8 其他工具
 9 更新/卸载
-----------------------------------------------
 0 退出脚本
请输入对应数字 > 1
-----------------------------------------------
/usr/share/clash/start.sh: line 55: /tmp/ShellClash_log: Permission denied
`

**Comment by juewuy** [comment]
@Whyjsee 也可能是/tmp目录有被额外配置权限，尝试运行chmod +w /tmp

**Comment by Whyjsee** [comment]
> @Whyjsee 也可能是/tmp目录有被额外配置权限，尝试运行chmod +w /tmp

谢谢回复，这边试一试
