### ISSUE TITLE
[Bug] ubuntu20.04桌面版ShellClash开启开机自启动后状态栏网络图标显示异常

### ISSUE THREAD

**Issue by huenrong** [juewuy/ShellClash#401]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

1. 我在VMware虚拟机中使用ubuntu20.04桌面版
2. 设置ShellClash开机自启动后, 系统重启后系统网络连接图标显示"问号". 我在`clash.service`文件中增加`ExecStartPre=/bin/sleep 1s`后开机时网络连接图标显示正常
3. 在`clash.service`文件中增加`ExecStartPre=/bin/sleep 1s`的前提下. ubuntu虚拟机在后台运行一段时间再打开, 系统网络连接图标也会显示"问号"
4. 上述系统网络连接图标显示"问号"时网络实际可用

**Comment by juewuy** [comment]
@huenrong 桌面版没必要设置开机启动，随用随开比较好，实在想用去设置自启延迟
