### ISSUE TITLE
[Bug] 修改内置DNS的选项不见了

### ISSUE THREAD

**Issue by expliyh** [juewuy/ShellClash#402]
### Verify steps

- [x]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

<img width="575" alt="image" src="https://github.com/juewuy/ShellClash/assets/54161210/3f571a67-d2ec-48c8-a686-4fef6772ea5c">

**Comment by juewuy** [comment]
6-6
