### ISSUE TITLE
[Bug] 不断启动 clash 进程, 腾讯云 Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by fioepq9** [juewuy/ShellClash#404]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

Welcome to Ubuntu 22.04 LTS (GNU/Linux 5.15.0-56-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  System information as of Mon May 22 04:05:02 PM CST 2023

  System load:  0.0               Processes:             217
  Usage of /:   7.7% of 49.10GB   Users logged in:       0
  Memory usage: 86%               IPv4 address for eth0: 10.0.8.15
  Swap usage:   0%

 * Strictly confined Kubernetes makes edge and IoT secure. Learn how MicroK8s
   just raised the bar for easy, resilient and secure K8s cluster deployment.

   https://ubuntu.com/engage/secure-kubernetes-at-the-edge

Last login: Mon May 22 16:03:16 2023 from 116.24.67.128
ubuntu@site:~$ systemctl status clash
● clash.service - clash
     Loaded: loaded (/lib/systemd/system/clash.service; enabled; vendor preset: enabled)
     Active: activating (start-post) since Mon 2023-05-22 16:04:12 CST; 1min 1s ago
   Main PID: 83262 (su); Control PID: 83263 (start.sh)
      Tasks: 3 (limit: 2237)
     Memory: 5.2M
        CPU: 197ms
     CGroup: /system.slice/clash.service
             ├─83263 /bin/bash /etc/clash/start.sh afstart
             └─83301 ntpd -n -q -p 203.107.6.88
             ‣ 83262 /bin/su shellclash -c "/etc/clash/clash -d /etc/clash"

May 22 16:04:14 site ntpd[83301]: failed to init interface for address 127.0.0.1
May 22 16:04:14 site ntpd[83301]: bind(19) AF_INET 10.0.8.15#123 flags 0x19 failed: Address already in use
May 22 16:04:14 site ntpd[83301]: unable to create socket on eth0 (5) for 10.0.8.15#123
May 22 16:04:14 site ntpd[83301]: failed to init interface for address 10.0.8.15
May 22 16:04:14 site ntpd[83301]: bind(19) AF_INET6 ::1#123 flags 0x5 failed: Address already in use
May 22 16:04:14 site ntpd[83301]: unable to create socket on lo (6) for ::1#123
May 22 16:04:14 site ntpd[83301]: failed to init interface for address ::1
May 22 16:04:14 site ntpd[83301]: bind(19) AF_INET6 fe80::5054:ff:fec7:7704%2#123 flags 0x11 failed: Address already in use
May 22 16:04:14 site ntpd[83301]: unable to create socket on eth0 (7) for fe80::5054:ff:fec7:7704%2#123
May 22 16:04:14 site ntpd[83301]: failed to init interface for address fe80::5054:ff:fec7:7704%2
ubuntu@site:~$ ps -aux | grep clash
root       39029  0.0  0.6 711952 13572 ?        Sl   13:23   0:01 /etc/clash/clash -d /etc/clash
root       39687  0.0  0.6 711952 13192 ?        Sl   13:25   0:00 /etc/clash/clash -d /etc/clash
root       40107  0.0  0.6 712208 13244 ?        Sl   13:26   0:00 /etc/clash/clash -d /etc/clash
root       40539  0.0  0.6 712208 13352 ?        Sl   13:28   0:00 /etc/clash/clash -d /etc/clash
root       40952  0.0  0.6 711952 13352 ?        Sl   13:29   0:00 /etc/clash/clash -d /etc/clash
root       41425  0.0  0.6 711952 13172 ?        Sl   13:31   0:00 /etc/clash/clash -d /etc/clash
root       41823  0.0  0.6 711952 13368 ?        Sl   13:33   0:00 /etc/clash/clash -d /etc/clash
root       42268  0.0  0.6 711952 13256 ?        Sl   13:34   0:00 /etc/clash/clash -d /etc/clash
root       42712  0.0  0.6 711952 13348 ?        Sl   13:36   0:00 /etc/clash/clash -d /etc/clash
root       43132  0.0  0.6 711952 13320 ?        Sl   13:37   0:00 /etc/clash/clash -d /etc/clash
root       43581  0.0  0.6 711952 13344 ?        Sl   13:39   0:00 /etc/clash/clash -d /etc/clash
root       43991  0.0  0.6 712208 13108 ?        Sl   13:40   0:00 /etc/clash/clash -d /etc/clash
root       44441  0.0  0.6 712208 13244 ?        Sl   13:42   0:00 /etc/clash/clash -d /etc/clash
root       44851  0.0  0.6 711952 13204 ?        Sl   13:44   0:00 /etc/clash/clash -d /etc/clash
root       45302  0.0  0.6 712208 12928 ?        Sl   13:45   0:00 /etc/clash/clash -d /etc/clash
root       45736  0.0  0.6 711952 12964 ?        Sl   13:47   0:00 /etc/clash/clash -d /etc/clash
root       46152  0.0  0.6 712208 13328 ?        Sl   13:48   0:00 /etc/clash/clash -d /etc/clash
root       46611  0.0  0.6 712208 13152 ?        Sl   13:50   0:00 /etc/clash/clash -d /etc/clash
root       47025  0.0  0.6 712208 13156 ?        Sl   13:52   0:00 /etc/clash/clash -d /etc/clash
root       47467  0.0  0.6 711952 13424 ?        Sl   13:53   0:00 /etc/clash/clash -d /etc/clash
root       47908  0.0  0.6 711952 13308 ?        Sl   13:55   0:00 /etc/clash/clash -d /etc/clash
root       48329  0.0  0.6 711952 13228 ?        Sl   13:56   0:00 /etc/clash/clash -d /etc/clash
root       48758  0.0  0.6 712208 13252 ?        Sl   13:58   0:00 /etc/clash/clash -d /etc/clash
root       49208  0.0  0.6 711952 13156 ?        Sl   14:00   0:00 /etc/clash/clash -d /etc/clash
root       49626  0.0  0.6 711952 13312 ?        Sl   14:01   0:00 /etc/clash/clash -d /etc/clash
root       50060  0.0  0.6 711952 13432 ?        Sl   14:03   0:00 /etc/clash/clash -d /etc/clash
root       50481  0.0  0.6 712208 13276 ?        Sl   14:04   0:00 /etc/clash/clash -d /etc/clash
root       50937  0.0  0.6 712208 13312 ?        Sl   14:06   0:00 /etc/clash/clash -d /etc/clash
root       51423  0.0  0.6 711952 13008 ?        Sl   14:08   0:00 /etc/clash/clash -d /etc/clash
root       51865  0.0  0.6 712208 13308 ?        Sl   14:09   0:00 /etc/clash/clash -d /etc/clash
root       52309  0.0  0.6 711952 13396 ?        Sl   14:11   0:00 /etc/clash/clash -d /etc/clash
root       52732  0.0  0.6 711952 13144 ?        Sl   14:12   0:00 /etc/clash/clash -d /etc/clash
root       53182  0.0  0.6 711952 13116 ?        Sl   14:14   0:00 /etc/clash/clash -d /etc/clash
root       53592  0.0  0.6 711952 13224 ?        Sl   14:15   0:00 /etc/clash/clash -d /etc/clash
root       54048  0.0  0.6 712208 13300 ?        Sl   14:17   0:00 /etc/clash/clash -d /etc/clash
root       54456  0.0  0.6 711952 13292 ?        Sl   14:19   0:00 /etc/clash/clash -d /etc/clash
root       54905  0.0  0.6 711952 13208 ?        Sl   14:20   0:00 /etc/clash/clash -d /etc/clash
root       55341  0.0  0.6 711952 13368 ?        Sl   14:22   0:00 /etc/clash/clash -d /etc/clash
root       55754  0.0  0.6 711952 13044 ?        Sl   14:23   0:00 /etc/clash/clash -d /etc/clash
root       56214  0.0  0.6 712208 13268 ?        Sl   14:25   0:00 /etc/clash/clash -d /etc/clash
root       56627  0.0  0.6 711952 13168 ?        Sl   14:27   0:00 /etc/clash/clash -d /etc/clash
root       57067  0.0  0.6 711952 13144 ?        Sl   14:28   0:00 /etc/clash/clash -d /etc/clash
root       57516  0.0  0.6 711952 13156 ?        Sl   14:30   0:00 /etc/clash/clash -d /etc/clash
root       57941  0.0  0.6 711952 13036 ?        Sl   14:31   0:00 /etc/clash/clash -d /etc/clash
root       58367  0.0  0.6 712208 13248 ?        Sl   14:33   0:00 /etc/clash/clash -d /etc/clash
root       58807  0.0  0.6 712208 13148 ?        Sl   14:35   0:00 /etc/clash/clash -d /etc/clash
root       59224  0.0  0.6 711952 13436 ?        Sl   14:36   0:00 /etc/clash/clash -d /etc/clash
root       59657  0.0  0.6 711952 12972 ?        Sl   14:38   0:00 /etc/clash/clash -d /etc/clash
root       60077  0.0  0.6 712208 13440 ?        Sl   14:39   0:00 /etc/clash/clash -d /etc/clash
root       60533  0.0  0.6 711952 13332 ?        Sl   14:41   0:00 /etc/clash/clash -d /etc/clash
root       60965  0.0  0.6 711952 13184 ?        Sl   14:43   0:00 /etc/clash/clash -d /etc/clash
root       61385  0.0  0.6 711952 13156 ?        Sl   14:44   0:00 /etc/clash/clash -d /etc/clash
root       61825  0.0  0.6 711952 13344 ?        Sl   14:46   0:00 /etc/clash/clash -d /etc/clash
root       62243  0.0  0.6 712208 13204 ?        Sl   14:47   0:00 /etc/clash/clash -d /etc/clash
root       62692  0.0  0.6 711952 13288 ?        Sl   14:49   0:00 /etc/clash/clash -d /etc/clash
root       63101  0.0  0.6 711952 13412 ?        Sl   14:50   0:00 /etc/clash/clash -d /etc/clash
root       63553  0.0  0.6 712208 13144 ?        Sl   14:52   0:00 /etc/clash/clash -d /etc/clash
root       63966  0.0  0.6 711952 13316 ?        Sl   14:54   0:00 /etc/clash/clash -d /etc/clash
root       64409  0.0  0.6 712208 13332 ?        Sl   14:55   0:00 /etc/clash/clash -d /etc/clash
root       64856  0.0  0.6 711952 13356 ?        Sl   14:57   0:00 /etc/clash/clash -d /etc/clash
root       65257  0.0  0.6 712208 13168 ?        Sl   14:58   0:00 /etc/clash/clash -d /etc/clash
root       65730  0.0  0.6 712208 13168 ?        Sl   15:00   0:00 /etc/clash/clash -d /etc/clash
root       66145  0.0  0.6 712208 13328 ?        Sl   15:02   0:00 /etc/clash/clash -d /etc/clash
root       66595  0.0  0.6 711952 13128 ?        Sl   15:03   0:00 /etc/clash/clash -d /etc/clash
root       67100  0.0  0.6 712208 13220 ?        Sl   15:05   0:00 /etc/clash/clash -d /etc/clash
root       67531  0.0  0.6 712208 13364 ?        Sl   15:06   0:00 /etc/clash/clash -d /etc/clash
root       67961  0.0  0.6 711952 13288 ?        Sl   15:08   0:00 /etc/clash/clash -d /etc/clash
root       68405  0.0  0.6 711952 13288 ?        Sl   15:10   0:00 /etc/clash/clash -d /etc/clash
root       68832  0.0  0.6 712208 13376 ?        Sl   15:11   0:00 /etc/clash/clash -d /etc/clash
root       69265  0.0  0.6 711952 13128 ?        Sl   15:13   0:00 /etc/clash/clash -d /etc/clash
root       69704  0.0  0.6 711952 13360 ?        Sl   15:14   0:00 /etc/clash/clash -d /etc/clash
root       70144  0.0  0.6 712208 13128 ?        Sl   15:16   0:00 /etc/clash/clash -d /etc/clash
root       70588  0.0  0.6 711952 13284 ?        Sl   15:18   0:00 /etc/clash/clash -d /etc/clash
root       71005  0.0  0.6 711952 13080 ?        Sl   15:19   0:00 /etc/clash/clash -d /etc/clash
root       71450  0.0  0.6 712208 13276 ?        Sl   15:21   0:00 /etc/clash/clash -d /etc/clash
root       71870  0.0  0.6 711952 13088 ?        Sl   15:22   0:00 /etc/clash/clash -d /etc/clash
root       72322  0.0  0.6 711952 13316 ?        Sl   15:24   0:00 /etc/clash/clash -d /etc/clash
root       72738  0.0  0.6 711952 13300 ?        Sl   15:26   0:00 /etc/clash/clash -d /etc/clash
root       73191  0.0  0.6 711952 13312 ?        Sl   15:27   0:00 /etc/clash/clash -d /etc/clash
root       73610  0.0  0.6 712208 13220 ?        Sl   15:29   0:00 /etc/clash/clash -d /etc/clash
root       74062  0.0  0.6 712208 13276 ?        Sl   15:30   0:00 /etc/clash/clash -d /etc/clash
root       74515  0.0  0.6 711952 13304 ?        Sl   15:32   0:00 /etc/clash/clash -d /etc/clash
root       74919  0.0  0.6 711952 13448 ?        Sl   15:33   0:00 /etc/clash/clash -d /etc/clash
root       75385  0.0  0.6 712208 13212 ?        Sl   15:35   0:00 /etc/clash/clash -d /etc/clash
root       75798  0.0  0.6 711952 13504 ?        Sl   15:37   0:00 /etc/clash/clash -d /etc/clash
root       76320  0.0  0.6 711952 13424 ?        Sl   15:38   0:00 /etc/clash/clash -d /etc/clash
root       76761  0.0  0.6 712208 13280 ?        Sl   15:40   0:00 /etc/clash/clash -d /etc/clash
root       77185  0.0  0.6 711952 13604 ?        Sl   15:41   0:00 /etc/clash/clash -d /etc/clash
root       77616  0.0  0.6 712208 13544 ?        Sl   15:43   0:00 /etc/clash/clash -d /etc/clash
root       78043  0.0  0.6 712208 13356 ?        Sl   15:45   0:00 /etc/clash/clash -d /etc/clash
root       78484  0.0  0.6 712208 13444 ?        Sl   15:46   0:00 /etc/clash/clash -d /etc/clash
root       78896  0.0  0.6 711952 13076 ?        Sl   15:48   0:00 /etc/clash/clash -d /etc/clash
root       79323  0.0  0.6 712208 13260 ?        Sl   15:49   0:00 /etc/clash/clash -d /etc/clash
root       79755  0.0  0.6 711952 13284 ?        Sl   15:51   0:00 /etc/clash/clash -d /etc/clash
root       80184  0.0  0.6 712208 13332 ?        Sl   15:53   0:00 /etc/clash/clash -d /etc/clash
root       80598  0.0  0.6 712208 13256 ?        Sl   15:54   0:00 /etc/clash/clash -d /etc/clash
root       81036  0.0  0.6 711952 13316 ?        Sl   15:56   0:00 /etc/clash/clash -d /etc/clash
root       81447  0.0  0.6 711952 13284 ?        Sl   15:57   0:00 /etc/clash/clash -d /etc/clash
root       81891  0.0  0.6 712208 13260 ?        Sl   15:59   0:00 /etc/clash/clash -d /etc/clash
root       82305  0.0  0.6 711952 13596 ?        Sl   16:01   0:00 /etc/clash/clash -d /etc/clash
root       82743  0.1  0.7 711952 14908 ?        Sl   16:02   0:00 /etc/clash/clash -d /etc/clash
root       83262  0.0  0.2  10200  4512 ?        Ss   16:04   0:00 /bin/su shellclash -c /etc/clash/clash -d /etc/clash
root       83263  0.0  0.2   8952  5144 ?        Ss   16:04   0:00 /bin/bash /etc/clash/start.sh afstart
root       83266  0.0  0.0   2888  1008 ?        S    16:04   0:00 sh -c /etc/clash/clash -d /etc/clash
root       83267  0.2  0.7 711952 15156 ?        Sl   16:04   0:00 /etc/clash/clash -d /etc/clash
ubuntu     83680  0.0  0.1   6608  2268 pts/0    R+   16:05   0:00 grep --color=auto clash
ubuntu@site:~$ uname -a
Linux site 5.15.0-56-generic #62-Ubuntu SMP Tue Nov 22 19:54:14 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by fioepq9** [comment]
复现：
1. 腾讯云轻量服务器重装系统 ubuntu 22.04 LTS
2. ssh
3. sudo -i
4. export url='https://fastly.jsdelivr.net/gh/juewuy/ShellClash@master' && wget -q --no-check-certificate -O /tmp/install.sh $url/install.sh  && bash /tmp/install.sh && source /etc/profile &> /dev/null
5. clash
root@VM-8-15-ubuntu:~# export url='https://fastly.jsdelivr.net/gh/juewuy/ShellClash@master' && wget -q --no-check-certificate -O /tmp/install.sh $url/install.sh  && bash /tmp/install.sh && source /etc/profile &> /dev/null
***********************************************
**                 欢迎使用                  **
**                ShellClash                 **
**                             by  Juewuy    **
***********************************************
-----------------------------------------------
请选择想要安装的版本：
 1 Shellclash公测版
 2 Shellclash稳定版
-----------------------------------------------
请输入相应数字 > 1
最新版本：1.7.8
-----------------------------------------------
如遇问题请加TG群反馈： t.me/ShellClash 
支持各种基于openwrt的路由器设备
支持Debian、Centos等标准Linux系统
-----------------------------------------------
注意：安装ShellClash至少需要预留约1MB的磁盘空间
 1 在/etc目录下安装(适合root用户)
 2 在/usr/share目录下安装(适合Linux系统)
 3 在当前用户目录下安装(适合非root用户)
 4 在外置存储中安装
 5 手动设置安装目录
 0 退出安装
-----------------------------------------------
请输入相应数字 > 1
目标目录/etc空间剩余：44G
确认安装？(1/0) > 1
-----------------------------------------------
开始从服务器获取安装文件！
-----------------------------------------------
############################################################################################################################################################### 100.0%
-----------------------------------------------
开始解压文件！
-----------------------------------------------
ShellClash 已经安装成功!
-----------------------------------------------
输入 clash 命令即可管理！！！
-----------------------------------------------
root@VM-8-15-ubuntu:~# clash
-----------------------------------------------
欢迎使用ShellClash！            版本：1.7.8
Clash服务没有运行（纯净模式），未设置开机启动！
TG频道：https://t.me/ShellClash
-----------------------------------------------
-----------------------------------------------
 欢迎使用ShellClash新手引导！ 
-----------------------------------------------
请先选择你的使用环境： 
(你之后依然可以在设置中更改各种配置)
-----------------------------------------------
 1 路由设备配置局域网透明代理
 2 Linux设备仅配置本机代理
-----------------------------------------------
请输入对应数字 > 2
-----------------------------------------------
请选择设置本机代理的方式
-----------------------------------------------
 2 使用nftables增强模式配置(支持docker,推荐！)
 3 使用环境变量方式配置(部分应用可能无法使用,不推荐！)
 0 返回上级菜单
-----------------------------------------------
请选择本机代理方式 > 2
-----------------------------------------------
是否开启公网访问Dashboard面板及socks服务？
注意当前设备必须有公网IP才能从公网正常访问
此功能会增加暴露风险请谨慎使用！
vps设备可能还需要额外在服务商后台开启相关端口
现在开启？(1/0) > 0
-----------------------------------------------
是否导入配置文件？(这是运行前的最后一步)
你必须拥有一份yaml格式的配置文件才能运行clash服务！
-----------------------------------------------
现在开始导入？(1/0) > 1
-----------------------------------------------
 欢迎使用导入配置文件功能！
-----------------------------------------------
 1 在线生成Clash配置文件
 2 导入Clash配置文件链接
 3 还原配置文件
 4 更新配置文件
 5 设置自动更新
 6 配置文件覆写
-----------------------------------------------
请输入对应数字 > 1
-----------------------------------------------
 欢迎使用在线生成配置文件功能！
-----------------------------------------------
-----------------------------------------------
本功能依赖第三方在线subconverter服务实现，脚本本身不提供任何代理服务！
严禁使用本脚本从事任何非法活动，否则一切后果请自负！
-----------------------------------------------
支持批量(<=99)导入订阅链接、分享链接
-----------------------------------------------
 1 开始生成配置文件（原文件将被备份）
 2 设置节点过滤关键字 
 3 设置节点筛选关键字 
 4 选取在线配置规则模版
 5 选取在线生成服务器
 0 撤销输入并返回上级菜单
-----------------------------------------------
请直接输入第1个链接或对应数字选项 > https://123123123
-----------------------------------------------
本功能依赖第三方在线subconverter服务实现，脚本本身不提供任何代理服务！
严禁使用本脚本从事任何非法活动，否则一切后果请自负！
-----------------------------------------------
支持批量(<=99)导入订阅链接、分享链接
-----------------------------------------------
 1 开始生成配置文件（原文件将被备份）
 2 设置节点过滤关键字 
 3 设置节点筛选关键字 
 4 选取在线配置规则模版
 5 选取在线生成服务器
 0 撤销输入并返回上级菜单
-----------------------------------------------
请直接输入第2个链接或对应数字选项 > 1
-----------------------------------------------
链接地址为：https://123123123
可以手动复制该链接到浏览器打开并查看数据是否正常！
      -=O=-                    #          #           #           #                                                                                                  
已成功获取配置文件！
-----------------------------------------------
很好！现在只需要执行启动就可以愉快的使用了！
-----------------------------------------------
立即启动clash服务？(1/0) > 1
-----------------------------------------------
未找到clash核心，正在下载！
############################################################################################################################################################### 100.0%
卡住

**Comment by juewuy** [comment]
更新脚本或者尝试使用保守模式启动
