### ISSUE TITLE
[Bug] 开启clash服务时,更新订阅文件报错

### ISSUE THREAD

**Issue by lyxhwy** [juewuy/ShellClash#407]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

在开启clash服务时,更细订阅文件报错,实测浏览器可以打开订阅地址

runtime stack:
runtime.throw({0xf0878a?, 0x0?})
	runtime/panic.go:1047 +0x40 fp=0x7fd67c6850 sp=0x7fd67c6820 pc=0x45820
runtime.(*mheap).sysAlloc(0x1a730a0, 0x0?, 0x1a83238, 0x1)
	runtime/malloc.go:712 +0x2f8 fp=0x7fd67c68f0 sp=0x7fd67c6850 pc=0x1ba98
runtime.(*mheap).grow(0x1a730a0, 0x362c8?)
	runtime/mheap.go:1472 +0x84 fp=0x7fd67c6970 sp=0x7fd67c68f0 pc=0x36f94
runtime.(*mheap).allocSpan(0x1a730a0, 0x1, 0x0, 0x0?)
	runtime/mheap.go:1243 +0x160 fp=0x7fd67c6a00 sp=0x7fd67c6970 pc=0x367f0
runtime.(*mheap).alloc.func1()
	runtime/mheap.go:961 +0x6c fp=0x7fd67c6a50 sp=0x7fd67c6a00 pc=0x362dc
runtime.(*mheap).alloc(0x7fd67c6ad8?, 0x25c30?, 0xd8?)
	runtime/mheap.go:955 +0x54 fp=0x7fd67c6aa0 sp=0x7fd67c6a50 pc=0x36234
runtime.(*mcentral).grow(0x7fd67c6b18?)
	runtime/mcentral.go:246 +0x5c fp=0x7fd67c6ae0 sp=0x7fd67c6aa0 pc=0x25e7c
runtime.(*mcentral).cacheSpan(0x1a85ab8)
	runtime/mcentral.go:166 +0x318 fp=0x7fd67c6b50 sp=0x7fd67c6ae0 pc=0x25cd8
runtime.(*mcache).refill(0x7f7c6d3108, 0xf8?)
	runtime/mcache.go:182 +0x1bc fp=0x7fd67c6ba0 sp=0x7fd67c6b50 pc=0x2535c
runtime.(*mcache).nextFree(0x7f7c6d3108, 0x28)
	runtime/malloc.go:855 +0x84 fp=0x7fd67c6bf0 sp=0x7fd67c6ba0 pc=0x1bf44
runtime.mallocgc(0x140, 0xc76180, 0x1)
	runtime/malloc.go:1042 +0x428 fp=0x7fd67c6c60 sp=0x7fd67c6bf0 pc=0x1c4c8
runtime.newobject(0x7fd67c7d84?)
	runtime/malloc.go:1254 +0x2c fp=0x7fd67c6c90 sp=0x7fd67c6c60 pc=0x1ca7c
internal/cpu.doinit()
	internal/cpu/cpu_arm64.go:23 +0x24 fp=0x7fd67c6cc0 sp=0x7fd67c6c90 pc=0x11574
({0x0, 0x0})
	internal/cpu/cpu.go:126 +0x24 fp=0x7fd67c6ce0 sp=0x7fd67c6cc0 pc=0x11024
runtime.cpuinit(...)
	runtime/proc.go:622
runtime.schedinit()
	runtime/proc.go:715 +0xb4 fp=0x7fd67c6d40 sp=0x7fd67c6ce0 pc=0x49054
runtime.rt0_go()
	runtime/asm_arm64.s:86 +0xa4 fp=0x7fd67c6d70 sp=0x7fd67c6d40 pc=0x77e84
配置文件加载失败！请查看报错信息！
fatal error: out of memory allocating heap arena map

runtime stack:
runtime.throw({0xf0878a?, 0x0?})
	runtime/panic.go:1047 +0x40 fp=0x7ff0a16320 sp=0x7ff0a162f0 pc=0x45820
runtime.(*mheap).sysAlloc(0x1a730a0, 0x0?, 0x1a83238, 0x1)
	runtime/malloc.go:712 +0x2f8 fp=0x7ff0a163c0 sp=0x7ff0a16320 pc=0x1ba98
runtime.(*mheap).grow(0x1a730a0, 0x362c8?)
	runtime/mheap.go:1472 +0x84 fp=0x7ff0a16440 sp=0x7ff0a163c0 pc=0x36f94
runtime.(*mheap).allocSpan(0x1a730a0, 0x1, 0x0, 0x0?)
	runtime/mheap.go:1243 +0x160 fp=0x7ff0a164d0 sp=0x7ff0a16440 pc=0x367f0
runtime.(*mheap).alloc.func1()
	runtime/mheap.go:961 +0x6c fp=0x7ff0a16520 sp=0x7ff0a164d0 pc=0x362dc
runtime.(*mheap).alloc(0x7ff0a165a8?, 0x25c30?, 0xa8?)
	runtime/mheap.go:955 +0x54 fp=0x7ff0a16570 sp=0x7ff0a16520 pc=0x36234
runtime.(*mcentral).grow(0x7ff0a165e8?)
	runtime/mcentral.go:246 +0x5c fp=0x7ff0a165b0 sp=0x7ff0a16570 pc=0x25e7c
runtime.(*mcentral).cacheSpan(0x1a85ab8)
	runtime/mcentral.go:166 +0x318 fp=0x7ff0a16620 sp=0x7ff0a165b0 pc=0x25cd8
runtime.(*mcache).refill(0x7fade75108, 0xf8?)
	runtime/mcache.go:182 +0x1bc fp=0x7ff0a16670 sp=0x7ff0a16620 pc=0x2535c
runtime.(*mcache).nextFree(0x7fade75108, 0x28)
	runtime/malloc.go:855 +0x84 fp=0x7ff0a166c0 sp=0x7ff0a16670 pc=0x1bf44
runtime.mallocgc(0x140, 0xc76180, 0x1)
	runtime/malloc.go:1042 +0x428 fp=0x7ff0a16730 sp=0x7ff0a166c0 pc=0x1c4c8
runtime.newobject(0x7ff0a17854?)
	runtime/malloc.go:1254 +0x2c fp=0x7ff0a16760 sp=0x7ff0a16730 pc=0x1ca7c
internal/cpu.doinit()
	internal/cpu/cpu_arm64.go:23 +0x24 fp=0x7ff0a16790 sp=0x7ff0a16760 pc=0x11574
({0x0, 0x0})
	internal/cpu/cpu.go:126 +0x24 fp=0x7ff0a167b0 sp=0x7ff0a16790 pc=0x11024
runtime.cpuinit(...)
	runtime/proc.go:622
runtime.schedinit()
	runtime/proc.go:715 +0xb4 fp=0x7ff0a16810 sp=0x7ff0a167b0 pc=0x49054
runtime.rt0_go()
	runtime/asm_arm64.s:86 +0xa4 fp=0x7ff0a16840 sp=0x7ff0a16810 pc=0x77e84
fatal error: out of memory allocating heap arena map

runtime stack:
runtime.throw({0xf0878a?, 0x0?})
	runtime/panic.go:1047 +0x40 fp=0x7fc4740540 sp=0x7fc4740510 pc=0x45820
runtime.(*mheap).sysAlloc(0x1a730a0, 0x0?, 0x1a83238, 0x1)
	runtime/malloc.go:712 +0x2f8 fp=0x7fc47405e0 sp=0x7fc4740540 pc=0x1ba98
runtime.(*mheap).grow(0x1a730a0, 0x362c8?)
	runtime/mheap.go:1472 +0x84 fp=0x7fc4740660 sp=0x7fc47405e0 pc=0x36f94
runtime.(*mheap).allocSpan(0x1a730a0, 0x1, 0x0, 0x0?)
	runtime/mheap.go:1243 +0x160 fp=0x7fc47406f0 sp=0x7fc4740660 pc=0x367f0
runtime.(*mheap).alloc.func1()
	runtime/mheap.go:961 +0x6c fp=0x7fc4740740 sp=0x7fc47406f0 pc=0x362dc
runtime.(*mheap).alloc(0x7fc47407c8?, 0x25c30?, 0xc8?)
	runtime/mheap.go:955 +0x54 fp=0x7fc4740790 sp=0x7fc4740740 pc=0x36234
runtime.(*mcentral).grow(0x7fc4740808?)
	runtime/mcentral.go:246 +0x5c fp=0x7fc47407d0 sp=0x7fc4740790 pc=0x25e7c
runtime.(*mcentral).cacheSpan(0x1a85ab8)
	runtime/mcentral.go:166 +0x318 fp=0x7fc4740840 sp=0x7fc47407d0 pc=0x25cd8
runtime.(*mcache).refill(0x7f8c52c108, 0xf8?)
	runtime/mcache.go:182 +0x1bc fp=0x7fc4740890 sp=0x7fc4740840 pc=0x2535c
runtime.(*mcache).nextFree(0x7f8c52c108, 0x28)
	runtime/malloc.go:855 +0x84 fp=0x7fc47408e0 sp=0x7fc4740890 pc=0x1bf44
runtime.mallocgc(0x140, 0xc76180, 0x1)
	runtime/malloc.go:1042 +0x428 fp=0x7fc4740950 sp=0x7fc47408e0 pc=0x1c4c8
runtime.newobject(0x7fc4741a74?)
	runtime/malloc.go:1254 +0x2c fp=0x7fc4740980 sp=0x7fc4740950 pc=0x1ca7c
internal/cpu.doinit()
	internal/cpu/cpu_arm64.go:23 +0x24 fp=0x7fc47409b0 sp=0x7fc4740980 pc=0x11574
({0x0, 0x0})
	internal/cpu/cpu.go:126 +0x24 fp=0x7fc47409d0 sp=0x7fc47409b0 pc=0x11024
runtime.cpuinit(...)
	runtime/proc.go:622
runtime.schedinit()
	runtime/proc.go:715 +0xb4 fp=0x7fc4740a30 sp=0x7fc47409d0 pc=0x49054
runtime.rt0_go()
	runtime/asm_arm64.s:86 +0xa4 fp=0x7fc4740a60 sp=0x7fc4740a30 pc=0x77e84

**Comment by juewuy** [comment]
内存不足？

**Comment by lyxhwy** [comment]
> 内存不足？

不会呀,256M其他都没安装

**Comment by lyxhwy** [comment]
> 内存不足？

只有热更新存在问题,关闭clash服务之后就没问题

**Comment by juewuy** [comment]
@lyxhwy 麻烦提供一下报错截图

**Comment by lyxhwy** [comment]
> @lyxhwy 麻烦提供一下报错截图

就是我最上面发的那一大堆英文字符,我全复制过来了

**Comment by juewuy** [comment]
@lyxhwy 那就是内存溢出了
