### ISSUE TITLE
[Bug] HTTP 和 Socks 代理端口无法固化

### ISSUE THREAD

**Issue by EstrellaXD** [juewuy/ShellClash#409]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

安装环境: LXC Debian 11

问题描述: 安装 yacd ui 之后配置页面 HTTP 与 Socks5 代理端口均为 0，配置完成之后如果重启 LXC 端口会被重置成 0。是否有相关固化配置选项。

**Comment by juewuy** [comment]
@EstrellaXD 用混合端口

**Comment by EstrellaXD** [comment]
> @EstrellaXD 用混合端口

问题已解决
