### ISSUE TITLE
自定义其他功能

### ISSUE THREAD

**Issue by loveu5522** [juewuy/ShellClash#410]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

  自定义其他功能里,生成的user.yaml文件,我这边添加rules规则后他不会自动和原本的rules合并,会重新在最上面写一行rules,导致原先的rules记录时效,
其次,添加后在清空user.yaml文件,原先的config.yaml配置文件里添加的规则不会删除,会给移动到文件最下方,导致文件错误,clash服务启动不了,不知道这个是不是bug.

我在user.yaml里添加的规则是

rules:
 - DOMAIN-SUFFIX,m-team.cc,DIRECT  #域名后缀匹配模式 PT站直连列表
 - DOMAIN-SUFFIX,ourbits.club,DIRECT
 - DOMAIN-SUFFIX,audiences.me,DIRECT
 - DOMAIN-SUFFIX,btschool.club,DIRECT
 - DOMAIN-SUFFIX,pthome.net,DIRECT
 - DOMAIN-SUFFIX,hdarea.co,DIRECT
 - DOMAIN-SUFFIX,hhanclub.top,DIRECT
 - DOMAIN-SUFFIX,hdatmos.club,DIRECT
 - DOMAIN-SUFFIX,msg.vg,DIRECT
 - DOMAIN-SUFFIX,soulvoice.club,DIRECT
 - DOMAIN-SUFFIX,beitai.pt,DIRECT
 - DOMAIN-SUFFIX,piggo.me,DIRECT
 - DOMAIN-SUFFIX,ptchina.org,DIRECT
 - DOMAIN-SUFFIX,pttime.org,DIRECT
 - DOMAIN-SUFFIX,et8.org,DIRECT
 - DOMAIN-SUFFIX,hdhome.org,DIRECT
 - DOMAIN-SUFFIX,totheglory.im,DIRECT
 - DOMAIN-SUFFIX,lemonhd.org,DIRECT
 - DOMAIN-SUFFIX,pterclub.com,DIRECT
 - DOMAIN-SUFFIX,open.cd,DIRECT
 - DOMAIN-SUFFIX,dicmusic.club,DIRECT
 - DOMAIN-SUFFIX,hdsky.me,DIRECT
 - DOMAIN-SUFFIX,chdbits.co,DIRECT

**Comment by juewuy** [comment]
@loveu5522 user里不允许添加rules
rules请使用最新公测版的6-6添加

**Comment by loveu5522** [comment]
原来如此,就是使用管理自定义规则里,然后在rules.yaml 文件里添加rules规则就好了是吧
