### ISSUE TITLE
[Feature] add cloudflare to ShellDDNS

### ISSUE THREAD

**Issue by anyuzu99** [juewuy/ShellClash#411]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

cloudflare is the most trust worthy platform to do free ddns

**Comment by juewuy** [comment]
这取决于openwrt内置的ddns应用
而非脚本
脚本只提供了交互接口

**Comment by anyuzu99** [comment]
明白了，那我自己用py腳本實現吧。On Jun 4, 2023, at 18:45, juewuy ***@***.***> wrote:﻿
这取决于openwrt内置的ddns应用
而非脚本
脚本只提供了交互接口
