### ISSUE TITLE
[Feature] 

### ISSUE THREAD

**Issue by xiaoqi2020** [juewuy/ShellClash#412]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

老板能不能出一个完整的docker安装的教程？
新买的小米AX7000，自带docker。权限已经打开了

**Comment by juewuy** [comment]
@xiaoqi2020 路由设备请直接在ssh里安装

**Comment by xiaoqi2020** [comment]
规则一直下载失败




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年6月6日(星期二) 下午3:51
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [juewuy/ShellClash] [Feature]  (Issue #412)





 
@xiaoqi2020 路由设备请直接在ssh里安装

**Comment by xiaoqi2020** [comment]
> @xiaoqi2020 路由设备请直接在ssh里安装

![image](https://github.com/juewuy/ShellClash/assets/50669177/44adf1f1-acf7-42a7-9948-8deff5687504)

**Comment by juewuy** [comment]
@xiaoqi2020 更新里换源并手动下载
