### ISSUE TITLE
[Feature] DDNS列表里面没有阿里云

### ISSUE THREAD

**Issue by xiaoqi2020** [juewuy/ShellClash#414]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

DDNS列表里面没有阿里云吗？

**Comment by juewuy** [comment]
@xiaoqi2020 你可以尝试手动更新/etc/ddns下面的描述脚本，从最新的openwrt主干提取
