### ISSUE TITLE
[Bug] 小米AX9000公测版1.7.9d不能添加自定义规则

### ISSUE THREAD

**Issue by xilaochengv** [juewuy/ShellClash#415]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

今天更新了1.7.9d后，无法添加自定义规则，不管是手动修改rules.yaml文件还是在6-6-3-1中添加，都是提示以下信息：
![360截图20230607195730567](https://github.com/juewuy/ShellClash/assets/134846861/c2ddb966-a1b0-4b39-92b6-0394a401d407)

我的config.yaml文件第375行：
![360截图20230607195229284](https://github.com/juewuy/ShellClash/assets/134846861/3b70d4fb-4fb6-4491-b183-f2ec346ce5db)

**Comment by xilaochengv** [comment]
我知道原因了，原来是肥羊提供的规则列表，在每个-符号前有两个空格导致的
我在start.sh脚本第404行的sed 's/^ *-/  -/g'里的第二个-符号前加多一个空格解决了

**Comment by lim0513** [comment]
这个缩进好像跟机场订阅格式有关，希望能增加一个“缩进设置”，或者自动识别一下。

**Comment by juewuy** [comment]
@lim0513 1.7.9e已修复
