### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by foreverlong** [juewuy/ShellClash#417]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

版本：1.7.9e
设备：AX3600
问题描述：在进阶设置-ipv6相关中仅开启“ipv6-DNS解析”，但是设备无法ipv6上网，就很神奇，有的版本能ipv6上网，有的时候就不行了，也不知道是咋设置出问题了。“混合模式”与“Redir”模式都不行。关闭clash后，电脑可以访问ipv6。开启clash提示“DNS_PROBE_FINISHED_NXDOMAIN”

**Comment by juewuy** [comment]
@foreverlong 必须开启ipv6内核支持
