### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by mu-bibai** [juewuy/ShellClash#418]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

windows11 wsl中使用无法启动clash服务，
System has not been booted with systemd as init system (PID 1). Can't operate.
大概是因为wsl没有systemd ，请问有无手动启动的办法？
尝试service start clash 和service start clashservice 都无法找到服务。

**Comment by juewuy** [comment]
@mu-bibai 用保守模式，或者自行谷歌相关报错，有解决办法
