### ISSUE TITLE
[Bug] 开启shellclash之后银河奇异果无法使用

### ISSUE THREAD

**Issue by abcfy2** [juewuy/ShellClash#419]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

一个比较奇怪的问题，即使config.yaml保持初始，不设置任何额外的规则，也会导致银河奇异果无法使用，在开屏界面一直转圈。

重现方案，可以用任何Android模拟器运行银河奇异果，我用的是夜神模拟器： https://www.yeshen.com/

然后安装银河奇异果（从爱奇艺官方下载页面可以下载： https://www.iqiyi.com/appstore.html?vfrm=pcw_home&vfrmblk=712211_download&vfrmrst= ）

运行就可以看到类似于这样的情况：

![image](https://github.com/juewuy/ShellClash/assets/5327677/17875a39-82b3-4f96-ba2d-1fd61cba1e33)

可以看到右上角的天气也加载不出来，不知道是不是某个配置还是什么规则导致银河奇异果无法连接到服务器？

网络测试也显示服务端无法连通：
![image](https://github.com/juewuy/ShellClash/assets/5327677/b3cf8ec4-cf00-4e38-a0bc-2cf9d8624378)

![image](https://github.com/juewuy/ShellClash/assets/5327677/a1619a76-5638-40cd-bce5-3052b1ce6fcd)

**Comment by abcfy2** [comment]
好像是开了shellclash之后，爱奇艺某些资源无法加载，看日志都是DIRECT链接，但是无法加载:

```
$ curl -Lv --compressed http://cserver.iqiyi.com/mobile/static/css/app.f8b516bc9300d762f8053fd44cc83c56.css
*   Trying 111.63.147.98:80...
* Connected to cserver.iqiyi.com (111.63.147.98) port 80 (#0)
> GET /mobile/static/css/app.f8b516bc9300d762f8053fd44cc83c56.css HTTP/1.1
> Host: cserver.iqiyi.com
> User-Agent: curl/8.1.2
> Accept: */*
> Accept-Encoding: deflate, gzip, br, zstd
>
* Empty reply from server
* Closing connection 0
curl: (52) Empty reply from server
```

但是关闭clash之后这个请求没有任何问题，请问这是怎么回事？

**Comment by juewuy** [comment]
@abcfy2 请提供面板相关日志

**Comment by abcfy2** [comment]
面板日志上似乎看不出什么问题:

```
23-06-16 21:50:33[ info ][TCP] 192.168.50.196:14002 --> 111.13.235.139:80 doesn't match any rule using DIRECT
23-06-16 21:50:33[ info ][TCP] 192.168.50.196:14001 --> 111.13.235.48:80 doesn't match any rule using DIRECT
23-06-16 21:50:30[ info ][TCP] 192.168.50.196:13998 --> cserver.iqiyi.com:80 doesn't match any rule using DIRECT
```

**Comment by abcfy2** [comment]
我好像发现了点什么。在路由器上用curl请求就是无法访问的，但是本机却一切正常，不知道什么情况。

关闭clash。在路由器上直接使用

```
# curl -Lv http://cserver.iqiyi.com/mobile/static/css/app.f8b516bc9300d762f8053fd44cc83c56
.css
*   Trying 111.63.147.98:80...
* Connected to cserver.iqiyi.com (111.63.147.98) port 80 (#0)
> GET /mobile/static/css/app.f8b516bc9300d762f8053fd44cc83c56.css HTTP/1.1
> Host: cserver.iqiyi.com
> User-Agent: curl/7.84.0
> Accept: */*
>
# 这里就hang住了，直到超时
```

但是在本机请求却没有任何问题，奇怪:

```sh
$ curl -Lv --compressed http://cserver.iqiyi.com/mobile/static/css/app.f8b516bc9300d762f8053fd44cc83c56.css
*   Trying 111.63.147.98:80...
* Connected to cserver.iqiyi.com (111.63.147.98) port 80 (#0)
> GET /mobile/static/css/app.f8b516bc9300d762f8053fd44cc83c56.css HTTP/1.1
> Host: cserver.iqiyi.com
> User-Agent: curl/8.1.2
> Accept: */*
> Accept-Encoding: deflate, gzip, br, zstd
>
< HTTP/1.1 200 OK
< Content-Type: text/css
< Transfer-Encoding: chunked
< Connection: keep-alive
< Server: APISIX/2.0
< Server: nginx/1.13.3
< Date: Fri, 16 Jun 2023 13:53:10 GMT
< Last-Modified: Tue, 13 Jun 2023 03:41:57 GMT
< ETag: W/"6487e585-12c64"
< Expires: Fri, 16 Jun 2023 19:53:10 GMT
< Cache-Control: max-age=21600
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Credentials: true
< Access-Control-Expose-Headers: X-Cache
< Access-Control-Allow-Headers: X-Cache,DNT,X-Mx-ReqToken,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type
< Content-Encoding: gzip
<

# 这里已经可以打印出资源了
```

开启clash之后，本机表现就跟路由器一致了。

无论是否开启clash，本机和路由器执行ping这个域名都是通的，但是路由器curl这个地址就会超时，不知道什么情况？

**Comment by juewuy** [comment]
@abcfy2 这不是很清楚，尝试启用绕过cnIP

**Comment by abcfy2** [comment]
> @abcfy2 这不是很清楚，尝试启用绕过cnIP

作者大大感谢，绕过cnIP似乎可以解决这个问题。不过这样一来对于linkedin.com会被跳转为linkedin.cn，这个问题有没有办法解决？

尽管linkedin.com已经在gfwlist中，但是由于域名被解析到了中国ip上，然后被linkedin.com跳转到linkedin.cn了，有没有什么配置可以强制让linkedin.com可以使用？

**Comment by abcfy2** [comment]
似乎是因为linkedin.com在国内会被解析到国内ip上，启用绕过cn ip会导致即使在rule set中添加了linkedin.com也不会起作用？

**Comment by juewuy** [comment]
@abcfy2 比较麻烦，如果用的不多可以自定义一下hosts
