### ISSUE TITLE
[Feature] ax6000有办法清理内存么？

### ISSUE THREAD

**Issue by twedu** [juewuy/ShellClash#420]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

用一段时间，更新内核啥的会不会占用内存，有没有办法定期清理一下？

**Comment by juewuy** [comment]
@twedu 定时重启
