### ISSUE TITLE
[Bug] 为什么git clone下来的文件足足有1.8GB啊

### ISSUE THREAD

**Issue by ikiwihome** [juewuy/ShellClash#421]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

[Bug] 为什么git clone下来的文件足足有1.8GB啊

**Comment by juewuy** [comment]
@ikiwihome 有历史版本内核等文件

**Comment by Sczlog** [comment]
可以加上 --depth=1 还有 --single-branch
