### ISSUE TITLE
请问如何卸载/重装？

### ISSUE THREAD

**Issue by isshe** [juewuy/ShellClash#422]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

疑似影响 SSH 访问，想要卸载重装之类的。

**Comment by juewuy** [comment]
@isshe clash -h

**Comment by isshe** [comment]
好，多谢。不过这个是由于和 oh-my-zsh 不兼容，导致我没找到 clash，进而导致没看到卸载选项。

**Comment by isshe** [comment]
如果是安装在 /etc/ 目录，命令如下：

```
export clashdir="/etc/clash"
bash /etc/clash/clash.sh
```
