### ISSUE TITLE
[Bug] cpu飙升的问题

### ISSUE THREAD

**Issue by wujiagg** [juewuy/ShellClash#424]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

    一、因为流控的原因，一直在使用爱快。网上所有的教程都是旁路由配合爱快科学使用。参考这个帖子https://www.right.com.cn/forum/thread-8180290-1-1.html可以登陆爱快的ssh，再使用大佬的shellclash脚本可以在爱快里直接使用clash，根本上改变爱快科学上网的方式。未提及但是需要注意的有2点，1、登陆用户名为sshd。2、docker镜像拉取不了，需要下载到本地后上传到爱快系统后开启。
    二、目前用这种方式使用时间超过1个月了。期间遇到的主要问题是shellclash在运行的2天内，爱快系统的cpu占用必定从原来的1-2%飙升到80%多。只能手动重启shellclash才能把cpu占用重新降下来，脚本带的自动重启不起作用。
    三、硬件J4125CPU。爱快版本3.7.2 x64 Build202304211807。shellclash版本1.7.0f，同时也尝试了1.7.9e。
1 启动/重启clash服务。会报这个提示：Another app is currently holding the xtables lock. Perhaps you want to use the -w option?
同时内存占用不断增加。
<img src="https://img1.imgtp.com/2023/06/24/JH0R6zFX.png" alt="屏幕截图 2023-06-24 201436.png" title="屏幕截图 2023-06-24 201436.png" />
<img src="https://img1.imgtp.com/2023/06/24/IPVn3pwx.png" alt="屏幕截图 2023-06-24 211414.png" title="屏幕截图 2023-06-24 211414.png" />
<img src="https://img1.imgtp.com/2023/06/24/occoBLnA.png" alt="屏幕截图 2023-06-24 211524.png" title="屏幕截图 2023-06-24 211524.png" />
麻请大佬有时间抽空看看

**Comment by juewuy** [comment]
Another app is currently holding the xtables lock. Perhaps you want to use the -w option?
这个报错一般只能重启设备解决，说明有其他应用在调用iptables并产生了冲突

至于占用高的问题需要配合面板日志及连接排查

**Comment by wujiagg** [comment]
1、不代理udp的情况下，不会有Another app is currently holding the xtables lock. Perhaps you want to use the -w option?
但是连接数还是会从正常的300-400变成上万
2、现有的选项一天最多只能重启一次，我想每12个小时重启一次试试，可以自定义重启时间吗？
3、贴上日志，大佬指点下
<img src="https://img1.imgtp.com/2023/06/28/P5LsphOJ.png" alt="屏幕截图 2023-06-28 195057.png" title="屏幕截图 2023-06-28 195057.png" />
<img src="https://img1.imgtp.com/2023/06/28/HA5cWwR1.png" alt="屏幕截图 2023-06-28 195236.png" title="屏幕截图 2023-06-28 195236.png" />
<img src="https://img1.imgtp.com/2023/06/28/8Hycy5PK.png" alt="屏幕截图 2023-06-28 195151.png" title="屏幕截图 2023-06-28 195151.png" />

**Comment by juewuy** [comment]
@0xMastermind 重启设备

**Comment by wujiagg** [comment]
不会玩，转openwrt了
