### ISSUE TITLE
[HELP WANTED] unraid系统安装shellclash，重启后没有clash命令

### ISSUE THREAD

**Issue by 77-arthur** [juewuy/ShellClash#425]
## 问题描述
unraid系统安装shellclash，安装后代理和面板都正常使用，不过重启后没有clash命令。

**Comment by juewuy** [comment]
未适配的系统，需要手动将这个初始化命令设置为开机启动：{安装目录}/start.sh init

**Comment by 1tsAll1nTheCard** [comment]
> 未适配的系统，需要手动将这个初始化命令设置为开机启动：{安装目录}/start.sh init

手动初始化后，程序在后台运行了，Crash命令还是无效，请问怎么调出shell控制面板

**Comment by juewuy** [comment]
@1tsAll1nTheCard source环境变量文件

**Comment by sincere-x** [comment]
> > 未适配的系统，需要手动将这个初始化命令设置为开机启动：{安装目录}/start.sh init
> 
> 手动初始化后，程序在后台运行了，Crash命令还是无效，请问怎么调出shell控制面板

兄弟 解决了吗
