### ISSUE TITLE
[HELP WANTED]磁力链（magnet）无法下载元数据

### ISSUE THREAD

**Issue by zzzshanghai** [juewuy/ShellClash#427]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

作者您好，我红米AX6000+shellclash，用的是最新版clash1.17.0内核，Tproxy+fakeip模式，用qbittorrent下载磁力链（magnet），无法下载元数据。请教如何配置才能解决这个问题。谢谢。

**Comment by juewuy** [comment]
@zzzshanghai 升级脚本

**Comment by zzzshanghai** [comment]
@juewuy 您好，脚本已升级至1.7.9f，只代理常用端口：未开启，屏蔽QUIC流量：已启用，其他设置未更改。关闭qbittorrent后重新打开，下载磁力链（magnet）还是无法下载元数据。

**Comment by zzzshanghai** [comment]
我的需求是：下载磁力链，外网被墙的tracker需要走代理，而bt/pt的流量走直连。实际使用中发现，http:// https:// 开头的tracker走代理没有问题，但是 udp:// 开头的tracker走代理无法连接（比如：udp://tracker.sbsub.com:2710/announce）。

**Comment by juewuy** [comment]
添加fakeip过滤或者更换DNS模式
