### ISSUE TITLE
[Bug] 使用管理界面(:9999)不停的跳到固定界面

### ISSUE THREAD

**Issue by bigpo** [juewuy/ShellClash#428]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

![image](https://github.com/juewuy/ShellClash/assets/9010202/ddf32420-3a07-4cf0-85df-2551803c06a1)

打开管理界面后，不停的跳到上图示的界面，请问是怎么回事儿呀

**Comment by juewuy** [comment]
@bigpo 原因很多，先尝试更换浏览器，或者下载里更换其他面板
