### ISSUE TITLE
[Bug] others.yaml自定义规则无法自动加载

### ISSUE THREAD

**Issue by xilaochengv** [juewuy/ShellClash#429]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

如题，根据6-6-6提示使用others.yaml添加其它自定义功能，添加完后没有自动加载。
start.sh代码里搜索others关键字也没搜到相关代码，请问是不是漏了写呢，谢谢

**Comment by juewuy** [comment]
https://github.com/juewuy/ShellClash/commit/cd49bd5067d4b054edeaf3320c3946f0193019d7
