### ISSUE TITLE
[Feature] 加入`tcp-concurrent`的开关

### ISSUE THREAD

**Issue by Karmylr** [juewuy/ShellClash#431]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

加入`tcp-concurrent`的开关

**Comment by juewuy** [comment]
https://github.com/juewuy/ShellClash/commit/cd49bd5067d4b054edeaf3320c3946f0193019d7
可以在user.yaml内自定义添加
