### ISSUE TITLE
[Bug] `user.yaml`内的内容无效

### ISSUE THREAD

**Issue by Karmylr** [juewuy/ShellClash#432]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

在`user.yaml`内写了`log-level: silent`，但是经过覆写的配置文件不会用`log-level: silent`替换掉默认的`log-level: info`，而是又加了一行`log-level: silent`。然后启动时就会报错`line 33: mapping key \"log-level\" already defined at line 7"`。

**Comment by juewuy** [comment]
@Karmylr 后续会优化

**Comment by juewuy** [comment]
https://github.com/juewuy/ShellClash/commit/cd49bd5067d4b054edeaf3320c3946f0193019d7
