### ISSUE TITLE
[Bug] iptables v1.8.3 (legacy): Couldn't load match `multiport':No such file or directory

### ISSUE THREAD

**Issue by jsf01** [juewuy/ShellClash#433]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

设备是ws1408 ,
固件是[LuCI openwrt-19.07 branch],
Linux armv7l

每次启动/重启clash,都提示：
-----------------------------------------------
iptables v1.8.3 (legacy): Couldn't load match `multiport':No such file or directory

Try `iptables -h' or 'iptables --help' for more information.
clash服务已启动！

**Comment by jsf01** [comment]
设备是ws1408 ,
固件是[LuCI openwrt-19.07 branch],
Linux armv7l

**Comment by juewuy** [comment]
@jsf01 iptables缺少部分依赖，尝试禁用只代理常用端口

**Comment by jsf01** [comment]
> @jsf01 iptables缺少部分依赖，尝试禁用只代理常用端口

谢谢，关闭 只代理常用端口后，报错没有了，可以正常使用了

**Comment by jsf01** [comment]
> @jsf01 iptables缺少部分依赖，尝试禁用只代理常用端口

请问缺少的是什么依赖，我该如何安装这些依赖？

**Comment by juewuy** [comment]
@jsf01 不同系统安装方式不同，请自行研究
