### ISSUE TITLE
[Bug] 纯净模式的小问题

### ISSUE THREAD

**Issue by nil-ca** [juewuy/ShellClash#435]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

R2S-OPENWRT原版
```
 1 切换Clash运行模式:   纯净模式
 2 切换DNS运行模式：    fake-ip
 3 跳过本地证书验证：   已开启   ————解决节点证书验证错误
 4 只代理常用端口：     已开启   ————用于过滤P2P流量
 5 过滤局域网设备：     未开启   ————使用黑/白名单进行过滤
 6 设置本机代理服务:    未开启   ————使本机流量经过clash内核
 7 屏蔽QUIC流量:        未开启   ————优化视频性能
 8 管理Fake-ip过滤列表
```
由于自己用fake-IP，写了条nftables到7890端口就可以用了，主要用shellclash来更新订阅。最近发现纯净模式下OPENWRT的iptables 会添加链导致局域网内部速度越来越低，每次重启clash都会加一条后面就变成这样。

![OZC_%MKPBMPFA~W0 E)D8IT](https://github.com/juewuy/ShellClash/assets/18211135/62bbeced-fc20-4bd0-8f32-2584b2dd4348)

重启一次就加一条，内网速度从800m到300m。问一下作者是不是在start.sh里面注释getlanip就可以了。

**Comment by juewuy** [comment]
@nil-ca 看起来是公网访问防火墙相关
