### ISSUE TITLE
安装失败[Bug] 

### ISSUE THREAD

**Issue by NathanDai** [juewuy/ShellClash#441]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

-----------------------------------------------
开始从服务器获取安装文件！
-----------------------------------------------
######################################################################################################### 100.0%
-----------------------------------------------
开始解压文件！
tar: clash.service：无法将所有权改为 uid 197609，gid 197609: 无效的参数
tar: clash.sh：无法将所有权改为 uid 197609，gid 197609: 无效的参数
tar: clashservice：无法将所有权改为 uid 197609，gid 197609: 无效的参数
tar: Country.mmdb：无法将所有权改为 uid 197609，gid 197609: 无效的参数
tar: getdate.sh：无法将所有权改为 uid 197609，gid 197609: 无效的参数
tar: init.sh：无法将所有权改为 uid 197609，gid 197609: 无效的参数
tar: misnap_init.sh：无法将所有权改为 uid 197609，gid 197609: 无效的参数
tar: servers.list：无法将所有权改为 uid 197609，gid 197609: 无效的参数
tar: start.sh：无法将所有权改为 uid 197609，gid 197609: 无效的参数
tar: 由于前次错误，将以上次的错误状态退出
tar (child): --no-same-owner：无法 open: 没有那个文件或目录
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
-----------------------------------------------
ShellClash 已经安装成功!

 OS: Debian GNU/Linux 10 (buster) x86_64

**Comment by juewuy** [comment]
@NathanDai 一般都是虚拟机权限问题
