### ISSUE TITLE
[Bug] GeoIP.dat无法读取

### ISSUE THREAD

**Issue by Toad-stool** [juewuy/ShellClash#442]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

配置文件已设置 geodata-mode: true

geosite.dat能正确读取，但IP貌似还是使用的country.mmdb（因为文件夹会生成country.mmdb并且面板查看规则里geoip规则为0）

![Screenshot_20230720011424](https://github.com/juewuy/ShellClash/assets/26811405/b48eeaa7-a5ac-46cd-81b1-df4600dc3b51)

**Comment by juewuy** [comment]
@Toad-stool 需要搭配相关规则使用

**Comment by Toad-stool** [comment]
> 

规则是写了的，例如
      - GEOSITE,telegram,PROXY
      - GEOIP,telegram,PROXY
但从主楼的截图看出来geosite有17条，但geoip为0，导致路由器下telegram无法正常联网，同样的配置手机使用clash meta for Android没有问题，telegram可以正常访问。

**Comment by juewuy** [comment]
@Toad-stool geoip本来就不会显示size，另外这应该是meta内核的问题，请去上游项目反馈
