### ISSUE TITLE
[Feature] 为"只代理常用端口"添加自定义端口功能

### ISSUE THREAD

**Issue by chuwza** [juewuy/ShellClash#443]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

有BT下载需求，所以开启了"只代理常用端口"功能，但是有些网站部署在特殊的非80、443等端口，且需要代理访问。这时候只能先把这个功能关掉、访问完再打开，很麻烦。

比如这个网站，是个下载站，一步步点击到最后会发现下载服务部署在183端口，且需要代理访问（https://userupload.net/0xjicjwbjutz）

所以希望增加端口自定义，好把目前尚不包含于默认常用范围内的端口添加进去
![Screenshot_20230722-205935_Chrome](https://github.com/juewuy/ShellClash/assets/30049891/c62e2b32-1079-4427-b58e-c3011f15d0eb)

**Comment by juewuy** [comment]
@chuwza 一直都支持

**Comment by chuwza** [comment]
> @chuwza 一直都支持

能说一下如何使用吗？一选择开启，就自动开启了，并且提示一连串端口，没有自定义端口的那一步

**Comment by juewuy** [comment]
@chuwza 6-6

**Comment by chuwza** [comment]
> @chuwza 6-6

非常感谢！
