### ISSUE TITLE
[Feature] Meta核以外的核心太旧了

### ISSUE THREAD

**Issue by 1779587460** [juewuy/ShellClash#444]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

建议把能支持的clash核和p核都更新了，自己上传的新核能识别版本但不能启动核

**Comment by juewuy** [comment]
@1779587460 其他内核里有测试版

**Comment by 1779587460** [comment]
@juewuy 换Meta时wget卡100%了😫😫，试了几次都没用，手动上传启动会出错，现在不方便截日志

**Comment by juewuy** [comment]
@1779587460 应该是设备存储空间不足

**Comment by 1779587460** [comment]
还是更新下另外两个核吧，clash在1.15前有路径穿越的漏洞。🥰

**Comment by juewuy** [comment]
@1779587460 普核没有更新必要，有需求可以使用pre或者meta内核

**Comment by 1779587460** [comment]
@juewuy p核也不是新的，四月多才修复路径穿越漏洞的😨

**Comment by 1779587460** [comment]
@juewuy 用非自定义源的话pre核是在https://github.com/juewuy/ShellClash/tree/master/bin/clashpre
这边更新的，是七个月前的版本😭建议同步下clash项目那边的pre发布版

**Comment by juewuy** [comment]
@1779587460 https://github.com/juewuy/ShellClash/releases/tag/clash.premium.latest

**Comment by 1779587460** [comment]
@juewuy 哈哈，我用公测私人源那个下载到是2022年的😓是源的问题吗

**Comment by 1779587460** [comment]
![image](https://github.com/juewuy/ShellClash/assets/57093174/011b321d-8705-4255-ac3d-67feb767ce00)
附个刚更新的图片

**Comment by juewuy** [comment]
@1779587460 自定义内核里

**Comment by 1779587460** [comment]
@juewuy 自定义内核貌似不支持小内存模式吧？T-T
