### ISSUE TITLE
问一下shellclash 支持rule-provider、 proxy-provider  么

### ISSUE THREAD

**Issue by loveu5522** [juewuy/ShellClash#446]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

问一下shellclash 支持rule-provider、 proxy-provider  么

**Comment by juewuy** [comment]
@loveu5522 6-6

**Comment by loveu5522** [comment]
啥意思呀

**Comment by zjz894251se** [comment]
跟shellclash没关系，跟用的clash内核有关系

**Comment by loveu5522** [comment]
> 跟shellclash没关系，跟用的clash内核有关系

原来如此，那应该是支持的
