### ISSUE TITLE
[Feature] 技术请教，带的内核为什么比原仓库release版本小很多？

### ISSUE THREAD

**Issue by zjz894251se** [juewuy/ShellClash#450]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

发现原仓库的库release版本都很大，这工程里面自带的为什么这么小啊，是怎么编译出来的啊？有知道的朋友吗？请教一下
例如：
[Clash.Meta](https://github.com/MetaCubeX/Clash.Meta) v1.15.0 armv8
官方的gz压缩包都10M了，解压完都27M了，这里面自带的怎么才8M？这是什么黑科技啊 ？求赐教，谢谢！

**Comment by juewuy** [comment]
@zjz894251se upx

**Comment by zjz894251se** [comment]
> @zjz894251se upx

多谢赐教，get 新知识。
