### ISSUE TITLE
[Feature] 通过url更新配置文件

### ISSUE THREAD

**Issue by lawxen** [juewuy/ShellClash#451]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

需求场景：
配制好路由器后，但是配置者外出，第三方配置文件更新导致无法访问，如何教在家的其他人更新配置文件是个大问题，如果有个链接可以更新就会非常方便。  
<img width="584" alt="image" src="https://github.com/juewuy/ShellClash/assets/20714821/eeb10409-f4f0-43db-9602-e2c3c7297e5a">

**Comment by juewuy** [comment]
@lawxen 可以使用公网访问ssh功能
