### ISSUE TITLE
[Bug]  1.7.10b测试版升级后导致容器无法代理。

### ISSUE THREAD

**Issue by WilsonVincent** [juewuy/ShellClash#453]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

执行升级后。不修改任何配置的情况下。提示：
iptables v1.8.7 (nf_tables): host/network `metric' not found
回到公测版恢复正常。
安装系统：Ubuntu 22.04.2 LTS
版本号：1.7.10b测试版
问题：无法代理dockers容器。每一次重启都会提示。

**Comment by juewuy** [comment]
@WilsonVincent 8-1-4发一下

**Comment by WilsonVincent** [comment]
-----------------------------------------------
 1 查看Clash运行时的报错信息(会停止clash服务)
 2 查看系统DNS端口(:53)占用 
 3 测试ssl加密(aes-128-gcm)跑分
 4 查看clash相关路由规则
 5 查看config.yaml前40行
 6 测试代理服务器连通性(google.tw)
-----------------------------------------------
 0 返回上级目录！
请输入对应数字 > 4
-------------------Redir---------------------
Chain PREROUTING (policy ACCEPT)
num  target     prot opt source               destination         
1    DOCKER     all  --  anywhere             anywhere             ADDRTYPE match dst-type LOCAL
2    clash_docker  tcp  --  172.16.0.0/12        anywhere            
3    REDIRECT   udp  --  172.16.0.0/12        anywhere             udp dpt:domain redir ports 1053iptables v1.8.7 (nf_tables): chain `clash_dns' in table `nat' is incompatible, use 'nft' tool.

iptables v1.8.7 (nf_tables): chain `clash' in table `nat' is incompatible, use 'nft' tool.

----------------OUTPUT-------------------
Chain OUTPUT (policy ACCEPT)
num  target     prot opt source               destination         
1    DOCKER     all  --  anywhere            !127.0.0.0/8          ADDRTYPE match dst-type LOCAL
2    clash_out  tcp  --  anywhere             anywhere            
3    clash_dns_out  udp  --  anywhere             anywhere             udp dpt:domain
Chain clash_out (1 references)
num  target     prot opt source               destination         
1    RETURN     all  --  anywhere             anywhere             owner GID match shellclash
2    RETURN     all  --  anywhere             172.22.0.1          
3    RETURN     all  --  anywhere             0.0.0.0/8           
4    RETURN     all  --  anywhere             10.0.0.0/8          
5    RETURN     all  --  anywhere             127.0.0.0/8         
6    RETURN     all  --  anywhere             100.64.0.0/10       
7    RETURN     all  --  anywhere             169.254.0.0/16      
8    RETURN     all  --  anywhere             172.16.0.0/12       
9    RETURN     all  --  anywhere             192.168.0.0/16      
10   RETURN     all  --  anywhere             base-address.mcast.net/4 
11   RETURN     all  --  anywhere             240.0.0.0/4         
12   REDIRECT   tcp  --  127.0.0.0/8          anywhere             redir ports 7892
13   REDIRECT   tcp  --  172.22.0.1           anywhere             redir ports 7892

**Comment by WilsonVincent** [comment]
使用：nftables增强模式docker无法走代理（可能是我不会配置）。
使用：iptables增强模式docker可以走代理（不需要配置）但是会报这个错误。iptables v1.8.7 (nf_tables): host/network `metric' not found。

**Comment by juewuy** [comment]
@WilsonVincent docker网卡要设成桥接模式

**Comment by juewuy** [comment]
@WilsonVincent 这个报错问题不大可以无视

**Comment by WilsonVincent** [comment]
> @WilsonVincent 这个报错问题不大可以无视

下一个版本会进行修复吗？

**Comment by WilsonVincent** [comment]
> @WilsonVincent 这个报错问题不大可以无视

一直都是桥接模式。但是我用这个模式下我没看见这个172.22.0.1/64。

table inet shellclash {
        chain dns_out {
                type nat hook output priority -100; policy accept;
                meta skgid 7890 return
                udp dport 53 redirect to :1053
        }

        chain output {
                type nat hook output priority -100; policy accept;
                meta skgid 7890 return
                ip daddr { 0.0.0.0/8, 10.0.0.0/8, 100.64.0.0/10, 127.0.0.0/8, 169.254.0.0/16, 172.16.0.0/12, 192.168.0.0/16, 224.0.0.0-255.255.255.255 } return
                meta l4proto tcp meta mark set 0x00001ed4 redirect to :7892
        }
}

**Comment by juewuy** [comment]
已修复

**Comment by WilsonVincent** [comment]
@juewuy 
欢迎使用ShellClash！            版本：1.7.10e
Clash服务正在运行（纯净模式），已设置开机启动！
当前内存占用：47568 kB，已运行：00小时00分48秒
TG频道：https://t.me/ShellClash
-----------------------------------------------
 1 启动/重启clash服务
 2 clash功能设置
 3 停止clash服务
 4 clash启动设置
 5 设置定时任务
 6 导入配置文件
 7 clash进阶设置
 8 其他工具
 9 更新/卸载
-----------------------------------------------
 0 退出脚本
请输入对应数字 > 1
-----------------------------------------------
Killed
iptables v1.8.7 (nf_tables): host/network `metric' not found
Try `iptables -h' or 'iptables --help' for more information.
clash服务已启动！

**Comment by juewuy** [comment]
@WilsonVincent 用nft增强模式，并且升级到最新版

**Comment by WilsonVincent** [comment]
> @WilsonVincent 用nft增强模式，并且升级到最新版

@juewuy 已尝试，确实可以了。谢谢提供的技术支持。辛苦看一下另外两个问题？
#459 #458

**Comment by WilsonVincent** [comment]
@juewuy 

这个报错信息是不是指向的这个东西？为什么会自动添加这个网段？

`欢迎使用ShellClash！            版本：1.7.10e
Clash服务正在运行（纯净模式），已设置开机启动！
当前内存占用：57168 kB，已运行：00小时00分03秒
TG频道：https://t.me/ShellClash
-----------------------------------------------
 1 启动/重启clash服务
 2 clash功能设置
 3 停止clash服务
 4 clash启动设置
 5 设置定时任务
 6 导入配置文件
 7 clash进阶设置
 8 其他工具
 9 更新/卸载
-----------------------------------------------
 0 退出脚本
请输入对应数字 > 7
-----------------------------------------------
欢迎使用进阶模式菜单：
如您并不了解clash的运行机制，请勿更改本页面功能！
-----------------------------------------------
 1 ipv6相关
 3 配置公网及局域网防火墙
 4 启用域名嗅探:        已启用  ————用于流媒体及防DNS污染
 5 启用节点绕过:        未启用  ————用于防止多设备多重流量
 6 配置内置DNS服务
-----------------------------------------------
 9 重置/备份/还原脚本设置
 0 返回上级菜单 
-----------------------------------------------
请输入对应数字 > 3
-----------------------------------------------
 1 公网访问Dashboard面板:       已开启
 2 公网访问Socks/Http代理:      已开启
 3 自定义透明路由ipv4网段:      适合vlan等复杂网络环境
-----------------------------------------------
请输入对应数字 > 3
-----------------------------------------------
当前已自动设置透明路由的网段为: 172.24.95.32/20 metric 100  172.22.0.1/24  172.17.0.1/16   
当前已添加的自定义网段为:`

**Comment by WilsonVincent** [comment]
```
root@vincent:~# netstat -r -anv
Kernel IP routing table
Destination     Gateway         Genmask         Flags   MSS Window  irtt Iface
0.0.0.0         172.24.95.253   0.0.0.0         UG        0 0          0 eth0
100.100.2.136   172.24.95.253   255.255.255.255 UGH       0 0          0 eth0
100.100.2.138   172.24.95.253   255.255.255.255 UGH       0 0          0 eth0
172.17.0.0      0.0.0.0         255.255.0.0     U         0 0          0 docker0
172.22.0.0      0.0.0.0         255.255.255.0   U         0 0          0 br-1b61d62fb5b2
172.24.80.0     0.0.0.0         255.255.240.0   U         0 0          0 eth0
172.24.95.253   0.0.0.0         255.255.255.255 UH        0 0          0 eth0
```

**Comment by juewuy** [comment]
@WilsonVincent 正常应该切掉的，你这个我也不清楚，可能是bug

**Comment by WilsonVincent** [comment]
> @WilsonVincent 正常应该切掉的，你这个我也不清楚，可能是bug
@juewuy 
有什么办法可以将：当前已自动设置透明路由的网段为: 172.24.95.32/20 metric 100  172.22.0.1/24  172.17.0.1/16
中的metric 100 给去除？

**Comment by WilsonVincent** [comment]
> @WilsonVincent 正常应该切掉的，你这个我也不清楚，可能是bug

测试了几次后发现，开启保守模式就会出现，关闭保守模式就解决了。

**Comment by juewuy** [comment]
https://github.com/juewuy/ShellClash/commit/11152e89476ec3c76d716ffa8d3293937ebd6bfc

**Comment by juewuy** [comment]
> > @WilsonVincent 正常应该切掉的，你这个我也不清楚，可能是bug
> 
> @juewuy 有什么办法可以将：当前已自动设置透明路由的网段为: 172.24.95.32/20 metric 100 172.22.0.1/24 172.17.0.1/16 中的metric 100 给去除？
> 
> 使用另外一个增强模式会持续性把我一个不需要走互联网只需要容器之间交互信息的容器一起代理进去。这样导致两个容器之间的链接变缓慢了。

https://github.com/juewuy/ShellClash/commit/11152e89476ec3c76d716ffa8d3293937ebd6bfc

**Comment by WilsonVincent** [comment]
@juewuy 好的，升级后没有出现这个问题了。谢谢提供的技术支持。辛苦。
