### ISSUE TITLE
[Bug] Ubuntu 22.04.2 LTS 版本：1.7.10e 读取剩余空间报错。

### ISSUE THREAD

**Issue by WilsonVincent** [juewuy/ShellClash#461]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

安装在/etc/clash也一样。

```

当前目录(/usr/share/clash)剩余空间：
/usr/share/clash/getdate.sh: 第 1277 行： [: : 需要整数表达式
-----------------------------------------------
 1 更新管理脚本         1.7.10e > 1.7.10e测试版
 2 切换clash核心        v1.15.0 > v1.15.0
 3 更新GeoIP/CN-IP      20230729 > 20230729
 4 安装本地Dashboard面板
 5 安装/更新本地根证书文件
 6 查看PAC自动代理配置

```

**Comment by juewuy** [comment]
未复现
请手动执行：
`df -h $clashdir |awk '{ for(i=1;i<=NF;i++){ if(NR==1){ arr[i]=$i; }else{ arr[i]=arr[i]" "$i; } } } END{ for(i=1;i<=NF;i++){ print arr[i]; } }' |grep Ava |awk '{print $2}'`

**Comment by WilsonVincent** [comment]
@juewuy 执行这行命令并未得到任何结果。
![image](https://github.com/juewuy/ShellClash/assets/60778141/15a82aba-e0d2-484f-9810-727db13dd264)

**Comment by juewuy** [comment]
@WilsonVincent df -h $clashdir呢？

**Comment by WilsonVincent** [comment]
@juewuy 

```
root@vincent:~# df -h $clashdir呢？
df: 呢？: 没有那个文件或目录
root@vincent:~# 
```

**Comment by juewuy** [comment]
@WilsonVincent 所以为什么你安装时没写入环境变量？

**Comment by WilsonVincent** [comment]
@juewuy 我是使用的是指导文档中的一键安装。而且是root权限。没有修改其他的东西。这是需要写入什么权限？或者需要执行什么补全环境？

**Comment by juewuy** [comment]
@WilsonVincent 参考https://github.com/juewuy/ShellClash/blob/master/README_CN.md
覆盖安装即可

**Comment by WilsonVincent** [comment]
![image](https://github.com/juewuy/ShellClash/assets/60778141/db759aee-b37a-4037-ac3c-2a93480551f4)

@juewuy 我直接卸载重装都好像不行。

**Comment by juewuy** [comment]
@WilsonVincent 不对啊，你为什么要复制“呢？”

**Comment by WilsonVincent** [comment]
@juewuy 大意了，不好意思。
![image](https://github.com/juewuy/ShellClash/assets/60778141/0ed26bd7-c180-493e-95ce-4eafbd58ad91)

**Comment by juewuy** [comment]
@WilsonVincent 说明环境变量还是没有配置成功，你可以手动添加到/etc/profile

**Comment by WilsonVincent** [comment]
@juewuy 将什么文件添加到/etc/profile？

**Comment by juewuy** [comment]
@WilsonVincent 参考https://github.com/juewuy/ShellClash/blob/master/scripts/init.sh#L190-L194

**Comment by WilsonVincent** [comment]
@juewuy 变量应该没有问题吧。我逐步拆解得到以下输出结果：

```
root@vincent:~# df -h $clashdir
文件系统        大小  已用  可用 已用% 挂载点
/dev/sda2       117G   28G   83G   25% /
root@vincent:~# df -h $clashdir | awk '{ for(i=1;i<=NF;i++){ if(NR==1){ arr[i]=$i; }else{ arr[i]=arr[i]" "$i; } } } END{ for(i=1;i<=NF;i++){ print arr[i]; } }'
文件系统 /dev/sda2
大小 117G
已用 28G
可用 83G
已用% 25%
挂载点 /
root@vincent:~# df -h $clashdir | awk '/Ava/ {print $2}'
```
无结果
```
df -h $clashdir | awk '/Ava/ {print $2}'
```

**Comment by WilsonVincent** [comment]
@juewuy 

```
root@vincent:~# df -h $clashdir | awk '/\/dev\/sda2/ {print $4}'
83G
```

**Comment by juewuy** [comment]
@WilsonVincent 什么神仙版本，还显示中文🙈

**Comment by WilsonVincent** [comment]
@juewuy 别骂了别骂了~

```
df -h . | awk 'NR==2 {print $4}'
```
可以尝试一下这个？
两个环境获取当前文件夹所在的磁盘剩余容量没有问题。

**Comment by juewuy** [comment]
@WilsonVincent 不用怀疑，这个我用过很多设备都不行

**Comment by WilsonVincent** [comment]
@juewuy 那我这个问题应该如何解决呢？环境变量应该是没问题的。

**Comment by juewuy** [comment]
@WilsonVincent 后续我会尝试修复

**Comment by WilsonVincent** [comment]
@juewuy 好的。谢谢。🤣特色中文版~

**Comment by WilsonVincent** [comment]
@juewuy g版本成功获取，谢谢大佬的技术支持。
