### ISSUE TITLE
[Bug] Ubuntu 22.04.2 LTS 版本：1.7.10e 无法读取进程名称。

### ISSUE THREAD

**Issue by WilsonVincent** [juewuy/ShellClash#462]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

![image](https://github.com/juewuy/ShellClash/assets/60778141/b9dcedb7-2254-4f56-a16d-da2a43682124)

**Comment by juewuy** [comment]
https://github.com/juewuy/ShellClash/commit/11152e89476ec3c76d716ffa8d3293937ebd6bfc
现在纯净模式会保留此功能

**Comment by WilsonVincent** [comment]
@juewuy  进程问题在两台Ubuntu中的纯净模式均已经恢复。嗅探域名好像是异常的。
两台电脑中，功能都是开启的，差不多每台电脑测了一下，200条链接中的嗅探域名全部是空的。

```
 1 ipv6相关
 3 配置公网及局域网防火墙
 4 启用域名嗅探:        已启用  ————用于流媒体及防DNS污染
 5 启用节点绕过:        未启用  ————用于防止多设备多重流量
 6 配置内置DNS服务

```

**Comment by juewuy** [comment]
@WilsonVincent 可能和你使用了user.yaml自定义配置有关

**Comment by WilsonVincent** [comment]
@juewuy 我去配置里了加一个嗅探开关也不行。

**Comment by juewuy** [comment]
@WilsonVincent 那就是内核问题了

**Comment by WilsonVincent** [comment]
@juewuy 

而且如果使用user.yaml还必须手动关闭7-4

**Comment by juewuy** [comment]
@WilsonVincent 这功能很久没改动过了，孤例不证，没有其他用户报告过类似问题

**Comment by WilsonVincent** [comment]
@juewuy 

![image](https://github.com/juewuy/ShellClash/assets/60778141/c7795e64-902c-4099-8ac1-53fa6adb81d0)

**Comment by juewuy** [comment]
@WilsonVincent 没看出来哪有问题

**Comment by WilsonVincent** [comment]
@juewuy 

正常上一个版本是嗅探：jd.com

**Comment by juewuy** [comment]
@WilsonVincent 嗅探只针对纯IP

**Comment by WilsonVincent** [comment]
@juewuy 好吧，可能是我理解错误了。
