### ISSUE TITLE
[Bug] 小米路由器上重新启动clash时候会出现iptables v1.6.2: Couldn't load target `clash':No such file or directory

### ISSUE THREAD

**Issue by TonyLiooo** [juewuy/ShellClash#465]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

![image](https://github.com/juewuy/ShellClash/assets/64239067/eb8c6964-f12c-4799-885a-02a78a71b0ed)

**Comment by juewuy** [comment]
重启设备
