### ISSUE TITLE
[Bug] 1.7.10g 默认不代理常用端口模式下，无法正常访问某些网址，比如epg.51zmt.top:8000

### ISSUE THREAD

**Issue by iceyheart** [juewuy/ShellClash#467]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

目前使用中发现的从前没有，现在存在的问题
1、比如epg.51zmt.top:8000无法打开
2、同花顺无法访问登录服务器

**Comment by juewuy** [comment]
@iceyheart 未能复现，请提供相关面板日志

**Comment by iceyheart** [comment]
补充，tun+fakeip模式。tproxy+redir_host正常。面板日志没有体现访问，比如请求epg.51zmt.top:8000的时候，网页打不开，日志里也没请求

**Comment by juewuy** [comment]
@iceyheart 没请求说明绕过cnip生效了，没进内核和clash关系应该不大

**Comment by iceyheart** [comment]
TUN模式不存在绕过cnip吧

**Comment by iceyheart** [comment]
这个问题是从升级1.7.10测试版后才开始出现

**Comment by juewuy** [comment]
@iceyheart 你可以关闭绕过cn再试
