### ISSUE TITLE
1.4.1版本电视版本看netflix问题

### ISSUE THREAD

**Issue by hubin23** [juewuy/ShellClash#47]
看您的版本更新介绍写了解决奈飞TV问题，现在情况是还是得用 fake-ip模式，电视端奈飞才能看，不然还是报NW-4-8，用其它模式的话，网游便进不去，请问如何解决，谢谢

**Comment by hubin23** [comment]
还有个问题，使用fake-ip模式，手机端农行APP无法跳转登录

**Comment by juewuy** [comment]
dns解锁的机场只能使用fakeip
只有原生机场才能使用redirhost

**Comment by hubin23** [comment]
我用的机场是魅影，他们号称是原生节点呀  T_T。。。

**Comment by juewuy** [comment]
这我就不清楚了，目前大家还没报告过1.4.1原生节点无法观看的问题
