### ISSUE TITLE
[Feature] 希望推送新增Server酱渠道

### ISSUE THREAD

**Issue by KarlLee830** [juewuy/ShellClash#471]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

现有的推送通道在安卓平台都无法做到较好的体验，故希望推送新增Server酱渠道。
Server酱有关地址：https://sct.ftqq.com/

**Comment by juewuy** [comment]
@KarlLee830 PushDeer就是Server酱开发的通道，并且没有次数限制

**Comment by KarlLee830** [comment]
> @KarlLee830 PushDeer就是Server酱开发的通道，并且没有次数限制

@juewuy PushDeer主要的问题是没法推到微信、钉钉等通道，在安卓端只能推送至App或者快应用。但前者（App）目前已不支持MiPush或Google Cloud Messaging等推送服务，必须要常驻后台，后者（快应用）需要自行上架，但需要企业资质。
总而言之PushDeer在安卓平台的体验难言优秀，所以希望支持Server酱推送。

**Comment by juewuy** [comment]
@KarlLee830 由于免费版每日限额只有5条，不会考虑适配
