### ISSUE TITLE
[Bug] RedmiAX6000拨号上网后，shellclash监听异常

### ISSUE THREAD

**Issue by damoncui1993** [juewuy/ShellClash#472]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

之前是光猫拨号，AX6000级联，当时运行ShellClash没出现过任何问题，
近期搞公网IP，于是光猫做了桥接，路由器做拨号上网，不多久上不了外网，重启ShellClash后就可以了，但过一会又不行。
使用netstat -anpt|grep clash观察异常状态下clash状态，发现程序并没有crash，但是只有监听但无任何链接，
tcp        0      0 :::9999                 :::*                    LISTEN       0 0 3635/clash
tcp        0      0 :::7890                 :::*                    LISTEN       0 0 3635/clash
tcp        0      0 :::7892                 :::*                    LISTEN       0 0 3635/clash
tcp        0      0 :::7893                 :::*                    LISTEN       0 0 3635/clash

重启后恢复正常，
root@XiaoQiang:~# netstat -anpt|grep clash
tcp        0      1 123.118.12.63:29191     60.249.2.245:4003       SYN_SENT     0 0 3635/clash
tcp        0      0 123.118.12.63:2629      149.50.71.26:4003       ESTABLISHED  0 0 3635/clash
tcp        0      1 123.118.12.63:29127     60.249.2.245:4003       SYN_SENT     0 0 3635/clash
tcp        0      0 123.118.12.63:53037     149.50.69.200:4003      ESTABLISHED  0 0 3635/clash
tcp        0      0 123.118.12.63:57717     60.248.225.114:4003     ESTABLISHED  0 0 3635/clash
tcp        0      0 123.118.12.63:35447     61.135.179.241:443      ESTABLISHED  0 0 3635/clash
tcp        0      0 :::9999                 :::*                    LISTEN       0 0 3635/clash
tcp        0      0 :::7890                 :::*                    LISTEN       0 0 3635/clash
tcp        0      0 :::7892                 :::*                    LISTEN       0 0 3635/clash
tcp        0      0 :::7893                 :::*                    LISTEN       0 0 3635/clash
tcp        0      0 ::ffff:192.168.31.1:7892 ::ffff:192.168.31.200:54163 ESTABLISHED  0 0 3635/clash

但持续不了太久又不行了，当前版本已更新到最新，请问这种情况怎么处理？

**Comment by juewuy** [comment]
@damoncui1993 拨号会重置iptables，出现这种问题说明你运营商宽带不稳定，建议不要在路由上拨号

**Comment by damoncui1993** [comment]
> @damoncui1993 拨号会重置iptables，出现这种问题说明你运营商宽带不稳定，建议不要在路由上拨号

感谢回复，您意思是PPPOE拨号每过一段时间都需要获取运营商给的新IP地址从而导致IPtables失效对吗？运营商不稳定是说频繁的换IP导致IPtable被刷？
这和路由器无关对吗？
我可以在路由器里面写个脚本监控监听状态，异常就重启clash服务。

**Comment by juewuy** [comment]
@damoncui1993 是的
