### ISSUE TITLE
[Feature] 是否可支持 wireguard proxy

### ISSUE THREAD

**Issue by mumaxiaozi** [juewuy/ShellClash#473]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

error msg="initial proxy provider warp+ error: proxy 0 error: unsupport proxy type: wireguard"
自定义配置文件校验失败！将使用基础配置文件启动！

配置参考：
proxies:
  - name: Warp+0
    server: x.y.z.t
    port: 854
    type: wireguard
    ip: a.b.c.d
    private-key: 6J1K0LMTlqAQQcj13uajtMQyqqudkCr8TG+Gdpy/PMEI=
    public-key: bmXOC+F1FxEM120dyiK2H5/1SU1uH0JuVo51h2wPfgyo=
    udp: true

**Comment by juewuy** [comment]
@mumaxiaozi 更换meta内核
