### ISSUE TITLE
[Feature] 有考虑增加支持reality协议的支持吗

### ISSUE THREAD

**Issue by podradio** [juewuy/ShellClash#474]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

最近新出的reality协议有考虑支持吗

**Comment by juewuy** [comment]
@podradio meta内核支持

**Comment by podradio** [comment]
👍👍👍

**Comment by podradio** [comment]
我在加载 配置文件的时候遇到一个报错，不知道是否是配置问题，还是需要支持兼容的问题
配置文件加载失败！请查看报错信息！
INFO[0000] Start initial configuration in progress
ERRO[0000] proxy 0: unsupported xtls flow type: xtls-rprx-vision
configuration file /tmp/clash_config_root.yaml test failed

**Comment by podradio** [comment]
上面使用的是VLESS+reality+uTLS+Vision配置，如果用VLESS+reality+uTLS+gRPC则可以解析成功，加载配置后无法上外网，测速也是失败

**Comment by podradio** [comment]
-----------------------------------------------
当前clash核心： clash.meta v1.13.2
当前系统处理器架构： armv8

使用的 clash 核心版本

**Comment by juewuy** [comment]
@podradio 换公测源升级内核

**Comment by podradio** [comment]
非常感谢，升级到以下核心以后问题解决，非常棒～🌹🌹

当前clash核心： clash.meta v1.15.0
当前系统处理器架构： armv8
