### ISSUE TITLE
旁路网关模式下b站app的直播无法播放

### ISSUE THREAD

**Issue by darkliang** [juewuy/ShellClash#476]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

在使用b站app的时候，无法播放直播内容，一直显示加载中。

**Comment by juewuy** [comment]
关闭ipv6
如果未使用ipv6，请提供相关面板访问日志

**Comment by darkliang** [comment]
确实开了ipv6，有什么办法能同时用ipv6吗

**Comment by juewuy** [comment]
@darkliang 你可以自行查找旁路由兼容ipv6的办法
