### ISSUE TITLE
[Bug] Armbian作为旁路网关时，无法访问上级路由，同时开启CN_IP时无法访问CN_IP

### ISSUE THREAD

**Issue by deepjia** [juewuy/ShellClash#477]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

Armbian设备作为旁路网关运行ShellClash
ShellClash未开启IPv6、使用Tproxy混合+redir_host
终端设备的网关和DNS指向该Armbian设备
此时：
1、终端设备无妨访问主路由的上级路由
2、开启CN_IP时，终端设备无法访问在CN_IP范围内的地址

**Comment by juewuy** [comment]
@deepjia 旁路由不支持ipv6

**Comment by deepjia** [comment]
> @deepjia 旁路由不支持ipv6

未开启IPv6

**Comment by juewuy** [comment]
@deepjia 可能是未开启ipv4转发

**Comment by deepjia** [comment]
> @deepjia 可能是未开启ipv4转发

核实了一下，ipv4转发也是开启的，有点没头绪
```
root@arm-64:~# sysctl net.ipv6.conf.all.disable_ipv6
net.ipv6.conf.all.disable_ipv6 = 1
root@arm-64:~# sysctl net.ipv4.ip_forward
net.ipv4.ip_forward = 1
```
