### ISSUE TITLE
[Bug] 不断的自动重启Clash服务。

### ISSUE THREAD

**Issue by 13810169** [juewuy/ShellClash#478]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

我是用lxc的alpine安装的shellclash，只能使用保守模式，使用中发现会断网，就去看了下日志，发现clash服务在不断的重启。也看不出来具体问题在哪里。先使用的公测版，发现这个问题后换到稳定版，还是出现同样的问题。

**这是8-3-1的日志**

2023-08-25_19:02:35~Clash服务即将关闭……
2023-08-25_19:02:43~Clash服务已启动！
2023-08-25_19:06:00~Clash服务即将关闭……
2023-08-25_19:06:08~Clash服务已启动！
2023-08-25_19:11:00~Clash服务即将关闭……
2023-08-25_19:11:08~Clash服务已启动！
2023-08-25_19:14:00~Clash服务即将关闭……
2023-08-25_19:14:08~Clash服务已启动！
2023-08-25_19:16:39~Clash服务即将关闭……
2023-08-25_19:17:23~Clash服务已启动！
2023-08-25_19:30:00~Clash服务即将关闭……
2023-08-25_19:30:08~Clash服务已启动！
2023-08-25_19:36:25~Clash服务即将关闭……
2023-08-25_19:36:34~Clash服务已启动！
2023-08-25_19:36:50~Clash服务即将关闭……
2023-08-25_19:36:50~Clash服务即将关闭……
2023-08-25_19:38:08~Clash服务已启动！

**这是8-1-1的日志**

INFO[2023-08-25T19:43:57.058920302+08:00] Start initial configuration in progress      
INFO[2023-08-25T19:43:57.065511164+08:00] Geodata Loader mode: memconservative         
INFO[2023-08-25T19:43:57.608530451+08:00] Start initial GeoSite rule CN => 🎯 全球直连, records: 65951 
INFO[2023-08-25T19:43:57.609348997+08:00] Initial configuration complete, total time: 550ms 
configuration file /tmp/ShellClash/config.yaml test is successful
测试通过！

**Comment by juewuy** [comment]
@13810169 看面板日志有无异常

**Comment by 13810169** [comment]
好家伙 看着面板日志等了20分钟，终于等到了。
貌似是出现这个东西就会服务重启。192.168.1.247是我安装shellclash的ip地址。
3-08-25 20:26:35[ info ][TCP] 192.168.1.247:42712 --> 192.168.1.247:7893 match IPCIDR(192.168.0.0/16) using 🎯 全球直连[DIRECT]
23-08-25 20:26:35[ info ][TCP] 192.168.1.247:42718 --> 192.168.1.247:7893 match IPCIDR(192.168.0.0/16) using 🎯 全球直连[DIRECT]
23-08-25 20:26:35[ info ][TCP] 192.168.1.247:42686 --> 192.168.1.247:7893 match IPCIDR(192.168.0.0/16) using 🎯 全球直连[DIRECT]
23-08-25 20:26:35[ info ][TCP] 192.168.1.247:42694 --> 192.168.1.247:7893 match IPCIDR(192.168.0.0/16) using 🎯 全球直连[DIRECT]
23-08-25 20:26:35[ info ][TCP] 192.168.1.247:42672 --> 192.168.1.247:7893 match IPCIDR(192.168.0.0/16) using 🎯 全球直连[DIRECT]
23-08-25 20:26:35[ info ][TCP] 192.168.1.247:42668 --> 192.168.1.247:7893 match IPCIDR(192.168.0.0/16) using 🎯 全球直连[DIRECT]
23-08-25 20:26:35[ info ][TCP] 192.168.1.247:42660 --> 192.168.1.247:7893 match IPCIDR(192.168.0.0/16) using 🎯 全球直连[DIRECT]
23-08-25 20:26:35[ info ][TCP] 192.168.1.247:42630 --> 192.168.1.247:7893 match IPCIDR(192.168.0.0/16) using 🎯 全球直连[DIRECT]
23-08-25 20:26:35[ info ][TCP] 192.168.1.247:42632 --> 192.168.1.247:7893 match IPCIDR(192.168.0.0/16) using 🎯 全球直连[DIRECT]
23-08-25 20:26:35[ info ][TCP] 192.168.1.247:42644 --> 192.168.1.247:7893 match IPCIDR(192.168.0.0/16) using 🎯 全球直连[DIRECT]
23-08-25 20:26:35[ info ][TCP] 192.168.1.247:42600 --> 192.168.1.247:7893 match IPCIDR(192.168.0.0/16) using 🎯 全球直连[DIRECT]
23-08-25 20:26:35[ info ][TCP] 192.168.1.247:42616 --> 192.168.1.247:7893 match IPCIDR(192.168.0.0/16) using 🎯 全球直连[DIRECT]
23-08-25 20:26:35[ info ][TCP] 192.168.1.247:42582 --> 192.168.1.247:7893 match IPCIDR(192.168.0.0/16) using 🎯 全球直连[DIRECT]
23-08-25 20:26:35[ info ][TCP] 192.168.1.247:42588 --> 192.168.1.247:7893 match IPCIDR(192.168.0.0/16) using 🎯 全球直连[DIRECT]
23-08-25 20:26:35[ info ][TCP] 192.168.1.247:42580 --> 192.168.1.247:7893 match IPCIDR(192.168.0.0/16) using 🎯 全球直连[DIRECT]
23-08-25 20:26:35[ info ][TCP] 192.168.1.247:42568 --> 192.168.1.247:7893 match IPCIDR(192.168.0.0/16) using 🎯 全球直连[DIRECT]
23-08-25 20:26:35[ info ][TCP] 192.168.1.247:42574 --> 192.168.1.247:7893 match IPCIDR(192.168.0.0/16) using 🎯 全球直连[DIRECT]
23-08-25 20:26:35[ info ][TCP] 192.168.1.247:42532 --> 192.168.1.247:7893 match IPCIDR(192.168.0.0/16) using 🎯 全球直连[DIRECT]
23-08-25 20:26:35[ info ][TCP] 192.168.1.247:42554 --> 192.168.1.247:7893 match IPCIDR(192.168.0.0/16) using 🎯 全球直连[DIRECT]
23-08-25 20:26:35[ info ][TCP] 192.168.1.247:42536 --> 192.168.1.247:7893 match IPCIDR(192.168.0.0/16) using 🎯 全球直连[DIRECT]
23-08-25 20:26:35[ info ][TCP] 192.168.1.247:42512 --> 192.168.1.247:7893 match IPCIDR(192.168.0.0/16) using 🎯 全球直连[DIRECT]
23-08-25 20:26:35[ info ][TCP] 192.168.1.247:42524 --> 192.168.1.247:7893 match IPCIDR(192.168.0.0/16) using 🎯 全球直连[DIRECT]
23-08-25 20:26:35[ info ][TCP] 192.168.1.247:42500 --> 192.168.1.247:7893 match IPCIDR(192.168.0.0/16) using 🎯 全球直连[DIRECT]
23-08-25 20:26:35[ info ][TCP] 192.168.1.247:42486 --> 192.168.1.247:7893 match IPCIDR(192.168.0.0/16) using 🎯 全球直连[DIRECT]
23-08-25 20:26:35[ info ][TCP] 192.168.1.247:42498 --> 192.168.1.247:7893 match IPCIDR(192.168.0.0/16) using 🎯 全球直连[DIRECT]
23-08-25 20:26:35[ info ][TCP] 192.168.1.247:42466 --> 192.168.1.247:7893 match IPCIDR(192.168.0.0/16) using 🎯 全球直连[DIRECT]
23-08-25 20:26:35[ info ][TCP] 192.168.1.247:42472 --> 192.168.1.247:7893 match IPCIDR(192.168.0.0/16) using 🎯 全球直连[DIRECT]
23-08-25 20:26:35[ info ][TCP] 192.168.1.247:42464 --> 192.168.1.247:7893 match IPCIDR(192.168.0.0/16) using 🎯 全球直连[DIRECT]
23-08-25 20:26:35[ info ][TCP] 192.168.1.247:42462 --> 192.168.1.247:7893 match IPCIDR(192.168.0.0/16) using 🎯 全球直连[DIRECT]
23-08-25 20:26:35[ info ][TCP] 192.168.1.247:42456 --> 192.168.1.247:7893 match IPCIDR(192.168.0.0/16) using 🎯 全球直连[DIRECT]
23-08-25 20:26:35[ info ][TCP] 192.168.1.247:42446 --> 192.168.1.247:7893 match IPCIDR(192.168.0.0/16) using 🎯 全球直连[DIRECT]
23-08-25 20:26:35[ info ][TCP] 192.168.1.247:42440 --> 192.168.1.247:7893 match IPCIDR(192.168.0.0/16) using 🎯 全球直连[DIRECT]
23-08-25 20:26:35[ info ][TCP] 192.168.1.247:42442 --> 192.168.1.247:7893 match IPCIDR(192.168.0.0/16) using 🎯 全球直连[DIRECT]
23-08-25 20:26:35[ info ][TCP] 192.168.1.247:42424 --> 192.168.1.247:7893 match IPCIDR(192.168.0.0/16) using 🎯 全球直连[DIRECT]
23-08-25 20:26:35[ info ][TCP] 192.168.1.247:42404 --> 192.168.1.247:7893 match IPCIDR(192.168.0.0/16) using 🎯 全球直连[DIRECT]

**Comment by 13810169** [comment]
> 看面板日志有无异常

@juewuy  面板日志已发，大佬帮忙看看

**Comment by juewuy** [comment]
流量回环了，没必要不要启用本机代理，alpine可能缺少部分依赖会导致回环

**Comment by 13810169** [comment]
> 流量回环了，没必要不要启用本机代理，alpine可能缺少部分依赖会导致回环

@juewuy 

**没有开启本机代理**

1 切换Clash运行模式:   Tproxy模式
 2 切换DNS运行模式：    fake-ip
 3 跳过本地证书验证：   已开启   ————解决节点证书验证错误
 4 只代理常用端口：     未开启   ————用于过滤P2P流量
 5 过滤局域网设备：     未开启   ————使用黑/白名单进行过滤
 6 设置本机代理服务:    未开启   ————使本机流量经过clash内核
 7 屏蔽QUIC流量:        已启用   ————优化视频性能
 8 管理Fake-ip过滤列表

**Comment by juewuy** [comment]
@13810169 那就不要用alpine了，换Debian或者openwrt吧

**Comment by 13810169** [comment]
> @13810169 那就不要用alpine了，换Debian或者openwrt吧

@juewuy  
好的  多谢解答了

**Comment by cmulittlechild** [comment]
我也遇到了一个问题，不过我是cent os 7.6，与你截图相同，本机localhost疯狂请求，cpu干到100%，带宽占满，所有的网页都连不上，只能重启服务器，想看看有什么解决办法
