### ISSUE TITLE
[Bug] docker bridge 模式代理不生效

### ISSUE THREAD

**Issue by Dreamail** [juewuy/ShellClash#480]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

docker容器使用bridge网络不走代理，使用host是可以的
> table inet shellclash {
>         chain dns_out {
>                 type nat hook output priority -100; policy accept;
>                 meta skgid 7890 return
>                 udp dport 53 redirect to :1053
>         }
> 
>         chain output {
>                 type nat hook output priority -100; policy accept;
>                 meta skgid 7890 return
>                 ip daddr { 0.0.0.0/8, 10.0.0.0/8, 100.64.0.0/10, 127.0.0.0/8, 169.254.0.0/16, 172.16.0.0/12, 192.168.0.0/16, 224.0.0.0-255.255.255.255 } return
>                 meta l4proto tcp meta mark set 0x00001ed4 redirect to :7892
>         }
> 
>         chain docker {
>                 type nat hook prerouting priority dstnat; policy accept;
>                 ip saddr != 172.16.0.0/12 return
>                 ip daddr { 0.0.0.0/8, 10.0.0.0/8, 100.64.0.0/10, 127.0.0.0/8, 169.254.0.0/16, 172.16.0.0/12, 192.168.0.0/16, 224.0.0.0-255.255.255.255 } return
>                 udp dport 53 redirect to :1053
>                 meta l4proto tcp meta mark set 0x00001ed4 redirect to :7892
>         }
> }

> 当前已自动设置透明路由的网段为: 10.168.1.4/24  172.17.0.1/16  172.18.0.1/16  172.16.0.1/16

**Comment by juewuy** [comment]
本地无法复现
