### ISSUE TITLE
[Bug] 黑名单设备的DNS问题

### ISSUE THREAD

**Issue by AquanJSW** [juewuy/ShellClash#481]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

```bash
#ShellClash配置文件，不明勿动！
versionsh_l=1.8.0
update_url=https://fastly.jsdelivr.net/gh/juewuy/ShellClash
userguide=1
redir_mod=Nft混合
ipv6_redir=已开启
ipv6_support=已开启
ipv6_dns=已开启
dns_nameserver='https://223.5.5.5/dns-query, https://doh.pub/dns-query, tls://dns.rubyfish.cn:853'
dns_fallback='https://1.0.0.1/dns-query, https://8.8.4.4/dns-query, https://doh.opendns.com/dns-query'
cpucore=amd64
clashcore=clash
clashv=v1.7.1
dns_mod=fake-ip
common_ports=未开启
local_proxy=已开启
local_type=nftables增强模式
macfilter_type=黑名单
dns_redir=未开启
```
OpenWrt中，该配置下，黑名单中的设备dns请求会被路由器的dnsmasq处理，但reply似乎又被dns_out链劫持了，导致黑名单中的设备仍得到fake ip
我尝试通过在dns_out链中加入dnsmasq的gid似乎解决了
```bash
meta skgid { 7890, 453 } return
```
所以是否可以在dns_out链中常驻这条rule呢

**Comment by juewuy** [comment]
https://github.com/juewuy/ShellClash/commit/9a982fd78be0576438e9fb947e97571c141082f1
