### ISSUE TITLE
[Bug] 360V6启动报错

### ISSUE THREAD

**Issue by xiaoqi2020** [juewuy/ShellClash#482]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

/usr/share/clash/start.sh: line 14: nft: not found
![image](https://github.com/juewuy/ShellClash/assets/50669177/752e9856-0580-44fb-9d96-6bb94b47f1c7)
启动后web可以打开，但是所有节点测速都失败，国际网站也打不开
设备是360V6
![image](https://github.com/juewuy/ShellClash/assets/50669177/74414563-e878-4760-b649-1416b7d085a8)

**Comment by juewuy** [comment]
@xiaoqi2020 不要使用nft模式

**Comment by xiaoqi2020** [comment]
> @xiaoqi2020 不要使用nft模式

不明白你说的这个模式是什么，请问怎么切换呢？

**Comment by xiaoqi2020** [comment]
> @xiaoqi2020 不要使用nft模式

‘我切换为tun模式正常启动诶呦报错了，但是所有节点都不通呢？’

**Comment by xiaoqi2020** [comment]
> @xiaoqi2020 不要使用nft模式

最新问题，我选择的Linux安装模式，重启路由器后，clahs就没了，输入clash提示-ash: clash: not found

**Comment by xiaoqi2020** [comment]
@juewuy 大佬求助啊，安装到任何目录重启后都没了，外置储存又找不到U盘

**Comment by juewuy** [comment]
@xiaoqi2020 未适配官方系统，可以尝试刷openwrt使用

**Comment by xiaoqi2020** [comment]
> @xiaoqi2020 未适配官方系统，可以尝试刷openwrt使用

刚从op刷回来，op不稳定
