### ISSUE TITLE
[Bug] fedora 38 clashservice 服务启动失败

### ISSUE THREAD

**Issue by kevinwang930** [juewuy/ShellClash#483]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

fedora38 安装 shellclash后，clash.service服务启动失败，报203, 已经排除 clash.core 下载不完整，切换到root后直接运行execStart 中的命令后再进入clash显示服务已启动，但是命令面板直接启动clash 报错

**Comment by juewuy** [comment]
@kevinwang930 使用保守模式启动

**Comment by kevinwang930** [comment]
@juewuy 保守模式启动成功，谢谢！
