### ISSUE TITLE
[Bug] Nft混合模式下，只要代理全部端口，外网访问内网就失效

### ISSUE THREAD

**Issue by chuwza** [juewuy/ShellClash#485]
大佬好，OpenWrt 22.03.5、ShellClash 1.8.0、Nft混合模式且代理全部端口。手机用流量的情况下，无法访问经过端口转发过的内网服务（Home Assistant内网192.168.1.4:8123，手机用流量访问 http://ip:33333 失败）
![屏幕截图(292)z](https://github.com/juewuy/ShellClash/assets/30049891/e8571834-acb6-40f1-ad66-0a8cb060a32c)

不过经测试，端口转发OpenWrt luci界面，是可以访问的，无法访问的是下属设备的服务
![屏幕截图(293)z](https://github.com/juewuy/ShellClash/assets/30049891/df907178-70f5-4bc4-ae8c-60cf3d69c856)

临时解决方法是不开代理UDP（也就是使用Nft基础）就正常。并且还有个解决办法：Nft混合下，开启仅代理部分端口之后，就能访问

因为想要代理全部端口，所以只能暂时用回Nft基础

**Comment by juewuy** [comment]
@chuwza 建议使用局域网设备过滤功能过滤相关设备，对内网设备的访问默认是屏蔽的防止网络攻击

**Comment by chuwza** [comment]
> @chuwza 建议使用局域网设备过滤功能过滤相关设备，对内网设备的访问默认是屏蔽的防止网络攻击

那可以手动解除这个屏蔽吗？这个内网设备既需要搭建外网服务，又需要网络代理，不可以过滤掉

**Comment by juewuy** [comment]
@chuwza 不支持这种设置

**Comment by chuwza** [comment]
> @chuwza 不支持这种设置

好的，另外想问下，为什么Nft基础+代理全部端口，就可以外网访问下属设备；但是Nft混合+代理全部端口，就不可以访问下属设备？这个屏蔽只针对Nft混合代理UDP吗？

**Comment by juewuy** [comment]
@chuwza 不是很确定相关原因，你可以追踪一下clash日志看是否有流量经过
