### ISSUE TITLE
[Feature] 希望能够支持 metacubexd

### ISSUE THREAD

**Issue by klchen0112** [juewuy/ShellClash#487]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

[metacubexd](https://github.com/MetaCubeX/metacubexd) is Clash.Meta Dashboard

**Comment by tunanx** [comment]
你可以尝试使用在线版本，例如下列三个官方提供的链接。
GH Pages Custom Domain: http://d.metacubex.one/
GH Pages: https://metacubex.github.io/metacubexd
Cloudflare Pages: https://metacubexd.pages.dev/
打开网页后，点击⚙进入设置，点击切换后端，输入路由器ip即可，密钥默认为空。

**Comment by juewuy** [comment]
https://github.com/juewuy/ShellClash/commit/9a982fd78be0576438e9fb947e97571c141082f1
