### ISSUE TITLE
[Bug] 在关闭公网访问的情况下，仍然能够公网访问

### ISSUE THREAD

**Issue by chinazyq123** [juewuy/ShellClash#488]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

在关闭公网访问的情况下，仍然能够公网访问。使用的是最新公测版

**Comment by juewuy** [comment]
@chinazyq123 该功能依赖iptables，如果防火墙是nftables可能无法起作用

**Comment by chinazyq123** [comment]
但是似乎之前的版本没有这个问题，至少我去年第一次装的时候，不开公网访问是真的不能访问的
我的openwrt及路由器均未更换。我尝试卸载重装但还是一样结果

**Comment by chinazyq123** [comment]
已解决，thanks
