### ISSUE TITLE
能否自行添加绕过内核的IP或者IP段呢？

### ISSUE THREAD

**Issue by ddd-zero** [juewuy/ShellClash#493]
找了一圈没找到这个功能。

**Comment by juewuy** [comment]
请说清楚是源IP还是目标IP

**Comment by ddd-zero** [comment]
> 请说清楚是源IP还是目标IP

目标IP。

**Comment by juewuy** [comment]
@ddd-zero 你可以启用绕过cn，之后手动修改绕过cn的ip文件列表

**Comment by ddd-zero** [comment]
> @ddd-zero 你可以启用绕过cn，之后手动修改绕过cn的ip文件列表

shellclash会不会有自动更新GeoIP/CN-IP 导致我改的没啥效果了？

**Comment by juewuy** [comment]
@ddd-zero 不会自动更新
