### ISSUE TITLE
能否在dns中添加 default server的自定义

### ISSUE THREAD

**Issue by in-out** [juewuy/ShellClash#50]
clash的定义

[default server](https://lancellc.gitbook.io/clash/clash-config-file/dns#default-nameserver-optional)

**Comment by juewuy** [comment]
请问覆盖这个有什么明确的意义吗？？
如果只是个例需求请使用7-7
然后在config.yaml中修改

**Comment by in-out** [comment]
> 请问覆盖这个有什么明确的意义吗？？
> 如果只是个例需求请使用7-7
> 然后在config.yaml中修改

如文档所说，用来解析DOH或是DOT的域名
但是，clash 1.6.5中又在dns设置中多了一个
[nameserver-policy](https://github.com/Dreamacro/clash/pull/1406)

要求shellclash对应所有的clash新的feature实在是过意不去

还是手动添加吧 多谢这个项目以及你的付出
