### ISSUE TITLE
[Feature] 支持从本地导入配置文件

### ISSUE THREAD

**Issue by ObcbO** [juewuy/ShellClash#500]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

如果是自己写的配置文件，又不想公开，从本地上传就十分有用

**Comment by juewuy** [comment]
@ObcbO 请参考
https://juewuy.github.io/bdaz/

**Comment by ObcbO** [comment]
根据juewuy提供的链接解决了

仅需将 `yaml` 或 `yml` 文件传到 `/tmp`, 再执行 `clash` 命令就会提示导入了

**Comment by chenbihao** [comment]
> @ObcbO 请参考 https://juewuy.github.io/bdaz/

请教一下，用docker跑的话这个、tmp的提示导入是否还有效，我打ls /tmp是可以看到文件的，但是打crash没提示🌚
