### ISSUE TITLE
[Bug] 华硕 RT-AC68U 无法启动clash

### ISSUE THREAD

**Issue by piggy2011** [juewuy/ShellClash#504]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

shellclash已经成功安装在华硕 RT-AC68U （firmware ：386.9）下，配置warp功能测试正常。但昨天突然发现warp功能无法正常工作，登录路由器发现clash无法运行。提示如下：

```
Connie-ASUS@RT-AC68U:/tmp/home/root# clash
-sh: clash: not found
```
其它信息如下：

```
Connie-ASUS@RT-AC68U:/tmp/home/root#
Connie-ASUS@RT-AC68U:/tmp/home/root# uname -a
Linux RT-AC68U 2.6.36.4brcmarm #1 SMP PREEMPT Mon Sep 4 11:49:01 EDT 2023 armv7l ASUSWRT-Merlin
Connie-ASUS@RT-AC68U:/tmp/home/root# uname -r
2.6.36.4brcmarm
Connie-ASUS@RT-AC68U:/tmp/home/root#
Connie-ASUS@RT-AC68U:/tmp/home/root# cat /etc/profile
export PATH="/bin:/usr/bin:/sbin:/usr/sbin:/home/$USER:/mmc/sbin:/mmc/bin:/mmc/usr/sbin:/mmc/usr/bin:/opt/sbin:/opt/bin:/opt/usr/sbin:/opt/usr/bin"
export PS1='\u@\h:\w\$ '

alias l='ls -lFA'
alias ll='ls -lF'

ldd() {
        LD_TRACE_LOADED_OBJECTS=1 $*;
}

[ -n "${TMOUT+x}" ] || export TMOUT="$(nvram get shell_timeout 2>/dev/null)"

[ -f /opt/etc/profile ] && . /opt/etc/profile
[ "$(nvram get jffs2_scripts)" = "1" ] && [ -f /jffs/configs/profile.add ] && . /jffs/configs/profile.add
Connie-ASUS@RT-AC68U:/tmp/home/root#
```

路由器配置信息一直没有做过修改，不知道到底问题出在哪里？谢谢！

**Comment by juewuy** [comment]
@piggy2011 尝试用usb启动方式安装

**Comment by piggy2011** [comment]
重新执行以下指令安装后问题解决

`export url='https://fastly.jsdelivr.net/gh/juewuy/ShellClash@master' && sh -c "$(curl -kfsSl $url/install.sh)" && source /etc/profile &> /dev/null`
