### ISSUE TITLE
is it a typo in line 103 of the install.sh?

### ISSUE THREAD

**Issue by fsdrw08** [juewuy/ShellClash#51]
shtype=sh && [ -n "$(ls -l /bin/sh|grep -o **dash**)" ] && shtype=bash
should the "dash" be "bash"?

**Comment by juewuy** [comment]
这里只是强制用bash执行脚本，不会更改系统默认的sh设置

**Comment by fsdrw08** [comment]
这一行是不是检测系统可用的shell入口？默认用sh，如果sh里面有检测到dash(bash?)就把入口改成bash？
在vyos中，sh被强制转换成show，而不是bash，因此会导致执行完此脚本后，clash的alias是"sh /xxx/clash.sh"，在vyos中无法执行，如果把这一行的dash改成bash，clash的alias就成了bash /xxx/clash.sh，执行起来没问题

**Comment by juewuy** [comment]
回头我加上show的判断就好了
