### ISSUE TITLE
[Bug] Linux服务器本机配置无法运行clash

### ISSUE THREAD

**Issue by Cooperx521** [juewuy/ShellClash#510]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

![image](https://github.com/juewuy/ShellClash/assets/131770126/1fd0b0c1-792a-4e82-af85-c2197983a024)

订阅已经成功配置，但是无法正常开启clash，看到了相关的issue推荐使用保守模式，但是现在似乎没有这个模式

![image](https://github.com/juewuy/ShellClash/assets/131770126/8c751288-eca1-41a2-bb21-0d0f652b98ff)

以下是我的型号
![image](https://github.com/juewuy/ShellClash/assets/131770126/fa4c4299-9877-4ab4-9ba6-d1866a971015)

**Comment by juewuy** [comment]
@Cooperx521 启动设置
