### ISSUE TITLE
iptables: Chain already exists.

### ISSUE THREAD

**Issue by jkwang** [juewuy/ShellClash#54]
小米ax3600路由器，每次启动shell clash 都会出现这一行。
管理脚本         1.4.1
clash核心        v1.6.0
GeoIP/CN-IP      20210623 > 20210623
请问这是一个报错还是正常的，另外geoip和cn-ip好像之能势20210623版本的？这是最新版本吗？
谢谢！

**Comment by juewuy** [comment]
重启一下设备就好了
