### ISSUE TITLE
和dmz主机冲突

### ISSUE THREAD

**Issue by zengyaoqi** [juewuy/ShellClash#55]
开了clash之后dmz主机不工作，nas没法用

**Comment by juewuy** [comment]
请使用过滤局域网设备功能

**Comment by joescon** [comment]
同样遇到这个问题。
clash--2--5，使用黑名单模式过滤了局域网的nas，但还是访问不了nas。
请问设置步骤有没有问题？谢谢

设备：群晖nas，小米ax3600
管理脚本1.4.3，核心 2021.07.03
