### ISSUE TITLE
在linux上安装后仍然无法翻墙

### ISSUE THREAD

**Issue by callzhang** [juewuy/ShellClash#57]
Ubuntu 18.04
安装后尝试各种模式：Tun、纯净模式、Redir模式
Terminal无法ping通google.com
请问如何操作？

**Comment by juewuy** [comment]
Clash不支持ICMP协议，也就不支持ping命令

**Comment by callzhang** [comment]
你好，请问如何正确地在terminal中使用？我是ssh进入的远程服务器。

**Comment by juewuy** [comment]
功能设置开启本机代理
