### ISSUE TITLE
Xiaomi MI4A gigabit

### ISSUE THREAD

**Issue by Pecco69791215** [juewuy/ShellClash#61]
Hi Sir, How to install clash on router xiaomi mi4a gigabit?

**Comment by juewuy** [comment]
You need to find a way to open SSH, and then install it according to the content of the https://github.com/juewuy/ShellClash#readme

**Comment by Pecco69791215** [comment]
> You need to find a way to open SSH, and then https://github.com/juewuy/ShellClash#readme
![photo_2021-07-22_20-00-41](https://user-images.githubusercontent.com/82424377/126635944-d923cd67-cdf8-4d80-b6e2-3bf98ee7f50e.jpg)

**Comment by Pecco69791215** [comment]
I stuck here.

**Comment by juewuy** [comment]
Just enter one link
