### ISSUE TITLE
AX1800 开机自启问题

### ISSUE THREAD

**Issue by PatZhuang** [juewuy/ShellClash#62]
脚本版本 1.4.3 正式版

打开开机自启以后，路由器重启，执行 `clash` 显示正在运行，但实际上没有运行代理，也无法访问面板，需要手动重启 clash 服务。

已经试过开关重启功能，无效。试过执行 `mtd erase crash` 无效。

**Comment by juewuy** [comment]
重置一下设备试试

**Comment by PatZhuang** [comment]
> 重置一下设备试试

重置以后重新安装就好了 感谢
