### ISSUE TITLE
订阅链接中的'%26'会被解析为‘&’致使导入配置文件失败

### ISSUE THREAD

**Issue by AutoRip** [juewuy/ShellClash#63]
![image](https://user-images.githubusercontent.com/22536147/126928386-091223f6-a9a5-4f8a-ad30-516fe04aa0c8.png)  
 

红色标记位置的‘%26’被解析为‘&’  （url参数中包含的url字符编码‘%26’被转义，预期动作应为禁止转义）

原始链接为https://[hidden_content]/sub?target=clash&emoji=true&url=https%3A%2F%2F[hidden_content]%2Fmodules%2Fservers%2FV2raySocks%2Fosubscribe.php%3Fsid%3D286%26token%3D[hidden_content]%26sip002%3D1  

解析后的链接为https://[hidden_content]/sub?target=clash&emoji=true&url=https%3A%2F%2F[hidden_content]%2Fmodules%2Fservers%2FV2raySocks%2Fosubscribe.php%3Fsid%3D286&token%3D[hidden_content]&sip002%3D1

**Comment by juewuy** [comment]
这不是bug，解析失败也应该不是这个原因
subconverter对两种形式都是兼容的

**Comment by AutoRip** [comment]
> 这不是bug，解析失败也应该不是这个原因
> subconverter对两种形式都是兼容的

看了下源码，找到两处字符转义：

1. **getdate.sh:197** -> 将&替换为%26（对issue中所示链接无影响）  
2. **start.sh:120** -> 将%26替换为&（对issue中所示链接有影响。订阅链接中所包含的url参数值已经为url encoded，转义后该参数值的完整性被破坏，导致通过输入链接获取配置文件的失败）  

对于转义2，如果用户导入配置文件链接时输入了一个第三方的包含url参数的订阅链接，且该url参数值按照subconverter要求已经进行了url encode，那么shellclash中的导入将会因为上述转义操作无法访问正确地址而失败。

**Comment by AutoRip** [comment]
话说为啥要加这俩个转义啊😂
Ver 1.2.0的这个“~修复部分情况下导入包含“&”符号的配置文件失败的bug”是个啥bug😂

**Comment by juewuy** [comment]
有的用户的链接里面会附带一些条件，如果用%26就会转换失败
还不如全转为&让subconverter来处理

**Comment by AutoRip** [comment]
对于使用第三方subconverter（比如机场自行提供的订阅转换api）的场景，会考虑在shellclash里增加自定义服务器的选项吗？

**Comment by juewuy** [comment]
你可以直接使用6-2导入

**Comment by AutoRip** [comment]
> 你可以直接使用6-2导入

抱歉，可能我没讲清楚context，我的意思就是在使用6-2导入机场提供的subconverter api订阅链接的时候会产生上面的错误。

**Comment by maokwen** [comment]
我在使用自己搭建的 subconverter 生成的地址时也遇到了同样的问题。

6-2 是否不应该处理传入的字符串？一般来说多层嵌套转义都会维持层级上的差异（因为转义字符 % 本身也可以转义），因此单单针对 6-2 这个特殊情况，不做转义不应该会出问题。但是如果手动解开一层转义的话就会同时有两个 url 处于 0 阶上，就会出现歧义了。

subconverter 被设计为要处理多个转换相嵌套的情况（例如：原始规则-机场主-用户），所以出现不同层级的 & 应该是较为常见的情况，所以我认为这个问题应该得到处理。

以上仅针对 6-2，至于 6-1 下的诸多情况我没有考虑到。



而对于 shellclash 中的 6-2 ，我认为不需要处理这种情况。

**Comment by juewuy** [comment]
@maokwen 转义只是因为shell环境下&是特殊符号，没有别的原因

**Comment by StormYudi** [comment]
同求解决此问题！困扰我已久了。

**Comment by Equity0** [comment]
生成一个短链接导入即可

**Comment by 1251801899** [comment]
啊哈，我解决了这个问题
用这个网站转换一下就好了：https://sub-store.usuc.cc/
