### ISSUE TITLE
start.sh里的iptables规则可否考虑过滤掉在Clash config里设置了代理的地址？

### ISSUE THREAD

**Issue by ingjieye** [juewuy/ShellClash#64]
https://github.com/juewuy/ShellClash/blob/cd801e120caba2db89daac812029139b5ea24a44/scripts/start.sh#L311-L320

例如我在Clash里设置了
`- IP-CIDR,10.0.0.0/8,Proxy,no-resolve`
但是因为start.sh里把所有局域网地址都用iptables规则过滤掉了，导致这些流量无法被clash处理

**Comment by juewuy** [comment]
这里使用的都是常见的内网地址，如果确实有需求可以自行修改相关代码
