### ISSUE TITLE
小米ax3600在配置端口转发之后会导致代理出现异常

### ISSUE THREAD

**Issue by VulpesFennex** [juewuy/ShellClash#76]
小米官方固件稳定版1.1.19，通过SSH安装ShellClash。
在启用clash之后配置端口转发，之后无法使用代理，查看面板里面活动的连接会一个接一个断开，日志也会停止输出，在代理界面能ping通节点但是不能访问外网。
重启clash能恢复部分访问（google搜索不能访问），重启路由器之后一切恢复正常。
root@XiaoQiang:~# uname -a
Linux XiaoQiang 4.4.60 #0 SMP PREEMPT Thu Jul 8 06:48:54 2021 aarch64 GNU/Linux

**Comment by juewuy** [comment]
这个确实无法完美兼容，因为官方端口转发会重置iptables，而clash的流量劫持依赖动态的iptables，会在其重启时失效
理论上重启clash应该可以恢复访问，不能访问可能是缓存问题
