### ISSUE TITLE
[Bug] 不使用 GeoSite.dat 

### ISSUE THREAD

**Issue by S8Cloud** [juewuy/ShellClash#770]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

已知：[梅林新版本会删除 GeoSite.dat 文件](https://t.me/merlinclashcat/655)
```
欢迎使用ShellCrash！            版本：1.9.1rc3
Clash服务正在运行（Tproxy模式），已设置开机启动！
当前内存占用：34.45 MB，已运行：00小时00分03秒
TG频道：https://t.me/ShellClash
-----------------------------------------------
 1 启动/重启服务
 2 内核功能设置
 3 停止内核服务
 4 内核启动设置
 5 配置自动任务
 6 导入配置文件
 7 内核进阶设置
 8 其他工具
 9 更新/卸载
-----------------------------------------------
 0 退出脚本
请输入对应数字 > 1
-----------------------------------------------
未找到GeoSite.dat文件，正在下载！
############################################################################# 100.0%
```

使用不包含 GeoSite GeoIP 规则时，每次重启仍将尝试下载 GeoSite.dat 文件。

尝试修改 `/jffs/ShellCrash/yamls/user.yaml` 设置为 `geodata-mode: false` 没有效果

**Comment by juewuy** [comment]
未使用相关规则时不会自动下载
       [ -n "$(cat "$CRASHDIR"/yamls/*.yaml | grep -oEi 'geosite')" ] && ckgeo GeoSite.dat geosite.dat
