### ISSUE TITLE
请问shellclash是否已经支持tun模式？

### ISSUE THREAD

**Issue by JMVoid** [juewuy/ShellClash#78]
我尝试用openwrt虚拟机以旁路由的方式安装 shellclash。用redir 模式能正常运行. 但是尝试用fake-ip + tun模式来代理同上网，但是无法进行上网。用ifconfig查询后，并没有发现虚拟卡（utun）。查询代码，似乎并没有用ip tuntap来生成虚拟网卡。所以咨询一下现代码是否已经支持tun模式？

**Comment by juewuy** [comment]
虚拟机的虚拟网卡和tun网卡冲突了，请自行解决
