### ISSUE TITLE
[Feature] TLS clientHello Packet Fragmentation

### ISSUE THREAD

**Issue by Graveyard9988** [juewuy/ShellClash#793]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

Fragments TLS ClientHello packets in multiple segments, making it harder to drop connections based on SNI filtering. Enable it by adding the tls_fragment entry to any outbound connection:

...
```
"outbounds": [
        {
            "type": "direct",
            "tag": "direct"
        },
        {
            "type": "direct",
            "tag": "fragment",
            "tcp_fast_open": false,
            "tls_fragment": {
                "enabled": true,
                "size": "20-100",
                "sleep": "0-2"
            }
        },
```
here's fork of sing box with "Fragment" :
https://github.com/kyochikuto/sing-box-plus

**Comment by juewuy** [comment]
暂时没有适配计划，请通过自定义内核+自定义配置文件功能自行实现
