### ISSUE TITLE
环境变量无法正常工作

### ISSUE THREAD

**Issue by huaxianyan** [juewuy/ShellClash#80]
每次连接的时候，在当前终端安装 ShellClash 的时候是正常的

但是一旦断开之后再连上，使用 ``clash`` 命令则提示（Zsh 与 Bash）：

```
zsh: command not found: clash
```
```
Command 'clash' not found, but can be installed with:

snap install clash
```
物理机，系统为 Ubuntu 20.04 LTS，用户 root

**Comment by juewuy** [comment]
安装时候注意看是否有权限报错

**Comment by huaxianyan** [comment]
并无报错，回显正常
```
***********************************************
**                 欢迎使用                  **
**                ShellClash                 **
**                             by  Juewuy    **
***********************************************
-----------------------------------------------
请选择想要安装的版本：
 1 Shellclash正式版
 2 Shellclash测试版
-----------------------------------------------
请输入相应数字 > 1
最新版本：1.4.3
-----------------------------------------------
如遇问题请加TG群反馈： t.me/clashfm
支持各种基于openwrt的路由器设备
支持Debian、Centos等标准Linux系统
-----------------------------------------------
安装ShellClash至少需要预留约1MB的磁盘空间
 1 在/etc目录下安装(适合root用户)
 2 在/usr/share目录下安装(适合Linux设备)
 3 在当前用户目录下安装(适合非root用户)
 4 手动设置安装目录
 0 退出安装
-----------------------------------------------
请输入相应数字 > 1
目标目录/etc空间剩余：170G
确认安装？(1/0) > 1
-----------------------------------------------
开始从服务器获取安装文件！
-----------------------------------------------
################################################################################################################# 100.0%
-----------------------------------------------
开始解压文件！
clash.service
clash.sh
clashservice
getdate.sh
start.sh
-----------------------------------------------
ShellClash 已经安装成功!
-----------------------------------------------
输入 clash 命令即可管理！！！
-----------------------------------------------
```

**Comment by huaxianyan** [comment]
我查了查安装脚本发现了这段

```
	#设置环境变量	
	[ -w /opt/etc/profile ] && profile=/opt/etc/profile
	[ -w /jffs/configs/profile.add ] && profile=/jffs/configs/profile.add
	[ -w ~/.bashrc ] && profile=~/.bashrc
	[ -w /etc/profile ] && profile=/etc/profile
	if [ -n "$profile" ];then
		sed -i '/alias clash=*/'d $profile
		echo "alias clash=\"$shtype $clashdir/clash.sh\"" >> $profile #设置快捷命令环境变量
		sed -i '/export clashdir=*/'d $profile
		echo "export clashdir=\"$clashdir\"" >> $profile #设置clash路径环境变量
	else
		echo 无法写入环境变量！请检查安装权限！
		exit 1
	fi
```

对照发现 ``/etc/profile`` 里写入了正常的环境变量，但是不知为何这个文件在 SSH 登录上去时并不会自动加载，目前在 ``~/.zshrc`` 中加入一条 ``source /etc/profile`` 来解决。

不好意思，占用各位宝贵的时间。

**Comment by juewuy** [comment]
这应该是SSH客户端的问题，默认大部分的SSH客户端都会自动加载/etc/profile

**Comment by aswirl4** [comment]
> 这应该是SSH客户端的问题，默认大部分的SSH客户端都会自动加载/etc/profile

如果ssh登陆的用户的默认shell不是bash的话, 依据shell的不同而可能不会加载 /etc/profiel. 和ssh客户端无关的样子
例如常用的zsh shell 读取的是 /etc/zshenv

请问作者为什么 init.sh中检测zsh的方式是如下代码
```bash
#设置环境变量
[ -w /opt/etc/profile ] && profile=/opt/etc/profile
[ -w /jffs/configs/profile.add ] && profile=/jffs/configs/profile.add
[ -w ~/.bashrc ] && profile=~/.bashrc
[ -w /etc/profile ] && profile=/etc/profile
if [ -n "$profile" ];then
        sed -i '/alias clash=*/'d $profile
        echo "alias clash=\"$shtype $clashdir/clash.sh\"" >> $profile #设置快捷命令环境变量
        sed -i '/export clashdir=*/'d $profile
        echo "export clashdir=\"$clashdir\"" >> $profile #设置clash路径环境变量
        source $profile &>/dev/null
        #适配zsh环境变量
        [ -n "$(ls -l /bin/sh|grep -oE 'zsh')" ] && [ -z "$(cat ~/.zshrc 2>/dev/null|grep clashdir)" ] && {
                echo "alias clash=\"$shtype $clashdir/clash.sh\"" >> ~/.zshrc
                echo "export clashdir=\"$clashdir\"" >> ~/.zshrc
                source ~/.zshrc &>/dev/null
        }
else
        echo -e "\033[33m无法写入环境变量！请检查安装权限！\033[0m"
        exit 1
fi
```
我用过的zsh都没有把sh link 到 zsh去啊?

**Comment by juewuy** [comment]
你没链接到sh，那么默认在bash下执行就和zsh无关
你要是通过ssh客户端登陆时的选项进入的zsh，那么请提供可用的检测手段

**Comment by aswirl4** [comment]
> 你没链接到sh，那么默认在bash下执行就和zsh无关 你要是通过ssh客户端登陆时的选项进入的zsh，那么请提供可用的检测手段

不知道我是否理解了您的意思:
- 我想表达我不理解, 为什么要通过检测`/bin/sh`是否`link`到`ZSH`来决定是否向`~/.zshrc`写入clash相关配置.  因为我不知道什么app或者什么情况下会有人改`/bin/sh`的link. ZSH好像没有这样的默认行为.
- 默认shell是zsh时不会加载/etc/profile的[refer](https://superuser.com/questions/881102/etc-profile-not-being-sourced-at-login)

**Comment by juewuy** [comment]
@aswirl4 你要是有其他方式检测请提供，如果没有那就只能做到这样

**Comment by jqtmviyu** [comment]
electerm, 默认shell是zsh,  没有加载 /etc/profile,  按楼上的方法解决

**Comment by chmdir** [comment]
> 我查了查安装脚本发现了这段
> 
> ```
> 	#设置环境变量	
> 	[ -w /opt/etc/profile ] && profile=/opt/etc/profile
> 	[ -w /jffs/configs/profile.add ] && profile=/jffs/configs/profile.add
> 	[ -w ~/.bashrc ] && profile=~/.bashrc
> 	[ -w /etc/profile ] && profile=/etc/profile
> 	if [ -n "$profile" ];then
> 		sed -i '/alias clash=*/'d $profile
> 		echo "alias clash=\"$shtype $clashdir/clash.sh\"" >> $profile #设置快捷命令环境变量
> 		sed -i '/export clashdir=*/'d $profile
> 		echo "export clashdir=\"$clashdir\"" >> $profile #设置clash路径环境变量
> 	else
> 		echo 无法写入环境变量！请检查安装权限！
> 		exit 1
> 	fi
> ```
> 
> 对照发现 `/etc/profile` 里写入了正常的环境变量，在 SSH 登录上去时并不会自动加载这个文件，目前在 `~/.zshrc` 中加入一条 `source /etc/profile` 来解决。
我是denian12后装的zsh,在/etc/zsh/zshenv 下加入
alias clash="bash /etc/clash/clash.sh"
export clashdir="/etc/clash"
这两行好点，不然按你这个方法 SSH连接后 命令行就是个 
`#`
