### ISSUE TITLE
pidof: command not found

### ISSUE THREAD

**Issue by sherlockwho** [juewuy/ShellClash#88]
<img width="575" alt="截屏2021-11-01 05 08 47" src="https://user-images.githubusercontent.com/48094111/139601307-43ad6009-4546-41f8-a5d7-85bc0e65b559.png">

**Comment by juewuy** [comment]
缺少相关依赖，应该不影响使用

**Comment by jkle112** [comment]
不知道你用的路由器情况，如果是OPENWRT系统，更新一下再安装，我没有碰到这样的错误！
