### ISSUE TITLE
开启后部分国内网站打不开或显示不全，请问在哪里设置

### ISSUE THREAD

**Issue by 6kun** [juewuy/ShellClash#89]
开启后部分国内网站打不开或显示不全，请问在哪里设置

**Comment by wfinewy** [comment]
我也想知道

**Comment by juewuy** [comment]
规则里禁用广告过滤或者使用不带去广告的规则

**Comment by jkle112** [comment]
应该不用设置吧，默认的RULE规则和内置的DNS配置，我看了都是分流的，国内的直连，用的也是国内的DNS。
我安装后，禁用了内置的DNS，改用自己的，广告过滤用的其他的工具，没有碰到你们说的问题。

**Comment by wbg111** [comment]
DNS设置我头疼了一阵
