### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by Me-x** [juewuy/ShellClash#91]
能否增加第一次安装时，自定义安装目录 。默认/etc目录不够用，导致每次路由器重启回丢失核心文件 。

**Comment by juewuy** [comment]
一直都支持，除了padavan和梅林系统，此2者安装位置是强制的

**Comment by jkle112** [comment]
最新的安装脚本已经提示安装文件位置了，可以试试

**Comment by wbg111** [comment]
安装好以后复制一份放在jffs，消失了就执行一个copy都回来了。
