### ISSUE TITLE
youtube的tv客户端无法加载视频内容

### ISSUE THREAD

**Issue by goukey** [juewuy/ShellClash#92]
旁路由模式
索尼电视直装油管tv客户端和Googletv内置油管客户端两种环境，都是在shellclash下无法加载视频内容。菜单和视频选择画面都正常。
尝试更换shellclash的各种模式，依然无法解决。
将旁路由更换为openwrt的ssrp就能正常播放，非常神奇的问题，希望指导解决。

**Comment by tyc502044421** [comment]
切换内核为clashpre预览版 试试.

**Comment by goukey** [comment]
> 切换内核为clashpre预览版 试试.

shellclash哪儿能切换内核？这现象是不传递ip的锅吧

**Comment by juewuy** [comment]
请检查dns配置
更多请参考常见问题：https://juewuy.github.io/

**Comment by PatZhuang** [comment]
我遇到了同样的问题。我找到的解决方法如下：
进入 7. clash 进阶设置 
进入 6. 配置内置 DNS 服务
启用 6. 使用 dnsmasq 转发 DNS
