### ISSUE TITLE
config.yaml中 规则代码不支持RULE-SET模式

### ISSUE THREAD

**Issue by Wyk19951223** [juewuy/ShellClash#93]
设备：小米ax1800
版本：1.4.4
RT，将以下链接中的规则写入config.yaml后，shellclash重启报错，提示不支持RULE-SET模式。
链接：https://github.com/Loyalsoldier/clash-rules
不清楚是否是我操作有误，如果真的没有这个功能，希望大佬后续能加上这个功能。
十分感谢！

**Comment by juewuy** [comment]
请使用premium内核

**Comment by Wyk19951223** [comment]
请问shellclash里面自带切换内核的功能吗？

**Comment by Wyk19951223** [comment]
具体要如何操作呢？

**Comment by juewuy** [comment]
更新里
