### ISSUE TITLE
路由器装clash，不能获取在线订阅文件，下载下来想要文件直接导入，请问导入的路径和文件名应该是什么？感谢。

### ISSUE THREAD

**Issue by Taohongyi** [juewuy/ShellClash#95]
路由器装clash，不能获取在线订阅文件，下载下来想要文件直接导入，请问导入的路径和文件名应该是什么？感谢。

**Comment by jkle112** [comment]
我是在线安装的，你如果导入配置文件的话，先关闭clash，将配置文件改名为config.yaml，通过FTP或SCP工具或命令行导入到对应的配置文件位置，看你之前选择的哪里，再开启应该就识别了。

**Comment by wbg111** [comment]
入门确实有点头疼
