### ISSUE TITLE
Ubuntu 20.04 shellclash脚本重启后出错

### ISSUE THREAD

**Issue by 0xDkXy** [juewuy/ShellClash#96]
wget下载脚本运行后没问题，但是重启后在terminal中就不能使用clash命令执行脚本了，感觉是环境变量出错了，进入clash目录手动执行./clash.sh也出现错误提示没有文件start.sh，但是实际上当前目录中是有start.sh的

**Comment by 0xDkXy** [comment]
在`/root/.bashrc`中写入 `alias clash='bash /usr/share/clash/clash.sh'`后，reboot后可以可以使用clash打开脚本，但是脚本中提示_环境变量配置有误！清重新安装脚本！_和_chmod: 无法访问 '/start.sh':没有那个文件或目录_

**Comment by oodzchen** [comment]
我这儿一样的，不管是安装到`/etc/`还是`/usr/share/`还是当前用户目录下，每次重启之后都失效了，直接运行 `clash.sh`也一直报错，只能重新安装

不过我现在是安装完之后直接设置了开机自动启动，用是能用了，就是没法用脚本设置东西

**Comment by juewuy** [comment]
请使用root/root用户安装脚本
注意必须是双root
不支持sudo或者su安装
支持sudo -i临时提权
