### ISSUE TITLE
频繁导致路由无法上网，有解吗兄弟们

### ISSUE THREAD

**Issue by saury** [juewuy/ShellClash#98]
路由是ax3600，安装选的都是低占用的选项，经常出现路由无法上网的情况，最近几个月情况越来越严重，几乎每周都要死两次，ssh进路由发现的情况是clash的内存占用会到40mb+（平时好像一直都是15mb左右）无法通过菜单界面停止clash运行，只能找到进程强制kill，kill进程之后网络马上就恢复了，有遇到相似问题的吗?
附上clash版本：
```
 1 更新管理脚本  	1.3.0
 2 切换clash核心 	v1.7.1
 3 更新GeoIP数据库	202109150303
```
管理脚步没升到1.4.4-test是因为有个test的标，升级的第一天就出现无法上网的问题，立马降级了……

**Comment by jkle112** [comment]
个人建议供参考
刷机，https://openwrt.org/inbox/toh/xiaomi/xiaomi_ax3600
换固件后，在安装测试，一般情况下官方默认的配置很安全了
如果懂技术的，可以自己配置其他应用

**Comment by saury** [comment]
刷固件还是不折腾了，乱七八糟多出来的功能用不上不说，也不相信会比官方固件更稳定

**Comment by jkle112** [comment]
刷固件好，默认是纯净版的，根据需要安装应用，跑起来飞快，还可以自己升级无线，后期也是持续升级的

**Comment by saury** [comment]
> 刷固件好，默认是纯净版的，根据需要安装应用，跑起来飞快，还可以自己升级无线，后期也是持续升级的

兄弟，这有点屎拉不出来怪马桶没吸力的感觉，现在这个情况感觉是shellclash爆内存之后DNS解析出了问题，硬要重刷个系统，感觉两者关系不大，况且话说回来刷完了openwrt如果有mesh组网需求该怎么办？

**Comment by jkle112** [comment]
是这样的，我碰到过这样的问题，给路由器安装应用，由于添加的配置文件太大，超过了硬件的承受能力，所以我给你推荐的以上方案。
刷固件，官方是纯净版的，这样系统不需要的都精简了，不再占用内存了，shellclash就可以正常运行，这样DNS解析自然会恢复正常的。
安全方面，技术资料显示需要屏蔽小米路由器官方上传，不少用的是HOSTS文件，官方体积有限制，会占用内存和带宽，刷机一劳永逸。
关于mesh组网，可以看看是否可以安装对应的应用，如果是家用，面积在范围内，可以在刷机后的固件调整发射功率的，我的linksys wrt1900 ac v1就是这样弄的，结果7楼的机子在1楼都有信号。

**Comment by saury** [comment]
感谢楼上的老哥，尽管并不打算太折腾刷op……最近两天clash设置了小闪存模式+每天定时重启，暂时没出啥问题，如果再出问题只好考虑搞个旁路由挂梯子了

**Comment by qqjianyue** [comment]
> 

小闪存是省文件空间不是省内存是吧？
我家的3600也是一样内存不够网络不太稳定，即使我每天定时重启两次了

**Comment by jkle112** [comment]
最安全的方法是刷固件，https://openwrt.org/inbox/toh/xiaomi/xiaomi_ax3600
之后安装adblock,smartdns,shellclash，应该可以了。

**Comment by juewuy** [comment]
过去版本因为有回环bug会导致之类问题，早已经在最新版本修复。
